
-- --------------------------------------------------------

--
-- Struttura della tabella `gb`
--

DROP TABLE IF EXISTS `gb`;
CREATE TABLE IF NOT EXISTS `gb` (
  `id` int NOT NULL AUTO_INCREMENT,
  `game_name` varchar(200) CHARACTER SET utf8mb3 DEFAULT NULL,
  `genre_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  `publisher_name` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL,
  `release_year` int DEFAULT NULL,
  `platform_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=98 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dump dei dati per la tabella `gb`
--

INSERT INTO `gb` (`id`, `game_name`, `genre_name`, `publisher_name`, `release_year`, `platform_name`) VALUES
(1, 'Harry Potter and the Sorcerer\'s Stone', 'Action', 'Electronic Arts', 2001, 'GB'),
(2, 'Mario Golf', 'Action', 'Nintendo', 1999, 'GB'),
(3, 'Metal Gear Solid', 'Action', 'Konami Digital Entertainment', 2000, 'GB'),
(4, 'Teenage Mutant Ninja Turtles II: Back from the Sewers', 'Action', 'Konami Digital Entertainment', 1991, 'GB'),
(5, 'The Legend of Zelda: Link\'s Awakening', 'Action', 'Nintendo', 1992, 'GB'),
(6, 'The Legend of Zelda: Oracle of Ages', 'Action', 'Nintendo', 2001, 'GB'),
(7, 'Metroid II: Return of Samus', 'Adventure', 'Nintendo', 1991, 'GB'),
(8, 'Sakura Wars GB', 'Adventure', 'Media Factory', 2000, 'GB'),
(9, 'Super Mario Land 2: 6 Golden Coins', 'Adventure', 'Nintendo', 1992, 'GB'),
(10, 'The Legend of Zelda: Link\'s Awakening DX', 'Adventure', 'Nintendo', 1998, 'GB'),
(11, 'The Legend of Zelda: Oracle of Seasons', 'Adventure', 'Nintendo', 2001, 'GB'),
(12, 'Game & Watch Gallery', 'Misc', 'Nintendo', 1997, 'GB'),
(13, 'Game & Watch Gallery 2', 'Misc', 'Nintendo', 1997, 'GB'),
(14, 'Game & Watch Gallery 3', 'Misc', 'Nintendo', 1999, 'GB'),
(15, 'Gameboy Gallery', 'Misc', 'Nintendo', 1995, 'GB'),
(16, 'Kirby\'s Pinball Land', 'Misc', 'Nintendo', 1992, 'GB'),
(17, 'Pokemon Pinball', 'Misc', 'Nintendo', 1999, 'GB'),
(18, 'Yakuman', 'Misc', 'Nintendo', 1989, 'GB'),
(19, 'Yu-Gi-Oh! Dark Duel Stories', 'Misc', 'Konami Digital Entertainment', 2000, 'GB'),
(20, 'Disney\'s DuckTales', 'Platform', 'Capcom', 1988, 'GB'),
(21, 'Donkey Kong', 'Platform', 'Nintendo', 1994, 'GB'),
(22, 'Donkey Kong Country', 'Platform', 'Nintendo', 2000, 'GB'),
(23, 'Donkey Kong GB: Dinky Kong & Dixie Kong', 'Platform', 'Nintendo', 2000, 'GB'),
(24, 'Donkey Kong Land', 'Platform', 'Nintendo', 1994, 'GB'),
(25, 'Donkey Kong Land II', 'Platform', 'Nintendo', 1996, 'GB'),
(26, 'Kirby\'s Dream Land', 'Platform', 'Nintendo', 1992, 'GB'),
(27, 'Kirby\'s Dream Land 2', 'Platform', 'Nintendo', 1995, 'GB'),
(28, 'Mega Man II', 'Platform', 'Nintendo', 1991, 'GB'),
(29, 'Mega Man Xtreme', 'Platform', 'Capcom', 2000, 'GB'),
(30, 'Mega Man Xtreme 2', 'Platform', 'Capcom', 2001, 'GB'),
(31, 'Mega Man: Dr. Wily\'s Revenge', 'Platform', 'Nintendo', 1991, 'GB'),
(32, 'Super Mario Bros.', 'Platform', 'Nintendo', 1999, 'GB'),
(33, 'Super Mario Land', 'Platform', 'Nintendo', 1989, 'GB'),
(34, 'Super Mario Land 3: Wario Land', 'Platform', 'Nintendo', 1994, 'GB'),
(35, 'Wario Land 3', 'Platform', 'Nintendo', 2000, 'GB'),
(36, 'Wario Land II', 'Platform', 'Nintendo', 1997, 'GB'),
(37, 'Wario Land II (GBC)', 'Platform', 'Nintendo', 1998, 'GB'),
(38, 'Alleyway', 'Puzzle', 'Nintendo', 1989, 'GB'),
(39, 'Dr. Mario', 'Puzzle', 'Nintendo', 1989, 'GB'),
(40, 'Kirby Tilt \'n\' Tumble', 'Puzzle', 'Nintendo', 2000, 'GB'),
(41, 'Kirby\'s Block Ball', 'Puzzle', 'Nintendo', 1995, 'GB'),
(42, 'Kirby\'s Star Stacker', 'Puzzle', 'Nintendo', 1997, 'GB'),
(43, 'Mario\'s Picross', 'Puzzle', 'Nintendo', 1995, 'GB'),
(44, 'Picross 2', 'Puzzle', 'Nintendo', 1996, 'GB'),
(45, 'Qix', 'Puzzle', 'Nintendo', 1990, 'GB'),
(46, 'Tetris', 'Puzzle', 'Nintendo', 1989, 'GB'),
(47, 'Tetris 2 (All region sales)', 'Puzzle', 'Nintendo', 1992, 'GB'),
(48, 'Tetris 2 (weekly jp sales)', 'Puzzle', 'Nintendo', 1992, 'GB'),
(49, 'Tetris Attack', 'Puzzle', 'Nintendo', 1996, 'GB'),
(50, 'Tetris DX', 'Puzzle', 'Nintendo', 1998, 'GB'),
(51, 'Yoshi', 'Puzzle', 'Nintendo', 1991, 'GB'),
(52, 'Yoshi\'s Cookie', 'Puzzle', 'Nintendo', 1992, 'GB'),
(53, 'F-1 Race', 'Racing', 'Nintendo', 1990, 'GB'),
(54, 'Super R.C. Pro-Am', 'Racing', 'Nintendo', 1991, 'GB'),
(55, 'Dragon Quest Monsters 2', 'Role-Playing', 'Enix Corporation', 2001, 'GB'),
(56, 'Dragon Warrior I&II', 'Role-Playing', 'Enix Corporation', 1999, 'GB'),
(57, 'Dragon Warrior III', 'Role-Playing', 'Enix Corporation', 2000, 'GB'),
(58, 'Dragon Warrior Monsters', 'Role-Playing', 'Eidos Interactive', 1998, 'GB'),
(59, 'Final Fantasy Adventure', 'Role-Playing', 'SquareSoft', 1991, 'GB'),
(60, 'Final Fantasy Legend III', 'Role-Playing', 'SquareSoft', 1991, 'GB'),
(61, 'From TV Animation One Piece: Yume no Lufy Kaizokudan Tanjou!', 'Role-Playing', 'Banpresto', 2001, 'GB'),
(62, 'Fushigi no Dungeon: Fuurai no Shiren GB: Tsukikagemura no Kaibutsu', 'Role-Playing', 'ChunSoft', 1996, 'GB'),
(63, 'Hamtaro: Ham-Hams Unite!', 'Role-Playing', 'Nintendo', 2001, 'GB'),
(64, 'Medarot 2: Kabuto / Kuwagata Version', 'Role-Playing', 'Imagineer', 1999, 'GB'),
(65, 'Medarot 3: Kabuto / Kuwagata Version', 'Role-Playing', 'Imagineer', 2000, 'GB'),
(66, 'Medarot 4: Kabuto / Kuwagata Version', 'Role-Playing', 'Imagineer', 2001, 'GB'),
(67, 'Medarot: Kabuto / Kuwagata Version', 'Role-Playing', 'Imagineer', 1997, 'GB'),
(68, 'Pokémon Crystal Version', 'Role-Playing', 'Nintendo', 2000, 'GB'),
(69, 'Pokemon Gold/Pokemon Silver', 'Role-Playing', 'Nintendo', 1999, 'GB'),
(70, 'Pokemon Red/Pokemon Blue', 'Role-Playing', 'Nintendo', 1996, 'GB'),
(71, 'Pokémon Yellow: Special Pikachu Edition', 'Role-Playing', 'Nintendo', 1998, 'GB'),
(72, 'Star Ocean: Blue Sphere', 'Role-Playing', 'Enix Corporation', 2001, 'GB'),
(73, 'The Final Fantasy Legend', 'Role-Playing', 'SquareSoft', 1989, 'GB'),
(74, 'Yu-Gi-Oh! Monster Capture GB', 'Role-Playing', 'Konami Digital Entertainment', 2000, 'GB'),
(75, 'Yu-Gi-Oh: Duel Monsters 4', 'Role-Playing', 'Konami Digital Entertainment', 2000, 'GB'),
(76, 'SolarStriker', 'Shooter', 'Nintendo', 1989, 'GB'),
(77, 'Game de Hakken!! Tamagotchi 2', 'Simulation', 'Namco Bandai Games', 1997, 'GB'),
(78, 'Hamster Tarou', 'Simulation', 'Jorudan', 1999, 'GB'),
(79, 'Harvest Moon 2 GBC', 'Simulation', 'Ubisoft', 1999, 'GB'),
(80, 'Harvest Moon GB', 'Simulation', 'Victor Interactive', 1997, 'GB'),
(81, 'Tamagotchi', 'Simulation', 'Namco Bandai Games', 1996, 'GB'),
(82, 'Baseball', 'Sports', 'Nintendo', 1989, 'GB'),
(83, 'Extra Bases', 'Sports', 'Namco Bandai Games', 1990, 'GB'),
(84, 'Golf', 'Sports', 'Nintendo', 1989, 'GB'),
(85, 'Mario Tennis', 'Sports', 'Nintendo', 2000, 'GB'),
(86, 'Power Pro GB', 'Sports', 'Konami Digital Entertainment', 1998, 'GB'),
(87, 'Power Pro Kun Pocket', 'Sports', 'Konami Digital Entertainment', 1999, 'GB'),
(88, 'Power Pro Kun Pocket 2', 'Sports', 'Konami Digital Entertainment', 2000, 'GB'),
(89, 'Tennis', 'Sports', 'Nintendo', 1989, 'GB'),
(90, 'Tony Hawk\'s Pro Skater', 'Sports', 'Activision', 2000, 'GB'),
(91, 'GameBoy Wars', 'Strategy', 'Nintendo', 1991, 'GB'),
(92, 'Mini-Yonku GB: Let\'s & Go!!', 'Strategy', 'ASCII Entertainment', 1997, 'GB'),
(93, 'Pokemon Card GB2: Here Comes Team GR!', 'Strategy', 'Nintendo', 2001, 'GB'),
(94, 'Pokémon Trading Card Game', 'Strategy', 'Nintendo', 1998, 'GB'),
(95, 'Trade & Battle: Card Hero', 'Strategy', 'Nintendo', 2000, 'GB'),
(96, 'Yu-Gi-Oh! Duel Monsters', 'Strategy', 'Konami Digital Entertainment', 1998, 'GB'),
(97, 'Yu-Gi-Oh! Duel Monsters II: Dark Duel Stories', 'Strategy', 'Konami Digital Entertainment', 1999, 'GB');
