
-- --------------------------------------------------------

--
-- Struttura della tabella `gba`
--

DROP TABLE IF EXISTS `gba`;
CREATE TABLE IF NOT EXISTS `gba` (
  `id` int NOT NULL AUTO_INCREMENT,
  `game_name` varchar(200) CHARACTER SET utf8mb3 DEFAULT NULL,
  `genre_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  `publisher_name` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL,
  `release_year` int DEFAULT NULL,
  `platform_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=812 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dump dei dati per la tabella `gba`
--

INSERT INTO `gba` (`id`, `game_name`, `genre_name`, `publisher_name`, `release_year`, `platform_name`) VALUES
(1, '2 Games in 1 Double Pack: The Incredibles / Finding Nemo: The Continuing Adventures', 'Action', 'THQ', 2007, 'GBA'),
(2, '2 Games in 1: Disney\'s Brother Bear / The Lion King 1 1/2', 'Action', 'THQ', 2005, 'GBA'),
(3, 'Alienators: Evolution Continues', 'Action', 'Activision', 2001, 'GBA'),
(4, 'Altered Beast: Guardian of the Realms', 'Action', 'THQ', 2002, 'GBA'),
(5, 'Around the World in 80 Days', 'Action', 'Hip Interactive', 2004, 'GBA'),
(6, 'Astro Boy: Omega Factor', 'Action', 'THQ', 2003, 'GBA'),
(7, 'Barbie and the Magic of Pegasus', 'Action', 'Vivendi Games', 2005, 'GBA'),
(8, 'Barnyard', 'Action', 'THQ', 2006, 'GBA'),
(9, 'Batman Begins', 'Action', 'Electronic Arts', 2005, 'GBA'),
(10, 'Batman: Rise of Sin Tzu', 'Action', 'Ubisoft', 2003, 'GBA'),
(11, 'BattleBots: Beyond the BattleBox', 'Action', 'Vivendi Games', 2002, 'GBA'),
(12, 'Battlebots: Design & Destroy', 'Action', 'Majesco Entertainment', 2003, 'GBA'),
(13, 'Beyblade G-Revolution', 'Action', 'Atari', 2004, 'GBA'),
(14, 'Beyblade VForce: Ultimate Blader Jam', 'Action', 'Atari', 2003, 'GBA'),
(15, 'Big Idea\'s VeggieTales: LarryBoy and the Bad Apple', 'Action', 'Crave Entertainment', 2006, 'GBA'),
(16, 'Bionicle', 'Action', 'THQ', 2003, 'GBA'),
(17, 'Blackthorne', 'Action', 'Activision', 2003, 'GBA'),
(18, 'Boboboubo Boubobo: Ougi 87.5 Bakuretsu Hanage Shinken', 'Action', 'Hudson Soft', 2002, 'GBA'),
(19, 'Buffy the Vampire Slayer: Wrath of the Darkhul King', 'Action', 'THQ', 2003, 'GBA'),
(20, 'Butt Ugly Martians: B.K.M. Battles', 'Action', 'Vivendi Games', 2002, 'GBA'),
(21, 'Care Bears - Care Quest', 'Action', 'Game Factory', 2005, 'GBA'),
(22, 'Catwoman', 'Action', 'Electronic Arts', 2004, 'GBA'),
(23, 'Chicken Shoot', 'Action', 'Zoo Digital Publishing', 2005, 'GBA'),
(24, 'Classic NES Series: Bomberman', 'Action', 'Nintendo', 2004, 'GBA'),
(25, 'Crayon Shin-Chan: Densetsu o Yobu Omake no To Shukkugaan!', 'Action', 'Banpresto', 2006, 'GBA'),
(26, 'Crouching Tiger, Hidden Dragon', 'Action', 'Ubisoft', 2003, 'GBA'),
(27, 'CT Special Forces', 'Action', 'LSP Games', 2002, 'GBA'),
(28, 'Curious George', 'Action', 'Namco Bandai Games', 2006, 'GBA'),
(29, 'Danny Phantom: The Ultimate Enemy', 'Action', 'THQ', 2005, 'GBA'),
(30, 'Dinotopia: The Timestone Pirates', 'Action', 'TDK Core', 2002, 'GBA'),
(31, 'Disney\'s Brother Bear', 'Action', 'THQ', 2003, 'GBA'),
(32, 'Disney\'s Home on the Range', 'Action', 'Disney Interactive Studios', 2004, 'GBA'),
(33, 'Disney\'s Magical Quest 2 Starring Mickey and Minnie', 'Action', 'Capcom', 2003, 'GBA'),
(34, 'Disney\'s Magical Quest 3 Starring Mickey and Donald', 'Action', 'Capcom', 2003, 'GBA'),
(35, 'Disney\'s Magical Quest Starring Mickey and Minnie', 'Action', 'Nintendo', 2002, 'GBA'),
(36, 'Disney\'s Tarzan: Return to the Jungle', 'Action', 'Activision', 2002, 'GBA'),
(37, 'Disney\'s Treasure Planet', 'Action', 'Ubisoft', 2002, 'GBA'),
(38, 'Double Dragon Advance', 'Action', 'Atlus', 2003, 'GBA'),
(39, 'Dr. Seuss: Green Eggs and Ham', 'Action', 'NewKidCo', 2003, 'GBA'),
(40, 'Dragon Ball GT: Transformation', 'Action', 'Atari', 2005, 'GBA'),
(41, 'Dragon Ball Z: Buu\'s Fury', 'Action', 'Atari', 2004, 'GBA'),
(42, 'Dragon Ball Z: Buu\'s Fury / Dragon Ball GT: Transformation', 'Action', 'Atari', 2006, 'GBA'),
(43, 'Dragon Ball: Advanced Adventure', 'Action', 'Namco Bandai Games', 2004, 'GBA'),
(44, 'Driver 2 Advance', 'Action', 'Atari', 2002, 'GBA'),
(45, 'Dynasty Warriors Advance', 'Action', 'Nintendo', 2005, 'GBA'),
(46, 'E.T. The Extra-Terrestrial', 'Action', 'NewKidCo', 2001, 'GBA'),
(47, 'Elf: The Movie', 'Action', 'Crave Entertainment', 2004, 'GBA'),
(48, 'F-14 Tomcat', 'Action', 'Majesco Entertainment', 2001, 'GBA'),
(49, 'Famicom Mini: Adventure Island', 'Action', 'Hudson Soft', 2004, 'GBA'),
(50, 'Famicom Mini: Balloon Fight', 'Action', 'Nintendo', 2004, 'GBA'),
(51, 'Famicom Mini: Nazo no Murasame-Jou', 'Action', 'Nintendo', 2004, 'GBA'),
(52, 'Fantastic 4: Flame On', 'Action', 'Activision', 2005, 'GBA'),
(53, 'Fear Factor: Unleashed', 'Action', 'Hip Interactive', 2004, 'GBA'),
(54, 'Finding Nemo', 'Action', 'THQ', 2003, 'GBA'),
(55, 'Finding Nemo: The Continuing Adventures', 'Action', 'THQ', 2004, 'GBA'),
(56, 'Fortress', 'Action', 'Majesco Entertainment', 2001, 'GBA'),
(57, 'Frogger Advance: The Great Quest', 'Action', 'Konami Digital Entertainment', 2002, 'GBA'),
(58, 'Frogger\'s Journey: The Forgotten Relic', 'Action', 'Konami Digital Entertainment', 2003, 'GBA'),
(59, 'Galidor: Defenders of the Outer Dimension', 'Action', 'Electronic Arts', 2002, 'GBA'),
(60, 'Games Explosion!', 'Action', 'THQ', 2006, 'GBA'),
(61, 'Gekido Advance: Kintaro\'s Revenge', 'Action', 'Zoo Digital Publishing', 2002, 'GBA'),
(62, 'Grand Theft Auto', 'Action', 'Take-Two Interactive', 2004, 'GBA'),
(63, 'Gumby vs. the Astrobots', 'Action', 'Namco Bandai Games', 2005, 'GBA'),
(64, 'Gyakuten Saiban 2', 'Action', 'Capcom', 2002, 'GBA'),
(65, 'Hamtaro: Ham-Ham Heartbreak', 'Action', 'Nintendo', 2002, 'GBA'),
(66, 'Harry Potter and the Chamber of Secrets', 'Action', 'Electronic Arts', 2002, 'GBA'),
(67, 'Harry Potter and the Goblet of Fire', 'Action', 'Electronic Arts', 2005, 'GBA'),
(68, 'Harry Potter and the Prisoner of Azkaban', 'Action', 'Electronic Arts', 2004, 'GBA'),
(69, 'Harry Potter and the Sorcerer\'s Stone', 'Action', 'Electronic Arts', 2001, 'GBA'),
(70, 'He-Man: Power of Grayskull', 'Action', 'TDK Mediactive', 2002, 'GBA'),
(71, 'Hi Hi Puffy AmiYumi: Kaznapped', 'Action', 'D3Publisher', 2005, 'GBA'),
(72, 'Hot Potato!', 'Action', 'BAM! Entertainment', 2001, 'GBA'),
(73, 'Ice Age', 'Action', 'Ubisoft', 2002, 'GBA'),
(74, 'Jackie Chan Adventures: Legend of the Dark Hand', 'Action', 'Activision', 2001, 'GBA'),
(75, 'Jet Grind Radio', 'Action', 'Sega', 2003, 'GBA'),
(76, 'Jim Henson\'s Muppets in Spy Muppets: License to Croak', 'Action', 'TDK Mediactive', 2003, 'GBA'),
(77, 'Jim Henson\'s the Muppets: On With the Show!', 'Action', 'TDK Mediactive', 2003, 'GBA'),
(78, 'Justice League Heroes: The Flash', 'Action', 'Eidos Interactive', 2006, 'GBA'),
(79, 'Kong: King of Atlantis', 'Action', 'THQ', 2005, 'GBA'),
(80, 'Kong: The 8th Wonder of the World', 'Action', 'Ubisoft', 2005, 'GBA'),
(81, 'Kong: The Animated Series', 'Action', 'BAM! Entertainment', 2002, 'GBA'),
(82, 'Kouchuu Ouja Mushi King', 'Action', 'Sega', 2005, 'GBA'),
(83, 'LEGO Knights\' Kingdom', 'Action', 'THQ', 2004, 'GBA'),
(84, 'LEGO Star Wars II: The Original Trilogy', 'Action', 'LucasArts', 2006, 'GBA'),
(85, 'LEGO Star Wars: The Video Game', 'Action', 'Eidos Interactive', 2005, 'GBA'),
(86, 'Lilo & Stitch 2: Hämsterviel Havoc', 'Action', 'Disney Interactive Studios', 2004, 'GBA'),
(87, 'Lizzie McGuire 2: Lizzie Diaries', 'Action', 'Disney Interactive Studios', 2004, 'GBA'),
(88, 'Madagascar: Operation Penguin', 'Action', 'Activision', 2005, 'GBA'),
(89, 'Mega Man Battle Network 2', 'Action', 'Ubisoft', 2002, 'GBA'),
(90, 'Metroid Fusion', 'Action', 'Nintendo', 2002, 'GBA'),
(91, 'Minority Report: Everybody Runs', 'Action', 'Activision', 2002, 'GBA'),
(92, 'Naruto: Ninja Council', 'Action', 'Tomy Corporation', 2003, 'GBA'),
(93, 'Nicktoons: Freeze Frame Frenzy', 'Action', 'THQ', 2004, 'GBA'),
(94, 'No Rules: Get Phat', 'Action', 'TDK Mediactive', 2001, 'GBA'),
(95, 'Operation Armored Liberty', 'Action', 'Majesco Entertainment', 2003, 'GBA'),
(96, 'Pac-Man World 2', 'Action', 'Zoo Digital Publishing', 2005, 'GBA'),
(97, 'Planet Monsters', 'Action', 'Titus', 2001, 'GBA'),
(98, 'Planet of the Apes', 'Action', 'Ubisoft', 2001, 'GBA'),
(99, 'Polly Pocket: Super Splash Island', 'Action', 'Knowledge Adventure', 2003, 'GBA'),
(100, 'Power Rangers Double Pack', 'Action', 'THQ', 2005, 'GBA'),
(101, 'Power Rangers: Dino Thunder', 'Action', 'THQ', 2003, 'GBA'),
(102, 'Power Rangers: S.P.D.', 'Action', 'THQ', 2004, 'GBA'),
(103, 'Power Rangers: Time Force', 'Action', 'THQ', 2001, 'GBA'),
(104, 'Power Rangers: Wild Force', 'Action', 'THQ', 2002, 'GBA'),
(105, 'Prince of Persia: The Sands of Time', 'Action', 'Ubisoft', 2003, 'GBA'),
(106, 'Ratatouille', 'Action', 'THQ', 2007, 'GBA'),
(107, 'Rescue Heroes: Billy Blazes', 'Action', 'Vivendi Games', 2003, 'GBA'),
(108, 'River City Ransom EX', 'Action', 'Atlus', 2004, 'GBA'),
(109, 'Rocket Power: Dream Scheme', 'Action', 'THQ', 2001, 'GBA'),
(110, 'Rugrats: Castle Capers', 'Action', 'THQ', 2001, 'GBA'),
(111, 'Rugrats: I Gotta Go Party', 'Action', 'THQ', 2002, 'GBA'),
(112, 'Sabrina The Teenage Witch: Potion Commotion', 'Action', 'Ubisoft', 2002, 'GBA'),
(113, 'Scooby-Doo 2: Monsters Unleashed', 'Action', 'THQ', 2004, 'GBA'),
(114, 'Scooby-Doo! Mystery Mayhem', 'Action', 'THQ', 2003, 'GBA'),
(115, 'Shark Tale', 'Action', 'Activision', 2004, 'GBA'),
(116, 'Shonen Jump\'s Shaman King: Legacy of the Spirits - Soaring Hawk/Sprinting Wolf', 'Action', 'Konami Digital Entertainment', 2005, 'GBA'),
(117, 'Shrek SuperSlam', 'Action', 'Activision', 2005, 'GBA'),
(118, 'Shrek: Hassle at the Castle', 'Action', 'TDK Mediactive', 2002, 'GBA'),
(119, 'Sky Dancers', 'Action', 'Crave Entertainment', 2005, 'GBA'),
(120, 'Spider-Man 2', 'Action', 'Activision', 2004, 'GBA'),
(121, 'Spider-Man: Mysterio\'s Menace', 'Action', 'Activision', 2001, 'GBA'),
(122, 'Spider-Man: The Movie', 'Action', 'Activision', 2002, 'GBA'),
(123, 'Spongebob Squarepants / Fairly Odd Parents Double Pack', 'Action', 'THQ', 2005, 'GBA'),
(124, 'SpongeBob SquarePants: SuperSponge', 'Action', 'THQ', 2001, 'GBA'),
(125, 'Spyro Orange: The Cortex Conspiracy', 'Action', 'Vivendi Games', 2004, 'GBA'),
(126, 'Star Wars Episode II: Attack of the Clones', 'Action', 'THQ', 2002, 'GBA'),
(127, 'Star Wars Episode III: Revenge of the Sith', 'Action', 'Ubisoft', 2005, 'GBA'),
(128, 'Star Wars Trilogy: Apprentice of the Force', 'Action', 'Ubisoft', 2004, 'GBA'),
(129, 'Star Wars: Flight of the Falcon', 'Action', 'THQ', 2003, 'GBA'),
(130, 'Star Wars: Jedi Power Battles', 'Action', 'THQ', 2002, 'GBA'),
(131, 'Super Army War', 'Action', 'Flashpoint Games', 2005, 'GBA'),
(132, 'Teenage Mutant Ninja Turtles', 'Action', 'Unknown', 2003, 'GBA'),
(133, 'Teenage Mutant Ninja Turtles 2: Battle Nexus', 'Action', 'Konami Digital Entertainment', 2004, 'GBA'),
(134, 'Teenage Mutant Ninja Turtles Double Pack', 'Action', 'Konami Digital Entertainment', 2006, 'GBA'),
(135, 'Terminator 3: Rise of the Machines', 'Action', 'Atari', 2003, 'GBA'),
(136, 'The Adventures of Jimmy Neutron Boy Genius vs. Jimmy Negatron', 'Action', 'THQ', 2002, 'GBA'),
(137, 'The Adventures of Jimmy Neutron Boy Genius: Attack of the Twonkies', 'Action', 'THQ', 2004, 'GBA'),
(138, 'The Adventures of Jimmy Neutron Boy Genius: Jet Fusion', 'Action', 'THQ', 2003, 'GBA'),
(139, 'The Incredible Hulk', 'Action', 'Universal Interactive', 2003, 'GBA'),
(140, 'The Incredibles', 'Action', 'THQ', 2004, 'GBA'),
(141, 'The Incredibles: Rise of the Underminer', 'Action', 'THQ', 2005, 'GBA'),
(142, 'The Invincible Iron Man', 'Action', 'Activision', 2002, 'GBA'),
(143, 'The Legend of Zelda: A Link to the Past', 'Action', 'Nintendo', 2002, 'GBA'),
(144, 'The Legend of Zelda: The Minish Cap', 'Action', 'Nintendo', 2004, 'GBA'),
(145, 'The Lord of the Rings: The Return of the King', 'Action', 'Electronic Arts', 2003, 'GBA'),
(146, 'The Lord of the Rings: The Two Towers', 'Action', 'Electronic Arts', 2002, 'GBA'),
(147, 'The Mummy', 'Action', 'Ubisoft', 2002, 'GBA'),
(148, 'The Ripping Friends', 'Action', 'THQ', 2002, 'GBA'),
(149, 'The Scorpion King: Sword of Osiris', 'Action', 'Vivendi Games', 2002, 'GBA'),
(150, 'The Wild Thornberrys: Chimp Chase', 'Action', 'THQ', 2001, 'GBA'),
(151, 'Tom and Jerry: Infurnal Escape', 'Action', 'Ubisoft', 2003, 'GBA'),
(152, 'Tom Clancy\'s Splinter Cell', 'Action', 'Ubisoft', 2003, 'GBA'),
(153, 'Tom Clancy\'s Splinter Cell: Pandora Tomorrow', 'Action', 'Ubisoft', 2004, 'GBA'),
(154, 'Tomb Raider: The Prophecy', 'Action', 'Ubisoft', 2002, 'GBA'),
(155, 'Tron 2.0: Killer App', 'Action', 'Disney Interactive Studios', 2004, 'GBA'),
(156, 'Ty the Tasmanian Tiger 3: Night of the Quinkan', 'Action', 'Zoo Digital Publishing', 2005, 'GBA'),
(157, 'Ultimate Spider-Man', 'Action', 'Activision', 2005, 'GBA'),
(158, 'Van Helsing', 'Action', 'Activision', 2004, 'GBA'),
(159, 'X-Men: Reign of Apocalypse', 'Action', 'Activision', 2001, 'GBA'),
(160, 'X-Men: The Official Game', 'Action', 'Activision', 2006, 'GBA'),
(161, 'XXX', 'Action', 'Activision', 2002, 'GBA'),
(162, 'Yu Yu Hakusho Ghost Files: Spirit Detective', 'Action', 'Atari', 2003, 'GBA'),
(163, 'Barbie as The Island Princess', 'Adventure', 'Activision', 2007, 'GBA'),
(164, 'Barbie as the Princess and the Pauper', 'Adventure', 'Vivendi Games', 2004, 'GBA'),
(165, 'Batman: Vengeance', 'Adventure', 'Ubisoft', 2001, 'GBA'),
(166, 'Broken Sword: The Shadow of the Templars', 'Adventure', 'BAM! Entertainment', 2002, 'GBA'),
(167, 'Casper', 'Adventure', 'Microids', 2002, 'GBA'),
(168, 'Charlie and the Chocolate Factory', 'Adventure', 'Global Star', 2005, 'GBA'),
(169, 'Chicken Shoot 2', 'Adventure', 'Zoo Digital Publishing', 2005, 'GBA'),
(170, 'Classic NES Series: Metroid', 'Adventure', 'Nintendo', 2004, 'GBA'),
(171, 'Classic NES Series: The Legend of Zelda', 'Adventure', 'Nintendo', 2004, 'GBA'),
(172, 'Classic NES Series: Zelda II: The Adventure of Link', 'Adventure', 'Nintendo', 2004, 'GBA'),
(173, 'Dexter\'s Laboratory Deesaster Strikes', 'Adventure', 'BAM! Entertainment', 2001, 'GBA'),
(174, 'Dora the Explorer: Super Star Adventures', 'Adventure', 'Game Factory', 2004, 'GBA'),
(175, 'Dora the Explorer: The Search for Pirate Pig\'s Treasure', 'Adventure', 'NewKidCo', 2002, 'GBA'),
(176, 'Ed, Edd n Eddy: Jawbreakers!', 'Adventure', 'BAM! Entertainment', 2002, 'GBA'),
(177, 'everGirl', 'Adventure', 'THQ', 2005, 'GBA'),
(178, 'Famicom Mini: Famicom Mukashi Banashi - Shin Oniga Shima Zenkouhen', 'Adventure', 'Nintendo', 2004, 'GBA'),
(179, 'Famicom Mini: Famicom Tantei Club - Kieta Koukeisha Zenkouhen', 'Adventure', 'Nintendo', 2004, 'GBA'),
(180, 'Famicom Mini: Famicom Tantei Club Part II - Ushiro ni Tatsu Shoujo Zenkouhen', 'Adventure', 'Nintendo', 2004, 'GBA'),
(181, 'Frogger\'s Adventures 2: The Lost Wand', 'Adventure', 'Konami Digital Entertainment', 2002, 'GBA'),
(182, 'Gyakuten Saiban 3', 'Adventure', 'Capcom', 2004, 'GBA'),
(183, 'Jurassic Park III: Island Attack', 'Adventure', 'Konami Digital Entertainment', 2001, 'GBA'),
(184, 'Konjiki no Gashbell!! Makai no Bookmark', 'Adventure', 'Banpresto', 2004, 'GBA'),
(185, 'Let\'s Ride! Dreamer', 'Adventure', 'DTP Entertainment', 2005, 'GBA'),
(186, 'Metroid: Zero Mission', 'Adventure', 'Nintendo', 2004, 'GBA'),
(187, 'Monster House', 'Adventure', 'THQ', 2006, 'GBA'),
(188, 'Monsters, Inc.', 'Adventure', 'THQ', 2001, 'GBA'),
(189, 'Pirates of the Caribbean: Dead Man\'s Chest', 'Adventure', 'Disney Interactive Studios', 2006, 'GBA'),
(190, 'Scooby-Doo and the Cyber Chase', 'Adventure', 'Ubisoft', 2001, 'GBA'),
(191, 'SeaWorld Adventure Parks: Shamu\'s Deep Sea Adventure', 'Adventure', 'Activision', 2005, 'GBA'),
(192, 'Shrek 2: Beg for Mercy', 'Adventure', 'Activision', 2004, 'GBA'),
(193, 'Slime MoriMori Dragon Quest: Shougeki No Shippo Dan', 'Adventure', 'Square Enix', 2003, 'GBA'),
(194, 'Strawberry Shortcake: Summertime Adventure', 'Adventure', 'Majesco Entertainment', 2004, 'GBA'),
(195, 'That\'s So Raven', 'Adventure', 'Disney Interactive Studios', 2004, 'GBA'),
(196, 'That\'s So Raven 2: Supernatural Style', 'Adventure', 'Disney Interactive Studios', 2005, 'GBA'),
(197, 'The Fairly Odd Parents: Clash with the Anti-World', 'Adventure', 'THQ', 2005, 'GBA'),
(198, 'The Polar Express', 'Adventure', 'THQ', 2004, 'GBA'),
(199, 'Thomas the Tank Engine & Friends', 'Adventure', 'N/A', 2004, 'GBA'),
(200, 'Digimon Battle Spirit 2', 'Fighting', 'Namco Bandai Games', 2003, 'GBA'),
(201, 'Dragon Ball Z: Supersonic Warriors', 'Fighting', 'Atari', 2004, 'GBA'),
(202, 'Dragon Ball Z: Taiketsu', 'Fighting', 'Atari', 2003, 'GBA'),
(203, 'Final Fight One', 'Fighting', 'Ubisoft', 2001, 'GBA'),
(204, 'Fire ProWrestling', 'Fighting', 'Spike', 2001, 'GBA'),
(205, 'Godzilla: Domination!', 'Fighting', 'Atari', 2002, 'GBA'),
(206, 'Guilty Gear X: Advance Edition', 'Fighting', 'Sammy Corporation', 2002, 'GBA'),
(207, 'Gundam Seed: Battle Assault', 'Fighting', 'Namco Bandai Games', 2004, 'GBA'),
(208, 'Hajime no Ippo: The Fighting', 'Fighting', 'ESP', 2002, 'GBA'),
(209, 'Legends of Wrestling II', 'Fighting', 'Acclaim Entertainment', 2002, 'GBA'),
(210, 'Mortal Kombat: Deadly Alliance', 'Fighting', 'Midway Games', 2002, 'GBA'),
(211, 'Mortal Kombat: Tournament Edition', 'Fighting', 'Midway Games', 2003, 'GBA'),
(212, 'Mucha Lucha! Mascaritas of the Lost Code', 'Fighting', 'Ubisoft', 2003, 'GBA'),
(213, 'Punch King', 'Fighting', 'Acclaim Entertainment', 2002, 'GBA'),
(214, 'Rave Master: Special Attack Force!', 'Fighting', 'Konami Digital Entertainment', 2002, 'GBA'),
(215, 'Street Fighter Alpha 3', 'Fighting', 'Capcom', 2002, 'GBA'),
(216, 'Super Street Fighter II: Turbo Revival', 'Fighting', 'Ubisoft', 2001, 'GBA'),
(217, 'Tekken Advance', 'Fighting', 'Infogrames', 2001, 'GBA'),
(218, 'The King of Fighters EX2: Howling Blood', 'Fighting', 'Marvelous Interactive', 2002, 'GBA'),
(219, 'Ultimate Muscle - The Kinnikuman Legacy: The Path of the Superhero', 'Fighting', 'Banpresto', 2002, 'GBA'),
(220, 'WWE Road to WrestleMania X8', 'Fighting', 'THQ', 2002, 'GBA'),
(221, 'WWE Survivor Series', 'Fighting', 'THQ', 2004, 'GBA'),
(222, 'Zatch Bell! Electric Arena', 'Fighting', 'Banpresto', 2003, 'GBA'),
(223, '2 Games in 1: Disney Princess & The Lion King', 'Misc', 'THQ', 2004, 'GBA'),
(224, '2 Games in 1: Sonic Advance & ChuChu Rocket!', 'Misc', 'THQ', 2005, 'GBA'),
(225, '2 Games in 1: Sonic Battle & ChuChu Rocket!', 'Misc', 'THQ', 2005, 'GBA'),
(226, '2 Games in 1: Sonic Pinball Party & Columns Crown', 'Misc', 'Sega', 2005, 'GBA'),
(227, 'Activision Anthology', 'Misc', 'Activision', 2003, 'GBA'),
(228, 'All Grown Up! Express Yourself', 'Misc', 'THQ', 2004, 'GBA'),
(229, 'All Grown Up!: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(230, 'American Idol', 'Misc', 'Codemasters', 2003, 'GBA'),
(231, 'Archer Maclean\'s 3D Pool', 'Misc', 'Crave Entertainment', 2003, 'GBA'),
(232, 'Atari Anniversary Advance', 'Misc', 'Atari', 2002, 'GBA'),
(233, 'Barbie Groovy Games', 'Misc', 'Universal Interactive', 2002, 'GBA'),
(234, 'Barbie Superpack: Secret Agent / Groovy Games', 'Misc', 'Vivendi Games', 2005, 'GBA'),
(235, 'Bentley\'s Hackpack', 'Misc', 'N/A', 2005, 'GBA'),
(236, 'Board Game Classics', 'Misc', 'Destination Software, Inc', 2005, 'GBA'),
(237, 'Bratz: Rock Angelz', 'Misc', 'THQ', 2004, 'GBA'),
(238, 'Britney\'s Dance Beat', 'Misc', 'THQ', 2002, 'GBA'),
(239, 'Cabbage Patch Kids: The Patch Puppy Rescue', 'Misc', 'D3Publisher', 2007, 'GBA'),
(240, 'Caesars Palace Advance: Millennium Gold Edition', 'Misc', 'Majesco Entertainment', 2001, 'GBA'),
(241, 'CandyLand / Chutes & Ladders / Memory', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(242, 'Cartoon Network Block Party', 'Misc', 'Majesco Entertainment', 2004, 'GBA'),
(243, 'Cartoon Network Block Party / Cartoon Network Speedway Double Pack', 'Misc', 'THQ', 2005, 'GBA'),
(244, 'Cartoon Network Collection: Game Boy Advance Video Platinum Edition', 'Misc', 'N/A', 2005, 'GBA'),
(245, 'Cartoon Network Collection: Game Boy Advance Video Special Edition', 'Misc', 'N/A', 2005, 'GBA'),
(246, 'Cartoon Network Collection: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(247, 'Cartoon Network Collection: Game Boy Advance Video Volume 2', 'Misc', 'N/A', 2004, 'GBA'),
(248, 'Centipede / Breakout / Warlords', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(249, 'Chessmaster', 'Misc', 'Ubisoft', 2002, 'GBA'),
(250, 'Codename: Kids Next Door: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(251, 'Connect Four / Perfection / Trouble', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(252, 'Crash Superpack: Crash Bandicoot 2: N-Tranced / Crash Nitro Kart', 'Misc', 'Vivendi Games', 2005, 'GBA'),
(253, 'Dexter\'s Lab Chess Challenge', 'Misc', 'BAM! Entertainment', 2002, 'GBA'),
(254, 'Disney Channel Collection Vol. 1', 'Misc', 'N/A', 2004, 'GBA'),
(255, 'Disney\'s Party', 'Misc', 'Hudson Entertainment', 2003, 'GBA'),
(256, 'Dora the Explorer: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(257, 'Dragon Ball GT: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(258, 'Dragon Ball Z: Collectible Card Game', 'Misc', 'Infogrames', 2002, 'GBA'),
(259, 'Duel Masters: Kaijudo Showdown', 'Misc', 'Atari', 2004, 'GBA'),
(260, 'Duel Masters: Sempai Legends', 'Misc', 'Atari', 2003, 'GBA'),
(261, 'Duel Masters: Shadow of the Code', 'Misc', 'Atari', 2004, 'GBA'),
(262, 'EX Monopoly', 'Misc', 'Takara', 2001, 'GBA'),
(263, 'Franklin the Turtle', 'Misc', 'Game Factory', 2005, 'GBA'),
(264, 'Game & Watch Gallery 4', 'Misc', 'Nintendo', 2002, 'GBA'),
(265, 'Gauntlet / Rampart', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(266, 'Golden Nugget Casino', 'Misc', 'Majesco Entertainment', 2004, 'GBA'),
(267, 'Golden Nugget Casino / Texas Hold \'Em Double Pack', 'Misc', 'Majesco Entertainment', 2005, 'GBA'),
(268, 'Hello Kitty: Happy Party Pals', 'Misc', 'THQ', 2005, 'GBA'),
(269, 'Konami Collector\'s Series: Arcade Advanced', 'Misc', 'Konami Digital Entertainment', 2002, 'GBA'),
(270, 'Mario Party Advance', 'Misc', 'Nintendo', 2005, 'GBA'),
(271, 'Mario Pinball Land', 'Misc', 'Nintendo', 2004, 'GBA'),
(272, 'Mary-Kate and Ashley: Girls Night Out', 'Misc', 'Acclaim Entertainment', 2002, 'GBA'),
(273, 'Mega Man Battle Chip Challenge', 'Misc', 'Capcom', 2003, 'GBA'),
(274, 'Midway\'s Greatest Arcade Hits', 'Misc', 'Midway Games', 2001, 'GBA'),
(275, 'Millipede / Super Breakout / Lunar Lander', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(276, 'Mousetrap / Operation / Simon', 'Misc', 'DSI Games', 2005, 'GBA'),
(277, 'Namco Museum', 'Misc', 'Namco Bandai Games', 2001, 'GBA'),
(278, 'Namco Museum: 50th Anniversary', 'Misc', 'Namco Bandai Games', 2005, 'GBA'),
(279, 'Nicktoons Collection: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(280, 'Nicktoons Collection: Game Boy Advance Video Volume 2', 'Misc', 'N/A', 2004, 'GBA'),
(281, 'Nicktoons Collection: Game Boy Advance Video Volume 3', 'Misc', 'N/A', 2005, 'GBA'),
(282, 'Pac-Man Pinball Advance', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(283, 'Paperboy / Rampage', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(284, 'Petz: Hamsterz Life 2', 'Misc', 'Ubisoft', 2007, 'GBA'),
(285, 'Pinball Tycoon', 'Misc', 'Ignition Entertainment', 2002, 'GBA'),
(286, 'Pocket Dogs', 'Misc', 'Agatsuma Entertainment', 2004, 'GBA'),
(287, 'Pokémon Beach Blank-out Blastoise / Go West Young Meowth Game Boy Advance Video', 'Misc', 'Nintendo', 2004, 'GBA'),
(288, 'Pokémon I Choose You / Squirtle Squad Game Boy Advance Video', 'Misc', 'Nintendo', 2004, 'GBA'),
(289, 'Pokemon Pinball: Ruby & Sapphire', 'Misc', 'Nintendo', 2003, 'GBA'),
(290, 'Pokémon: For Ho-Oh the Bells Toll!: Game Boy Advance Video', 'Misc', 'Nintendo', 2004, 'GBA'),
(291, 'Pokémon: Johto Photo Finish: Game Boy Advance Video', 'Misc', 'N/A', 2004, 'GBA'),
(292, 'Pong / Asteroids / Yars\' Revenge', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(293, 'Power Rangers: Ninja Storm', 'Misc', 'THQ', 2003, 'GBA'),
(294, 'Rhythm Tengoku', 'Misc', 'Nintendo', 2006, 'GBA'),
(295, 'Risk / Battleship / Clue', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(296, 'Scrabble Blast!', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(297, 'Sega Arcade Gallery', 'Misc', 'THQ', 2003, 'GBA'),
(298, 'Sega Smash Pack', 'Misc', 'Atari', 2002, 'GBA'),
(299, 'Shrek / Shark Tale Game Boy Advance Video', 'Misc', 'Hasbro Interactive', 2006, 'GBA'),
(300, 'Shrek / Shrek 2 2-in-1 Gameboy Advance Video', 'Misc', 'N/A', 2007, 'GBA'),
(301, 'Shrek 2 and Shark Tale 2-in-1 Pack', 'Misc', 'Activision', 2005, 'GBA'),
(302, 'Sonic Advance & Sonic Pinball Party Combo Pack', 'Misc', 'Sega', 2005, 'GBA'),
(303, 'Sonic X: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(304, 'Sorry! / Aggravation / Scrabble Junior', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(305, 'Space Channel 5: Ulala\'s Cosmic Attack', 'Misc', 'Atari', 2002, 'GBA'),
(306, 'SpongeBob SquarePants: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(307, 'SpongeBob SquarePants: Game Boy Advance Video Volume 2', 'Misc', 'N/A', 2004, 'GBA'),
(308, 'SpongeBob SquarePants: Game Boy Advance Video Volume 3', 'Misc', 'N/A', 2004, 'GBA'),
(309, 'SpongeBob SquarePants: Lights, Camera, Pants!', 'Misc', 'THQ', 2005, 'GBA'),
(310, 'Strawberry Shortcake: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(311, 'Super Robot Monkey Team: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2005, 'GBA'),
(312, 'Teenage Mutant Ninja Turtles: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(313, 'Texas Hold \'Em Poker', 'Misc', 'Majesco Entertainment', 2004, 'GBA'),
(314, 'The Bible Game', 'Misc', 'Crave Entertainment', 2005, 'GBA'),
(315, 'The Cheetah Girls', 'Misc', 'Disney Interactive Studios', 2006, 'GBA'),
(316, 'The Fairly Odd Parents: Game Boy Advance Video Volume 1', 'Misc', 'N/A', 2004, 'GBA'),
(317, 'The Fairly Odd Parents: Game Boy Advance Video Volume 2', 'Misc', 'N/A', 2004, 'GBA'),
(318, 'The Game of Life / Yahtzee / Payday', 'Misc', 'Zoo Digital Publishing', 2005, 'GBA'),
(319, 'The Pinball of the Dead', 'Misc', 'Sega', 2002, 'GBA'),
(320, 'Trollz: Hair Affair!', 'Misc', 'Ubisoft', 2005, 'GBA'),
(321, 'Ultimate Brain Games', 'Misc', 'Telegames', 2003, 'GBA'),
(322, 'Ultimate Card Games', 'Misc', 'Telegames', 2003, 'GBA'),
(323, 'World Championship Poker', 'Misc', 'Crave Entertainment', 2004, 'GBA'),
(324, 'World Poker Tour', 'Misc', 'Take-Two Interactive', 2005, 'GBA'),
(325, 'Yu-Gi-Oh! 7 Trials to Glory: World Championship Tournament 2005', 'Misc', 'Konami Digital Entertainment', 2005, 'GBA'),
(326, 'Yu-Gi-Oh! Destiny Board Traveler', 'Misc', 'Konami Digital Entertainment', 2004, 'GBA'),
(327, 'Yu-Gi-Oh! Dungeon Dice Monsters', 'Misc', 'Konami Digital Entertainment', 2001, 'GBA'),
(328, 'Yu-Gi-Oh! GX: Duel Academy', 'Misc', 'Konami Digital Entertainment', 2005, 'GBA'),
(329, 'Yu-Gi-Oh! The Eternal Duelist Soul (JP sales)', 'Misc', 'Konami Digital Entertainment', 2001, 'GBA'),
(330, 'Yu-Gi-Oh! Ultimate Masters: World Championship Tournament 2006', 'Misc', 'Konami Digital Entertainment', 2006, 'GBA'),
(331, 'Yu-Gi-Oh! World Championship Tournament 2004', 'Misc', 'Konami Digital Entertainment', 2004, 'GBA'),
(332, 'Yu-Gi-Oh! Worldwide Edition: Stairway to the Destined Duel', 'Misc', 'Konami Digital Entertainment', 2003, 'GBA'),
(333, '2 Games in 1: SpongeBob SquarePants: SuperSponge & Rugrats Go Wild', 'Platform', 'THQ', 2005, 'GBA'),
(334, '2-in-1 Game Pack: Spider-Man & Spider-Man 2', 'Platform', 'Activision', 2005, 'GBA'),
(335, 'An American Tail: Fievel\'s Gold Rush', 'Platform', 'Conspiracy Entertainment', 2002, 'GBA'),
(336, 'Banjo-Kazooie: Grunty\'s Revenge', 'Platform', 'THQ', 2003, 'GBA'),
(337, 'Bionicle: Matoran Adventures', 'Platform', 'Electronic Arts', 2002, 'GBA'),
(338, 'Blender Bros.', 'Platform', 'Unknown', 2002, 'GBA'),
(339, 'Bratz', 'Platform', 'Ubisoft', 2002, 'GBA'),
(340, 'Castlevania Double Pack', 'Platform', 'Konami Digital Entertainment', 2006, 'GBA'),
(341, 'Castlevania: Aria of Sorrow', 'Platform', 'Konami Digital Entertainment', 2003, 'GBA'),
(342, 'Castlevania: Circle of the Moon', 'Platform', 'Konami Digital Entertainment', 2001, 'GBA'),
(343, 'Castlevania: Harmony of Dissonance', 'Platform', 'Konami Digital Entertainment', 2002, 'GBA'),
(344, 'Classic NES Series: Castlevania', 'Platform', 'Nintendo', 2004, 'GBA'),
(345, 'Classic NES Series: Donkey Kong', 'Platform', 'Nintendo', 2004, 'GBA'),
(346, 'Classic NES Series: Ice Climber', 'Platform', 'Nintendo', 2004, 'GBA'),
(347, 'Classic NES Series: Super Mario Bros.', 'Platform', 'Nintendo', 2004, 'GBA'),
(348, 'Codename: Kids Next Door: Operation S.O.D.A.', 'Platform', 'Global Star', 2004, 'GBA'),
(349, 'Crash & Spyro Superpack', 'Platform', 'Vivendi Games', 2005, 'GBA'),
(350, 'Crash Bandicoot 2: N-Tranced', 'Platform', 'Vivendi Games', 2003, 'GBA'),
(351, 'Crash Bandicoot Purple: Ripto\'s Rampage', 'Platform', 'Vivendi Games', 2004, 'GBA'),
(352, 'Crash Bandicoot: The Huge Adventure', 'Platform', 'Universal Interactive', 2002, 'GBA'),
(353, 'Densetsu no Stafi', 'Platform', 'Nintendo', 2002, 'GBA'),
(354, 'Densetsu no Stafi 2', 'Platform', 'Nintendo', 2003, 'GBA'),
(355, 'Densetsu no Stafi 3', 'Platform', 'Nintendo', 2004, 'GBA'),
(356, 'Disney Princess', 'Platform', 'THQ', 2003, 'GBA'),
(357, 'Disney\'s Aladdin', 'Platform', 'Capcom', 2003, 'GBA'),
(358, 'Disney\'s Atlantis: The Lost Empire', 'Platform', 'THQ', 2001, 'GBA'),
(359, 'Disney\'s Chicken Little', 'Platform', 'Disney Interactive Studios', 2005, 'GBA'),
(360, 'Disney\'s Donald Duck Advance', 'Platform', 'Ubisoft', 2001, 'GBA'),
(361, 'Disney\'s Kim Possible 2: Drakken\'s Demise', 'Platform', 'Disney Interactive Studios', 2004, 'GBA'),
(362, 'Disney\'s Kim Possible 3: Team Possible', 'Platform', 'Disney Interactive Studios', 2005, 'GBA'),
(363, 'Disney\'s Kim Possible: Revenge of Monkey Fist', 'Platform', 'THQ', 2002, 'GBA'),
(364, 'Disney\'s Lilo & Stitch', 'Platform', 'Ubisoft', 2002, 'GBA'),
(365, 'Disney\'s Peter Pan: Return to Never Land', 'Platform', 'Ubisoft', 2002, 'GBA'),
(366, 'Disney\'s The Jungle Book', 'Platform', 'Ubisoft', 2002, 'GBA'),
(367, 'Disney\'s Winnie the Pooh\'s Rumbly Tumbly Adventure', 'Platform', 'Ubisoft', 2005, 'GBA'),
(368, 'DK: King of Swing', 'Platform', 'Nintendo', 2005, 'GBA'),
(369, 'Donkey Kong Country', 'Platform', 'Nintendo', 2003, 'GBA'),
(370, 'Donkey Kong Country 2', 'Platform', 'Nintendo', 2004, 'GBA'),
(371, 'Donkey Kong Country 3', 'Platform', 'Nintendo', 2005, 'GBA'),
(372, 'Dora the Explorer: Super Spies', 'Platform', 'Gotham Games', 2004, 'GBA'),
(373, 'Dragon Tales: Dragon Adventures', 'Platform', 'NewKidCo', 2003, 'GBA'),
(374, 'Earthworm Jim', 'Platform', 'Interplay', 2001, 'GBA'),
(375, 'Earthworm Jim 2', 'Platform', 'Vivendi Games', 2002, 'GBA'),
(376, 'Ed, Edd n Eddy: The Mis-Edventures', 'Platform', 'Midway Games', 2005, 'GBA'),
(377, 'Famicom Mini: Ganbare Goemon! Karakuri Douchuu', 'Platform', 'Konami Digital Entertainment', 2004, 'GBA'),
(378, 'Famicom Mini: Hikari Shinwa: Palutena no Kagami', 'Platform', 'Nintendo', 2004, 'GBA'),
(379, 'Famicom Mini: Makaimura', 'Platform', 'Capcom', 2004, 'GBA'),
(380, 'Famicom Mini: Mappy', 'Platform', 'Nintendo', 2004, 'GBA'),
(381, 'Famicom Mini: Mario Bros.', 'Platform', 'Nintendo', 2004, 'GBA'),
(382, 'Famicom Mini: Super Mario Bros. 2', 'Platform', 'Nintendo', 2004, 'GBA'),
(383, 'Garfield: The Search for Pooky', 'Platform', 'Game Factory', 2003, 'GBA'),
(384, 'Hey Arnold! The Movie', 'Platform', 'THQ', 2002, 'GBA'),
(385, 'Ice Age 2: The Meltdown', 'Platform', 'Vivendi Games', 2006, 'GBA'),
(386, 'James Pond: Codename Robocod', 'Platform', 'Play It', 2005, 'GBA'),
(387, 'Jimmy Neutron: Boy Genius', 'Platform', 'THQ', 2001, 'GBA'),
(388, 'Justice League: Chronicles', 'Platform', 'Midway Games', 2003, 'GBA'),
(389, 'Kao the Kangaroo', 'Platform', 'Titus', 2001, 'GBA'),
(390, 'Kirby & the Amazing Mirror', 'Platform', 'Nintendo', 2004, 'GBA'),
(391, 'Kirby: Nightmare in Dream Land', 'Platform', 'Nintendo', 2002, 'GBA'),
(392, 'Klonoa 2: Dream Champ Tournament', 'Platform', 'Namco Bandai Games', 2002, 'GBA'),
(393, 'Klonoa: Empire of Dreams', 'Platform', 'Infogrames', 2001, 'GBA'),
(394, 'Lady Sia', 'Platform', 'TDK Mediactive', 2001, 'GBA'),
(395, 'LEGO Bionicle', 'Platform', 'LEGO Media', 2001, 'GBA'),
(396, 'Lemony Snicket\'s A Series of Unfortunate Events', 'Platform', 'Activision', 2004, 'GBA'),
(397, 'Lizzie McGuire 3: Homecoming Havoc', 'Platform', 'Disney Interactive Studios', 2005, 'GBA'),
(398, 'Looney Tunes: Back in Action', 'Platform', 'Electronic Arts', 2003, 'GBA'),
(399, 'Madagascar', 'Platform', 'Activision', 2005, 'GBA'),
(400, 'Mega Man & Bass', 'Platform', 'Capcom', 2002, 'GBA'),
(401, 'Mega Man Zero', 'Platform', 'Capcom', 2002, 'GBA'),
(402, 'Mega Man Zero 2', 'Platform', 'Capcom', 2003, 'GBA'),
(403, 'Mega Man Zero 3', 'Platform', 'Capcom', 2004, 'GBA'),
(404, 'Mega Man Zero 4', 'Platform', 'Capcom', 2005, 'GBA'),
(405, 'Mission: Impossible - Operation Surma', 'Platform', 'Atari', 2003, 'GBA'),
(406, 'Oddworld: Munch\'s Oddysee', 'Platform', 'THQ', 2003, 'GBA'),
(407, 'Over the Hedge', 'Platform', 'Activision', 2006, 'GBA'),
(408, 'Ozzy & Drix', 'Platform', 'Midway Games', 2003, 'GBA'),
(409, 'Piglet\'s Big Game', 'Platform', 'THQ', 2003, 'GBA'),
(410, 'Pinobee: Wings of Adventure', 'Platform', 'Hudson Entertainment', 2001, 'GBA'),
(411, 'Pirates of the Caribbean: The Curse of the Black Pearl', 'Platform', 'TDK Mediactive', 2003, 'GBA'),
(412, 'Pitfall: The Lost Expedition', 'Platform', 'Activision', 2003, 'GBA'),
(413, 'Pitfall: The Mayan Adventure', 'Platform', 'Interplay', 2001, 'GBA'),
(414, 'Popeye: Rush for Spinach', 'Platform', 'Atari', 2005, 'GBA'),
(415, 'Prehistorik Man', 'Platform', 'THQ', 2001, 'GBA'),
(416, 'Rayman 10th Anniversary', 'Platform', 'Ubisoft', 2005, 'GBA'),
(417, 'Rayman 3', 'Platform', 'Ubisoft', 2003, 'GBA'),
(418, 'Rayman Advance', 'Platform', 'Ubisoft', 2001, 'GBA'),
(419, 'Rayman: Hoodlum\'s Revenge', 'Platform', 'Ubisoft', 2005, 'GBA'),
(420, 'Rocket Power: Beach Bandits', 'Platform', 'THQ', 2002, 'GBA'),
(421, 'Samurai Jack: The Amulet of Time', 'Platform', 'Zoo Digital Publishing', 2003, 'GBA'),
(422, 'Scooby-Doo', 'Platform', 'THQ', 2001, 'GBA'),
(423, 'Scooby-Doo! Unmasked', 'Platform', 'THQ', 2005, 'GBA'),
(424, 'Secret Agent Barbie: Royal Jewels Mission', 'Platform', 'Vivendi Games', 2002, 'GBA'),
(425, 'Shrek: Reekin\' Havoc', 'Platform', 'TDK Mediactive', 2003, 'GBA'),
(426, 'Sitting Ducks', 'Platform', 'LSP Games', 2003, 'GBA'),
(427, 'Sonic Advance', 'Platform', 'Sega', 2001, 'GBA'),
(428, 'Sonic Advance 2', 'Platform', 'Sega', 2002, 'GBA'),
(429, 'Sonic Advance 3', 'Platform', 'THQ', 2004, 'GBA'),
(430, 'Spirit: Stallion of the Cimarron', 'Platform', 'THQ', 2002, 'GBA'),
(431, 'Spirits & Spells', 'Platform', 'Wanadoo', 2003, 'GBA'),
(432, 'SpongeBob SquarePants: Battle for Bikini Bottom', 'Platform', 'THQ', 2003, 'GBA'),
(433, 'SpongeBob SquarePants: Double Pack', 'Platform', 'THQ', 2005, 'GBA'),
(434, 'SpongeBob SquarePants: Revenge of the Flying Dutchman', 'Platform', 'THQ', 2002, 'GBA'),
(435, 'Spy Kids 3-D: Game Over', 'Platform', 'Disney Interactive Studios', 2003, 'GBA'),
(436, 'Spy Kids Challenger', 'Platform', 'Disney Interactive Studios', 2002, 'GBA'),
(437, 'Spyro 2: Season of Flame', 'Platform', 'Vivendi Games', 2002, 'GBA'),
(438, 'Spyro: Attack of the Rhynocs', 'Platform', 'Universal Interactive', 2003, 'GBA'),
(439, 'Spyro: Season of Ice', 'Platform', 'Vivendi Games', 2001, 'GBA'),
(440, 'Stuart Little 2', 'Platform', 'Activision', 2002, 'GBA'),
(441, 'Super Ghouls \'n Ghosts', 'Platform', 'Capcom', 2002, 'GBA'),
(442, 'Super Mario Advance', 'Platform', 'Nintendo', 2001, 'GBA'),
(443, 'Super Mario Bros. 3', 'Platform', 'Nintendo', 2003, 'GBA'),
(444, 'Super Mario World', 'Platform', 'Nintendo', 2001, 'GBA'),
(445, 'Super Mario World 2: Yoshi\'s Island', 'Platform', 'Nintendo', 2002, 'GBA'),
(446, 'Superman: Countdown to Apokolips', 'Platform', 'Atari', 2003, 'GBA'),
(447, 'Tak 2: The Staff of Dreams', 'Platform', 'THQ', 2004, 'GBA'),
(448, 'Tak and the Power of Juju', 'Platform', 'THQ', 2003, 'GBA'),
(449, 'Tak: The Great Juju Challenge', 'Platform', 'THQ', 2005, 'GBA'),
(450, 'The Ant Bully', 'Platform', 'Midway Games', 2006, 'GBA'),
(451, 'The Berenstain Bears and the Spooky Old Tree', 'Platform', 'Namco Bandai Games', 2005, 'GBA'),
(452, 'The Cat in the Hat', 'Platform', 'Jack of All Games', 2005, 'GBA'),
(453, 'The Fairly Odd Parents: Breakin\' Da Rules', 'Platform', 'THQ', 2003, 'GBA'),
(454, 'The Fairly Odd Parents: Enter the Cleft', 'Platform', 'THQ', 2002, 'GBA'),
(455, 'The Fairly Odd Parents: Shadow Showdown', 'Platform', 'THQ', 2004, 'GBA'),
(456, 'The Flintstones: Big Trouble in Bedrock', 'Platform', 'Swing! Entertainment', 2001, 'GBA'),
(457, 'The Hobbit', 'Platform', 'Vivendi Games', 2003, 'GBA'),
(458, 'The Land Before Time: Into the Mysterious Beyond', 'Platform', 'Game Factory', 2006, 'GBA'),
(459, 'The Powerpuff Girls: Him and Seek', 'Platform', 'BAM! Entertainment', 2002, 'GBA'),
(460, 'The Revenge of Shinobi', 'Platform', 'Atari', 2002, 'GBA'),
(461, 'The SpongeBob SquarePants Movie', 'Platform', 'THQ', 2004, 'GBA'),
(462, 'The Wild Thornberrys Movie', 'Platform', 'THQ', 2002, 'GBA'),
(463, 'Tim Burton\'s The Nightmare Before Christmas: The Pumpkin King', 'Platform', 'Disney Interactive Studios', 2005, 'GBA'),
(464, 'Totally Spies!', 'Platform', 'Atari', 2005, 'GBA'),
(465, 'Ty the Tasmanian Tiger 2: Bush Rescue', 'Platform', 'Electronic Arts', 2004, 'GBA'),
(466, 'Walt Disney Pictures Presents: The Wild', 'Platform', 'Disney Interactive Studios', 2006, 'GBA'),
(467, 'Wario Land 4', 'Platform', 'Nintendo', 2001, 'GBA'),
(468, 'Woody Woodpecker in Crazy Castle 5', 'Platform', 'Kemco', 2002, 'GBA'),
(469, 'X2: Wolverine\'s Revenge', 'Platform', 'Activision', 2003, 'GBA'),
(470, 'Yoshi Topsy-Turvy', 'Platform', 'Nintendo', 2004, 'GBA'),
(471, 'Zapper: One Wicked Cricket!', 'Platform', 'Infogrames', 2002, 'GBA'),
(472, 'Atomic Betty', 'Puzzle', 'Atari', 2005, 'GBA'),
(473, 'Bomberman Max 2: Blue Advance', 'Puzzle', 'Vivendi Games', 2002, 'GBA'),
(474, 'Bomberman Max 2: Red Advance', 'Puzzle', 'Vivendi Games', 2002, 'GBA'),
(475, 'Bomberman Tournament', 'Puzzle', 'Activision', 2001, 'GBA'),
(476, 'Bookworm', 'Puzzle', 'Unknown', 2004, 'GBA'),
(477, 'Bubble Bobble: Old & New', 'Puzzle', 'Empire Interactive', 2002, 'GBA'),
(478, 'Classic NES Series: Dr. Mario', 'Puzzle', 'Nintendo', 2004, 'GBA'),
(479, 'Classic NES Series: Pac-Man', 'Puzzle', 'Nintendo', 2004, 'GBA'),
(480, 'Denki Blocks!', 'Puzzle', 'Rage Software', 2001, 'GBA'),
(481, 'Dr. Mario / Puzzle League', 'Puzzle', 'Nintendo', 2005, 'GBA'),
(482, 'Famicom Mini: Clu Clu Land', 'Puzzle', 'Nintendo', 2004, 'GBA'),
(483, 'Famicom Mini: Dig Dug', 'Puzzle', 'Namco Bandai Games', 2004, 'GBA'),
(484, 'Famicom Mini: Wrecking Crew', 'Puzzle', 'Nintendo', 2004, 'GBA'),
(485, 'KuruKuru Kururin', 'Puzzle', 'Nintendo', 2001, 'GBA'),
(486, 'Kururin Paradise', 'Puzzle', 'Unknown', 2002, 'GBA'),
(487, 'M&M\'s Blast!', 'Puzzle', 'Unknown', 2001, 'GBA'),
(488, 'Marble Madness / Klax', 'Puzzle', 'Zoo Digital Publishing', 2005, 'GBA'),
(489, 'Mario vs. Donkey Kong', 'Puzzle', 'Nintendo', 2004, 'GBA'),
(490, 'Mighty Beanz: Pocket Puzzles', 'Puzzle', 'Majesco Entertainment', 2004, 'GBA'),
(491, 'Mr. Driller 2', 'Puzzle', 'Namco Bandai Games', 2001, 'GBA'),
(492, 'Ms. Pac-Man Maze Madness', 'Puzzle', 'Zoo Digital Publishing', 2004, 'GBA'),
(493, 'Ms. Pac-Man: Maze Madness / Pac-Man World', 'Puzzle', 'Namco Bandai Games', 2005, 'GBA'),
(494, 'Pac-Man Collection', 'Puzzle', 'Atari', 2001, 'GBA'),
(495, 'Puyo Pop', 'Puzzle', 'Sega', 2001, 'GBA'),
(496, 'Snood', 'Puzzle', 'Destination Software, Inc', 2001, 'GBA'),
(497, 'Snood 2: On Vacation', 'Puzzle', 'Zoo Digital Publishing', 2005, 'GBA'),
(498, 'Sudoku Fever', 'Puzzle', 'Take-Two Interactive', 2006, 'GBA'),
(499, 'Super Bust-A-Move', 'Puzzle', 'Ubisoft', 2001, 'GBA'),
(500, 'Super Collapse! II', 'Puzzle', 'Majesco Entertainment', 2004, 'GBA'),
(501, 'Super Monkey Ball Jr.', 'Puzzle', 'Atari', 2002, 'GBA'),
(502, 'Tetris Worlds', 'Puzzle', 'THQ', 2001, 'GBA'),
(503, 'The Lost Vikings', 'Puzzle', 'Activision', 2003, 'GBA'),
(504, 'Tiny Toon Adventures: Wacky Stackers', 'Puzzle', 'Conspiracy Entertainment', 2001, 'GBA'),
(505, 'Tringo', 'Puzzle', 'Liquid Games', 2006, 'GBA'),
(506, 'Turbo Turtle Adventure', 'Puzzle', 'Majesco Entertainment', 2002, 'GBA'),
(507, 'Ultimate Puzzle Games', 'Puzzle', 'Telegames', 2005, 'GBA'),
(508, 'WarioWare, Inc.: Mega MicroGame$', 'Puzzle', 'Nintendo', 2003, 'GBA'),
(509, 'Whac-A-Mole', 'Puzzle', 'Zoo Digital Publishing', 2005, 'GBA'),
(510, 'ZooCube', 'Puzzle', 'Acclaim Entertainment', 2002, 'GBA'),
(511, '2 Games in 1 Double Pack: Hot Wheels Velocity X / Hot Wheels World Race', 'Racing', 'THQ', 2005, 'GBA'),
(512, 'ATV: Quad Power Racing', 'Racing', 'Liquid Games', 2002, 'GBA'),
(513, 'Banjo-Pilot', 'Racing', 'THQ', 2005, 'GBA'),
(514, 'Big Mutha Truckers', 'Racing', 'Zoo Digital Publishing', 2005, 'GBA'),
(515, 'Cars', 'Racing', 'THQ', 2006, 'GBA'),
(516, 'Classic NES Series: Excitebike', 'Racing', 'Nintendo', 2004, 'GBA'),
(517, 'Colin McRae Rally 2.0', 'Racing', 'Codemasters', 2002, 'GBA'),
(518, 'Corvette', 'Racing', 'TDK Mediactive', 2003, 'GBA'),
(519, 'Crash City Mayhem', 'Racing', 'THQ', 2004, 'GBA'),
(520, 'Crash Nitro Kart', 'Racing', 'Vivendi Games', 2003, 'GBA'),
(521, 'Crazy Taxi: Catch a Ride', 'Racing', 'THQ', 2003, 'GBA'),
(522, 'Demon Driver: Time to Burn Rubber!', 'Racing', 'Ignition Entertainment', 2003, 'GBA'),
(523, 'Digimon Racing', 'Racing', 'Namco Bandai Games', 2004, 'GBA'),
(524, 'Driv3r', 'Racing', 'Atari', 2005, 'GBA'),
(525, 'Driven', 'Racing', 'BAM! Entertainment', 2001, 'GBA'),
(526, 'Drome Racers', 'Racing', 'THQ', 2003, 'GBA'),
(527, 'F-Zero: GP Legend', 'Racing', 'Nintendo', 2003, 'GBA'),
(528, 'F-Zero: Maximum Velocity', 'Racing', 'Nintendo', 2001, 'GBA'),
(529, 'F1 2002', 'Racing', 'Destination Software, Inc', 2002, 'GBA'),
(530, 'Ford Racing 3', 'Racing', 'Zoo Digital Publishing', 2005, 'GBA'),
(531, 'Freekstyle', 'Racing', 'Zoo Digital Publishing', 2003, 'GBA'),
(532, 'GT Advance 2: Rally Racing', 'Racing', 'THQ', 2001, 'GBA'),
(533, 'GT Advance 3: Pro Concept Racing', 'Racing', 'THQ', 2002, 'GBA'),
(534, 'GT Advance Championship Racing', 'Racing', 'THQ', 2001, 'GBA'),
(535, 'Herbie: Fully Loaded', 'Racing', 'Disney Interactive Studios', 2005, 'GBA'),
(536, 'Hot Wheels Velocity X', 'Racing', 'THQ', 2002, 'GBA'),
(537, 'Hot Wheels: Burnin\' Rubber', 'Racing', 'THQ', 2001, 'GBA'),
(538, 'Hot Wheels: Stunt Track Challenge', 'Racing', 'THQ', 2004, 'GBA'),
(539, 'Hot Wheels: Stunt Track Challenge / World Race', 'Racing', 'Destination Software, Inc', 2006, 'GBA'),
(540, 'Hot Wheels: World Race', 'Racing', 'THQ', 2003, 'GBA'),
(541, 'Karnaaj Rally', 'Racing', 'Jaleco', 2003, 'GBA'),
(542, 'Konami Krazy Racers', 'Racing', 'Konami Digital Entertainment', 2001, 'GBA'),
(543, 'LEGO Island Xtreme Stunts', 'Racing', 'LEGO Media', 2002, 'GBA'),
(544, 'Mario Kart: Super Circuit', 'Racing', 'Nintendo', 2001, 'GBA'),
(545, 'Matchbox Cross Town Heroes', 'Racing', 'THQ', 2002, 'GBA'),
(546, 'Midnight Club: Street Racing', 'Racing', 'Rebellion', 2001, 'GBA'),
(547, 'Monster Jam: Maximum Destruction', 'Racing', 'Ubisoft', 2002, 'GBA'),
(548, 'Monster Truck Madness', 'Racing', 'THQ', 2003, 'GBA'),
(549, 'Monster Trucks', 'Racing', 'Majesco Entertainment', 2004, 'GBA'),
(550, 'Moto Racer Advance', 'Racing', 'Ubisoft', 2002, 'GBA'),
(551, 'Motocross Maniacs Advance', 'Racing', 'Konami Digital Entertainment', 2002, 'GBA'),
(552, 'MotoGP', 'Racing', 'THQ', 2002, 'GBA'),
(553, 'MX 2002 Featuring Ricky Carmichael', 'Racing', 'THQ', 2001, 'GBA'),
(554, 'NASCAR Heat 2002', 'Racing', 'Infogrames', 2002, 'GBA'),
(555, 'Need for Speed Underground', 'Racing', 'Electronic Arts', 2003, 'GBA'),
(556, 'Need for Speed Underground 2', 'Racing', 'Electronic Arts', 2004, 'GBA'),
(557, 'Need for Speed: Most Wanted', 'Racing', 'Electronic Arts', 2005, 'GBA'),
(558, 'Need for Speed: Porsche Unleashed', 'Racing', 'Zoo Digital Publishing', 2004, 'GBA'),
(559, 'NickToons: Racing', 'Racing', 'Infogrames', 2002, 'GBA'),
(560, 'Racing Gears Advance', 'Racing', 'Zoo Digital Publishing', 2004, 'GBA'),
(561, 'Road Rash: Jailbreak', 'Racing', 'Zoo Digital Publishing', 2003, 'GBA'),
(562, 'Road Trip: Shifting Gears', 'Racing', 'Zoo Digital Publishing', 2002, 'GBA'),
(563, 'Rock \'N Roll Racing', 'Racing', 'Activision', 2003, 'GBA'),
(564, 'Shrek Swamp Kart Speedway', 'Racing', 'TDK Mediactive', 2002, 'GBA'),
(565, 'Smashing Drive', 'Racing', 'Zoo Digital Publishing', 2004, 'GBA'),
(566, 'Smuggler\'s Run', 'Racing', 'Rebellion', 2002, 'GBA'),
(567, 'Spy Hunter / Super Sprint', 'Racing', 'Zoo Digital Publishing', 2005, 'GBA'),
(568, 'Starsky & Hutch', 'Racing', 'Empire Interactive', 2003, 'GBA'),
(569, 'Stuntman', 'Racing', 'Atari', 2003, 'GBA'),
(570, 'The Simpsons: Road Rage', 'Racing', 'THQ', 2003, 'GBA'),
(571, 'Thunder Alley', 'Racing', 'XS Games', 2004, 'GBA'),
(572, 'Tokyo Xtreme Racer Advance', 'Racing', 'Crave Entertainment', 2005, 'GBA'),
(573, 'Top Gear Rally', 'Racing', 'Kemco', 2003, 'GBA'),
(574, 'V-Rally 3', 'Racing', 'Atari', 2002, 'GBA'),
(575, 'Advance Guardian Heroes', 'Role-Playing', 'Ubisoft', 2004, 'GBA'),
(576, 'Baldur\'s Gate: Dark Alliance', 'Role-Playing', 'Destination Software, Inc', 2004, 'GBA'),
(577, 'Boktai 2: Solar Boy Django', 'Role-Playing', 'Konami Digital Entertainment', 2004, 'GBA'),
(578, 'Boktai: The Sun is in Your Hand', 'Role-Playing', 'Konami Digital Entertainment', 2003, 'GBA'),
(579, 'Breath of Fire', 'Role-Playing', 'Ubisoft', 2001, 'GBA'),
(580, 'Breath of Fire II', 'Role-Playing', 'Ubisoft', 2001, 'GBA'),
(581, 'Car Battler Joe', 'Role-Playing', 'Victor Interactive', 2001, 'GBA'),
(582, 'CIMA: The Enemy', 'Role-Playing', 'Marvelous Interactive', 2003, 'GBA'),
(583, 'DemiKids: Dark Version', 'Role-Playing', 'Atlus', 2002, 'GBA'),
(584, 'DemiKids: Light Version', 'Role-Playing', 'Atlus', 2002, 'GBA'),
(585, 'Dragon Ball Z: The Legacy of Goku', 'Role-Playing', 'Infogrames', 2002, 'GBA'),
(586, 'Dragon Ball Z: The Legacy of Goku I & II', 'Role-Playing', 'Atari', 2005, 'GBA'),
(587, 'Dragon Ball Z: The Legacy of Goku II', 'Role-Playing', 'Atari', 2003, 'GBA'),
(588, 'Dragon Quest Monsters: Caravan Heart', 'Role-Playing', 'Enix Corporation', 2003, 'GBA'),
(589, 'Dungeons & Dragons: Eye of the Beholder', 'Role-Playing', 'Atari', 2002, 'GBA'),
(590, 'Eyeshield 21: DevilBats DevilDays', 'Role-Playing', 'Nintendo', 2006, 'GBA'),
(591, 'Final Fantasy I & II: Dawn of Souls', 'Role-Playing', 'Nintendo', 2004, 'GBA'),
(592, 'Final Fantasy IV Advance', 'Role-Playing', 'Nintendo', 2005, 'GBA'),
(593, 'Final Fantasy Tactics Advance', 'Role-Playing', 'SquareSoft', 2003, 'GBA'),
(594, 'Final Fantasy V Advance', 'Role-Playing', 'Nintendo', 2006, 'GBA'),
(595, 'Final Fantasy VI Advance', 'Role-Playing', 'Nintendo', 2006, 'GBA'),
(596, 'Fire Emblem: Fuuin no Tsurugi', 'Role-Playing', 'Nintendo', 2002, 'GBA'),
(597, 'Golden Sun', 'Role-Playing', 'Nintendo', 2001, 'GBA'),
(598, 'Golden Sun: The Lost Age', 'Role-Playing', 'Nintendo', 2002, 'GBA'),
(599, 'Kingdom Hearts: Chain of Memories', 'Role-Playing', 'Square Enix', 2004, 'GBA'),
(600, 'Klonoa Heroes: Densetsu no Star Medal', 'Role-Playing', 'Namco Bandai Games', 2002, 'GBA'),
(601, 'Lufia: The Ruins of Lore', 'Role-Playing', 'Taito', 2002, 'GBA'),
(602, 'Lunar Legend', 'Role-Playing', 'Media Rings', 2002, 'GBA'),
(603, 'Magical Vacation', 'Role-Playing', 'Nintendo', 2001, 'GBA'),
(604, 'Mahou Sensei Negima! Private Lesson 2: Ojama Shimasu Parasite de Chu', 'Role-Playing', 'Marvelous Interactive', 2006, 'GBA'),
(605, 'Mario & Luigi: Superstar Saga', 'Role-Playing', 'Nintendo', 2003, 'GBA'),
(606, 'Medabots AX: Metabee', 'Role-Playing', 'Natsume', 2002, 'GBA'),
(607, 'Medabots: Metabee', 'Role-Playing', 'Natsume', 2002, 'GBA'),
(608, 'Mega Man Battle Network', 'Role-Playing', 'Capcom', 2001, 'GBA'),
(609, 'Mega Man Battle Network 3 Blue / White Version', 'Role-Playing', 'Capcom', 2002, 'GBA'),
(610, 'Mega Man Battle Network 4: Red Sun / Blue Moon', 'Role-Playing', 'Capcom', 2003, 'GBA'),
(611, 'Mega Man Battle Network 5: Team Colonel / Protoman', 'Role-Playing', 'Capcom', 2004, 'GBA'),
(612, 'Mega Man Battle Network 6: Cybeast Falzar / Gregar', 'Role-Playing', 'Capcom', 2005, 'GBA'),
(613, 'Monster Guardians', 'Role-Playing', 'Konami Digital Entertainment', 2001, 'GBA'),
(614, 'Mother 1+2', 'Role-Playing', 'Nintendo', 2003, 'GBA'),
(615, 'Mother 3', 'Role-Playing', 'Nintendo', 2006, 'GBA'),
(616, 'Phantasy Star Collection', 'Role-Playing', 'Atari', 2002, 'GBA'),
(617, 'Pokémon Emerald Version', 'Role-Playing', 'Nintendo', 2004, 'GBA'),
(618, 'Pokemon FireRed/Pokemon LeafGreen', 'Role-Playing', 'Nintendo', 2004, 'GBA'),
(619, 'Pokémon Mystery Dungeon: Red Rescue Team (US weekly sales)', 'Role-Playing', 'Nintendo', 2005, 'GBA'),
(620, 'Pokemon Mystery Dungeon: Red/Blue Rescue Team', 'Role-Playing', 'Nintendo', 2005, 'GBA'),
(621, 'Pokemon Ruby/Pokemon Sapphire', 'Role-Playing', 'Nintendo', 2002, 'GBA'),
(622, 'Riviera: The Promised Land', 'Role-Playing', 'Sting', 2004, 'GBA'),
(623, 'Robopon 2: Cross Version', 'Role-Playing', 'Hudson Entertainment', 2001, 'GBA'),
(624, 'Robopon 2: Ring Version', 'Role-Playing', 'Hudson Entertainment', 2001, 'GBA'),
(625, 'RockMan EXE 4.5 Real Operation', 'Role-Playing', 'Capcom', 2004, 'GBA'),
(626, 'Shaman King: Chou Senjiryokketsu 3', 'Role-Playing', 'King Records', 2002, 'GBA'),
(627, 'Shining Force: Resurrection of the Dark Dragon', 'Role-Playing', 'THQ', 2004, 'GBA'),
(628, 'Shining Soul', 'Role-Playing', 'Atari', 2002, 'GBA'),
(629, 'Shining Soul II', 'Role-Playing', 'THQ', 2003, 'GBA'),
(630, 'Shonen Jump\'s Shaman King: Master of Spirits', 'Role-Playing', 'Konami Digital Entertainment', 2004, 'GBA'),
(631, 'Shonen Jump\'s Shaman King: Master of Spirits 2', 'Role-Playing', 'Konami Digital Entertainment', 2005, 'GBA'),
(632, 'Sigma Star Saga', 'Role-Playing', 'Atari', 2005, 'GBA'),
(633, 'Summon Night Craft Sword Monogatari: Hajimari no Ishi', 'Role-Playing', 'Banpresto', 2005, 'GBA'),
(634, 'Summon Night: Swordcraft Story', 'Role-Playing', 'Banpresto', 2003, 'GBA'),
(635, 'Super Robot Taisen: Original Generation', 'Role-Playing', 'Banpresto', 2002, 'GBA'),
(636, 'Sword of Mana', 'Role-Playing', 'Nintendo', 2003, 'GBA'),
(637, 'Tactics Ogre: The Knight of Lodis', 'Role-Playing', 'Nintendo', 2001, 'GBA'),
(638, 'Tales of Phantasia', 'Role-Playing', 'Nintendo', 2003, 'GBA'),
(639, 'Tales of the World: Narikiri Dungeon 2', 'Role-Playing', 'Namco Bandai Games', 2002, 'GBA'),
(640, 'The Lord of the Rings: The Third Age', 'Role-Playing', 'Electronic Arts', 2004, 'GBA'),
(641, 'Yggdra Union: We\'ll Never Fight Alone', 'Role-Playing', 'Sting', 2006, 'GBA'),
(642, 'Yu-Gi-Oh! Double Pack', 'Role-Playing', 'Konami Digital Entertainment', 2006, 'GBA'),
(643, 'Yu-Gi-Oh! The Sacred Cards', 'Role-Playing', 'Konami Digital Entertainment', 2002, 'GBA'),
(644, 'Yu-Gi-Oh! The Sacred Cards (American and Others sales)', 'Role-Playing', 'Konami Digital Entertainment', 2002, 'GBA'),
(645, 'Yu-Gi-Oh! The Sacred Cards (JP weekly sales)', 'Role-Playing', 'Konami Digital Entertainment', 2002, 'GBA'),
(646, 'Zoids: Legacy', 'Role-Playing', 'Tomy Corporation', 2003, 'GBA'),
(647, 'Zone of the Enders: The Fist of Mars', 'Role-Playing', 'Konami Digital Entertainment', 2001, 'GBA'),
(648, 'AirForce Delta Storm', 'Shooter', 'Konami Digital Entertainment', 2002, 'GBA'),
(649, 'Ballistic: Ecks vs. Sever', 'Shooter', 'BAM! Entertainment', 2002, 'GBA'),
(650, 'Classic NES Series: Xevious', 'Shooter', 'Nintendo', 2004, 'GBA'),
(651, 'Contra Advance: The Alien Wars EX', 'Shooter', 'Konami Digital Entertainment', 2002, 'GBA'),
(652, 'CT Special Forces 2: Back in the Trenches', 'Shooter', 'LSP Games', 2003, 'GBA'),
(653, 'Dark Arena', 'Shooter', 'THQ', 2002, 'GBA'),
(654, 'Dead to Rights', 'Shooter', 'Zoo Digital Publishing', 2004, 'GBA'),
(655, 'Doom', 'Shooter', 'Activision', 2001, 'GBA'),
(656, 'Doom II: Hell on Earth', 'Shooter', 'Activision', 2002, 'GBA'),
(657, 'Famicom Mini: Star Soldier', 'Shooter', 'Nintendo', 2004, 'GBA'),
(658, 'Famicom Mini: TwinBee', 'Shooter', 'Konami Digital Entertainment', 2004, 'GBA'),
(659, 'Gradius Galaxies', 'Shooter', 'Konami Digital Entertainment', 2001, 'GBA'),
(660, 'Greg Hastings\' Tournament Paintball Max\'d', 'Shooter', 'Activision', 2006, 'GBA'),
(661, 'Gunstar Super Heroes', 'Shooter', 'Sega', 2005, 'GBA'),
(662, 'Iridion 3D', 'Shooter', 'THQ', 2001, 'GBA'),
(663, 'Iridion II', 'Shooter', 'Vivendi Games', 2003, 'GBA'),
(664, 'James Bond 007: Everything or Nothing', 'Shooter', 'Electronic Arts', 2003, 'GBA'),
(665, 'James Bond 007: Nightfire', 'Shooter', 'Electronic Arts', 2003, 'GBA'),
(666, 'Kill.Switch', 'Shooter', 'Zoo Digital Publishing', 2004, 'GBA'),
(667, 'Max Payne', 'Shooter', 'Take-Two Interactive', 2003, 'GBA'),
(668, 'Medal of Honor: Infiltrator', 'Shooter', 'Electronic Arts', 2003, 'GBA'),
(669, 'Medal of Honor: Underground', 'Shooter', 'Zoo Digital Publishing', 2002, 'GBA'),
(670, 'Metal Slug Advance', 'Shooter', 'Ignition Entertainment', 2004, 'GBA'),
(671, 'Monster Force', 'Shooter', 'Universal Interactive', 2002, 'GBA'),
(672, 'Pocky & Rocky with Becky', 'Shooter', 'Altron', 2001, 'GBA'),
(673, 'R-Type III: The Third Lightning', 'Shooter', 'Zoo Digital Publishing', 2004, 'GBA'),
(674, 'Reign of Fire', 'Shooter', 'BAM! Entertainment', 2002, 'GBA'),
(675, 'Robotech: The Macross Saga', 'Shooter', 'TDK Mediactive', 2002, 'GBA'),
(676, 'SD Gundam Force', 'Shooter', 'Namco Bandai Games', 2004, 'GBA'),
(677, 'Serious Sam Advance', 'Shooter', 'Global Star', 2004, 'GBA'),
(678, 'Silent Scope', 'Shooter', 'Konami Digital Entertainment', 2002, 'GBA'),
(679, 'Space Invaders', 'Shooter', 'Activision', 2002, 'GBA'),
(680, 'Star X', 'Shooter', 'BAM! Entertainment', 2002, 'GBA'),
(681, 'The Sum of All Fears', 'Shooter', 'Ubisoft', 2002, 'GBA'),
(682, 'Thunderbirds', 'Shooter', 'Vivendi Games', 2004, 'GBA'),
(683, 'Tom Clancy\'s Rainbow Six: Rogue Spear', 'Shooter', 'Ubisoft', 2002, 'GBA'),
(684, 'Top Gun: Firestorm Advance', 'Shooter', 'Titus', 2002, 'GBA'),
(685, 'Turok: Evolution', 'Shooter', 'Acclaim Entertainment', 2002, 'GBA'),
(686, 'Winx Club', 'Shooter', 'Konami Digital Entertainment', 2005, 'GBA'),
(687, 'Wolfenstein 3D', 'Shooter', 'BAM! Entertainment', 2002, 'GBA'),
(688, 'Catz', 'Simulation', 'Ubisoft', 2005, 'GBA'),
(689, 'Desert Strike Advance', 'Simulation', 'Electronic Arts', 2002, 'GBA'),
(690, 'Dogz', 'Simulation', 'Ubisoft', 2004, 'GBA'),
(691, 'F/A-18F Super Hornet', 'Simulation', 'Majesco Entertainment', 2004, 'GBA'),
(692, 'Flight Control Rocket', 'Simulation', 'THQ', 2005, 'GBA'),
(693, 'Hamster Club 3', 'Simulation', 'Jorudan', 2002, 'GBA'),
(694, 'Hamster Club 4: Shigessa Daidassou', 'Simulation', 'Jorudan', 2003, 'GBA'),
(695, 'Harvest Moon: Friends of Mineral Town', 'Simulation', 'Ubisoft', 2003, 'GBA'),
(696, 'Harvest Moon: More Friends of Mineral Town', 'Simulation', 'Ubisoft', 2003, 'GBA'),
(697, 'Jurassic Park III: Park Builder', 'Simulation', 'Konami Digital Entertainment', 2001, 'GBA'),
(698, 'Monster Rancher Advance 2', 'Simulation', 'Tecmo Koei', 2002, 'GBA'),
(699, 'Paws & Claws: Pet Resort', 'Simulation', 'THQ', 2006, 'GBA'),
(700, 'SimCity 2000', 'Simulation', 'Zoo Digital Publishing', 2003, 'GBA'),
(701, 'The Sims 2', 'Simulation', 'Electronic Arts', 2005, 'GBA'),
(702, 'The Sims: Bustin\' Out', 'Simulation', 'Electronic Arts', 2003, 'GBA'),
(703, 'The Urbz: Sims in the City', 'Simulation', 'Electronic Arts', 2004, 'GBA'),
(704, 'Top Gun: Combat Zones', 'Simulation', 'Mastiff', 2004, 'GBA'),
(705, 'Wing Commander: Prophecy', 'Simulation', 'Destination Software, Inc', 2003, 'GBA'),
(706, 'All-Star Baseball 2003', 'Sports', 'Acclaim Entertainment', 2002, 'GBA'),
(707, 'All-Star Baseball 2004', 'Sports', 'Acclaim Entertainment', 2003, 'GBA'),
(708, 'American Bass Challenge', 'Sports', 'Starfish', 2001, 'GBA'),
(709, 'Backyard Baseball', 'Sports', 'Atari', 2002, 'GBA'),
(710, 'Backyard Baseball 2006', 'Sports', 'Atari', 2005, 'GBA'),
(711, 'Backyard Basketball', 'Sports', 'Atari', 2004, 'GBA'),
(712, 'Backyard Hockey', 'Sports', 'Atari', 2003, 'GBA'),
(713, 'Backyard NFL Football', 'Sports', 'Infogrames', 2002, 'GBA'),
(714, 'Backyard NFL Football 2006', 'Sports', 'Atari', 2005, 'GBA'),
(715, 'Backyard Skateboarding 2006', 'Sports', 'Atari', 2004, 'GBA'),
(716, 'Barbie Horse Adventures: Blue Ribbon Race', 'Sports', 'Knowledge Adventure', 2003, 'GBA'),
(717, 'Baseball Advance', 'Sports', 'Sega', 2002, 'GBA'),
(718, 'Boxing Fever', 'Sports', 'THQ', 2001, 'GBA'),
(719, 'Cabela\'s Big Game Hunter', 'Sports', 'Activision Value', 2002, 'GBA'),
(720, 'Cabela\'s Big Game Hunter 2005 Adventures', 'Sports', 'Activision', 2004, 'GBA'),
(721, 'Calcio Bit', 'Sports', 'Nintendo', 2006, 'GBA'),
(722, 'Crushed Baseball', 'Sports', 'Summitsoft', 2004, 'GBA'),
(723, 'Dave Mirra Freestyle BMX 2', 'Sports', 'Acclaim Entertainment', 2001, 'GBA'),
(724, 'Dave Mirra Freestyle BMX 3', 'Sports', 'Acclaim Entertainment', 2002, 'GBA'),
(725, 'Davis Cup Tennis', 'Sports', 'Ubisoft', 2002, 'GBA'),
(726, 'Derby Stallion Advance', 'Sports', 'Enterbrain', 2002, 'GBA'),
(727, 'Disney Sports Basketball', 'Sports', 'Konami Digital Entertainment', 2002, 'GBA'),
(728, 'Disney Sports Football', 'Sports', 'Unknown', 2002, 'GBA'),
(729, 'Disney Sports Skateboarding', 'Sports', 'Konami Digital Entertainment', 2002, 'GBA'),
(730, 'Disney Sports Soccer', 'Sports', 'Konami Digital Entertainment', 2002, 'GBA'),
(731, 'Disney\'s Extreme Skate Adventure', 'Sports', 'Activision', 2003, 'GBA'),
(732, 'Elf Bowling 1 & 2', 'Sports', 'Ignition Entertainment', 2005, 'GBA'),
(733, 'ESPN Final Round Golf 2002', 'Sports', 'Konami Digital Entertainment', 2001, 'GBA'),
(734, 'ESPN Great Outdoor Games Bass 2002', 'Sports', 'Konami Digital Entertainment', 2001, 'GBA'),
(735, 'ESPN Winter X-Games: Snowboarding 2002', 'Sports', 'Konami Digital Entertainment', 2000, 'GBA'),
(736, 'ESPN X Games Skateboarding', 'Sports', 'Konami Digital Entertainment', 2001, 'GBA'),
(737, 'FIFA Soccer 06', 'Sports', 'Electronic Arts', 2005, 'GBA'),
(738, 'FIFA Soccer 2003', 'Sports', 'Electronic Arts', 2002, 'GBA'),
(739, 'FIFA Soccer 2004', 'Sports', 'Electronic Arts', 2003, 'GBA'),
(740, 'FIFA Soccer 2005', 'Sports', 'Electronic Arts', 2004, 'GBA'),
(741, 'FIFA World Cup: Germany 2006', 'Sports', 'Electronic Arts', 2006, 'GBA'),
(742, 'Hamtaro: Ham-Ham Games', 'Sports', 'Nintendo', 2004, 'GBA'),
(743, 'Harry Potter: Quidditch World Cup', 'Sports', 'Electronic Arts', 2003, 'GBA'),
(744, 'Kelly Slater\'s Pro Surfer', 'Sports', 'Activision', 2002, 'GBA'),
(745, 'LEGO Soccer Mania', 'Sports', 'Electronic Arts', 2002, 'GBA'),
(746, 'Let\'s Ride: Sunshine Stables', 'Sports', 'DTP Entertainment', 2005, 'GBA'),
(747, 'Madden NFL 06', 'Sports', 'Electronic Arts', 2005, 'GBA'),
(748, 'Madden NFL 07', 'Sports', 'Electronic Arts', 2006, 'GBA'),
(749, 'Madden NFL 2002', 'Sports', 'Electronic Arts', 2001, 'GBA'),
(750, 'Madden NFL 2003', 'Sports', 'Electronic Arts', 2002, 'GBA'),
(751, 'Madden NFL 2004', 'Sports', 'Electronic Arts', 2003, 'GBA'),
(752, 'Madden NFL 2005', 'Sports', 'Electronic Arts', 2004, 'GBA'),
(753, 'Mario Golf: Advance Tour', 'Sports', 'Nintendo', 2004, 'GBA'),
(754, 'Mario Tennis: Power Tour', 'Sports', 'Nintendo', 2005, 'GBA'),
(755, 'Mat Hoffman\'s Pro BMX', 'Sports', 'Activision', 2001, 'GBA'),
(756, 'Mat Hoffman\'s Pro BMX 2', 'Sports', 'Activision', 2002, 'GBA'),
(757, 'Mike Tyson Boxing', 'Sports', 'Ubisoft', 2002, 'GBA'),
(758, 'Monster! Bass Fishing', 'Sports', 'Ignition Entertainment', 2003, 'GBA'),
(759, 'NBA Jam 2002', 'Sports', 'Acclaim Entertainment', 2002, 'GBA'),
(760, 'NHL 2002', 'Sports', 'Electronic Arts', 2002, 'GBA'),
(761, 'Power Poke Dash', 'Sports', 'Konami Digital Entertainment', 2006, 'GBA'),
(762, 'Power Pro Kun Pocket 1+2', 'Sports', 'Konami Digital Entertainment', 2004, 'GBA'),
(763, 'Power Pro Kun Pocket 3', 'Sports', 'Konami Digital Entertainment', 2001, 'GBA'),
(764, 'Power Pro Kun Pocket 4', 'Sports', 'Konami Digital Entertainment', 2002, 'GBA'),
(765, 'Power Pro Kun Pocket 5', 'Sports', 'Konami Digital Entertainment', 2003, 'GBA'),
(766, 'Power Pro Kun Pocket 6', 'Sports', 'Konami Digital Entertainment', 2003, 'GBA'),
(767, 'Rapala Pro Fishing', 'Sports', 'Zoo Digital Publishing', 2004, 'GBA'),
(768, 'Razor Freestyle Scooter', 'Sports', 'Ubisoft', 2001, 'GBA'),
(769, 'Rocket Power: Zero Gravity Zone', 'Sports', 'THQ', 2003, 'GBA'),
(770, 'Salt Lake 2002', 'Sports', 'Ubisoft', 2002, 'GBA'),
(771, 'Shaun Palmer\'s Pro Snowboarder', 'Sports', 'Activision', 2001, 'GBA'),
(772, 'Sports Illustrated for Kids: Baseball', 'Sports', 'BAM! Entertainment', 2001, 'GBA'),
(773, 'Sports Illustrated for Kids: Football', 'Sports', 'BAM! Entertainment', 2003, 'GBA'),
(774, 'SSX 3', 'Sports', 'Electronic Arts', 2003, 'GBA'),
(775, 'SSX Tricky', 'Sports', 'Electronic Arts', 2002, 'GBA'),
(776, 'Stadium Games', 'Sports', 'Ignition Entertainment', 2003, 'GBA'),
(777, 'Street Jam Basketball', 'Sports', 'Zoo Digital Publishing', 2004, 'GBA'),
(778, 'Super Dodge Ball Advance', 'Sports', 'Ubisoft', 2001, 'GBA'),
(779, 'Ten Pin Alley 2', 'Sports', 'XS Games', 2004, 'GBA'),
(780, 'Tennis no Oji-Sama: Aim at The Victory!', 'Sports', 'Konami Digital Entertainment', 2002, 'GBA'),
(781, 'Tennis no Oji-Sama: Genius Boys Academy', 'Sports', 'Konami Digital Entertainment', 2002, 'GBA'),
(782, 'Tiger Woods PGA Tour 2004', 'Sports', 'Electronic Arts', 2003, 'GBA'),
(783, 'Tiger Woods PGA Tour Golf', 'Sports', 'Ubisoft', 2002, 'GBA'),
(784, 'Tony Hawk\'s American Sk8land', 'Sports', 'Activision', 2005, 'GBA'),
(785, 'Tony Hawk\'s Pro Skater 2', 'Sports', 'Activision', 2001, 'GBA'),
(786, 'Tony Hawk\'s Pro Skater 3', 'Sports', 'Activision', 2002, 'GBA'),
(787, 'Tony Hawk\'s Pro Skater 4', 'Sports', 'Activision', 2002, 'GBA'),
(788, 'Tony Hawk\'s Underground', 'Sports', 'Activision', 2003, 'GBA'),
(789, 'Tony Hawk\'s Underground 2', 'Sports', 'Activision', 2004, 'GBA'),
(790, 'Virtua Tennis', 'Sports', 'Atari', 2002, 'GBA'),
(791, 'Wade Hixton\'s Counter Punch', 'Sports', 'Destination Software, Inc', 2004, 'GBA'),
(792, 'Wakeboarding Unleashed Featuring Shaun Murray', 'Sports', 'Aspyr', 2003, 'GBA'),
(793, 'WTA Tour Tennis', 'Sports', 'Konami Digital Entertainment', 2002, 'GBA'),
(794, 'Advance Wars', 'Strategy', 'Nintendo', 2001, 'GBA'),
(795, 'Advance Wars 2: Black Hole Rising', 'Strategy', 'Nintendo', 2003, 'GBA'),
(796, 'ChuChu Rocket!', 'Strategy', 'Atari', 2001, 'GBA'),
(797, 'Famicom Mini: SD Gundam World Gachapon Senshi - Scramble Wars', 'Strategy', 'Nintendo', 2004, 'GBA'),
(798, 'Fire Emblem', 'Strategy', 'Nintendo', 2003, 'GBA'),
(799, 'Fire Emblem: The Sacred Stones', 'Strategy', 'Nintendo', 2004, 'GBA'),
(800, 'L\'Aigle de Guerre', 'Strategy', 'Nintendo', 2001, 'GBA'),
(801, 'Onimusha Tactics', 'Strategy', 'Capcom', 2003, 'GBA'),
(802, 'Rebelstar: Tactical Command', 'Strategy', 'Atari', 2005, 'GBA'),
(803, 'Super Robot Taisen A', 'Strategy', 'Banpresto', 2001, 'GBA'),
(804, 'Super Robot Taisen D', 'Strategy', 'Banpresto', 2003, 'GBA'),
(805, 'Super Robot Taisen J', 'Strategy', 'Banpresto', 2005, 'GBA'),
(806, 'Super Robot Taisen R', 'Strategy', 'Banpresto', 2002, 'GBA'),
(807, 'Virtual Kasparov', 'Strategy', 'Titus', 2002, 'GBA'),
(808, 'Worms World Party', 'Strategy', 'Ubisoft', 2002, 'GBA'),
(809, 'Yu Yu Hakusho: Tournament Tactics', 'Strategy', 'Atari', 2004, 'GBA'),
(810, 'Yu-Gi-Oh! Reshef of Destruction', 'Strategy', 'Konami Digital Entertainment', 2003, 'GBA'),
(811, 'Yu-Gi-Oh! The Eternal Duelist Soul', 'Strategy', 'Konami Digital Entertainment', 2001, 'GBA');
