
-- --------------------------------------------------------

--
-- Struttura della tabella `nes`
--

DROP TABLE IF EXISTS `nes`;
CREATE TABLE IF NOT EXISTS `nes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `game_name` varchar(200) CHARACTER SET utf8mb3 DEFAULT NULL,
  `genre_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  `publisher_name` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL,
  `release_year` int DEFAULT NULL,
  `platform_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=99 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dump dei dati per la tabella `nes`
--

INSERT INTO `nes` (`id`, `game_name`, `genre_name`, `publisher_name`, `release_year`, `platform_name`) VALUES
(1, 'Commando', 'Action', 'Capcom', 1986, 'NES'),
(2, 'Doraemon', 'Action', 'Hudson Soft', 1986, 'NES'),
(3, 'Ghosts \'n Goblins', 'Action', 'Capcom', 1986, 'NES'),
(4, 'Jurassic Park', 'Action', 'Ocean', 1993, 'NES'),
(5, 'Kung Fu', 'Action', 'Nintendo', 1985, 'NES'),
(6, 'Mega Man 2', 'Action', 'Capcom', 1988, 'NES'),
(7, 'Metroid', 'Action', 'Nintendo', 1986, 'NES'),
(8, 'Pinball', 'Action', 'Nintendo', 1984, 'NES'),
(9, 'Teenage Mutant Ninja Turtles', 'Action', 'Palcom', 1989, 'NES'),
(10, 'Teenage Mutant Ninja Turtles II: The Arcade Game', 'Action', 'Konami Digital Entertainment', 1990, 'NES'),
(11, 'Teenage Mutant Ninja Turtles III: The Manhattan Project', 'Action', 'Konami Digital Entertainment', 1991, 'NES'),
(12, 'The Legend of Zelda', 'Action', 'Nintendo', 1986, 'NES'),
(13, 'The Mysterious Murasame Castle', 'Action', 'Nintendo', 1986, 'NES'),
(14, 'Zelda II: The Adventure of Link', 'Adventure', 'Nintendo', 1987, 'NES'),
(15, 'Mike Tyson\'s Punch-Out!!', 'Fighting', 'Nintendo', 1987, 'NES'),
(16, 'Pro Wrestling', 'Fighting', 'Nintendo', 1987, 'NES'),
(17, 'Tag Team Match M.U.S.C.L.E.', 'Fighting', 'Namco Bandai Games', 1985, 'NES'),
(18, 'Teenage Mutant Ninja Turtles: Tournament Fighters', 'Fighting', 'Konami Digital Entertainment', 1992, 'NES'),
(19, '4 Nin uchi Mahjong', 'Misc', 'Nintendo', 1984, 'NES'),
(20, 'Mahjong', 'Misc', 'Nintendo', 1983, 'NES'),
(21, 'Adventure Island', 'Platform', 'Hudson Soft', 1986, 'NES'),
(22, 'Balloon Fight', 'Platform', 'Nintendo', 1985, 'NES'),
(23, 'Castlevania', 'Platform', 'Konami Digital Entertainment', 1986, 'NES'),
(24, 'Castlevania II: Simon\'s Quest', 'Platform', 'Konami Digital Entertainment', 1987, 'NES'),
(25, 'Castlevania III: Dracula\'s Curse', 'Platform', 'Konami Digital Entertainment', 1989, 'NES'),
(26, 'Disney\'s Chip \'n Dale: Rescue Rangers', 'Platform', 'Capcom', 1990, 'NES'),
(27, 'Disney\'s DuckTales', 'Platform', 'Capcom', 1989, 'NES'),
(28, 'Donkey Kong', 'Platform', 'Nintendo', 1983, 'NES'),
(29, 'Donkey Kong Classics', 'Platform', 'Nintendo', 1988, 'NES'),
(30, 'Donkey Kong Jr.', 'Platform', 'Nintendo', 1983, 'NES'),
(31, 'Ganbare Goemon! Karakuri Douchuu', 'Platform', 'Konami Digital Entertainment', 1986, 'NES'),
(32, 'Ice Climber', 'Platform', 'Nintendo', 1985, 'NES'),
(33, 'Kid Icarus', 'Platform', 'Nintendo', 1986, 'NES'),
(34, 'Kirby\'s Adventure', 'Platform', 'Nintendo', 1993, 'NES'),
(35, 'Mappy', 'Platform', 'Namco Bandai Games', 1984, 'NES'),
(36, 'Mario Bros.', 'Platform', 'Nintendo', 1983, 'NES'),
(37, 'Mega Man', 'Platform', 'Capcom', 1987, 'NES'),
(38, 'Mega Man 3', 'Platform', 'Capcom', 1990, 'NES'),
(39, 'Mega Man 4', 'Platform', 'Capcom', 1991, 'NES'),
(40, 'Mega Man 5', 'Platform', 'Capcom', 1992, 'NES'),
(41, 'Mega Man 6', 'Platform', 'Capcom', 1993, 'NES'),
(42, 'Ninja Hattori Kun: Ninja wa Shuugyou Degogiru no Maki', 'Platform', 'Hudson Soft', 1986, 'NES'),
(43, 'Popeye', 'Platform', 'Nintendo', 1983, 'NES'),
(44, 'Super Mario Bros.', 'Platform', 'Nintendo', 1985, 'NES'),
(45, 'Super Mario Bros. 2', 'Platform', 'Nintendo', 1988, 'NES'),
(46, 'Super Mario Bros. 3', 'Platform', 'Nintendo', 1988, 'NES'),
(47, 'Super Mario Bros.: The Lost Levels', 'Platform', 'Nintendo', 1986, 'NES'),
(48, 'Wrecking Crew', 'Platform', 'Nintendo', 1985, 'NES'),
(49, 'Adventures of Lolo', 'Puzzle', 'HAL Laboratory', 1989, 'NES'),
(50, 'Bomberman', 'Puzzle', 'Hudson Soft', 1985, 'NES'),
(51, 'Bomberman II', 'Puzzle', 'Hudson Soft', 1991, 'NES'),
(52, 'Clu Clu Land', 'Puzzle', 'Nintendo', 1984, 'NES'),
(53, 'Dig Dug', 'Puzzle', 'Namco Bandai Games', 1985, 'NES'),
(54, 'Dr. Mario', 'Puzzle', 'Nintendo', 1990, 'NES'),
(55, 'Gyromite', 'Puzzle', 'Nintendo', 1985, 'NES'),
(56, 'Lode Runner', 'Puzzle', 'Hudson Soft', 1984, 'NES'),
(57, 'Pac-Man', 'Puzzle', 'Namco Bandai Games', 1984, 'NES'),
(58, 'Tetris', 'Puzzle', 'Nintendo', 1988, 'NES'),
(59, 'Tetris 2', 'Puzzle', 'Nintendo', 1993, 'NES'),
(60, 'Tetris 2 + Bombliss', 'Puzzle', 'BPS', 1991, 'NES'),
(61, 'Yoshi', 'Puzzle', 'Nintendo', 1991, 'NES'),
(62, 'Yoshi\'s Cookie', 'Puzzle', 'Nintendo', 1992, 'NES'),
(63, 'Excitebike', 'Racing', 'Nintendo', 1984, 'NES'),
(64, 'F1 Race', 'Racing', 'Nintendo', 1984, 'NES'),
(65, 'R.C. Pro-Am', 'Racing', 'Nintendo', 1988, 'NES'),
(66, 'Rad Racer', 'Racing', 'Nintendo', 1986, 'NES'),
(67, 'Dragon Ball: Daimaou Fukkatsu', 'Role-Playing', 'Namco Bandai Games', 1988, 'NES'),
(68, 'Dragon Warrior', 'Role-Playing', 'Capcom', 1986, 'NES'),
(69, 'Dragon Warrior II', 'Role-Playing', 'Enix Corporation', 1987, 'NES'),
(70, 'Dragon Warrior III', 'Role-Playing', 'Enix Corporation', 1988, 'NES'),
(71, 'Dragon Warrior IV', 'Role-Playing', 'Enix Corporation', 1990, 'NES'),
(72, 'Famicom Jump: Eiyuu Retsuden', 'Role-Playing', 'Namco Bandai Games', 1989, 'NES'),
(73, 'Final Fantasy', 'Role-Playing', 'SquareSoft', 1987, 'NES'),
(74, 'Final Fantasy I & II', 'Role-Playing', 'Square', 1994, 'NES'),
(75, 'Final Fantasy II', 'Role-Playing', 'SquareSoft', 1988, 'NES'),
(76, 'Final Fantasy III', 'Role-Playing', 'SquareSoft', 1990, 'NES'),
(77, 'Gegege no Kitarou 2: Youkai Gundan no Chousen', 'Role-Playing', 'Namco Bandai Games', 1987, 'NES'),
(78, '1942', 'Shooter', 'Capcom', 1985, 'NES'),
(79, 'Duck Hunt', 'Shooter', 'Nintendo', 1984, 'NES'),
(80, 'Gradius', 'Shooter', 'Konami Digital Entertainment', 1986, 'NES'),
(81, 'Hogan\'s Alley', 'Shooter', 'Nintendo', 1984, 'NES'),
(82, 'Star Soldier', 'Shooter', 'Hudson Soft', 1986, 'NES'),
(83, 'TwinBee', 'Shooter', 'Konami Digital Entertainment', 1986, 'NES'),
(84, 'Xevious', 'Shooter', 'Namco Bandai Games', 1984, 'NES'),
(85, 'Baseball', 'Sports', 'Nintendo', 1983, 'NES'),
(86, 'Famista \'91', 'Sports', 'Namco Bandai Games', 1990, 'NES'),
(87, 'Famista \'92', 'Sports', 'Namco Bandai Games', 1991, 'NES'),
(88, 'Golf', 'Sports', 'Nintendo', 1984, 'NES'),
(89, 'Ice Hockey', 'Sports', 'Nintendo', 1988, 'NES'),
(90, 'NES Open Tournament Golf', 'Sports', 'Nintendo', 1991, 'NES'),
(91, 'Nintendo World Cup', 'Sports', 'Nintendo', 1990, 'NES'),
(92, 'Pro Yakyuu Family Stadium', 'Sports', 'Namco Bandai Games', 1986, 'NES'),
(93, 'Pro Yakyuu Family Stadium \'87', 'Sports', 'Namco Bandai Games', 1987, 'NES'),
(94, 'Pro Yakyuu Family Stadium \'88', 'Sports', 'Namco Bandai Games', 1988, 'NES'),
(95, 'Soccer', 'Sports', 'Nintendo', 1985, 'NES'),
(96, 'Tennis', 'Sports', 'Nintendo', 1984, 'NES'),
(97, 'Volleyball', 'Sports', 'Nintendo', 1987, 'NES'),
(98, 'World Class Track Meet', 'Sports', 'Namco Bandai Games', 1986, 'NES');
