
-- --------------------------------------------------------

--
-- Struttura della tabella `psp`
--

DROP TABLE IF EXISTS `psp`;
CREATE TABLE IF NOT EXISTS `psp` (
  `id` int NOT NULL AUTO_INCREMENT,
  `game_name` varchar(200) CHARACTER SET utf8mb3 DEFAULT NULL,
  `genre_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  `publisher_name` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL,
  `release_year` int DEFAULT NULL,
  `platform_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1198 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dump dei dati per la tabella `psp`
--

INSERT INTO `psp` (`id`, `game_name`, `genre_name`, `publisher_name`, `release_year`, `platform_name`) VALUES
(1, '300: March to Glory', 'Action', 'Warner Bros. Interactive Entertainment', 2007, 'PSP'),
(2, '50 Cent: Bulletproof', 'Action', 'Vivendi Games', 2006, 'PSP'),
(3, 'Abunai: Koi no Sousa Shitsu', 'Action', 'Quinrose', 2012, 'PSP'),
(4, 'Ailu de Puzzle', 'Action', 'Capcom', 2012, 'PSP'),
(5, 'Aliens vs Predator: Requiem', 'Action', 'Vivendi Games', 2007, 'PSP'),
(6, 'All Kamen Rider: Rider Generation 2', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(7, 'Ano Hi Mita Hana no Namae o Bokutachi wa Mada Shiranai', 'Action', '5pb', 2012, 'PSP'),
(8, 'Ao no Exorcist: Genkoku no Labyrinth', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(9, 'Arcana Famiglia: Vascello Phantasma no Majutsushi', 'Action', 'Comfort', 2012, 'PSP'),
(10, 'Assassin\'s Creed: Bloodlines', 'Action', 'Ubisoft', 2009, 'PSP'),
(11, 'Astro Boy: The Video Game', 'Action', 'D3Publisher', 2009, 'PSP'),
(12, 'Avatar: The Game', 'Action', 'Ubisoft', 2009, 'PSP'),
(13, 'Bakemonogatari Portable', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(14, 'Bakugan Battle Brawlers: Defenders of the Core', 'Action', 'Activision', 2010, 'PSP'),
(15, 'Bakumatsu Rock', 'Action', 'Marvelous Entertainment', 2014, 'PSP'),
(16, 'Ben 10 Alien Force: Vilgax Attacks', 'Action', 'D3Publisher', 2009, 'PSP'),
(17, 'Ben 10: Alien Force', 'Action', 'Koch Media', 2008, 'PSP'),
(18, 'Ben 10: Protector of Earth', 'Action', 'D3Publisher', 2007, 'PSP'),
(19, 'Beowulf: The Game', 'Action', 'Ubisoft', 2007, 'PSP'),
(20, 'Bounty Hounds', 'Action', 'Namco Bandai Games', 2006, 'PSP'),
(21, 'Brothers Conflict: Passion Pink', 'Action', 'Idea Factory', 2012, 'PSP'),
(22, 'Bunmei Haruka: Aoiza Ibunroku', 'Action', 'FuRyu', 2011, 'PSP'),
(23, 'Bunmei Kaika: Aoiza Ibunroku Saien', 'Action', 'FuRyu', 2012, 'PSP'),
(24, 'Busou Shinki: Battle Masters', 'Action', 'Konami Digital Entertainment', 2010, 'PSP'),
(25, 'Busou Shinki: Battle Masters Mk. 2', 'Action', 'Konami Digital Entertainment', 2011, 'PSP'),
(26, 'Code Lyoko: Quest for Infinity', 'Action', 'Game Factory', 2008, 'PSP'),
(27, 'Crash of the Titans', 'Action', 'Vivendi Games', 2007, 'PSP'),
(28, 'Custom Drive', 'Action', 'D3Publisher', 2012, 'PSP'),
(29, 'Danball Senki Boost', 'Action', 'Level 5', 2011, 'PSP'),
(30, 'Dante\'s Inferno', 'Action', 'Electronic Arts', 2010, 'PSP'),
(31, 'Dead Head Fred', 'Action', 'D3Publisher', 2007, 'PSP'),
(32, 'Def Jam Fight For NY: The Takeover', 'Action', 'Electronic Arts', 2006, 'PSP'),
(33, 'Detective Conan: Prelude from the Past', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(34, 'Dies Irae: Amantes Amentes', 'Action', 'Views', 2012, 'PSP'),
(35, 'Digimon World Re:Digitize', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(36, 'Downstream Panic!', 'Action', 'Atari', 2008, 'PSP'),
(37, 'Dynasty Warriors', 'Action', 'Tecmo Koei', 2004, 'PSP'),
(38, 'Dynasty Warriors Vol. 2', 'Action', 'Tecmo Koei', 2006, 'PSP'),
(39, 'Dynasty Warriors Vol. 2 (JP sales)', 'Action', 'Tecmo Koei', 2006, 'PSP'),
(40, 'Dynasty Warriors: Strikeforce', 'Action', 'Ubisoft Annecy', 2009, 'PSP'),
(41, 'EA Replay', 'Action', 'Electronic Arts', 2006, 'PSP'),
(42, 'Earth Defense Force 2: Invaders from Planet Space', 'Action', 'D3Publisher', 2011, 'PSP'),
(43, 'Elkrone no Atelier: Dear for Otomate', 'Action', 'Idea Factory', 2012, 'PSP'),
(44, 'Eragon', 'Action', 'Vivendi Games', 2006, 'PSP'),
(45, 'Evangelion: Jo', 'Action', 'Namco Bandai Games', 2009, 'PSP'),
(46, 'Even in a Game Listen to Me Girls. I Am Your Father!', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(47, 'Fairy Tail: Zelef Kakusei', 'Action', 'Unknown', 2012, 'PSP'),
(48, 'Family Guy', 'Action', 'Take-Two Interactive', 2006, 'PSP'),
(49, 'Fat Princess: Fistful of Cake', 'Action', 'Sony Computer Entertainment', 2010, 'PSP'),
(50, 'Fate/Extra CCC', 'Action', 'Marvelous Entertainment', 2013, 'PSP'),
(51, 'FIFA Soccer 13', 'Action', 'Electronic Arts', 2012, 'PSP'),
(52, 'From Russia With Love', 'Action', 'Electronic Arts', 2006, 'PSP'),
(53, 'Fuun Shinsengumi Bakumatsuden Portable', 'Action', 'From Software', 2009, 'PSP'),
(54, 'G-Force', 'Action', 'Electronic Arts', 2009, 'PSP'),
(55, 'G.I. Joe: The Rise of Cobra', 'Action', 'Electronic Arts', 2009, 'PSP'),
(56, 'GachiTora! Abarenbou Kyoushi in High School', 'Action', 'Spike', 2011, 'PSP'),
(57, 'Genroh', 'Action', 'Idea Factory', 2012, 'PSP'),
(58, 'Ghost Rider', 'Action', 'Take-Two Interactive', 2007, 'PSP'),
(59, 'Ghostbusters: The Video Game', 'Action', 'Atari', 2009, 'PSP'),
(60, 'Gintama no Sugoroku', 'Action', 'Namco Bandai Games', 2013, 'PSP'),
(61, 'Gladiator Begins', 'Action', 'PQube', 2010, 'PSP'),
(62, 'God Eater', 'Action', 'Unknown', 2010, 'PSP'),
(63, 'God of War: Chains of Olympus', 'Action', 'Sony Computer Entertainment', 2008, 'PSP'),
(64, 'God of War: Ghost of Sparta', 'Action', 'Sony Computer Entertainment', 2010, 'PSP'),
(65, 'Gods Eater Burst', 'Action', 'Namco Bandai Games', 2010, 'PSP'),
(66, 'Grand Theft Auto: Chinatown Wars', 'Action', 'Take-Two Interactive', 2009, 'PSP'),
(67, 'Grand Theft Auto: Liberty City Stories', 'Action', 'Take-Two Interactive', 2005, 'PSP'),
(68, 'Grand Theft Auto: Vice City Stories', 'Action', 'Take-Two Interactive', 2006, 'PSP'),
(69, 'Great Battle Full Blast', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(70, 'Gun Showdown', 'Action', 'Activision', 2006, 'PSP'),
(71, 'Gundam Assault Survive', 'Action', 'Namco Bandai Games', 2010, 'PSP'),
(72, 'Gundam Battle Chronicle', 'Action', 'Namco Bandai Games', 2007, 'PSP'),
(73, 'Gundam Battle Royale', 'Action', 'Namco Bandai Games', 2006, 'PSP'),
(74, 'Gundam Battle Tactics', 'Action', 'Namco Bandai Games', 2005, 'PSP'),
(75, 'Gundam Memories: Tatakai no Kioku', 'Action', 'Namco Bandai Games', 2011, 'PSP'),
(76, 'Hagane no Renkinjutsushi - Fullmetal Alchemist: Yakusoku no Hi e', 'Action', 'Namco Bandai Games', 2010, 'PSP'),
(77, 'Hakuouki: Bakumatsu Musou Roku', 'Action', 'Idea Factory', 2012, 'PSP'),
(78, 'Hakuouki: Yuugi Roku Ni - Matsuri Hayashi to Taishitachi', 'Action', 'Idea Factory', 2012, 'PSP'),
(79, 'Hammerin\' Hero', 'Action', 'Irem Software Engineering', 2008, 'PSP'),
(80, 'Hanaoni: Yume no Tsudzuki', 'Action', 'Idea Factory', 2012, 'PSP'),
(81, 'Harry Potter and the Goblet of Fire', 'Action', 'Electronic Arts', 2005, 'PSP'),
(82, 'Harry Potter and the Half-Blood Prince', 'Action', 'Electronic Arts', 2009, 'PSP'),
(83, 'Harry Potter and the Order of the Phoenix', 'Action', 'Electronic Arts', 2007, 'PSP'),
(84, 'Harukanaru Toki no Naka de 6', 'Action', 'Tecmo Koei', 2015, 'PSP'),
(85, 'Heatseeker', 'Action', 'Codemasters', 2007, 'PSP'),
(86, 'Hellboy: The Science of Evil', 'Action', 'Konami Digital Entertainment', 2008, 'PSP'),
(87, 'Hot Wheels Ultimate Racing', 'Action', 'Activision', 2007, 'PSP'),
(88, 'Hunter x Hunter: Wonder Adventure', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(89, 'Hyakki Yagyou Kaidan Romance', 'Action', 'Quinrose', 2012, 'PSP'),
(90, 'Ikki Tousen: Xross Impact', 'Action', 'Marvelous Interactive', 2010, 'PSP'),
(91, 'Indiana Jones and the Staff of Kings', 'Action', 'Activision', 2009, 'PSP'),
(92, 'Invizimals: The Lost Tribes', 'Action', 'Sony Computer Entertainment', 2011, 'PSP'),
(93, 'Iron Man', 'Action', 'Sega', 2008, 'PSP'),
(94, 'Iron Man 2', 'Action', 'Sega', 2010, 'PSP'),
(95, 'Jackass the Game', 'Action', 'Empire Interactive', 2007, 'PSP'),
(96, 'Jikkyou Powerful Pro Yakyuu 2012', 'Action', 'Konami Digital Entertainment', 2012, 'PSP'),
(97, 'Juusanshi Engi Engetsu Sangokuden 2', 'Action', 'Idea Factory', 2014, 'PSP'),
(98, 'Jyuzaengi: Engetsu Sangokuden', 'Action', 'Idea Factory', 2012, 'PSP'),
(99, 'Kenka Bancho Bros: Tokyo Battle Royale', 'Action', 'Spike', 2012, 'PSP'),
(100, 'Kenka Bancho: Badass Rumble', 'Action', 'Spike', 2008, 'PSP'),
(101, 'Kenka Banchou 4: Ichinen Sensou', 'Action', 'Spike', 2010, 'PSP'),
(102, 'Kenka Banchou 5: Otoko no Housoku', 'Action', 'Spike', 2011, 'PSP'),
(103, 'Kenka Banchou Portable', 'Action', 'Spike', 2009, 'PSP'),
(104, 'Kimikare: New Semester', 'Action', 'Idea Factory', 2012, 'PSP'),
(105, 'Kingdom: Ikkitousen no Ken', 'Action', 'Konami Digital Entertainment', 2010, 'PSP'),
(106, 'Koi Sentai Love & Peace the P.S.P: Power Zenkai! Special Youso Tenkomori de Portable Ka Daisakusen de Aru!', 'Action', 'Broccoli', 2012, 'PSP'),
(107, 'Kokoro Connect: Yochi Random', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(108, 'Kurohyou 2: Ryu ga Gotoku Ashura Hen', 'Action', 'Sega', 2012, 'PSP'),
(109, 'L.G.S: Shinsetsu Houshinengi', 'Action', 'Idea Factory', 2012, 'PSP'),
(110, 'LEGO Harry Potter: Years 1-4', 'Action', 'Warner Bros. Interactive Entertainment', 2010, 'PSP'),
(111, 'LEGO Indiana Jones 2: The Adventure Continues', 'Action', 'Activision', 2009, 'PSP'),
(112, 'LEGO Indiana Jones: The Original Adventures', 'Action', 'LucasArts', 2008, 'PSP'),
(113, 'LEGO Pirates of the Caribbean: The Video Game', 'Action', 'Disney Interactive Studios', 2011, 'PSP'),
(114, 'LEGO Star Wars II: The Original Trilogy', 'Action', 'LucasArts', 2006, 'PSP'),
(115, 'LEGO Star Wars III: The Clone Wars', 'Action', 'LucasArts', 2011, 'PSP'),
(116, 'Little Busters! Converted Edition', 'Action', 'Prototype', 2010, 'PSP'),
(117, 'Macross Triangle Frontier', 'Action', 'Namco Bandai Games', 2011, 'PSP'),
(118, 'Macross Ultimate Frontier', 'Action', 'Namco Bandai Games', 2009, 'PSP'),
(119, 'Manhunt 2', 'Action', 'Take-Two Interactive', 2007, 'PSP'),
(120, 'Meiji Toukyou Renka: Twilight Kiss', 'Action', 'Broccoli', 2015, 'PSP'),
(121, 'Mercury Meltdown', 'Action', 'Atari', 2006, 'PSP'),
(122, 'Metal Fight Beyblade Portable: Chouzetsu Tensei Vulcan Horses', 'Action', 'Takara Tomy', 2010, 'PSP'),
(123, 'Metal Gear Solid: Peace Walker', 'Action', 'Konami Digital Entertainment', 2010, 'PSP'),
(124, 'Metal Gear Solid: Portable Ops', 'Action', 'Konami Digital Entertainment', 2006, 'PSP'),
(125, 'Metal Gear Solid: Portable Ops Plus', 'Action', 'Konami Digital Entertainment', 2007, 'PSP'),
(126, 'Mind Quiz', 'Action', 'Ubisoft', 2006, 'PSP'),
(127, 'Miyako: Awayuki no Utage', 'Action', 'Idea Factory', 2012, 'PSP'),
(128, 'Mobile Suit Gundam Age: Universe Accel / Cosmic Drive', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(129, 'Mobile Suit Gundam: Mokuba no Kiseki', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(130, 'My Little Sister Can\'t Be This Cute Portable', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(131, 'Nano Diver', 'Action', 'Takara Tomy', 2011, 'PSP'),
(132, 'Naruto Shippuden: Kizuna Drive', 'Action', 'Namco Bandai Games', 2010, 'PSP'),
(133, 'Nayuta no Kiseki', 'Action', 'Nihon Falcom Corporation', 2012, 'PSP'),
(134, 'NBA 2K11', 'Action', 'Take-Two Interactive', 2010, 'PSP'),
(135, 'Obscure: The Aftermath', 'Action', 'Playlogic Game Factory', 2009, 'PSP'),
(136, 'Onechanbara Special', 'Action', 'D3Publisher', 2011, 'PSP'),
(137, 'Ookami Kakushi', 'Action', 'Konami Digital Entertainment', 2009, 'PSP'),
(138, 'Ore wa Shoujo Mangaka', 'Action', 'Giza10', 2012, 'PSP'),
(139, 'Oumagatoki: Kaidan Romance', 'Action', 'Quinrose', 2012, 'PSP'),
(140, 'Peter Jackson\'s King Kong: The Official Game of the Movie', 'Action', 'Ubisoft', 2005, 'PSP'),
(141, 'Pirates of the Caribbean: At World\'s End', 'Action', 'Disney Interactive Studios', 2007, 'PSP'),
(142, 'Pocket Pool', 'Action', 'Conspiracy Entertainment', 2007, 'PSP'),
(143, 'Power Stone Collection', 'Action', 'Capcom', 2006, 'PSP'),
(144, 'Prince of Persia: Rival Swords', 'Action', 'Ubisoft', 2007, 'PSP'),
(145, 'Prince of Persia: The Forgotten Sands', 'Action', 'Ubisoft', 2010, 'PSP'),
(146, 'Pro Evolution Soccer 2012', 'Action', 'Konami Digital Entertainment', 2011, 'PSP'),
(147, 'Pro Evolution Soccer 2014', 'Action', 'Konami Digital Entertainment', 2013, 'PSP'),
(148, 'Pursuit Force: Extreme Justice', 'Action', 'Sony Computer Entertainment', 2007, 'PSP'),
(149, 'Rainbow Islands: Revolution', 'Action', 'Rising Star Games', 2005, 'PSP'),
(150, 'Ratatouille', 'Action', 'THQ', 2007, 'PSP'),
(151, 'Rengoku II:  The Stairway To H.E.A.V.E.N.', 'Action', 'Konami Digital Entertainment', 2006, 'PSP'),
(152, 'Rengoku II: The Stairway to H.E.A.V.E.N. (jp sales)', 'Action', 'Konami Digital Entertainment', 2006, 'PSP'),
(153, 'Rengoku: The Tower of Purgatory', 'Action', 'Konami Digital Entertainment', 2005, 'PSP'),
(154, 'Rurouni Kenshin: Meiji Kenyaku Romantan - Kansen', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(155, 'Samurai Dou Portable', 'Action', 'Spike', 2008, 'PSP'),
(156, 'Samurai Warriors: State of War', 'Action', 'Tecmo Koei', 2005, 'PSP'),
(157, 'Seinaru Kana: Orichalcum no Na no Motoni', 'Action', 'CyberFront', 2012, 'PSP'),
(158, 'Sengoku Basara: Battle Heroes', 'Action', 'Capcom', 2009, 'PSP'),
(159, 'Sengoku Basara: Chronicle Heroes', 'Action', 'Capcom', 2011, 'PSP'),
(160, 'Sengoku Musou 3 Z Special', 'Action', 'Ackkstudios', 2012, 'PSP'),
(161, 'Shin Sangoku Musou 5 Empires', 'Action', 'Tecmo Koei', 2010, 'PSP'),
(162, 'Shin Sangoku Musou 5 Special', 'Action', 'Tecmo Koei', 2009, 'PSP'),
(163, 'Shin Sangoku Musou 6 Special', 'Action', 'Tecmo Koei', 2011, 'PSP'),
(164, 'Shin Sangoku Musou: Multi Raid 2', 'Action', 'Tecmo Koei', 2010, 'PSP'),
(165, 'Shrek the Third', 'Action', 'Activision', 2007, 'PSP'),
(166, 'Silent Hill: Origins', 'Action', 'Konami Digital Entertainment', 2007, 'PSP'),
(167, 'Silent Hill: Shattered Memories', 'Action', 'Konami Digital Entertainment', 2010, 'PSP'),
(168, 'Simple 2500 Series Portable!! Vol. 12: The Hohei 2: Senyuu yo, Sakini Ike', 'Action', 'D3Publisher', 2009, 'PSP'),
(169, 'Soukoku no Kusabi: Hiiro no Kakera 3 - Ashita e no Tobira', 'Action', 'Idea Factory', 2012, 'PSP'),
(170, 'Soul Eater: Battle Resonance', 'Action', 'Namco Bandai Games', 2009, 'PSP'),
(171, 'Spider-Man 2', 'Action', 'Activision', 2005, 'PSP'),
(172, 'Spider-Man: Friend or Foe', 'Action', 'Activision', 2007, 'PSP'),
(173, 'Spider-Man: Web of Shadows - Amazing Allies Edition', 'Action', 'Activision', 2008, 'PSP'),
(174, 'SpongeBob SquarePants: The Yellow Avenger', 'Action', 'THQ', 2006, 'PSP'),
(175, 'SpongeBob\'s Truth or Square', 'Action', 'THQ', 2009, 'PSP'),
(176, 'SpongeBob\'s Truth or Square (US sales)', 'Action', 'THQ', 2009, 'PSP'),
(177, 'Star Wars The Clone Wars: Republic Heroes', 'Action', 'LucasArts', 2009, 'PSP'),
(178, 'Star Wars: Lethal Alliance', 'Action', 'Ubisoft', 2006, 'PSP'),
(179, 'Star Wars: The Force Unleashed', 'Action', 'LucasArts', 2008, 'PSP'),
(180, 'Steins;Gate: Hiyoku Renri no Darling', 'Action', '5pb', 2012, 'PSP'),
(181, 'Storm Lover Kai!!', 'Action', 'D3Publisher', 2012, 'PSP'),
(182, 'Taito Legends Power Up', 'Action', 'Destineer', 2007, 'PSP'),
(183, 'Tenchu San Portable', 'Action', 'From Software', 2009, 'PSP'),
(184, 'Tenchu: Shadow Assassins', 'Action', 'Ubisoft', 2009, 'PSP'),
(185, 'The Amazing Spider-Man (DS & Mobile Versions)', 'Action', 'Eidos Interactive', 2009, 'PSP'),
(186, 'The Godfather: Mob Wars', 'Action', 'Electronic Arts', 2006, 'PSP'),
(187, 'The Idolm@ster: Shiny Festa - Honey Sound / Funky Note / Groovy Tune', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(188, 'The Lord of the Rings: Aragorn\'s Quest', 'Action', 'Warner Bros. Interactive Entertainment', 2010, 'PSP'),
(189, 'The Secret Saturdays: Beasts of the 5th Sun', 'Action', 'D3Publisher', 2009, 'PSP'),
(190, 'The Simpsons Game', 'Action', 'Electronic Arts', 2007, 'PSP'),
(191, 'The Warriors', 'Action', 'Take-Two Interactive', 2007, 'PSP'),
(192, 'Tiger & Bunny: Hero\'s Day', 'Action', 'D3Publisher', 2013, 'PSP'),
(193, 'Tiger & Bunny: On-Air Jack!', 'Action', 'Namco Bandai Games', 2012, 'PSP'),
(194, 'TMNT', 'Action', 'Ubisoft', 2007, 'PSP'),
(195, 'Toki no Kizuna: Sekigahara Kitan', 'Action', 'Idea Factory', 2012, 'PSP'),
(196, 'Tomb Raider: Anniversary', 'Action', 'Eidos Interactive', 2007, 'PSP'),
(197, 'Tomb Raider: Legend', 'Action', 'Eidos Interactive', 2006, 'PSP'),
(198, 'Toukiden Kiwami', 'Action', 'Tecmo Koei', 2014, 'PSP'),
(199, 'Toukiden: The Age of Demons', 'Action', 'Tecmo Koei', 2013, 'PSP'),
(200, 'Toy Story 3: The Video Game', 'Action', 'Disney Interactive Studios', 2010, 'PSP'),
(201, 'Transformers: The Game (XBox 360, PS2, PS3, Wii & PC Versions)', 'Action', 'Activision', 2007, 'PSP'),
(202, 'TRON: Evolution', 'Action', 'Disney Interactive Studios', 2010, 'PSP'),
(203, 'Tsuyo Kiss 3 Portable', 'Action', 'NetRevo', 2012, 'PSP'),
(204, 'Twisted Metal: Head On', 'Action', 'Sony Computer Entertainment', 2005, 'PSP'),
(205, 'Undead Knights', 'Action', 'Ubisoft Annecy', 2009, 'PSP'),
(206, 'Unending Bloody Call', 'Action', 'Asgard', 2012, 'PSP'),
(207, 'Up', 'Action', 'THQ', 2009, 'PSP'),
(208, 'Uta no * Prince-Sama: All Star', 'Action', 'Broccoli', 2013, 'PSP'),
(209, 'Uta no Prince-Sama: All Star After Secret', 'Action', 'Broccoli', 2015, 'PSP'),
(210, 'Viewtiful Joe: Red Hot Rumble', 'Action', 'Capcom', 2006, 'PSP'),
(211, 'Warhammer: Battle For Atluma', 'Action', 'Namco Bandai Games', 2006, 'PSP'),
(212, 'Warriors Orochi', 'Action', 'Tecmo Koei', 2008, 'PSP'),
(213, 'Warriors Orochi 2', 'Action', 'Tecmo Koei', 2008, 'PSP'),
(214, 'Warriors Orochi 3', 'Action', 'Ubisoft Annecy', 2012, 'PSP'),
(215, 'Way of the Samurai 2 Portable', 'Action', 'Spike', 2009, 'PSP'),
(216, 'X-Men Origins: Wolverine', 'Action', 'Activision', 2009, 'PSP'),
(217, 'Xiaolin Showdown', 'Action', 'Konami Digital Entertainment', 2006, 'PSP'),
(218, 'Zettai Zetsumei Toshi 3: Kowareyuku Machi to Kanojyo no Uta', 'Action', 'Irem Software Engineering', 2009, 'PSP'),
(219, '1/2 Summer +', 'Adventure', 'Kaga Create', 2013, 'PSP'),
(220, '11eyes: CrossOver', 'Adventure', '5pb', 2010, 'PSP'),
(221, '428: Fuusa Sareta Shibuya de', 'Adventure', 'Spike', 2009, 'PSP'),
(222, 'Accel World: Ginyoku no Kakusei', 'Adventure', 'Namco Bandai Games', 2012, 'PSP'),
(223, 'Accel World: Kasoku no Chouten', 'Adventure', 'Namco Bandai Games', 2013, 'PSP'),
(224, 'AIR', 'Adventure', 'Prototype', 2007, 'PSP'),
(225, 'Akatsuki no Goei Trinity', 'Adventure', '5pb', 2012, 'PSP'),
(226, 'AKB1/149: Love Election', 'Adventure', 'Namco Bandai Games', 2012, 'PSP'),
(227, 'Akiba\'s Trip', 'Adventure', 'Acquire', 2011, 'PSP'),
(228, 'Akiba\'s Trip Plus', 'Adventure', 'Acquire', 2012, 'PSP'),
(229, 'Amagami', 'Adventure', 'Kadokawa Shoten', 2011, 'PSP'),
(230, 'Amnesia', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(231, 'Angelique: Maren no Rokukishi', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(232, 'Arabians Lost: The Engagement on Desert', 'Adventure', 'Quinrose', 2012, 'PSP'),
(233, 'Arcana Famiglia 2', 'Adventure', 'Comfort', 2013, 'PSP'),
(234, 'Arcana Famiglia: La storia della Aracana Famiglia', 'Adventure', 'Comfort', 2011, 'PSP'),
(235, 'Are You Alice?', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(236, 'Avatar: The Last Airbender', 'Adventure', 'THQ', 2006, 'PSP'),
(237, 'B\'s-LOG Party♪', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(238, 'Blue Roses: Yousei to Aoi Hitomi no Senshitachi', 'Adventure', 'Nippon Ichi Software', 2010, 'PSP'),
(239, 'Boku no Natsuyasumi 4: Seitouchi Shounen Tanteidan, Boku to Himitsu no Chizu', 'Adventure', 'Sony Computer Entertainment', 2009, 'PSP'),
(240, 'Boku no Natsuyasumi Portable 2: Nazo Nazo Shimai to Chinbotsusen no Himitsu', 'Adventure', 'Sony Computer Entertainment', 2010, 'PSP'),
(241, 'Boku no Natsuyasumi Portable: Mushi Mushi Hakase to Teppen-yama no Himitsu!!', 'Adventure', 'Sony Computer Entertainment', 2006, 'PSP'),
(242, 'Brothers Conflict: Brilliant Blue', 'Adventure', 'Idea Factory', 2013, 'PSP'),
(243, 'Chaos;Head - Love Chu*Chu!', 'Adventure', '5pb', 2011, 'PSP'),
(244, 'Chaos;Head Noah', 'Adventure', '5pb', 2010, 'PSP'),
(245, 'Clannad', 'Adventure', 'Prototype', 2008, 'PSP'),
(246, 'Clannad: Mitsumi Mamoru Sakamichi de - Gekan', 'Adventure', 'Prototype', 2010, 'PSP'),
(247, 'Clannad: Mitsumi Mamoru Sakamichi de - Joukan', 'Adventure', 'Prototype', 2010, 'PSP'),
(248, 'Clock Zero: Shuuen no Ichibyou Portable', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(249, 'Clover no Kuni no Alice: Wonderful Wonder World', 'Adventure', 'Quinrose', 2011, 'PSP'),
(250, 'Code Geass: Hangyaku no Lelouch - Lost Colors', 'Adventure', 'Namco Bandai Games', 2008, 'PSP'),
(251, 'Corpse Party: Blood Covered - Repeated Fear', 'Adventure', '5pb', 2010, 'PSP'),
(252, 'Corpse Party: Book of Shadows', 'Adventure', '5pb', 2011, 'PSP'),
(253, 'Cross + Channel', 'Adventure', 'CyberFront', 2010, 'PSP'),
(254, 'D.C. III: Da Capo III', 'Adventure', 'Kadokawa Games', 2013, 'PSP'),
(255, 'Da Capo I & II Plus Situation Portable', 'Adventure', 'Kadokawa Shoten', 2010, 'PSP'),
(256, 'Daiya no Kuni no Alice: Wonderful Mirror World', 'Adventure', 'Quinrose', 2013, 'PSP'),
(257, 'Death Connection Portable', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(258, 'Detective Opera: Milky Holmes 2', 'Adventure', 'BushiRoad', 2012, 'PSP'),
(259, 'Diabolik Lovers', 'Adventure', 'Idea Factory', 2012, 'PSP'),
(260, 'Diabolik Lovers: More Blood', 'Adventure', 'Idea Factory', 2013, 'PSP'),
(261, 'Disgaea Infinite', 'Adventure', 'Nippon Ichi Software', 2010, 'PSP'),
(262, 'Durarara!! 3-way Standoff', 'Adventure', 'ASCII Media Works', 2010, 'PSP'),
(263, 'Durarara!! 3way Standoff: Alley', 'Adventure', 'Kadokawa Shoten', 2011, 'PSP'),
(264, 'Enkaku Sousa: Sana e no 23 Hiai', 'Adventure', 'Sony Computer Entertainment', 2009, 'PSP'),
(265, 'FairlyLife: MiracleDays', 'Adventure', 'Piacci', 2010, 'PSP'),
(266, 'GA - Geijutsuka Art Design Class: Slapstick Wonder Land', 'Adventure', 'Russel', 2010, 'PSP'),
(267, 'Gakuen Hetalia Portable', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(268, 'Gakuen K: Wonderful School Days', 'Adventure', 'Idea Factory', 2014, 'PSP'),
(269, 'Gangs of London', 'Adventure', 'Sony Computer Entertainment', 2006, 'PSP'),
(270, 'Gekka Ryouran Romance', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(271, 'Ghost in the Shell: Stand Alone Complex', 'Adventure', 'Atari', 2005, 'PSP'),
(272, 'Grisaia no Kajitsu: La Fruit de la Grisaia', 'Adventure', 'Prototype', 2013, 'PSP'),
(273, 'Hakuoki: Demon of the Fleeting Blossom', 'Adventure', 'Idea Factory', 2009, 'PSP'),
(274, 'Hakuouki Portable', 'Adventure', 'Idea Factory', 2009, 'PSP'),
(275, 'Hakuouki: Reimeiroku Portable', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(276, 'Hakuouki: Yuugi Roku', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(277, 'Hakuouki: Zuisouroku Portable', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(278, 'Hanaoni: Koisomeru Koku - Eikyuu no Shirushi', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(279, 'Hanayaka Kana, Ware ga Ichizoku', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(280, 'Hanayaka Kana, Ware ga Ichizoku: Tasogare Polarstar', 'Adventure', 'Idea Factory', 2013, 'PSP'),
(281, 'Harukanaru Toki no Naka de 3 with Izayoiki Aizouban', 'Adventure', 'Tecmo Koei', 2009, 'PSP'),
(282, 'Harukanaru Toki no Naka de 3: Unmei no Meikyuu Aizouban', 'Adventure', 'Tecmo Koei', 2009, 'PSP'),
(283, 'Harvey Birdman: Attorney at Law', 'Adventure', 'Capcom', 2008, 'PSP'),
(284, 'HatsuKare * Renai Debut Sengen!', 'Adventure', 'FuRyu', 2013, 'PSP'),
(285, 'Hayate no Gotoku! Nightmare Paradise', 'Adventure', 'Konami Digital Entertainment', 2009, 'PSP'),
(286, 'Heart no Kuni no Alice', 'Adventure', 'Prototype', 2009, 'PSP'),
(287, 'Heart no Kuni no Alice Anniversary Ver.: Wonderful Wonder World', 'Adventure', 'Quinrose', 2011, 'PSP'),
(288, 'Heart no Kuni no Alice: Wonderful Twin World', 'Adventure', 'Quinrose', 2014, 'PSP'),
(289, 'Higurashi Daybreak Portable', 'Adventure', 'Alchemist', 2008, 'PSP'),
(290, 'Higurashi Daybreak Portable Mega Edition', 'Adventure', 'Alchemist', 2009, 'PSP'),
(291, 'Hiiro no Kakera Portable', 'Adventure', 'Idea Factory', 2008, 'PSP'),
(292, 'Hiiro no Kakera: Shin Tamayori Hime Denshou - Piece of Future', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(293, 'Hiiro no Kakera: Shin Tamayori Hime Denshou Portable', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(294, 'Himawari: Pebble in the Sky Portable', 'Adventure', 'Kadokawa Shoten', 2010, 'PSP'),
(295, 'I Don\'t Have Many Friends Portable', 'Adventure', 'Namco Bandai Games', 2012, 'PSP'),
(296, 'Ishin Renka: Ryouma Gaiden', 'Adventure', 'D3Publisher', 2010, 'PSP'),
(297, 'Isshoni Gohan. Portable', 'Adventure', 'Boost On', 2013, 'PSP'),
(298, 'Iza, Shutsujin! Koisen', 'Adventure', 'Quinrose', 2011, 'PSP'),
(299, 'Joker no Kuni no Alice: Wonderful Wonder World', 'Adventure', 'Quinrose', 2011, 'PSP'),
(300, 'Kaitou Tenshi Twin Angel: Toki to Sekai no Meikyuu', 'Adventure', 'Alchemist', 2011, 'PSP'),
(301, 'Kamaitachi no Yoru 2: Tokubetsu Hen', 'Adventure', 'ChunSoft', 2006, 'PSP'),
(302, 'Kami Naru Kimi to', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(303, 'Kamigami no Asobi', 'Adventure', 'Broccoli', 2013, 'PSP'),
(304, 'Kana: Imouto', 'Adventure', 'CyberFront', 2010, 'PSP'),
(305, 'Kannou Mukashi Banashi Portable', 'Adventure', 'Idea Factory', 2012, 'PSP'),
(306, 'Kazoku Keikaku', 'Adventure', 'CyberFront', 2010, 'PSP'),
(307, 'Kiniro no Corda 3', 'Adventure', 'Tecmo Koei', 2010, 'PSP'),
(308, 'Koi to Senkyo to Chocolate Portable', 'Adventure', 'Kadokawa Shoten', 2012, 'PSP'),
(309, 'Koisuru Otome to Shugo no Tate Portable', 'Adventure', 'Alchemist', 2010, 'PSP'),
(310, 'Kono Aozora ni Yakusoku o: Tenohira no Rakuen', 'Adventure', 'TGL', 2009, 'PSP'),
(311, 'Kurohyou: Ryu ga Gotoku Shinshou', 'Adventure', 'Sega', 2010, 'PSP'),
(312, 'Kyoukai Senjou no Horizon Portable', 'Adventure', 'Kadokawa Shoten', 2013, 'PSP'),
(313, 'Last Escort: Club Katze', 'Adventure', 'D3Publisher', 2010, 'PSP'),
(314, 'Machi: Unmei no Kousaten', 'Adventure', 'ChunSoft', 2006, 'PSP'),
(315, 'Marriage Royale: Prism Story', 'Adventure', 'ASCII Media Works', 2010, 'PSP'),
(316, 'Mashiro Iro Symphony: *mutsu-no-hana', 'Adventure', 'Comfort', 2011, 'PSP'),
(317, 'MediEvil: Resurrection', 'Adventure', 'Sony Computer Entertainment', 2005, 'PSP'),
(318, 'Megamind: The Blue Defender', 'Adventure', 'THQ', 2010, 'PSP'),
(319, 'Meiji Toukyou Renka', 'Adventure', 'Broccoli', 2013, 'PSP'),
(320, 'Memories Off', 'Adventure', '5pb', 2008, 'PSP'),
(321, 'Memories Off #5: Togireta Film', 'Adventure', '5pb', 2009, 'PSP'),
(322, 'Memories Off: Yubikiri no Kikou', 'Adventure', '5pb', 2011, 'PSP'),
(323, 'Misshitsu no Sacrifice', 'Adventure', 'D3Publisher', 2010, 'PSP'),
(324, 'Miyako', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(325, 'Moe Moe 2-ji Taisen (Ryoku) * Deluxe', 'Adventure', 'System Soft', 2008, 'PSP'),
(326, 'Mother Goose no Himitsu no Yakata', 'Adventure', 'Quinrose', 2011, 'PSP'),
(327, 'Motto NUGA-CEL!', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(328, 'Moujuutsukai to Oujisama Portable', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(329, 'Moujuutsukai to Oujisama: Snow Bride Portable', 'Adventure', 'Idea Factory', 2012, 'PSP'),
(330, 'Myst', 'Adventure', 'Midway Games', 2006, 'PSP'),
(331, 'Narcissus: Moshimo Ashita ga Runara', 'Adventure', 'Kadokawa Shoten', 2010, 'PSP'),
(332, 'Natsuzora no Monologue', 'Adventure', 'Otomate', 2013, 'PSP'),
(333, 'Neo Angelique Special', 'Adventure', 'Tecmo Koei', 2008, 'PSP'),
(334, 'Neopets Petpet Adventures: The Wand of Wishing', 'Adventure', 'Sony Computer Entertainment', 2006, 'PSP'),
(335, 'Nisenochigiri', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(336, 'Nisenochigiri: Omoide no Saki e', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(337, 'Norn9: Norn + Nonette', 'Adventure', 'Idea Factory', 2013, 'PSP'),
(338, 'Okashi na Shima no Peter Pan: Sweet Never Land', 'Adventure', 'Quinrose', 2011, 'PSP'),
(339, 'Onigokko! Portable', 'Adventure', 'Alchemist', 2013, 'PSP'),
(340, 'Ore no Imouto ga Konna ni Kawaii wake ga Nai Portable', 'Adventure', 'Banpresto', 2011, 'PSP'),
(341, 'Otome wa Oanesama Boku ni Koi Shiteru Portable', 'Adventure', 'Alchemist', 2010, 'PSP'),
(342, 'Otome wa Oanesama ni Koi Shiteru Portable: 2-Jin no Elder', 'Adventure', 'Alchemist', 2011, 'PSP'),
(343, 'Otometeki Koi Kakumei * Love Revo! Portable', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(344, 'Ouka Sengoku Portable', 'Adventure', 'Alchemist', 2012, 'PSP'),
(345, 'Pastel Chime Continue', 'Adventure', '5pb', 2010, 'PSP'),
(346, 'PC Engine Best Collention: Ginga Ojousama Densetsu Collection', 'Adventure', 'Hudson Soft', 2008, 'PSP'),
(347, 'PhotoKano', 'Adventure', 'Kadokawa Shoten', 2012, 'PSP'),
(348, 'Pirates of the Caribbean: Dead Man\'s Chest', 'Adventure', 'Disney Interactive Studios', 2006, 'PSP'),
(349, 'Planetarian: Chiisana Hoshi no Yume', 'Adventure', 'Prototype', 2009, 'PSP'),
(350, 'Prince of Persia: Revelations', 'Adventure', 'Ubisoft', 2005, 'PSP'),
(351, 'Princess Frontier Portable', 'Adventure', 'Alchemist', 2011, 'PSP'),
(352, 'Renai 0 Kilometer', 'Adventure', 'Alchemist', 2013, 'PSP'),
(353, 'Renai Banchou: Inochi Meishi, Koiseyo Otome! Love is Power!!!', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(354, 'Ro-Kyu-Bu!', 'Adventure', 'Kadokawa Shoten', 2011, 'PSP'),
(355, 'Ro-Kyu-Bu! Lost Secret', 'Adventure', 'Kadokawa Shoten', 2013, 'PSP'),
(356, 'Romeo Vs. Juliet', 'Adventure', 'Quinrose', 2013, 'PSP'),
(357, 'S.Y.K Renshouden Portable', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(358, 'S.Y.K: Shinsetsu Saiyuuki Portable', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(359, 'Saka Agari Hurricane Portable', 'Adventure', 'Alchemist', 2011, 'PSP'),
(360, 'Saki Portable', 'Adventure', 'Alchemist', 2010, 'PSP'),
(361, 'Saki: Achiga-Hen Portable', 'Adventure', 'Alchemist', 2013, 'PSP'),
(362, 'Sakura Sakura: Haru Urara', 'Adventure', 'GN Software', 2010, 'PSP'),
(363, 'Sakura-Sou no Pet na Kanojo', 'Adventure', 'Kadokawa Games', 2013, 'PSP'),
(364, 'Sangoku Koi Senki: Otome no Heihou!', 'Adventure', 'Prototype', 2012, 'PSP'),
(365, 'Satomi Hakkenden: Hachi Tamanoki', 'Adventure', 'Quinrose', 2014, 'PSP'),
(366, 'Scooby-Doo! Who\'s Watching Who?', 'Adventure', 'THQ', 2006, 'PSP'),
(367, 'Secret Game Portable', 'Adventure', 'Yeti', 2010, 'PSP'),
(368, 'Sengoku Hime: Senran ni Mau Otometachi', 'Adventure', 'Yeti', 2009, 'PSP'),
(369, 'Shadow of Destiny', 'Adventure', 'Konami Digital Entertainment', 2009, 'PSP'),
(370, 'Shin Hisui no Shizuku: Hiiro no Kakera 2 Portable', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(371, 'Shin Koihime Musou: Otome Ryouran * Sangokushi Engi - Shu-Hen', 'Adventure', 'Yeti', 2010, 'PSP'),
(372, 'Shin Koihime Musou: Otome Ryouran * Sangokushi Engi - Wei-Hen', 'Adventure', 'Yeti', 2010, 'PSP'),
(373, 'Shin Koihime Musou: Otome Ryouran * Sangokushi Engi - Wu-Hen', 'Adventure', 'Yeti', 2010, 'PSP'),
(374, 'Shinigami to Shoujo', 'Adventure', 'Takuyo', 2011, 'PSP'),
(375, 'Shinobi Koutsutsu', 'Adventure', 'Idea Factory', 2014, 'PSP'),
(376, 'Shinseiki Evangelion 2: Tsukurareshi Sekai - Another Cases', 'Adventure', 'Namco Bandai Games', 2006, 'PSP'),
(377, 'Shinseiki Evangelion: Koutetsu no Girlfriend 2nd Portable', 'Adventure', 'CyberFront', 2009, 'PSP'),
(378, 'Shinseiki Evangelion: Koutetsu no Girlfriend Tokubetsu-Hen Portable', 'Adventure', 'CyberFront', 2009, 'PSP'),
(379, 'Shirahana no Ori: Hiiro no Kakera 4 - Shiki no Uta', 'Adventure', 'Idea Factory', 2013, 'PSP'),
(380, 'Shiratsuyu no Kai', 'Adventure', 'Idea Factory', 2013, 'PSP'),
(381, 'Shukufuku no Campanella Portable', 'Adventure', 'Kadokawa Shoten', 2010, 'PSP'),
(382, 'Snoopy vs the Red Baron', 'Adventure', 'Namco Bandai Games', 2006, 'PSP'),
(383, 'Snow Portable', 'Adventure', 'Prototype', 2007, 'PSP'),
(384, 'So-Ra-No-Wo-To: Otome no Gojuusou', 'Adventure', 'Compile Heart', 2010, 'PSP'),
(385, 'Sokukoku no Kusabi: Hiiro no Kakera 3 Portable', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(386, 'Sora no Otoshimono: DokiDoki Summer Vacation', 'Adventure', 'Kadokawa Shoten', 2010, 'PSP'),
(387, 'Star Driver: Kagayaki no Takuto - Ginga Bishounen Densetsu', 'Adventure', 'Namco Bandai Games', 2011, 'PSP'),
(388, 'Steins;Gate', 'Adventure', 'Kadokawa Shoten', 2011, 'PSP'),
(389, 'StormLover', 'Adventure', 'D3Publisher', 2010, 'PSP'),
(390, 'StormLover Karen!!', 'Adventure', 'D3Publisher', 2011, 'PSP'),
(391, 'Suzumiya Haruhi no Tsuisou', 'Adventure', 'Namco Bandai Games', 2011, 'PSP'),
(392, 'Suzumiya Haruhi no Yakusoku', 'Adventure', 'Namco Bandai Games', 2007, 'PSP'),
(393, 'Tantei Jinguuji Saburo: Hai to Diamond', 'Adventure', 'Arc System Works', 2009, 'PSP'),
(394, 'Tantei Opera: Milky Holmes', 'Adventure', 'Unknown', 2010, 'PSP'),
(395, 'Tears to Tiara: Kakan no Daichi Portable', 'Adventure', 'Aqua Plus', 2010, 'PSP'),
(396, 'Tenjin Ranman: Happy GO Lucky!!', 'Adventure', 'Russel', 2010, 'PSP'),
(397, 'The Idolm@ster SP: Wandering Star / Perfect Sun / Missing Moon', 'Adventure', 'Namco Bandai Games', 2009, 'PSP'),
(398, 'Time Travelers', 'Adventure', 'Level 5', 2012, 'PSP'),
(399, 'To Heart 2: Dungeon Travelers', 'Adventure', 'Aqua Plus', 2011, 'PSP'),
(400, 'To LoveRu Trouble: Doki Doki! Rinkaigakkou-Hen', 'Adventure', 'Marvelous Interactive', 2008, 'PSP'),
(401, 'Toaru Kagaku no Chou Denjihou', 'Adventure', 'Kadokawa Shoten', 2011, 'PSP'),
(402, 'Toaru Majutsu no Index', 'Adventure', 'Kadokawa Shoten', 2011, 'PSP'),
(403, 'Toaru Majutsu no Kagaku no Ensemble', 'Adventure', 'Namco Bandai Games', 2013, 'PSP'),
(404, 'Toki no Kizuna: Hanayui Tsuzuri', 'Adventure', 'Idea Factory', 2013, 'PSP'),
(405, 'Tokimeki Memorial 4', 'Adventure', 'Konami Digital Entertainment', 2009, 'PSP'),
(406, 'Tokimeki Memorial Girl\'s Side Premium: 3rd Story', 'Adventure', 'Konami Digital Entertainment', 2012, 'PSP'),
(407, 'Tomoyo After: It\'s a Wonderful Life CS Edition', 'Adventure', 'Prototype', 2009, 'PSP'),
(408, 'ToraDora Portable!', 'Adventure', 'Namco Bandai Games', 2009, 'PSP'),
(409, 'Trick x Logic: Season 1', 'Adventure', 'Sony Computer Entertainment', 2010, 'PSP'),
(410, 'Trick x Logic: Season 2', 'Adventure', 'Sony Computer Entertainment', 2010, 'PSP'),
(411, 'Tsuku Monogatari', 'Adventure', 'FuRyu', 2011, 'PSP'),
(412, 'Tsuyo Kiss 2 Portable', 'Adventure', 'NetRevo', 2010, 'PSP'),
(413, 'Twinkle * Crusaders GoGo!', 'Adventure', 'ASCII Media Works', 2010, 'PSP'),
(414, 'Umineko no Naku Koro ni Portable 1', 'Adventure', 'Alchemist', 2011, 'PSP'),
(415, 'Urakata Hakuoki', 'Adventure', 'Idea Factory', 2013, 'PSP'),
(416, 'Uta no * Prince-Sama', 'Adventure', 'Broccoli', 2010, 'PSP'),
(417, 'Uta no * Prince-Sama: Repeat', 'Adventure', 'Broccoli', 2011, 'PSP'),
(418, 'Uta no * Prince-Sama: Sweet Serenade', 'Adventure', 'Broccoli', 2011, 'PSP'),
(419, 'Uta no Prince-Sama: Debut', 'Adventure', 'Broccoli', 2012, 'PSP'),
(420, 'Uta no Prince-Sama: Music 2', 'Adventure', 'Broccoli', 2013, 'PSP'),
(421, 'Vitamin R', 'Adventure', 'D3Publisher', 2013, 'PSP'),
(422, 'Vitamin X Evolution Plus', 'Adventure', 'D3Publisher', 2010, 'PSP'),
(423, 'Vitamin X to Z', 'Adventure', 'D3Publisher', 2011, 'PSP'),
(424, 'Vitamin X: Detective B6', 'Adventure', 'D3Publisher', 2012, 'PSP'),
(425, 'Vitamin Z Revolution', 'Adventure', 'D3Publisher', 2010, 'PSP'),
(426, 'Wand of Fortune 2 FD: Kimi ni Sasageru Epilogue', 'Adventure', 'Idea Factory', 2012, 'PSP'),
(427, 'Wand of Fortune 2: Jikuu ni Shizumu Mokushiroku', 'Adventure', 'Idea Factory', 2011, 'PSP'),
(428, 'Wand of Fortune Portable', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(429, 'Wand of Fortune: Mirai e no Prologue Portable', 'Adventure', 'Idea Factory', 2010, 'PSP'),
(430, 'Yoake Yori Ruriiro na Portable', 'Adventure', 'Kadokawa Shoten', 2010, 'PSP'),
(431, 'BlazBlue: Calamity Trigger Portable', 'Fighting', 'PQube', 2010, 'PSP'),
(432, 'Blazblue: Continuum Shift Extend', 'Fighting', 'Arc System Works', 2012, 'PSP'),
(433, 'BlazBlue: Continuum Shift II', 'Fighting', 'PQube', 2011, 'PSP'),
(434, 'Bleach: Heat the Soul', 'Fighting', 'Sony Computer Entertainment', 2005, 'PSP'),
(435, 'Bleach: Heat the Soul 3', 'Fighting', 'Sony Computer Entertainment', 2006, 'PSP'),
(436, 'Bleach: Heat the Soul 4', 'Fighting', 'Sony Computer Entertainment', 2007, 'PSP'),
(437, 'Bleach: Heat the Soul 5', 'Fighting', 'Sony Computer Entertainment', 2008, 'PSP'),
(438, 'Bleach: Heat the Soul 6', 'Fighting', 'Sony Computer Entertainment', 2009, 'PSP'),
(439, 'Bleach: Heat the Soul 7', 'Fighting', 'Sony Computer Entertainment', 2010, 'PSP'),
(440, 'Bleach: Soul Carnival', 'Fighting', 'Sony Computer Entertainment', 2008, 'PSP'),
(441, 'Bleach: Soul Carnival 2', 'Fighting', 'Sony Computer Entertainment', 2009, 'PSP'),
(442, 'Darkstalkers Chronicle: The Chaos Tower', 'Fighting', 'Capcom', 2004, 'PSP'),
(443, 'Dissidia 012: Duodecim Final Fantasy', 'Fighting', 'Square Enix', 2011, 'PSP'),
(444, 'Dissidia: Final Fantasy', 'Fighting', 'Square Enix', 2008, 'PSP'),
(445, 'Dissidia: Final Fantasy Universal Tuning', 'Fighting', 'Square Enix', 2009, 'PSP'),
(446, 'Dragon Ball Z: Shin Budokai', 'Fighting', 'Atari', 2006, 'PSP'),
(447, 'Dragon Ball Z: Shin Budokai - Another Road', 'Fighting', 'Atari', 2007, 'PSP'),
(448, 'Dragon Ball Z: Tenkaichi Tag Team', 'Fighting', 'Namco Bandai Games', 2010, 'PSP'),
(449, 'Dragon Ball: Evolution', 'Fighting', 'Namco Bandai Games', 2009, 'PSP'),
(450, 'Fairy Tail: Portable Guild', 'Fighting', 'Konami Digital Entertainment', 2010, 'PSP'),
(451, 'Fairy Tail: Portable Guild 2', 'Fighting', 'Konami Digital Entertainment', 2011, 'PSP'),
(452, 'Fate/Tiger Colosseum', 'Fighting', 'Capcom', 2007, 'PSP'),
(453, 'Fate/Tiger Colosseum Upper', 'Fighting', 'Capcom', 2008, 'PSP'),
(454, 'Fate/Unlimited Codes Portable', 'Fighting', 'Capcom', 2009, 'PSP'),
(455, 'Fight Night Round 3', 'Fighting', 'Electronic Arts', 2006, 'PSP'),
(456, 'Guilty Gear Judgment', 'Fighting', 'Majesco Entertainment', 2006, 'PSP'),
(457, 'Guilty Gear XX Accent Core Plus', 'Fighting', 'PQube', 2008, 'PSP'),
(458, 'Gundam Battle Universe', 'Fighting', 'Namco Bandai Games', 2008, 'PSP'),
(459, 'Hajime no Ippo Portable: Victorious Spirits', 'Fighting', 'Grand Prix Games', 2007, 'PSP'),
(460, 'Heroes VS', 'Fighting', 'Namco Bandai Games', 2013, 'PSP'),
(461, 'Ikki Tousen: Eloquent Fist', 'Fighting', 'Marvelous Interactive', 2008, 'PSP'),
(462, 'Katekyoo Hitman Reborn! Battle Arena', 'Fighting', 'Marvelous Interactive', 2008, 'PSP'),
(463, 'Katekyoo Hitman Reborn! Battle Arena 2 - Spirits Burst', 'Fighting', 'Marvelous Interactive', 2009, 'PSP'),
(464, 'Katekyoo Hitman Reborn! Kizuna no Tag Battle', 'Fighting', 'Marvelous Interactive', 2010, 'PSP'),
(465, 'Legend of the Dragon', 'Fighting', 'Game Factory', 2007, 'PSP'),
(466, 'Mahou Shoujo Lyrical Nanoha A\'s Portable: The Gears of Destiny', 'Fighting', 'Namco Bandai Games', 2011, 'PSP'),
(467, 'Marvel Nemesis: Rise of the Imperfects', 'Fighting', 'Electronic Arts', 2005, 'PSP'),
(468, 'Marvel Super Hero Squad', 'Fighting', 'THQ', 2009, 'PSP'),
(469, 'Mobile Suit Gundam: Gundam vs. Gundam', 'Fighting', 'Namco Bandai Games', 2008, 'PSP'),
(470, 'Mobile Suit Gundam: Gundam vs. Gundam NEXT PLUS', 'Fighting', 'Namco Bandai Games', 2009, 'PSP'),
(471, 'Mortal Kombat: Unchained', 'Fighting', 'Midway Games', 2006, 'PSP'),
(472, 'Naruto Shippuden: Legends: Akatsuki Rising', 'Fighting', 'Namco Bandai Games', 2009, 'PSP'),
(473, 'Naruto Shippuden: Ultimate Ninja Heroes 3', 'Fighting', 'Namco Bandai Games', 2009, 'PSP'),
(474, 'Naruto Shippuden: Ultimate Ninja Impact', 'Fighting', 'Namco Bandai Games', 2011, 'PSP'),
(475, 'Naruto: Ultimate Ninja Heroes', 'Fighting', 'Namco Bandai Games', 2006, 'PSP'),
(476, 'Naruto: Ultimate Ninja Heroes (JP sales)', 'Fighting', 'Namco Bandai Games', 2006, 'PSP'),
(477, 'Naruto: Ultimate Ninja Heroes 2 - The Phantom Fortress', 'Fighting', 'Atari', 2006, 'PSP'),
(478, 'One Piece: Romance Dawn - Bouken no Yoake', 'Fighting', 'Namco Bandai Games', 2012, 'PSP'),
(479, 'Pac-Man: Adventures in Time', 'Fighting', 'Sony Computer Entertainment', 2006, 'PSP'),
(480, 'Rurouni Kenshin: Meiji Kenkaku Romantan Saisen', 'Fighting', 'Namco Bandai Games', 2011, 'PSP'),
(481, 'Saint Seiya Omega: Ultimate Cosmo', 'Fighting', 'Namco Bandai Games', 2012, 'PSP'),
(482, 'Shinseiki Evangelion: Battle Orchestra Portable', 'Fighting', 'Broccoli', 2009, 'PSP'),
(483, 'SNK vs. Capcom: The Match of the Millennium', 'Fighting', 'Sega', 2006, 'PSP'),
(484, 'SoulCalibur: Broken Destiny', 'Fighting', 'Namco Bandai Games', 2009, 'PSP'),
(485, 'Steambot Chronicles: Battle Tournament', 'Fighting', 'Irem Software Engineering', 2008, 'PSP'),
(486, 'Street Fighter Alpha 3 MAX', 'Fighting', 'Capcom', 2006, 'PSP'),
(487, 'Sunday vs Magazine Shuuketsu! Choujou Daikessen', 'Fighting', 'Konami Digital Entertainment', 2009, 'PSP'),
(488, 'Tales of VS.', 'Fighting', 'Namco Bandai Games', 2009, 'PSP'),
(489, 'Tekken 6', 'Fighting', 'Namco Bandai Games', 2009, 'PSP'),
(490, 'The Con', 'Fighting', 'Sony Computer Entertainment', 2005, 'PSP'),
(491, 'The King of Fighters Collection: The Orochi Saga', 'Fighting', 'Ignition Entertainment', 2008, 'PSP'),
(492, 'The King of Fighters Portable \'94~\'98: Chapter of Orochi', 'Fighting', 'SNK Playmore', 2010, 'PSP'),
(493, 'TNA iMPACT: Cross the Line', 'Fighting', 'SouthPeak Games', 2010, 'PSP'),
(494, 'UFC Undisputed 2010', 'Fighting', 'THQ', 2010, 'PSP'),
(495, 'Ultraman Fighting Evolution 0', 'Fighting', 'Banpresto', 2006, 'PSP'),
(496, 'WWE All Stars', 'Fighting', 'THQ', 2011, 'PSP'),
(497, 'WWE SmackDown vs Raw 2008', 'Fighting', 'THQ', 2007, 'PSP'),
(498, 'WWE SmackDown vs. RAW 2007', 'Fighting', 'THQ', 2006, 'PSP'),
(499, 'WWE SmackDown vs. Raw 2009', 'Fighting', 'THQ', 2008, 'PSP'),
(500, 'WWE SmackDown vs. Raw 2010', 'Fighting', 'THQ', 2009, 'PSP'),
(501, 'WWE SmackDown vs. Raw 2011', 'Fighting', 'THQ', 2010, 'PSP'),
(502, 'WWE SmackDown! vs. RAW 2006', 'Fighting', 'THQ', 2005, 'PSP'),
(503, 'Ys vs. Sora no Kiseki: Alternative Saga', 'Fighting', 'Falcom Corporation', 2010, 'PSP'),
(504, 'Activision Hits: Remixed', 'Misc', 'Activision', 2006, 'PSP'),
(505, 'AKB1/48: Idol to Guam de Koishitara...', 'Misc', 'Namco Bandai Games', 2011, 'PSP'),
(506, 'AKB1/48: Idol to Koishitara...', 'Misc', 'Namco Bandai Games', 2010, 'PSP'),
(507, 'Amnesia Crowd', 'Misc', 'Idea Factory', 2013, 'PSP'),
(508, 'Amnesia Later', 'Misc', 'Idea Factory', 2012, 'PSP'),
(509, 'Ape Escape Academy', 'Misc', 'Sony Computer Entertainment', 2004, 'PSP'),
(510, 'Ape Escape Academy (jp sales)', 'Misc', 'Sony Computer Entertainment', 2004, 'PSP'),
(511, 'Atari Classics Evolved', 'Misc', 'Atari', 2007, 'PSP'),
(512, 'B-Boy', 'Misc', 'Sony Computer Entertainment', 2006, 'PSP'),
(513, 'Bakumatsu Rock: Ultra Soul', 'Misc', 'Marvelous Interactive', 2014, 'PSP'),
(514, 'Beaterator', 'Misc', 'Take-Two Interactive', 2009, 'PSP'),
(515, 'Bomberman Land', 'Misc', 'Hudson Entertainment', 2007, 'PSP'),
(516, 'Buzz! Master Quiz', 'Misc', 'Sony Computer Entertainment', 2008, 'PSP'),
(517, 'Capcom Classics Collection Reloaded', 'Misc', 'Capcom', 2006, 'PSP'),
(518, 'Capcom Classics Collection Remixed', 'Misc', 'Capcom', 2006, 'PSP'),
(519, 'Chessmaster: The Art of Learning', 'Misc', 'Ubisoft', 2008, 'PSP'),
(520, 'Daito Giken Koushiki Pachi-Slot Simulator: Hihouden - Fuujirareta Megami Portable', 'Misc', 'Paon', 2011, 'PSP'),
(521, 'Daito Giken Koushiki Pachi-Slot Simulator: Ossu! Banchou Portable', 'Misc', 'Daito', 2006, 'PSP'),
(522, 'Daito Giken Koushiki Pachi-Slot Simulator: Ossu! Misao + Maguro Densetsu Portable', 'Misc', 'Paon', 2010, 'PSP'),
(523, 'Daito Giken Koushiki Pachi-Slot Simulator: Yoshimune Portable', 'Misc', 'Daito', 2006, 'PSP'),
(524, 'Danganronpa 2: Goodbye Despair', 'Misc', 'Spike', 2012, 'PSP'),
(525, 'Dead or Alive Paradise', 'Misc', 'Ubisoft Annecy', 2010, 'PSP'),
(526, 'DJ Max Fever', 'Misc', 'PM Studios', 2009, 'PSP'),
(527, 'DJ Max Portable 3', 'Misc', 'CyberFront', 2010, 'PSP'),
(528, 'Doko Demo Issho', 'Misc', 'Sony Computer Entertainment', 2004, 'PSP'),
(529, 'Doko Demo Issho: Let\'s Gakkou!', 'Misc', 'Sony Computer Entertainment', 2006, 'PSP'),
(530, 'Dragon Quest & Final Fantasy in Itadaki Street Portable', 'Misc', 'Square Enix', 2006, 'PSP'),
(531, 'Gekiatsu!! Pachi Game Tamashi Vol. 1: CR Evangelion - Shinjitsu no Tsubasa', 'Misc', 'Unknown', 2011, 'PSP'),
(532, 'Geten no Hana', 'Misc', 'Tecmo Koei', 2013, 'PSP'),
(533, 'Geten no Hana: Yume Akari', 'Misc', 'Tecmo Koei', 2014, 'PSP'),
(534, 'Gitaroo Man Lives!', 'Misc', 'Tecmo Koei', 2006, 'PSP'),
(535, 'Hanayaka Kana, Ware ga Ichizoku Twin Pack', 'Misc', 'Idea Factory', 2011, 'PSP'),
(536, 'Hannah Montana: Rock Out the Show', 'Misc', 'Disney Interactive Studios', 2009, 'PSP'),
(537, 'Hard Rock Casino', 'Misc', 'Oxygen Interactive', 2007, 'PSP'),
(538, 'Hatsune Miku: Project Diva', 'Misc', 'Sega', 2009, 'PSP'),
(539, 'Hatsune Miku: Project Diva 2nd', 'Misc', 'Sega', 2010, 'PSP'),
(540, 'Hatsune Miku: Project Diva Extend', 'Misc', 'Sega', 2011, 'PSP'),
(541, 'Higurashi no Naku Koro ni: Jan', 'Misc', 'AQ Interactive', 2009, 'PSP'),
(542, 'Hisshou Pachinko * Pachi-Slot Kouryaku Series Portable Vol. 2: CR Evangelion - Hajimari no Fukuin', 'Misc', 'D3Publisher', 2010, 'PSP'),
(543, 'Hisshou Pachinko*Pachi-Slot Kouryaku Series Portable Vol. 1: Shinseiki Evangelion - Tamashii no Kiseki', 'Misc', 'D3Publisher', 2010, 'PSP'),
(544, 'Jissen Pachislot Hisshouhou! Hokuto no Ken Portable SE', 'Misc', 'Sega', 2006, 'PSP'),
(545, 'K-ON! Houkago Live!!', 'Misc', 'Sega', 2010, 'PSP'),
(546, 'Kawashima Ryuuta Kyouju Kanshuu Nouryoku Trainer Portable 2', 'Misc', 'Sega', 2006, 'PSP'),
(547, 'Mahjong Fight Club', 'Misc', 'Konami Digital Entertainment', 2004, 'PSP'),
(548, 'MAPLUS: Portable Navi', 'Misc', 'Edia', 2006, 'PSP'),
(549, 'MAPLUS: Portable Navi 3', 'Misc', 'Edia', 2009, 'PSP'),
(550, 'Mega Minis Volume 2', 'Misc', 'Sony Computer Entertainment', 2011, 'PSP'),
(551, 'Mega Minis Volume 3', 'Misc', 'Sony Computer Entertainment', 2011, 'PSP'),
(552, 'Megpoid the Music#', 'Misc', 'Asgard', 2013, 'PSP'),
(553, 'Metal Gear Solid: Digital Graphic Novel', 'Misc', 'Konami Digital Entertainment', 2006, 'PSP'),
(554, 'Michael Jackson: The Experience', 'Misc', 'Ubisoft', 2010, 'PSP'),
(555, 'Midway Arcade Treasures: Extended Play', 'Misc', 'Midway Games', 2005, 'PSP'),
(556, 'Minna de Dokusho: Keatai Shousetsu Desu', 'Misc', 'Dorart', 2008, 'PSP'),
(557, 'Minna no Chizu', 'Misc', 'Zenrin', 2006, 'PSP'),
(558, 'Minna no Chizu 2', 'Misc', 'Zenrin', 2007, 'PSP'),
(559, 'Momotarou Dentetsu Tag Match: Yuujou - Doryoku - Shouri no Maki!', 'Misc', 'Hudson Soft', 2010, 'PSP'),
(560, 'My Spanish Coach', 'Misc', 'Ubisoft', 2008, 'PSP'),
(561, 'Namco Museum Battle Collection', 'Misc', 'Sony Computer Entertainment', 2005, 'PSP'),
(562, 'Namco Museum Battle Collection (JP sales)', 'Misc', 'Sony Computer Entertainment', 2005, 'PSP'),
(563, 'Nippon no Asoko de', 'Misc', 'Sony Computer Entertainment', 2008, 'PSP'),
(564, 'Online Chess Kingdoms', 'Misc', 'Konami Digital Entertainment', 2006, 'PSP'),
(565, 'PaRappa The Rapper', 'Misc', 'Sony Computer Entertainment', 2006, 'PSP'),
(566, 'Patapon', 'Misc', 'Sony Computer Entertainment', 2007, 'PSP'),
(567, 'Patapon 2', 'Misc', 'Sony Computer Entertainment', 2008, 'PSP'),
(568, 'Patapon 3', 'Misc', 'Sony Computer Entertainment', 2011, 'PSP'),
(569, 'Pinball Hall of Fame: The Gottlieb Collection', 'Misc', 'Play It', 2005, 'PSP'),
(570, 'Pinball Hall of Fame: The Williams Collection', 'Misc', 'System 3 Arcade Software', 2008, 'PSP'),
(571, 'Planetarium Creator Ohira Takayuki Kanshuu: HomeStar Portable - 21st Century Star Navigator', 'Misc', 'Sega', 2006, 'PSP'),
(572, 'Pop\'n Music Portable', 'Misc', 'Konami Digital Entertainment', 2010, 'PSP'),
(573, 'Pop\'n Music Portable 2', 'Misc', 'Konami Digital Entertainment', 2011, 'PSP'),
(574, 'Princess Arthur', 'Misc', 'Idea Factory', 2013, 'PSP'),
(575, 'Rock Band Unplugged', 'Misc', 'MTV Games', 2009, 'PSP'),
(576, 'Scrabble', 'Misc', 'Electronic Arts', 2009, 'PSP'),
(577, 'Sengoku Efuda Yuugi: Hototogisu Ran', 'Misc', 'Irem Software Engineering', 2008, 'PSP'),
(578, 'Slotter Mania P: Tetsuya Shinjuku vs Ueno', 'Misc', 'Dorart', 2010, 'PSP'),
(579, 'SNK Arcade Classics Vol. 1', 'Misc', 'Ignition Entertainment', 2008, 'PSP'),
(580, 'Sony Computer Science Kenkyuujo Mogi Kenichirou Hakase Kanshuu: Nou ni Kaikan Aha Taiken!', 'Misc', 'Sega', 2006, 'PSP'),
(581, 'Spelling Challenges and more!', 'Misc', 'Crave Entertainment', 2007, 'PSP'),
(582, 'Stacked with Daniel Negreanu', 'Misc', 'Myelin Media', 2006, 'PSP'),
(583, 'Starry ? Sky: After Autumn', 'Misc', 'Aqua Plus', 2011, 'PSP'),
(584, 'Starry ? Sky: After Spring', 'Misc', 'Aqua Plus', 2009, 'PSP'),
(585, 'Starry ? Sky: After Summer', 'Misc', 'Asgard', 2013, 'PSP'),
(586, 'Starry ? Sky: In Autumn', 'Misc', 'Asgard', 2010, 'PSP'),
(587, 'Starry ? Sky: In Spring', 'Misc', 'Asgard', 2010, 'PSP'),
(588, 'Starry ? Sky: In Summer', 'Misc', 'Asgard', 2010, 'PSP'),
(589, 'Starry ? Sky: In Winter', 'Misc', 'Asgard', 2011, 'PSP'),
(590, 'Storm Lover 2nd', 'Misc', 'D3Publisher', 2013, 'PSP'),
(591, 'Suzumiya Haruhi-Chan no Mahjong', 'Misc', 'Kadokawa Shoten', 2011, 'PSP'),
(592, 'Taiko no Tatsujin Portable 2', 'Misc', 'Namco Bandai Games', 2006, 'PSP'),
(593, 'Taiko no Tatsujin Portable DX', 'Misc', 'Namco Bandai Games', 2011, 'PSP'),
(594, 'TalkMan', 'Misc', 'Sony Computer Entertainment', 2006, 'PSP'),
(595, 'TalkMan (Japan)', 'Misc', 'Sony Computer Entertainment', 2005, 'PSP'),
(596, 'Touhoku Daigaku Mirai Kagaku Gijutsu Kyoudou Kenkyuu Center Kawashima Ryuuta Kyouju Kanshu: Nou Ryoku Trainer Portable', 'Misc', 'Sega', 2005, 'PSP'),
(597, 'Ultimate Board Game Collection', 'Misc', 'Xplosiv', 2007, 'PSP'),
(598, 'Uta no Prince-Sama: Music', 'Misc', 'Broccoli', 2011, 'PSP'),
(599, 'World Championship Cards', 'Misc', 'Crave Entertainment', 2008, 'PSP'),
(600, 'World Championship Poker 2: Featuring Howard Lederer', 'Misc', '505 Games', 2005, 'PSP'),
(601, 'World Championship Poker: Howard Lederer - All In', 'Misc', '505 Games', 2006, 'PSP'),
(602, 'World Poker Tour', 'Misc', 'Take-Two Interactive', 2006, 'PSP'),
(603, 'World Series of Poker', 'Misc', 'Activision', 2005, 'PSP'),
(604, 'World Series of Poker 2008: Battle for the Bracelets', 'Misc', 'Activision', 2007, 'PSP'),
(605, 'World Series of Poker: Tournament of Champions 2007 Edition', 'Misc', 'Activision', 2006, 'PSP'),
(606, 'Yamasa Digi Portable: Matsuri no Tatsujin - Win-Chan no Natsumatsuri', 'Misc', 'Yamasa Entertainment', 2006, 'PSP'),
(607, 'Zettai Meikyuu Grimm: Nanatsu no Kagi to Rakuen no Otome', 'Misc', 'Karin Entertainment', 2010, 'PSP'),
(608, 'Ape Escape: On the Loose', 'Platform', 'Sony Computer Entertainment', 2005, 'PSP'),
(609, 'Ben 10 Ultimate Alien: Cosmic Destruction', 'Platform', 'D3Publisher', 2010, 'PSP'),
(610, 'Castlevania: The Dracula X Chronicles', 'Platform', 'Konami Digital Entertainment', 2007, 'PSP'),
(611, 'CID The Dummy', 'Platform', 'Oxygen Interactive', 2009, 'PSP'),
(612, 'Cloudy With a Chance of Meatballs', 'Platform', 'Ubisoft', 2009, 'PSP'),
(613, 'Crash: Mind Over Mutant', 'Platform', 'Vivendi Games', 2008, 'PSP'),
(614, 'Daxter', 'Platform', 'Sony Computer Entertainment', 2006, 'PSP'),
(615, 'Death Jr.', 'Platform', 'Konami Digital Entertainment', 2005, 'PSP'),
(616, 'Death Jr. II: Root of Evil', 'Platform', 'Konami Digital Entertainment', 2006, 'PSP'),
(617, 'Despicable Me: The Game', 'Platform', 'D3Publisher', 2010, 'PSP'),
(618, 'Frogger: Helmet Chaos', 'Platform', 'Konami Digital Entertainment', 2005, 'PSP'),
(619, 'Goku Makaimura Kai', 'Platform', 'Capcom', 2007, 'PSP'),
(620, 'Impossible Mission', 'Platform', 'System 3 Arcade Software', 2007, 'PSP'),
(621, 'Jak and Daxter: The Lost Frontier', 'Platform', 'Sony Computer Entertainment', 2009, 'PSP'),
(622, 'Kao Challengers', 'Platform', 'Atari', 2005, 'PSP'),
(623, 'LittleBigPlanet', 'Platform', 'Sony Computer Entertainment', 2009, 'PSP'),
(624, 'LocoRoco', 'Platform', 'Sony Computer Entertainment', 2006, 'PSP'),
(625, 'LocoRoco 2', 'Platform', 'Sony Computer Entertainment', 2008, 'PSP'),
(626, 'Mega Man Maverick Hunter X', 'Platform', 'Capcom', 2005, 'PSP'),
(627, 'Mega Man Powered Up', 'Platform', 'Capcom', 2006, 'PSP'),
(628, 'N+', 'Platform', 'Atari', 2007, 'PSP'),
(629, 'Open Season', 'Platform', 'Ubisoft', 2006, 'PSP'),
(630, 'Over the Hedge: Hammy Goes Nuts!', 'Platform', 'Activision', 2006, 'PSP'),
(631, 'Pac-Man World 3', 'Platform', 'Namco Bandai Games', 2005, 'PSP'),
(632, 'Prinny 2: Dawn of Operation Panties, Dood!', 'Platform', 'Nippon Ichi Software', 2010, 'PSP'),
(633, 'Prinny: Can I Really Be the Hero?', 'Platform', 'Tecmo Koei', 2008, 'PSP'),
(634, 'Ratchet & Clank: Size Matters', 'Platform', 'Sony Computer Entertainment', 2007, 'PSP'),
(635, 'Saru! Get You! SaruSaru Daisakusen', 'Platform', 'Sony Computer Entertainment', 2007, 'PSP'),
(636, 'Secret Agent Clank', 'Platform', 'Sony Computer Entertainment', 2008, 'PSP'),
(637, 'Secret Agent Clank(US sales)', 'Platform', 'Sony Computer Entertainment', 2008, 'PSP'),
(638, 'Spider-Man 3', 'Platform', 'Activision', 2007, 'PSP'),
(639, 'Super Monkey Ball Adventure', 'Platform', 'Sega', 2006, 'PSP'),
(640, 'Tokobot', 'Platform', 'Take-Two Interactive', 2005, 'PSP'),
(641, 'Ultimate Ghosts \'n Goblins', 'Platform', 'Capcom', 2006, 'PSP'),
(642, 'Ultimate Ghosts \'n Goblins (JP sales)', 'Platform', 'Capcom', 2006, 'PSP'),
(643, 'Wall-E', 'Platform', 'THQ', 2008, 'PSP'),
(644, '7 Wonders of the Ancient World', 'Puzzle', 'Mumbo Jumbo', 2007, 'PSP'),
(645, 'Archer Maclean\'s Mercury', 'Puzzle', 'Ignition Entertainment', 2005, 'PSP'),
(646, 'Blokus Portable: Steambot Championship', 'Puzzle', 'Majesco Entertainment', 2006, 'PSP'),
(647, 'Bomberman', 'Puzzle', 'Konami Digital Entertainment', 2006, 'PSP'),
(648, 'Bomberman (jp sales)', 'Puzzle', 'Konami Digital Entertainment', 2006, 'PSP'),
(649, 'Bubble Bobble Evolution', 'Puzzle', 'Rising Star Games', 2006, 'PSP'),
(650, 'Bust-A-Move Deluxe', 'Puzzle', '505 Games', 2006, 'PSP'),
(651, 'Cake Mania: Baker\'s Challenge', 'Puzzle', 'Destineer', 2008, 'PSP'),
(652, 'Carol Vorderman\'s Sudoku', 'Puzzle', 'Xplosiv', 2006, 'PSP'),
(653, 'Chameleon', 'Puzzle', '505 Games', 2006, 'PSP'),
(654, 'Crush', 'Puzzle', 'Sega', 2007, 'PSP'),
(655, 'Cube', 'Puzzle', 'D3Publisher', 2007, 'PSP'),
(656, 'Diner Dash: Sizzle & Serve', 'Puzzle', 'Eidos Interactive', 2007, 'PSP'),
(657, 'echochrome', 'Puzzle', 'Sony Computer Entertainment', 2008, 'PSP'),
(658, 'Exit', 'Puzzle', 'Ubisoft', 2005, 'PSP'),
(659, 'Fading Shadows', 'Puzzle', 'Ivolgamus', 2008, 'PSP'),
(660, 'Frantix', 'Puzzle', 'Ubisoft', 2005, 'PSP'),
(661, 'Go! Sudoku', 'Puzzle', 'Sony Computer Entertainment', 2005, 'PSP'),
(662, 'Go! Sudoku (JP sales)', 'Puzzle', 'Sony Computer Entertainment', 2005, 'PSP'),
(663, 'GunPey', 'Puzzle', 'Atari', 2006, 'PSP'),
(664, 'Hot Pixel', 'Puzzle', 'Atari', 2007, 'PSP'),
(665, 'HotBrain', 'Puzzle', 'Midway Games', 2007, 'PSP'),
(666, 'Kotoba no Puzzle: Mojipittan Daijiten', 'Puzzle', 'Namco Bandai Games', 2004, 'PSP'),
(667, 'Lemmings', 'Puzzle', 'Sony Computer Entertainment', 2006, 'PSP'),
(668, 'Lumines ll', 'Puzzle', 'Disney Interactive Studios', 2006, 'PSP'),
(669, 'Lumines: Puzzle Fusion', 'Puzzle', 'Ubisoft', 2004, 'PSP'),
(670, 'Luxor: The Wrath of Set', 'Puzzle', 'Mumbo Jumbo', 2006, 'PSP'),
(671, 'Me & My Katamari', 'Puzzle', 'Namco Bandai Games', 2005, 'PSP'),
(672, 'Napoleon Dynamite: The Game', 'Puzzle', 'Crave Entertainment', 2007, 'PSP'),
(673, 'Pipe Mania', 'Puzzle', 'Empire Interactive', 2008, 'PSP'),
(674, 'PQ2: Practical Intelligence Quotient', 'Puzzle', 'D3Publisher', 2006, 'PSP'),
(675, 'PQ: Practical Intelligence Quotient', 'Puzzle', 'D3Publisher', 2005, 'PSP'),
(676, 'Puyo Pop Fever', 'Puzzle', 'Ignition Entertainment', 2004, 'PSP'),
(677, 'Puyo Puyo 7', 'Puzzle', 'Sega', 2009, 'PSP'),
(678, 'Puyo Puyo! 15th Anniversary', 'Puzzle', 'Sega', 2007, 'PSP'),
(679, 'Puzzle Challenge: Crosswords and More!', 'Puzzle', 'Crave Entertainment', 2006, 'PSP'),
(680, 'Puzzle Chronicles', 'Puzzle', 'Konami Digital Entertainment', 2010, 'PSP'),
(681, 'Puzzle Guzzle', 'Puzzle', 'DHM Interactive', 2007, 'PSP'),
(682, 'Puzzle Quest: Challenge of the Warlords', 'Puzzle', 'D3Publisher', 2007, 'PSP'),
(683, 'Quiz Mobile Gundam: Toi Senshi DX', 'Puzzle', 'Namco Bandai Games', 2006, 'PSP'),
(684, 'Smart Bomb', 'Puzzle', 'Eidos Interactive', 2005, 'PSP'),
(685, 'Ultimate Block Party', 'Puzzle', '505 Games', 2004, 'PSP'),
(686, 'WTF: Work Time Fun', 'Puzzle', 'Sony Computer Entertainment', 2005, 'PSP'),
(687, 'XI Coliseum', 'Puzzle', 'Sony Computer Entertainment', 2006, 'PSP'),
(688, 'ATV Offroad Fury Pro', 'Racing', 'Sony Computer Entertainment', 2006, 'PSP'),
(689, 'ATV Offroad Fury: Blazin\' Trails', 'Racing', 'SouthPeak Games', 2005, 'PSP'),
(690, 'Burnout Dominator', 'Racing', 'Electronic Arts', 2007, 'PSP'),
(691, 'Burnout Legends', 'Racing', 'Electronic Arts', 2005, 'PSP'),
(692, 'Cars', 'Racing', 'THQ', 2006, 'PSP'),
(693, 'Cars 2', 'Racing', 'Disney Interactive Studios', 2011, 'PSP'),
(694, 'Cars: Race-O-Rama', 'Racing', 'THQ', 2009, 'PSP'),
(695, 'Colin McRae Rally 2005 plus', 'Racing', 'Codemasters', 2005, 'PSP'),
(696, 'Crash Tag Team Racing', 'Racing', 'Vivendi Games', 2005, 'PSP'),
(697, 'Crazy Taxi: Fare Wars', 'Racing', 'Sega', 2007, 'PSP'),
(698, 'DiRT 2', 'Racing', 'Sony Computer Entertainment', 2009, 'PSP'),
(699, 'Driver \'76', 'Racing', 'Ubisoft', 2007, 'PSP'),
(700, 'DT Carnage', 'Racing', 'Agetec', 2009, 'PSP'),
(701, 'F1 2009', 'Racing', 'Codemasters', 2009, 'PSP'),
(702, 'FlatOut: Head On', 'Racing', 'Empire Interactive', 2008, 'PSP'),
(703, 'Ford Bold Moves Street Racing', 'Racing', 'Xplosiv', 2006, 'PSP'),
(704, 'Ford Racing Off Road', 'Racing', 'Xplosiv', 2008, 'PSP'),
(705, 'Full Auto 2: Battlelines', 'Racing', 'Sega', 2007, 'PSP'),
(706, 'Gran Turismo (PSP)', 'Racing', 'Sony Computer Entertainment', 2009, 'PSP'),
(707, 'GripShift', 'Racing', 'Ubisoft', 2005, 'PSP'),
(708, 'Hannspree Ten Kate Honda: SBK Superbike World Championship', 'Racing', 'Black Bean Games', 2007, 'PSP'),
(709, 'Initial D: Street Stage', 'Racing', 'Sega', 2006, 'PSP'),
(710, 'Juiced 2: Hot Import Nights', 'Racing', 'THQ', 2007, 'PSP'),
(711, 'Juiced: Eliminator', 'Racing', 'THQ', 2006, 'PSP'),
(712, 'Micro Machines V4', 'Racing', 'Codemasters', 2006, 'PSP'),
(713, 'Midnight Club 3: DUB Edition', 'Racing', 'Take-Two Interactive', 2005, 'PSP'),
(714, 'Midnight Club: LA Remix', 'Racing', 'Take-Two Interactive', 2008, 'PSP'),
(715, 'ModNation Racers', 'Racing', 'Sony Computer Entertainment', 2010, 'PSP'),
(716, 'Monster Jam: Path of Destruction', 'Racing', 'Activision', 2010, 'PSP'),
(717, 'Monster Jam: Urban Assault', 'Racing', 'Activision', 2008, 'PSP'),
(718, 'MotoGP', 'Racing', 'Sony Computer Entertainment', 2006, 'PSP'),
(719, 'MotorStorm: Arctic Edge', 'Racing', 'Sony Computer Entertainment', 2009, 'PSP'),
(720, 'MTX Mototrax', 'Racing', 'Activision', 2006, 'PSP'),
(721, 'MX vs. ATV Reflex', 'Racing', 'THQ', 2009, 'PSP'),
(722, 'MX vs. ATV Unleashed: On the Edge', 'Racing', 'THQ', 2006, 'PSP'),
(723, 'MX vs. ATV Untamed', 'Racing', 'THQ', 2007, 'PSP'),
(724, 'NASCAR', 'Racing', 'Electronic Arts', 2006, 'PSP'),
(725, 'Need for Speed Carbon: Own the City', 'Racing', 'Electronic Arts', 2006, 'PSP'),
(726, 'Need for Speed Underground Rivals', 'Racing', 'Electronic Arts', 2005, 'PSP'),
(727, 'Need for Speed: Most Wanted 5-1-0', 'Racing', 'Electronic Arts', 2005, 'PSP'),
(728, 'Need for Speed: ProStreet', 'Racing', 'Electronic Arts', 2008, 'PSP'),
(729, 'Need for Speed: Shift', 'Racing', 'Electronic Arts', 2009, 'PSP'),
(730, 'Need For Speed: Undercover', 'Racing', 'Electronic Arts', 2008, 'PSP'),
(731, 'NHRA Drag Racing: Countdown to the Championship', 'Racing', 'THQ', 2007, 'PSP'),
(732, 'OutRun 2006: Coast 2 Coast', 'Racing', 'Sega', 2006, 'PSP'),
(733, 'Pac-Man World Rally', 'Racing', 'Namco Bandai Games', 2006, 'PSP'),
(734, 'Pursuit Force', 'Racing', 'Sony Computer Entertainment', 2005, 'PSP'),
(735, 'Race Driver 2006', 'Racing', 'Codemasters', 2006, 'PSP'),
(736, 'Ridge Racer', 'Racing', 'Sony Computer Entertainment', 2004, 'PSP'),
(737, 'Ridge Racer 2', 'Racing', 'Sony Computer Entertainment', 2006, 'PSP'),
(738, 'Rush', 'Racing', 'Midway Games', 2006, 'PSP'),
(739, 'SBK Superbike World Championship', 'Racing', 'Black Bean Games', 2008, 'PSP'),
(740, 'Sega Rally Revo', 'Racing', 'Sega', 2007, 'PSP'),
(741, 'Shrek Smash n\' Crash Racing', 'Racing', 'Activision', 2006, 'PSP'),
(742, 'Sonic Rivals', 'Racing', 'Sega', 2006, 'PSP'),
(743, 'Sonic Rivals 2', 'Racing', 'Sega', 2007, 'PSP'),
(744, 'Split/Second', 'Racing', 'Disney Interactive Studios', 2010, 'PSP'),
(745, 'Street Supremacy', 'Racing', 'Konami Digital Entertainment', 2005, 'PSP'),
(746, 'Test Drive Unlimited', 'Racing', 'Atari', 2007, 'PSP'),
(747, 'The Fast and the Furious', 'Racing', 'Deep Silver', 2007, 'PSP'),
(748, 'TOCA Race Driver 2: Ultimate Racing Simulator', 'Racing', 'Codemasters', 2005, 'PSP'),
(749, 'Wangan Midnight Portable', 'Racing', 'Genki', 2007, 'PSP'),
(750, 'WipEout Pulse', 'Racing', 'Sony Computer Entertainment', 2007, 'PSP'),
(751, 'WipEout Pure', 'Racing', 'Sony Computer Entertainment', 2005, 'PSP'),
(752, 'WRC: FIA World Rally Championship', 'Racing', 'Sony Computer Entertainment', 2005, 'PSP'),
(753, '.hack//Link', 'Role-Playing', 'Namco Bandai Games', 2010, 'PSP'),
(754, '7th Dragon 2020', 'Role-Playing', 'Sega', 2011, 'PSP'),
(755, '7th Dragon 2020-II', 'Role-Playing', 'Sega', 2013, 'PSP'),
(756, 'Adventures to Go!', 'Role-Playing', 'Zushi Games', 2008, 'PSP'),
(757, 'Aedis Eclipse: Generation of Chaos', 'Role-Playing', 'Idea Factory', 2006, 'PSP'),
(758, 'Alien Syndrome', 'Role-Playing', 'Sega', 2007, 'PSP'),
(759, 'Antiphona no Seikahime: Tenshi no Gakufu Op.A', 'Role-Playing', 'Nippon Ichi Software', 2009, 'PSP'),
(760, 'Astonishia Story', 'Role-Playing', 'Ubisoft', 2006, 'PSP'),
(761, 'Battle Spirits: Hero\'s Soul', 'Role-Playing', 'Namco Bandai Games', 2010, 'PSP'),
(762, 'Battle Spirits: Kiseki no Hasha', 'Role-Playing', 'Namco Bandai Games', 2009, 'PSP'),
(763, 'Black * Rock Shooter: The Game', 'Role-Playing', 'Unknown', 2011, 'PSP'),
(764, 'Blade Dancer: Lineage of Light', 'Role-Playing', 'Atari', 2006, 'PSP'),
(765, 'Blaze Union: Story to Reach the Future', 'Role-Playing', 'Sting', 2010, 'PSP'),
(766, 'Blazing Souls: Accelate', 'Role-Playing', 'Idea Factory', 2009, 'PSP'),
(767, 'Brandish: The Dark Revenant', 'Role-Playing', 'Falcom Corporation', 2009, 'PSP'),
(768, 'Brave Story: New Traveler (US sales)', 'Role-Playing', 'Sony Computer Entertainment', 2006, 'PSP'),
(769, 'Brave Story: New Traveller (jp sales)', 'Role-Playing', 'Sony Computer Entertainment', 2006, 'PSP'),
(770, 'Breath of Fire III', 'Role-Playing', 'Capcom', 2005, 'PSP'),
(771, 'Class of Heroes', 'Role-Playing', 'Acquire', 2008, 'PSP'),
(772, 'Classic Dungeon X2', 'Role-Playing', 'Nippon Ichi Software', 2011, 'PSP'),
(773, 'Classic Dungeon: Fuyoku no Masoujin', 'Role-Playing', 'Nippon Ichi Software', 2010, 'PSP'),
(774, 'Coded Soul: Uke Keigareshi Idea', 'Role-Playing', 'Sony Computer Entertainment', 2008, 'PSP'),
(775, 'Conception: Please Give Birth to My Child!', 'Role-Playing', 'Spike', 2012, 'PSP'),
(776, 'Criminal Girls: Invite Only', 'Role-Playing', 'Nippon Ichi Software', 2010, 'PSP'),
(777, 'Crimson Gem Saga', 'Role-Playing', 'Sega', 2008, 'PSP'),
(778, 'Crisis Core: Final Fantasy VII', 'Role-Playing', 'Square Enix', 2007, 'PSP'),
(779, 'Danball Senki', 'Role-Playing', 'Level 5', 2011, 'PSP'),
(780, 'Densetsu no Yuusha no Densetsu: Legendary Saga', 'Role-Playing', 'Kadokawa Shoten', 2010, 'PSP'),
(781, 'Digimon Adventure', 'Role-Playing', 'Namco Bandai Games', 2013, 'PSP'),
(782, 'Disgaea 2: Dark Hero Days', 'Role-Playing', 'Nippon Ichi Software', 2009, 'PSP'),
(783, 'Disgaea: Afternoon of Darkness', 'Role-Playing', 'Tecmo Koei', 2006, 'PSP'),
(784, 'DokuSui: DokiDoki Suikoden', 'Role-Playing', 'Irem Software Engineering', 2011, 'PSP'),
(785, 'Dragoneer\'s Aria', 'Role-Playing', 'Tecmo Koei', 2007, 'PSP'),
(786, 'Dungeon Explorer: Warriors of Ancient Arts', 'Role-Playing', 'Rising Star Games', 2007, 'PSP'),
(787, 'Dungeon Maker II: The Hidden War', 'Role-Playing', 'Global A Entertainment', 2007, 'PSP'),
(788, 'Dungeon Maker: Hunting Ground', 'Role-Playing', 'Global A Entertainment', 2006, 'PSP'),
(789, 'Dungeon Siege: Throne of Agony', 'Role-Playing', 'Take-Two Interactive', 2006, 'PSP'),
(790, 'Dungeon Travelers 2: The Royal Library & The Monster Seal', 'Role-Playing', 'Aqua Plus', 2013, 'PSP'),
(791, 'Eiyuu Densetsu: Sora no Kiseki Material Collection Portable', 'Role-Playing', 'Falcom Corporation', 2007, 'PSP'),
(792, 'Elminage Gothic: Ulm Zakir to Yami no Gishiki', 'Role-Playing', 'Starfish', 2012, 'PSP'),
(793, 'Elminage II: Sousei no Megami to Unmei no Daichi', 'Role-Playing', 'Starfish', 2009, 'PSP'),
(794, 'Elminage III: Ankoku no Shito to Yaiyou no Kyuuden', 'Role-Playing', 'Starfish', 2011, 'PSP'),
(795, 'Elminage Original: Majo to Megami to Kamigami no Yubiwa', 'Role-Playing', 'Starfish', 2011, 'PSP'),
(796, 'Entaku no Seito: The Eternal Legend', 'Role-Playing', 'Kadokawa Games', 2012, 'PSP'),
(797, 'Eyeshield 21: Portable Edition', 'Role-Playing', 'Konami Digital Entertainment', 2006, 'PSP'),
(798, 'Fate/Extra', 'Role-Playing', 'Marvelous Interactive', 2010, 'PSP'),
(799, 'Final Fantasy Anniversary Edition', 'Role-Playing', 'Square Enix', 2007, 'PSP'),
(800, 'Final Fantasy II Anniversary Edition', 'Role-Playing', 'Square Enix', 2007, 'PSP'),
(801, 'Final Fantasy III', 'Role-Playing', 'Square Enix', 2012, 'PSP'),
(802, 'Final Fantasy IV: The Complete Collection', 'Role-Playing', 'Square Enix', 2011, 'PSP'),
(803, 'Final Fantasy Tactics: The War of the Lions', 'Role-Playing', 'Square Enix', 2007, 'PSP'),
(804, 'Final Fantasy Type-0', 'Role-Playing', 'Unknown', 2011, 'PSP'),
(805, 'Frontier Gate', 'Role-Playing', 'Konami Digital Entertainment', 2011, 'PSP'),
(806, 'Fushigi no Dungeon: Fuurai no Shiren 3 Portable', 'Role-Playing', 'Spike', 2010, 'PSP'),
(807, 'Gaku ? Ou: The Royal Seven Stars', 'Role-Playing', 'Alchemist', 2012, 'PSP'),
(808, 'Generation of Chaos', 'Role-Playing', 'Midas Interactive Entertainment', 2005, 'PSP'),
(809, 'Gensou Suikoden I & II', 'Role-Playing', 'Konami Digital Entertainment', 2006, 'PSP'),
(810, 'Gloria Union', 'Role-Playing', 'Atlus', 2011, 'PSP'),
(811, 'God Eater 2', 'Role-Playing', 'Namco Bandai Games', 2013, 'PSP'),
(812, 'Grand Knights History', 'Role-Playing', 'Marvelous Interactive', 2011, 'PSP'),
(813, 'Growlanser', 'Role-Playing', 'Atlus', 2009, 'PSP'),
(814, 'Growlanser IV: Over Reloaded', 'Role-Playing', 'Atlus', 2011, 'PSP'),
(815, 'Gungnir: Mayari no Gunshin to Eiyuu Sensou', 'Role-Playing', 'Atlus', 2011, 'PSP'),
(816, 'Half-Minute Hero', 'Role-Playing', 'Rising Star Games', 2009, 'PSP'),
(817, 'Harukanaru Toki no Naka de 4: Aizouban', 'Role-Playing', 'Tecmo Koei', 2010, 'PSP'),
(818, 'Harukanaru Toki no Naka de 5', 'Role-Playing', 'Tecmo Koei', 2011, 'PSP'),
(819, 'Harukanaru Toki no Naka de 5: Kazahanaki', 'Role-Playing', 'Ackkstudios', 2012, 'PSP'),
(820, 'Heroes Phantasia', 'Role-Playing', 'Namco Bandai Games', 2012, 'PSP'),
(821, 'Hexyz Force', 'Role-Playing', 'Atlus', 2009, 'PSP'),
(822, 'Holy Invasion of Privacy, Badman! What Did I Do to Deserve This?', 'Role-Playing', 'Nippon Ichi Software', 2007, 'PSP'),
(823, 'Jeanne d\'Arc', 'Role-Playing', 'Sony Computer Entertainment', 2006, 'PSP'),
(824, 'Jikandia: The Timeless Land', 'Role-Playing', 'Idea Factory', 2010, 'PSP'),
(825, 'Judie no Atelier: Guramnat no Renkinjutsu - Toraware no Morito', 'Role-Playing', 'Gust', 2010, 'PSP'),
(826, 'Justice League Heroes', 'Role-Playing', 'Eidos Interactive', 2006, 'PSP'),
(827, 'Ken to Mahou to Gakuen Mono. 2', 'Role-Playing', 'Acquire', 2009, 'PSP'),
(828, 'Ken to Mahou to Gakuen Mono. 3', 'Role-Playing', 'Acquire', 2010, 'PSP'),
(829, 'Kingdom Hearts: Birth by Sleep', 'Role-Playing', 'Square Enix', 2010, 'PSP'),
(830, 'Kingdom Hearts: Birth by Sleep - Final Mix', 'Role-Playing', 'Square Enix', 2011, 'PSP'),
(831, 'Kingdom of Paradise', 'Role-Playing', 'Sony Computer Entertainment', 2005, 'PSP'),
(832, 'Kiniro no Corda 2 f', 'Role-Playing', 'Tecmo Koei', 2009, 'PSP'),
(833, 'Kiniro no Corda 2 f Encore', 'Role-Playing', 'Tecmo Koei', 2009, 'PSP'),
(834, 'Knights in the Nightmare', 'Role-Playing', 'Atlus', 2010, 'PSP'),
(835, 'La Pucelle: Ragnarok', 'Role-Playing', 'Nippon Ichi Software', 2009, 'PSP'),
(836, 'Last Ranker', 'Role-Playing', 'Capcom', 2010, 'PSP'),
(837, 'Little Battlers eXperience W', 'Role-Playing', 'Level 5', 2012, 'PSP'),
(838, 'Lord of Apocalypse', 'Role-Playing', 'Square Enix', 2011, 'PSP'),
(839, 'Lord of Arcana', 'Role-Playing', 'Square Enix', 2010, 'PSP'),
(840, 'Lost Heroes', 'Role-Playing', 'Namco Bandai Games', 2012, 'PSP'),
(841, 'Lunar: Silver Star Harmony', 'Role-Playing', 'GungHo', 2009, 'PSP'),
(842, 'Magna Carta Portable', 'Role-Playing', 'Banpresto', 2006, 'PSP'),
(843, 'Makai Senki Disgaea Portable: Tsuushin Taisen Hajime Mashita', 'Role-Playing', 'Nippon Ichi Software', 2007, 'PSP'),
(844, 'Mana Khemia 2: Ochita Gakuen to Renkinjutsushi Tachi Portable+', 'Role-Playing', 'Gust', 2009, 'PSP'),
(845, 'Mana Khemia: Student Alliance', 'Role-Playing', 'Nippon Ichi Software', 2008, 'PSP'),
(846, 'Marvel: Ultimate Alliance', 'Role-Playing', 'Activision', 2006, 'PSP'),
(847, 'Marvel: Ultimate Alliance 2', 'Role-Playing', 'Activision', 2009, 'PSP'),
(848, 'Mimana Iyar Chronicle', 'Role-Playing', 'GungHo', 2009, 'PSP'),
(849, 'MonHun Nikki: Poka Poka Ailu Mura', 'Role-Playing', 'Capcom', 2010, 'PSP'),
(850, 'MonHun Nikki: Poka Poka Ailu Mura G', 'Role-Playing', 'Capcom', 2011, 'PSP'),
(851, 'Monster Hunter Freedom', 'Role-Playing', 'Capcom', 2005, 'PSP'),
(852, 'Monster Hunter Freedom 2', 'Role-Playing', 'Capcom', 2007, 'PSP'),
(853, 'Monster Hunter Freedom 3', 'Role-Playing', 'Capcom', 2010, 'PSP'),
(854, 'Monster Hunter Freedom Unite', 'Role-Playing', 'Capcom', 2008, 'PSP'),
(855, 'Monster Kingdom: Jewel Summoner', 'Role-Playing', 'Sony Computer Entertainment', 2006, 'PSP'),
(856, 'Nendoroid Generation', 'Role-Playing', 'Namco Bandai Games', 2012, 'PSP'),
(857, 'Neverland Card Battles', 'Role-Playing', 'Idea Factory', 2008, 'PSP'),
(858, 'Ore no Shikabane o Koete Yuke', 'Role-Playing', 'Sony Computer Entertainment', 2011, 'PSP'),
(859, 'PC Engine Best Collection: Tengai Makyou Collection', 'Role-Playing', 'Hudson Soft', 2008, 'PSP'),
(860, 'Persona 2: Eternal Punishment', 'Role-Playing', 'Atlus', 2012, 'PSP'),
(861, 'Phantasy Star Portable', 'Role-Playing', 'Sega', 2008, 'PSP'),
(862, 'Phantasy Star Portable 2', 'Role-Playing', 'Sega', 2009, 'PSP'),
(863, 'Phantasy Star Portable 2: Infinity', 'Role-Playing', 'Sega', 2011, 'PSP'),
(864, 'Phantom Brave: The Hermuda Triangle', 'Role-Playing', 'Nippon Ichi Software', 2010, 'PSP'),
(865, 'Phantom Kingdom Portable', 'Role-Playing', 'Nippon Ichi Software', 2011, 'PSP'),
(866, 'PoPoLoCrois', 'Role-Playing', 'Ignition Entertainment', 2005, 'PSP'),
(867, 'PoPoLoCrois (JP sales)', 'Role-Playing', 'Ignition Entertainment', 2005, 'PSP'),
(868, 'Puella Magi Madoka Magica Portable', 'Role-Playing', 'Namco Bandai Games', 2012, 'PSP'),
(869, 'Queen\'s Blade: Spiral Chaos', 'Role-Playing', 'Namco Bandai Games', 2009, 'PSP'),
(870, 'Queen\'s Gate: Spiral Chaos', 'Role-Playing', 'Namco Bandai Games', 2011, 'PSP'),
(871, 'Ragnarok: Hikari to Yami no Koujo', 'Role-Playing', 'GungHo', 2011, 'PSP'),
(872, 'Record of Agarest War: Marriage', 'Role-Playing', 'Compile Heart', 2012, 'PSP'),
(873, 'Riviera: The Promised Land', 'Role-Playing', '505 Games', 2006, 'PSP'),
(874, 'Saigo no Yakusoku no Monogatari', 'Role-Playing', 'Unknown', 2011, 'PSP'),
(875, 'Saru! Get You! Pipo Saru Senki', 'Role-Playing', 'Sony Computer Entertainment', 2009, 'PSP'),
(876, 'Senritsu no Stratus', 'Role-Playing', 'Konami Digital Entertainment', 2011, 'PSP'),
(877, 'Shin Ken to Mah? to Gakuenmono. Toki no Gakuen', 'Role-Playing', 'Acquire', 2012, 'PSP'),
(878, 'Shin Megami Tensei: Persona', 'Role-Playing', 'Atlus', 2009, 'PSP'),
(879, 'Shin Megami Tensei: Persona 2: Innocent Sin', 'Role-Playing', 'Atlus', 2011, 'PSP'),
(880, 'Shin Megami Tensei: Persona 3 Portable', 'Role-Playing', 'Ghostlight', 2009, 'PSP'),
(881, 'Shining Ark', 'Role-Playing', 'Sega', 2013, 'PSP'),
(882, 'Shining Blade', 'Role-Playing', 'Sega', 2012, 'PSP'),
(883, 'Shining Hearts', 'Role-Playing', 'Sega', 2010, 'PSP'),
(884, 'Shiren the Wanderer 4 - God\'s Eye and the Demon\'s Navel', 'Role-Playing', 'Spike', 2012, 'PSP'),
(885, 'Sol Trigger', 'Role-Playing', 'Image Epoch', 2012, 'PSP'),
(886, 'Spectral Souls: Resurrection of the Ethereal Empires', 'Role-Playing', 'Idea Factory', 2005, 'PSP'),
(887, 'Star Ocean: First Departure', 'Role-Playing', 'Square Enix', 2007, 'PSP'),
(888, 'Star Ocean: Second Evolution', 'Role-Playing', 'Square Enix', 2008, 'PSP'),
(889, 'Suikoden: Tsumugareshi Hyakunen no Toki', 'Role-Playing', 'Konami Digital Entertainment', 2012, 'PSP'),
(890, 'Summon Night 3', 'Role-Playing', 'Namco Bandai Games', 2012, 'PSP'),
(891, 'Summon Night 4', 'Role-Playing', 'Namco Bandai Games', 2012, 'PSP'),
(892, 'Summon Night 5', 'Role-Playing', 'Namco Bandai Games', 2013, 'PSP'),
(893, 'Sword Art Online: Infinity Moment', 'Role-Playing', 'Namco Bandai Games', 2013, 'PSP'),
(894, 'Tactics Ogre: Let Us Cling Together', 'Role-Playing', 'Square Enix', 2010, 'PSP'),
(895, 'Tales of Destiny 2', 'Role-Playing', 'Namco Bandai Games', 2007, 'PSP'),
(896, 'Tales of Eternia', 'Role-Playing', 'Ubisoft', 2005, 'PSP'),
(897, 'Tales of Phantasia (PS1 & PSP Versions)', 'Role-Playing', 'Namco Bandai Games', 2006, 'PSP'),
(898, 'Tales of Phantasia: Narikiri Dungeon X', 'Role-Playing', 'Namco Bandai Games', 2010, 'PSP'),
(899, 'Tales of Rebirth', 'Role-Playing', 'Namco Bandai Games', 2008, 'PSP'),
(900, 'Tales of the Heroes: Twin Brave', 'Role-Playing', 'Namco Bandai Games', 2012, 'PSP'),
(901, 'Tales of the World: Radiant Mythology', 'Role-Playing', 'Ubisoft', 2006, 'PSP'),
(902, 'Tales of the World: Radiant Mythology 2', 'Role-Playing', 'Namco Bandai Games', 2009, 'PSP'),
(903, 'Tales of the World: Radiant Mythology 3', 'Role-Playing', 'Namco Bandai Games', 2011, 'PSP'),
(904, 'Tegami Bachi: Kokoro Tsumugu Mono e', 'Role-Playing', 'Konami Digital Entertainment', 2010, 'PSP'),
(905, 'Tengai Makyo: Dai Yon no Mokushiroku', 'Role-Playing', 'Hudson Soft', 2006, 'PSP'),
(906, 'The 3rd Birthday', 'Role-Playing', 'Square Enix', 2010, 'PSP'),
(907, 'The Legend of Heroes II: Prophecy of the Moonlight Witch', 'Role-Playing', 'Namco Bandai Games', 2004, 'PSP'),
(908, 'The Legend of Heroes III: Song of the Ocean', 'Role-Playing', 'Namco Bandai Games', 2006, 'PSP'),
(909, 'The Legend of Heroes VII: The Trail of Blue', 'Role-Playing', 'Falcom Corporation', 2011, 'PSP'),
(910, 'The Legend of Heroes VII: The Trail of Zero', 'Role-Playing', 'Falcom Corporation', 2010, 'PSP'),
(911, 'The Legend of Heroes: A Tear of Vermillion', 'Role-Playing', 'Namco Bandai Games', 2005, 'PSP'),
(912, 'The Legend of Heroes: Trails in the Sky First Chapter', 'Role-Playing', 'Ghostlight', 2006, 'PSP'),
(913, 'The Legend of Heroes: Trails in the Sky Second Chapter', 'Role-Playing', 'Falcom Corporation', 2007, 'PSP'),
(914, 'The Legend of Heroes: Trails in the Sky Third Chapter', 'Role-Playing', 'Falcom Corporation', 2008, 'PSP'),
(915, 'Tokyo Mono Harashi: Karasu no Mori Gakuen Kitan', 'Role-Playing', 'Atlus', 2010, 'PSP'),
(916, 'Toriko: Gourmet Survival!', 'Role-Playing', 'Namco Bandai Games', 2011, 'PSP'),
(917, 'UnchainBlades EXXiV', 'Role-Playing', 'FuRyu', 2012, 'PSP'),
(918, 'Unchained Blades', 'Role-Playing', 'FuRyu', 2011, 'PSP'),
(919, 'Untold Legends: Brotherhood of the Blade', 'Role-Playing', 'Activision', 2005, 'PSP'),
(920, 'Untold Legends: The Warriors Code', 'Role-Playing', 'Ubisoft', 2006, 'PSP'),
(921, 'Utawarerumono Portable', 'Role-Playing', 'Aqua Plus', 2009, 'PSP'),
(922, 'Valhalla Knights', 'Role-Playing', 'Rising Star Games', 2006, 'PSP'),
(923, 'Valhalla Knights 2', 'Role-Playing', 'Rising Star Games', 2008, 'PSP'),
(924, 'Valhalla Knights 2: Battle Stance', 'Role-Playing', 'Marvelous Interactive', 2009, 'PSP'),
(925, 'Valkyria Chronicles II', 'Role-Playing', 'Sega', 2010, 'PSP'),
(926, 'Valkyrie Profile: Lenneth', 'Role-Playing', 'Square Enix', 2006, 'PSP'),
(927, 'Vantage Master Portable', 'Role-Playing', 'Falcom Corporation', 2008, 'PSP'),
(928, 'Venus & Braves: Majo to Megami to Horobi no Yogen', 'Role-Playing', 'Namco Bandai Games', 2011, 'PSP'),
(929, 'Violet no Atelier: Gramnad no Renkinjutsushi 2 - Gunjou no Omoide', 'Role-Playing', 'Gust', 2011, 'PSP'),
(930, 'Warriors of the Lost Empire', 'Role-Playing', 'Mercury Games', 2007, 'PSP'),
(931, 'Warriors of the Lost Empire (JP sales)', 'Role-Playing', 'Mercury Games', 2007, 'PSP'),
(932, 'What Did I Do to Deserve This, My Lord!? 2', 'Role-Playing', 'Nippon Ichi Software', 2008, 'PSP'),
(933, 'White Knight Chronicles: Origins', 'Role-Playing', 'Sony Computer Entertainment', 2011, 'PSP'),
(934, 'Wild ARMs XF', 'Role-Playing', '505 Games', 2007, 'PSP'),
(935, 'X-Men Legends II: Rise of Apocalypse', 'Role-Playing', 'Activision', 2005, 'PSP'),
(936, 'Yggdra Union: We\'ll Never Fight Alone', 'Role-Playing', 'Sting', 2008, 'PSP'),
(937, 'Ys I & II Chronicles', 'Role-Playing', 'Falcom Corporation', 2009, 'PSP'),
(938, 'Ys Seven', 'Role-Playing', 'Falcom Corporation', 2009, 'PSP'),
(939, 'Ys: The Ark of Napishtim', 'Role-Playing', 'Konami Digital Entertainment', 2006, 'PSP'),
(940, 'Ys: The Oath in Felghana', 'Role-Playing', 'Falcom Corporation', 2010, 'PSP'),
(941, 'Zetta Hero Project: Unlosing Ranger vs. Darkdeath Evilman', 'Role-Playing', 'Nippon Ichi Software', 2010, 'PSP'),
(942, 'Zill O\'ll Infinite Plus', 'Role-Playing', 'Tecmo Koei', 2009, 'PSP'),
(943, 'Zwei!!', 'Role-Playing', 'Falcom Corporation', 2008, 'PSP'),
(944, 'Army of Two: The 40th Day', 'Shooter', 'Electronic Arts', 2010, 'PSP'),
(945, 'Battlezone', 'Shooter', 'Atari', 2006, 'PSP'),
(946, 'Brothers In Arms: D-Day', 'Shooter', 'Ubisoft', 2006, 'PSP'),
(947, 'Call of Duty: Roads to Victory', 'Shooter', 'Activision', 2007, 'PSP'),
(948, 'Chili Con Carnage', 'Shooter', 'Eidos Interactive', 2007, 'PSP'),
(949, 'Coded Arms', 'Shooter', 'Konami Digital Entertainment', 2005, 'PSP'),
(950, 'Coded Arms: Contagion', 'Shooter', 'Konami Digital Entertainment', 2007, 'PSP'),
(951, 'Dead to Rights: Reckoning', 'Shooter', 'Electronic Arts', 2005, 'PSP'),
(952, 'Every Extend Extra', 'Shooter', 'Disney Interactive Studios', 2006, 'PSP'),
(953, 'Gradius Collection', 'Shooter', 'Konami Digital Entertainment', 2006, 'PSP'),
(954, 'Infected', 'Shooter', 'THQ', 2005, 'PSP'),
(955, 'Killzone: Liberation', 'Shooter', 'Sony Computer Entertainment', 2006, 'PSP'),
(956, 'Mahou Shoujo Lyrical Nanoha A\'s Portable: The Battle of Aces', 'Shooter', 'Namco Bandai Games', 2010, 'PSP'),
(957, 'Medal of Honor Heroes', 'Shooter', 'Electronic Arts', 2006, 'PSP'),
(958, 'Medal of Honor Heroes 2', 'Shooter', 'Electronic Arts', 2007, 'PSP'),
(959, 'Metal Slug Anthology', 'Shooter', 'Ignition Entertainment', 2007, 'PSP'),
(960, 'Metal Slug XX', 'Shooter', 'DHM Interactive', 2009, 'PSP'),
(961, 'Miami Vice: The Game', 'Shooter', 'Activision', 2006, 'PSP'),
(962, 'Mobile Suit Gundam Seed: Rengou vs. Z.A.F.T. Portable', 'Shooter', 'Namco Bandai Games', 2007, 'PSP'),
(963, 'Platypus', 'Shooter', 'Funsta', 2006, 'PSP'),
(964, 'Resistance: Retribution', 'Shooter', 'Sony Computer Entertainment', 2009, 'PSP'),
(965, 'SOCOM: Tactical Strike', 'Shooter', 'Sony Computer Entertainment', 2007, 'PSP'),
(966, 'SOCOM: U.S. Navy SEALs Fireteam Bravo', 'Shooter', 'Sony Computer Entertainment', 2005, 'PSP'),
(967, 'SOCOM: U.S. Navy SEALs Fireteam Bravo 2', 'Shooter', 'Sony Computer Entertainment', 2006, 'PSP'),
(968, 'SOCOM: U.S. Navy SEALs Fireteam Bravo 3', 'Shooter', 'Sony Computer Entertainment', 2010, 'PSP'),
(969, 'Space Invaders Extreme', 'Shooter', 'Square Enix', 2008, 'PSP'),
(970, 'Star Wars Battlefront: Elite Squadron', 'Shooter', 'LucasArts', 2009, 'PSP'),
(971, 'Star Wars Battlefront: Renegade Squadron', 'Shooter', 'LucasArts', 2007, 'PSP'),
(972, 'Star Wars: Battlefront II', 'Shooter', 'LucasArts', 2005, 'PSP'),
(973, 'SWAT: Target Liberty', 'Shooter', 'Vivendi Games', 2007, 'PSP'),
(974, 'Syphon Filter: Dark Mirror', 'Shooter', 'Sony Computer Entertainment', 2006, 'PSP'),
(975, 'Syphon Filter: Logan\'s Shadow', 'Shooter', 'Sony Computer Entertainment', 2007, 'PSP'),
(976, 'Tom Clancy\'s Ghost Recon Advanced Warfighter 2', 'Shooter', 'Ubisoft', 2007, 'PSP'),
(977, 'Tom Clancy\'s Ghost Recon: Predator', 'Shooter', 'Ubisoft', 2010, 'PSP'),
(978, 'Tom Clancy\'s Rainbow Six: Vegas', 'Shooter', 'Ubisoft', 2007, 'PSP'),
(979, 'Tom Clancy\'s Splinter Cell: Essentials', 'Shooter', 'Ubisoft', 2006, 'PSP'),
(980, 'Transformers: Revenge of the Fallen (XBox 360, PS3, & PC Versions)', 'Shooter', 'Activision', 2009, 'PSP'),
(981, 'A.C.E.: Another Century\'s Episode Portable', 'Simulation', 'Namco Bandai Games', 2011, 'PSP'),
(982, 'Ace Combat X: Skies of Deception', 'Simulation', 'Namco Bandai Games', 2006, 'PSP'),
(983, 'Ace Combat: Joint Assault', 'Simulation', 'Namco Bandai Games', 2010, 'PSP'),
(984, 'Air Conflicts: Aces of World War II', 'Simulation', 'Graffiti', 2009, 'PSP'),
(985, 'Armored Core 3 Portable', 'Simulation', 'From Software', 2009, 'PSP'),
(986, 'Armored Core SL: Silent Line Portable', 'Simulation', 'From Software', 2009, 'PSP'),
(987, 'Armored Core: Formula Front Extreme Battle', 'Simulation', '505 Games', 2004, 'PSP'),
(988, 'Armored Core: Last Raven Portable', 'Simulation', 'From Software', 2010, 'PSP'),
(989, 'Brooktown High: Senior Year', 'Simulation', 'Konami Digital Entertainment', 2007, 'PSP'),
(990, 'Dream C Club Portable', 'Simulation', 'D3Publisher', 2010, 'PSP'),
(991, 'EyePet', 'Simulation', 'Sony Computer Entertainment', 2010, 'PSP'),
(992, 'Harvest Moon: Boy & Girl', 'Simulation', 'Marvelous Interactive', 2005, 'PSP'),
(993, 'Harvest Moon: Hero of Leaf Valley', 'Simulation', 'Rising Star Games', 2009, 'PSP'),
(994, 'I Am In The Movie', 'Simulation', 'Namco Bandai Games', 2012, 'PSP'),
(995, 'IL-2 Sturmovik: Birds of Prey', 'Simulation', '505 Games', 2009, 'PSP'),
(996, 'Innocent Life: A Futuristic Harvest Moon', 'Simulation', 'Rising Star Games', 2006, 'PSP'),
(997, 'Machi-Ing Maker 3 x Tousouchuu', 'Simulation', 'D3Publisher', 2010, 'PSP'),
(998, 'Macross Ace Frontier', 'Simulation', 'Namco Bandai Games', 2008, 'PSP'),
(999, 'Petz: Dogz Family', 'Simulation', 'Ubisoft', 2009, 'PSP'),
(1000, 'Petz: Hamsterz Bunch', 'Simulation', 'Ubisoft', 2009, 'PSP'),
(1001, 'Petz: Saddle Club', 'Simulation', 'Ubisoft', 2009, 'PSP'),
(1002, 'Pilot Academy', 'Simulation', 'Rising Star Games', 2006, 'PSP'),
(1003, 'Portable Island: Tenohira Resort', 'Simulation', 'Namco Bandai Games', 2006, 'PSP'),
(1004, 'Shepherd\'s Crossing', 'Simulation', 'Success', 2009, 'PSP'),
(1005, 'The Sims 2', 'Simulation', 'Electronic Arts', 2005, 'PSP'),
(1006, 'The Sims 2: Castaway', 'Simulation', 'Electronic Arts', 2007, 'PSP'),
(1007, 'The Sims 2: Pets', 'Simulation', 'Electronic Arts', 2006, 'PSP'),
(1008, 'Warship Gunner 2 Portable', 'Simulation', 'Tecmo Koei', 2009, 'PSP'),
(1009, 'World Neverland 2in1 Portable: Olerud Kingdom & Republic of Pluto', 'Simulation', 'fonfun', 2008, 'PSP'),
(1010, '2010 FIFA World Cup South Africa', 'Sports', 'Electronic Arts', 2010, 'PSP'),
(1011, 'Blitz: Overtime', 'Sports', 'Midway Games', 2006, 'PSP'),
(1012, 'Brunswick Pro Bowling', 'Sports', '505 Games', 2007, 'PSP'),
(1013, 'Cabela\'s African Safari', 'Sports', 'Activision Value', 2006, 'PSP'),
(1014, 'Cabela\'s Dangerous Hunts: Ultimate Challenge', 'Sports', 'Activision Value', 2006, 'PSP'),
(1015, 'Cabela\'s Legendary Adventures', 'Sports', 'Activision', 2008, 'PSP'),
(1016, 'Cabela\'s North American Adventures', 'Sports', 'Activision', 2010, 'PSP'),
(1017, 'Dave Mirra BMX Challenge', 'Sports', 'Oxygen Interactive', 2006, 'PSP'),
(1018, 'Derby Stallion P', 'Sports', 'Enterbrain', 2006, 'PSP'),
(1019, 'Derby Time 2006', 'Sports', 'Sony Computer Entertainment', 2006, 'PSP'),
(1020, 'FIFA 12', 'Sports', 'Electronic Arts', 2011, 'PSP'),
(1021, 'FIFA 14', 'Sports', 'Electronic Arts', 2013, 'PSP'),
(1022, 'FIFA Soccer', 'Sports', 'Electronic Arts', 2005, 'PSP'),
(1023, 'FIFA Soccer 06', 'Sports', 'Electronic Arts', 2005, 'PSP'),
(1024, 'FIFA Soccer 07', 'Sports', 'Electronic Arts', 2006, 'PSP'),
(1025, 'FIFA Soccer 08', 'Sports', 'Electronic Arts', 2007, 'PSP'),
(1026, 'FIFA Soccer 09', 'Sports', 'Electronic Arts', 2008, 'PSP'),
(1027, 'FIFA Soccer 10', 'Sports', 'Electronic Arts', 2009, 'PSP'),
(1028, 'FIFA Soccer 11', 'Sports', 'Electronic Arts', 2010, 'PSP'),
(1029, 'FIFA Street 2', 'Sports', 'Electronic Arts', 2006, 'PSP'),
(1030, 'FIFA World Cup Germany 2006', 'Sports', 'Electronic Arts', 2006, 'PSP'),
(1031, 'Football Manager 2012', 'Sports', 'Sega', 2011, 'PSP'),
(1032, 'Football Manager Handheld 2008', 'Sports', 'Sega', 2007, 'PSP'),
(1033, 'Football Manager Handheld 2009', 'Sports', 'Sega', 2008, 'PSP'),
(1034, 'Football Manager Handheld 2010', 'Sports', 'Sega', 2009, 'PSP'),
(1035, 'Football Manager Handheld 2011', 'Sports', 'Sega', 2010, 'PSP'),
(1036, 'Gretzky NHL', 'Sports', 'Sony Computer Entertainment', 2005, 'PSP'),
(1037, 'Gretzky NHL 06', 'Sports', 'Sony Computer Entertainment', 2005, 'PSP'),
(1038, 'Hot Shots Golf: Open Tee', 'Sports', 'Sony Computer Entertainment', 2004, 'PSP'),
(1039, 'Hot Shots Golf: Open Tee 2', 'Sports', 'Sony Computer Entertainment', 2007, 'PSP'),
(1040, 'Hot Shots Tennis: Get a Grip', 'Sports', 'Sony Computer Entertainment', 2010, 'PSP'),
(1041, 'J-League Pro Soccer Club o Tsukurou! 6: Pride of J', 'Sports', 'Sega', 2009, 'PSP'),
(1042, 'J-League Pro Soccer Club o Tsukurou! 7 Euro Plus', 'Sports', 'Sega', 2011, 'PSP'),
(1043, 'J.League Pro Soccer Club o Tsukurou! 8 Euro Plus', 'Sports', 'Sega', 2013, 'PSP'),
(1044, 'Jikkyou Powerful Pro Yakyuu 2010', 'Sports', 'Konami Digital Entertainment', 2010, 'PSP'),
(1045, 'Jikkyou Powerful Pro Yakyuu 2011', 'Sports', 'Konami Digital Entertainment', 2011, 'PSP'),
(1046, 'Jikkyou Powerful Pro Yakyuu 2011 Ketteiban', 'Sports', 'Konami Digital Entertainment', 2011, 'PSP'),
(1047, 'Jikkyou Powerful Pro Yakyuu 2013', 'Sports', 'Konami Digital Entertainment', 2013, 'PSP'),
(1048, 'Jikkyou Powerful Pro Yakyuu Portable', 'Sports', 'Konami Digital Entertainment', 2006, 'PSP'),
(1049, 'Jikkyou Powerful Pro Yakyuu Portable 2', 'Sports', 'Konami Digital Entertainment', 2007, 'PSP'),
(1050, 'Jikkyou Powerful Pro Yakyuu Portable 3', 'Sports', 'Konami Digital Entertainment', 2008, 'PSP'),
(1051, 'Jikkyou Powerful Pro Yakyuu Portable 4', 'Sports', 'Konami Digital Entertainment', 2009, 'PSP'),
(1052, 'Kuroko\'s Basketball: Miracle Game', 'Sports', 'Namco Bandai Games', 2012, 'PSP'),
(1053, 'Madden NFL 06', 'Sports', 'Electronic Arts', 2005, 'PSP'),
(1054, 'Madden NFL 08', 'Sports', 'Electronic Arts', 2007, 'PSP'),
(1055, 'Madden NFL 09', 'Sports', 'Electronic Arts', 2008, 'PSP'),
(1056, 'Madden NFL 10', 'Sports', 'Electronic Arts', 2009, 'PSP'),
(1057, 'Madden NFL 11', 'Sports', 'Electronic Arts', 2010, 'PSP'),
(1058, 'Madden NFL 12', 'Sports', 'Electronic Arts', 2011, 'PSP'),
(1059, 'Major League Baseball 2K10', 'Sports', 'Take-Two Interactive', 2010, 'PSP'),
(1060, 'Major League Baseball 2K11', 'Sports', 'Take-Two Interactive', 2011, 'PSP'),
(1061, 'Major League Baseball 2K12', 'Sports', 'Take-Two Interactive', 2012, 'PSP'),
(1062, 'Major League Baseball 2K7', 'Sports', 'Take-Two Interactive', 2007, 'PSP'),
(1063, 'Major League Baseball 2K9', 'Sports', 'Spike', 2009, 'PSP'),
(1064, 'Minna no Golf Jou Vol.1', 'Sports', 'Sony Computer Entertainment', 2007, 'PSP'),
(1065, 'Minna no Sukkiri', 'Sports', 'Sony Computer Entertainment', 2009, 'PSP'),
(1066, 'MLB', 'Sports', 'Sony Computer Entertainment', 2005, 'PSP'),
(1067, 'MLB 06: The Show', 'Sports', 'Sony Computer Entertainment', 2006, 'PSP'),
(1068, 'MLB 07: The Show', 'Sports', 'Sony Computer Entertainment', 2007, 'PSP'),
(1069, 'MLB 08: The Show', 'Sports', 'Sony Computer Entertainment', 2008, 'PSP'),
(1070, 'MLB 09: The Show', 'Sports', 'Sony Computer Entertainment', 2009, 'PSP'),
(1071, 'MLB 10: The Show', 'Sports', 'Sony Computer Entertainment', 2010, 'PSP'),
(1072, 'MLB 11: The Show', 'Sports', 'Sony Computer Entertainment', 2011, 'PSP'),
(1073, 'MVP Baseball', 'Sports', 'Electronic Arts', 2005, 'PSP'),
(1074, 'NBA', 'Sports', 'Sony Computer Entertainment', 2005, 'PSP'),
(1075, 'NBA 06', 'Sports', 'Sony Computer Entertainment', 2005, 'PSP'),
(1076, 'NBA 07', 'Sports', 'Sony Computer Entertainment', 2006, 'PSP'),
(1077, 'NBA 08', 'Sports', 'Sony Computer Entertainment', 2007, 'PSP'),
(1078, 'NBA 09: The Inside', 'Sports', 'Sony Computer Entertainment', 2008, 'PSP'),
(1079, 'NBA 10: The Inside', 'Sports', 'Sony Computer Entertainment', 2009, 'PSP'),
(1080, 'NBA 2K10', 'Sports', 'Take-Two Interactive', 2009, 'PSP'),
(1081, 'NBA 2K12', 'Sports', 'Take-Two Interactive', 2011, 'PSP'),
(1082, 'NBA Ballers: Rebound', 'Sports', 'Midway Games', 2006, 'PSP'),
(1083, 'NBA Live 06', 'Sports', 'Electronic Arts', 2005, 'PSP'),
(1084, 'NBA Live 07', 'Sports', 'Electronic Arts', 2006, 'PSP'),
(1085, 'NBA Live 08', 'Sports', 'Electronic Arts', 2007, 'PSP'),
(1086, 'NBA Live 09', 'Sports', 'Electronic Arts', 2008, 'PSP'),
(1087, 'NBA Live 10', 'Sports', 'Electronic Arts', 2009, 'PSP'),
(1088, 'NBA Street: Showdown', 'Sports', 'Electronic Arts', 2005, 'PSP'),
(1089, 'NCAA Football 07', 'Sports', 'Electronic Arts', 2006, 'PSP'),
(1090, 'NCAA Football 09', 'Sports', 'Electronic Arts', 2008, 'PSP'),
(1091, 'NCAA Football 10', 'Sports', 'Electronic Arts', 2009, 'PSP'),
(1092, 'NFL Street 2 Unleashed', 'Sports', 'Electronic Arts', 2005, 'PSP'),
(1093, 'NFL Street 3', 'Sports', 'Electronic Arts', 2006, 'PSP'),
(1094, 'NHL 07', 'Sports', 'Electronic Arts', 2006, 'PSP'),
(1095, 'PANGYA: Fantasy Golf', 'Sports', 'Takara Tomy', 2009, 'PSP'),
(1096, 'Power Pro Success Legends', 'Sports', 'Konami Digital Entertainment', 2010, 'PSP'),
(1097, 'Pro Evolution Soccer 2008', 'Sports', 'Konami Digital Entertainment', 2008, 'PSP'),
(1098, 'Pro Evolution Soccer 2010', 'Sports', 'Konami Digital Entertainment', 2009, 'PSP'),
(1099, 'pro evolution soccer 2011', 'Sports', 'Konami Digital Entertainment', 2010, 'PSP'),
(1100, 'Pro Evolution Soccer 2013', 'Sports', 'Konami Digital Entertainment', 2012, 'PSP'),
(1101, 'Pro Yaky? Spirits 2010', 'Sports', 'Konami Digital Entertainment', 2010, 'PSP'),
(1102, 'Pro Yaky? Spirits 2011', 'Sports', 'Konami Digital Entertainment', 2011, 'PSP'),
(1103, 'Pro Yaky? Spirits 2012', 'Sports', 'Konami Digital Entertainment', 2012, 'PSP'),
(1104, 'Pro Yaky? Spirits 2013', 'Sports', 'Konami Digital Entertainment', 2013, 'PSP'),
(1105, 'Pro Yaky? Spirits 2014', 'Sports', 'Konami Digital Entertainment', 2014, 'PSP'),
(1106, 'Rapala Pro Bass Fishing 2010', 'Sports', 'Activision', 2010, 'PSP'),
(1107, 'Rapala Trophies', 'Sports', 'Activision', 2006, 'PSP'),
(1108, 'Reel Fishing: The Great Outdoors', 'Sports', 'Natsume', 2006, 'PSP'),
(1109, 'Rocky Balboa', 'Sports', 'Ubisoft', 2007, 'PSP'),
(1110, 'Shaun White Snowboarding', 'Sports', 'Ubisoft', 2008, 'PSP'),
(1111, 'Smash Court Tennis 3', 'Sports', 'Namco Bandai Games', 2007, 'PSP'),
(1112, 'SSX On Tour', 'Sports', 'Electronic Arts', 2005, 'PSP'),
(1113, 'Surf\'s Up', 'Sports', 'Ubisoft', 2007, 'PSP'),
(1114, 'The BIGS', 'Sports', 'Take-Two Interactive', 2007, 'PSP'),
(1115, 'The BIGS 2', 'Sports', 'Take-Two Interactive', 2009, 'PSP'),
(1116, 'The Hustle: Detroit Streets', 'Sports', 'Deep Silver', 2005, 'PSP'),
(1117, 'Tiger Woods PGA Tour', 'Sports', 'Electronic Arts', 2005, 'PSP'),
(1118, 'Tiger Woods PGA Tour 06', 'Sports', 'Electronic Arts', 2005, 'PSP'),
(1119, 'Tiger Woods PGA Tour 07', 'Sports', 'Electronic Arts', 2006, 'PSP'),
(1120, 'Tiger Woods PGA Tour 08', 'Sports', 'Electronic Arts', 2007, 'PSP'),
(1121, 'Tiger Woods PGA Tour 09', 'Sports', 'Electronic Arts', 2008, 'PSP'),
(1122, 'Tiger Woods PGA Tour 10', 'Sports', 'Electronic Arts', 2009, 'PSP'),
(1123, 'Tony Hawk\'s Project 8', 'Sports', 'Activision', 2006, 'PSP'),
(1124, 'Tony Hawk\'s Underground 2 Remix', 'Sports', 'Activision', 2005, 'PSP'),
(1125, 'UEFA Champions League 2006-2007', 'Sports', 'Electronic Arts', 2007, 'PSP'),
(1126, 'UEFA Euro 2008 Austria-Switzerland', 'Sports', 'Electronic Arts', 2008, 'PSP'),
(1127, 'Virtua Tennis 3', 'Sports', 'Sega', 2007, 'PSP'),
(1128, 'Virtua Tennis: World Tour (jp sales)', 'Sports', 'Sega', 2005, 'PSP'),
(1129, 'Virtua Tennis: World Tour (US & Others sales)', 'Sports', 'Sega', 2005, 'PSP'),
(1130, 'Winning Eleven: Pro Evolution Soccer 2007', 'Sports', 'Konami Digital Entertainment', 2006, 'PSP'),
(1131, 'Winning Post 7 2009', 'Sports', 'Tecmo Koei', 2009, 'PSP'),
(1132, 'Winning Post 7 2010', 'Sports', 'Tecmo Koei', 2010, 'PSP'),
(1133, 'Winning Post 7 2012', 'Sports', 'Ackkstudios', 2012, 'PSP'),
(1134, 'World Snooker Challenge 2005', 'Sports', 'Sega', 2005, 'PSP'),
(1135, 'World Soccer Winning Eleven 2010: Aoki Samurai no Chousen', 'Sports', 'Konami Digital Entertainment', 2010, 'PSP'),
(1136, 'World Soccer Winning Eleven 9 (JP & Others sales)', 'Sports', 'Konami Digital Entertainment', 2005, 'PSP'),
(1137, 'World Soccer Winning Eleven 9 (US sales)', 'Sports', 'Konami Digital Entertainment', 2005, 'PSP'),
(1138, 'World Tour Soccer', 'Sports', 'Sony Computer Entertainment', 2005, 'PSP'),
(1139, 'World Tour Soccer 06', 'Sports', 'Sony Computer Entertainment', 2006, 'PSP'),
(1140, 'Akatsuki no Amaneka to Aoi Kyojin', 'Strategy', 'CyberFront', 2010, 'PSP'),
(1141, 'Carnage Heart EXA', 'Strategy', 'ArtDink', 2010, 'PSP'),
(1142, 'Chuugen no Hasha: Sangoku Shouseiden', 'Strategy', 'Namco Bandai Games', 2006, 'PSP'),
(1143, 'Dai-2-Ji Super Robot Taisen Z Saisei-hen', 'Strategy', 'Namco Bandai Games', 2012, 'PSP'),
(1144, 'Dai-2-Ji Super Robot Taisen Z: Hakai-hen', 'Strategy', 'Banpresto', 2011, 'PSP'),
(1145, 'Dungeons & Dragons Tactics', 'Strategy', 'Atari', 2007, 'PSP'),
(1146, 'Field Commander', 'Strategy', 'Sony Online Entertainment', 2006, 'PSP'),
(1147, 'Hyakumanton no Bara Bara', 'Strategy', 'Sony Computer Entertainment', 2010, 'PSP'),
(1148, 'Invizimals', 'Strategy', 'Sony Computer Entertainment', 2009, 'PSP'),
(1149, 'Invizimals: Shadow Zone', 'Strategy', 'Sony Computer Entertainment', 2010, 'PSP'),
(1150, 'Ken to Mahou to Gakuen Mono. Final: Shinnyusei wa Ohimesama', 'Strategy', 'Acquire', 2011, 'PSP'),
(1151, 'Kidou Senshi Gundam: Giren no Yabou - Axis no Kyoui', 'Strategy', 'Namco Bandai Games', 2008, 'PSP'),
(1152, 'Kidou Senshi Gundam: Giren no Yabou - Axis no Kyoui V', 'Strategy', 'Namco Bandai Games', 2009, 'PSP'),
(1153, 'Kidou Senshi Gundam: Senjou no Kizuna Portable', 'Strategy', 'Namco Bandai Games', 2009, 'PSP'),
(1154, 'Kidou Senshi Gundam: Shin Gihren no Yabou', 'Strategy', 'Namco Bandai Games', 2011, 'PSP'),
(1155, 'Lord of the Rings: Tactics', 'Strategy', 'Electronic Arts', 2005, 'PSP'),
(1156, 'Making History: The Great War', 'Strategy', 'Namco Bandai Games', 2010, 'PSP'),
(1157, 'McDROID', 'Strategy', 'Namco Bandai Games', 2011, 'PSP'),
(1158, 'Metal Gear Ac!d', 'Strategy', 'Konami Digital Entertainment', 2004, 'PSP'),
(1159, 'Metal Gear Ac!d 2', 'Strategy', 'Konami Digital Entertainment', 2005, 'PSP'),
(1160, 'Military History: Commander - Europe at War', 'Strategy', 'Slitherine Software', 2009, 'PSP'),
(1161, 'Moe Moe 2-Ji Daisenryaku 2', 'Strategy', 'System Soft', 2010, 'PSP'),
(1162, 'Musou Tourou', 'Strategy', 'Nippon Ichi Software', 2009, 'PSP'),
(1163, 'Mytran Wars', 'Strategy', 'Deep Silver', 2009, 'PSP'),
(1164, 'Nobunaga no Yabou: Soutensoku with Power-Up Kit', 'Strategy', 'Tecmo Koei', 2011, 'PSP'),
(1165, 'PixelJunk Monsters Deluxe', 'Strategy', 'Sony Computer Entertainment', 2010, 'PSP'),
(1166, 'R-Type Command', 'Strategy', 'Rising Star Games', 2007, 'PSP'),
(1167, 'R-Type Command (correct US sales)', 'Strategy', 'Rising Star Games', 2007, 'PSP'),
(1168, 'Sakura Wars 1 & 2', 'Strategy', 'Sega', 2006, 'PSP'),
(1169, 'Scarface: Money. Power. Respect.', 'Strategy', 'Vivendi Games', 2006, 'PSP'),
(1170, 'SD Gundam G Generation Portable', 'Strategy', 'Namco Bandai Games', 2006, 'PSP'),
(1171, 'SD Gundam G Generation World', 'Strategy', 'Namco Bandai Games', 2011, 'PSP'),
(1172, 'SD Gundam G Generation: Overworld', 'Strategy', 'Namco Bandai Games', 2012, 'PSP'),
(1173, 'Sengoku Efuda Yuugi: Hototogisu Tairan', 'Strategy', 'Irem Software Engineering', 2010, 'PSP'),
(1174, 'Sengoku Hime 2 Arashi: Hyakubana Senran Tatsukaze no Gotoku', 'Strategy', 'System Soft', 2010, 'PSP'),
(1175, 'Shutsugeki! Otometachi no Senjou 2: Ikusabana no Kizuna', 'Strategy', 'System Soft', 2011, 'PSP'),
(1176, 'Sid Meier\'s Pirates!', 'Strategy', 'Take-Two Interactive', 2007, 'PSP'),
(1177, 'Star Trek: Tactical Assault', 'Strategy', 'Ubisoft', 2006, 'PSP'),
(1178, 'Strike Witches: Shirogane no Tsubasa', 'Strategy', 'Kadokawa Shoten', 2012, 'PSP'),
(1179, 'Super Robot Taisen A Portable', 'Strategy', 'Namco Bandai Games', 2008, 'PSP'),
(1180, 'Super Robot Taisen MX Portable', 'Strategy', 'Banpresto', 2005, 'PSP'),
(1181, 'Taikou Risshiden V', 'Strategy', 'Tecmo Koei', 2009, 'PSP'),
(1182, 'The Eye of Judgment: Legends', 'Strategy', 'Sony Computer Entertainment', 2010, 'PSP'),
(1183, 'Thrillville', 'Strategy', 'Atari', 2006, 'PSP'),
(1184, 'Thrillville: Off the Rails', 'Strategy', 'LucasArts', 2007, 'PSP'),
(1185, 'Tom Clancy\'s EndWar', 'Strategy', 'Ubisoft', 2008, 'PSP'),
(1186, 'Ultraman Star Chronicles', 'Strategy', 'Namco Bandai Games', 2013, 'PSP'),
(1187, 'Warhammer 40,000: Squad Command', 'Strategy', 'THQ', 2007, 'PSP'),
(1188, 'Weiss Schwarz Portable', 'Strategy', 'Namco Bandai Games', 2011, 'PSP'),
(1189, 'Worms: Open Warfare', 'Strategy', 'THQ', 2006, 'PSP'),
(1190, 'Worms: Open Warfare 2', 'Strategy', 'THQ', 2007, 'PSP'),
(1191, 'Yu-Gi-Oh! 5D\'s Tag Force 4', 'Strategy', 'Konami Digital Entertainment', 2009, 'PSP'),
(1192, 'Yu-Gi-Oh! 5D\'s Tag Force 5', 'Strategy', 'Konami Digital Entertainment', 2010, 'PSP'),
(1193, 'Yu-Gi-Oh! 5D\'s Tag Force 6', 'Strategy', 'Konami Digital Entertainment', 2011, 'PSP'),
(1194, 'Yu-Gi-Oh! GX: Tag Force', 'Strategy', 'Konami Digital Entertainment', 2006, 'PSP'),
(1195, 'Yu-Gi-Oh! GX: Tag Force 2', 'Strategy', 'Konami Digital Entertainment', 2007, 'PSP'),
(1196, 'Yu-Gi-Oh! GX: Tag Force 3', 'Strategy', 'Konami Digital Entertainment', 2008, 'PSP'),
(1197, 'Yuusha no Kuse ni Namaikida Or 3D', 'Strategy', 'Sony Computer Entertainment', 2010, 'PSP');
