
-- --------------------------------------------------------

--
-- Struttura della tabella `psv`
--

DROP TABLE IF EXISTS `psv`;
CREATE TABLE IF NOT EXISTS `psv` (
  `id` int NOT NULL AUTO_INCREMENT,
  `game_name` varchar(200) CHARACTER SET utf8mb3 DEFAULT NULL,
  `genre_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  `publisher_name` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL,
  `release_year` int DEFAULT NULL,
  `platform_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=413 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dump dei dati per la tabella `psv`
--

INSERT INTO `psv` (`id`, `game_name`, `genre_name`, `publisher_name`, `release_year`, `platform_name`) VALUES
(1, '3rd Super Robot Wars Z: Tengoku-Hen', 'Action', 'Namco Bandai Games', 2015, 'PSV'),
(2, 'A Good Librarian Like a Good Shepherd: Library Party', 'Action', 'Kaga Create', 2015, 'PSV'),
(3, 'Abunai: Koi no Sousa Shitsu', 'Action', 'Asgard', 2015, 'PSV'),
(4, 'Aegis of Earth: Protonovus Assault', 'Action', 'PQube', 2016, 'PSV'),
(5, 'Akiba\'s Trip: Undead & Undressed', 'Action', 'Nippon Ichi Software', 2013, 'PSV'),
(6, 'Angelique Retour', 'Action', 'Tecmo Koei', 2015, 'PSV'),
(7, 'Army Corps of Hell', 'Action', 'Square Enix', 2011, 'PSV'),
(8, 'Asphalt: Injection', 'Action', 'Ubisoft', 2011, 'PSV'),
(9, 'Assassin\'s Creed Chronicles', 'Action', 'Ubisoft', 2016, 'PSV'),
(10, 'Assassin\'s Creed III: Liberation', 'Action', 'Ubisoft', 2012, 'PSV'),
(11, 'Attack on Titan (KOEI)', 'Action', 'Tecmo Koei', 2016, 'PSV'),
(12, 'Bad Apple Wars', 'Action', 'Idea Factory', 2015, 'PSV'),
(13, 'Batman: Arkham Origins Blackgate', 'Action', 'Warner Bros. Interactive Entertainment', 2013, 'PSV'),
(14, 'BlazBlue: Chrono Phantasma Extend', 'Action', 'PQube', 2015, 'PSV'),
(15, 'Brothers Conflict: Precious Baby', 'Action', 'Idea Factory', 2017, 'PSV'),
(16, 'Bullet Girls', 'Action', 'D3Publisher', 2014, 'PSV'),
(17, 'Bullet Girls 2', 'Action', 'D3Publisher', 2016, 'PSV'),
(18, 'Call of Duty Black Ops: Declassified', 'Action', 'Activision', 2012, 'PSV'),
(19, 'Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shirube Kareru', 'Action', 'dramatic create', 2016, 'PSV'),
(20, 'Clock Zero: Shuuen no Ichibyou - ExTime', 'Action', 'Idea Factory', 2015, 'PSV'),
(21, 'Collar x Malice', 'Action', 'Idea Factory', 2016, 'PSV'),
(22, 'Coven and Labyrinth of Refrain', 'Action', 'Nippon Ichi Software', 2016, 'PSV'),
(23, 'Cross Ange: Tenshi to Ryuu no Rondo tr.', 'Action', 'Namco Bandai Games', 2015, 'PSV'),
(24, 'Dance with Devils', 'Action', 'N/A', 2016, 'PSV'),
(25, 'Danganronpa Another Episode: Ultra Despair Girls', 'Action', 'Nippon Ichi Software', 2014, 'PSV'),
(26, 'Darius Burst: Chronicle Saviours', 'Action', 'Kadokawa Games', 2016, 'PSV'),
(27, 'Date-A-Live Twin Edition: Rio Reincarnation', 'Action', 'Compile Heart', 2015, 'PSV'),
(28, 'Deception IV: Blood Ties', 'Action', 'Tecmo Koei', 2014, 'PSV'),
(29, 'Diabolik Lovers: Dark Fate', 'Action', 'Idea Factory', 2015, 'PSV'),
(30, 'Diabolik Lovers: Vandead Carnival', 'Action', 'Idea Factory', 2014, 'PSV'),
(31, 'Digimon World: Next Order', 'Action', 'Namco Bandai Games', 2016, 'PSV'),
(32, 'Disney Infinity', 'Action', 'Disney Interactive Studios', 2013, 'PSV'),
(33, 'Disney Infinity 2.0: Marvel Super Heroes', 'Action', 'Disney Interactive Studios', 2015, 'PSV'),
(34, 'Dokuro', 'Action', 'GungHo', 2012, 'PSV'),
(35, 'Dragon Quest Heroes II: Twin Kings and the Prophecy\'s End', 'Action', 'Square Enix', 2016, 'PSV'),
(36, 'Dungeon Hunter Alliance', 'Action', 'Ubisoft', 2012, 'PSV'),
(37, 'Durarara!! Relay', 'Action', 'Kadokawa Games', 2015, 'PSV'),
(38, 'Dynasty Warriors 8: Empires', 'Action', 'Tecmo Koei', 2015, 'PSV'),
(39, 'Dynasty Warriors 8: Xtreme Legends', 'Action', 'Tecmo Koei', 2013, 'PSV'),
(40, 'Dynasty Warriors Next', 'Action', 'Tecmo Koei', 2011, 'PSV'),
(41, 'Dynasty Warriors: Gundam Reborn', 'Action', 'Namco Bandai Games', 2013, 'PSV'),
(42, 'Earth Defense Force 2017 Portable', 'Action', 'D3Publisher', 2012, 'PSV'),
(43, 'Earth Defense Force 2: Invaders from Planet Space', 'Action', 'Xseed Games', 2014, 'PSV'),
(44, 'Ebikore Photo Kano Kiss', 'Action', 'Kadokawa Games', 2015, 'PSV'),
(45, 'FIFA Soccer 13', 'Action', 'Electronic Arts', 2012, 'PSV'),
(46, 'Fuuraiki 3', 'Action', 'Unknown', 2015, 'PSV'),
(47, 'Gal Gun: Double Peace', 'Action', 'PQube', 2015, 'PSV'),
(48, 'Gekijouban Madoka Magicka: The Battle Pentagram', 'Action', 'Namco Bandai Games', 2013, 'PSV'),
(49, 'Girl Friend Beta: Kimi to Sugosu Natsuyasumi', 'Action', 'Namco Bandai Games', 2015, 'PSV'),
(50, 'Girls und Panzer: I Will Master Tankery', 'Action', 'Namco Bandai Games', 2014, 'PSV'),
(51, 'God Eater Resurrection', 'Action', 'Namco Bandai Games', 2015, 'PSV'),
(52, 'God of War Collection', 'Action', 'Sony Computer Entertainment', 2014, 'PSV'),
(53, 'Gravity Rush', 'Action', 'Sony Computer Entertainment', 2012, 'PSV'),
(54, 'Gundam Breaker', 'Action', 'Namco Bandai Games', 2013, 'PSV'),
(55, 'Gundam Breaker 2', 'Action', 'Namco Bandai Games', 2014, 'PSV'),
(56, 'Gundam Breaker 3', 'Action', 'Namco Bandai Games', 2016, 'PSV'),
(57, 'Hakuoki Zuisouroku Omokage Hana', 'Action', 'Idea Factory', 2015, 'PSV'),
(58, 'Hakuoki: Reimeiroku - Omouhase Kara', 'Action', 'Idea Factory', 2015, 'PSV'),
(59, 'Hakuoki: Shinkai - Furi no Shou', 'Action', 'Idea Factory', 2015, 'PSV'),
(60, 'Harukanaru Toki no Naka de 6', 'Action', 'Tecmo Koei', 2015, 'PSV'),
(61, 'Higurashi no Naku Koro ni Iki', 'Action', 'Kaga Create', 2015, 'PSV'),
(62, 'Hyakka Yakou', 'Action', 'Unknown', 2015, 'PSV'),
(63, 'Hyperdimension Neptunia mk2', 'Action', 'Compile Heart', 2014, 'PSV'),
(64, 'Hyperdimension Neptunia Re;Birth 2', 'Action', 'Idea Factory International', 2014, 'PSV'),
(65, 'Hyperdimension Neptunia Re;Birth 3', 'Action', 'Idea Factory International', 2014, 'PSV'),
(66, 'Hyperdimension Neptunia U: Action Unleashed', 'Action', 'Idea Factory International', 2014, 'PSV'),
(67, 'Infinite Stratos 2: Love and Purge', 'Action', '5pb', 2015, 'PSV'),
(68, 'Invizimals: The Alliance', 'Action', 'Sony Computer Entertainment', 2013, 'PSV'),
(69, 'Irotoridori no Sekai: World\'s End Re-Birth', 'Action', 'HuneX', 2015, 'PSV'),
(70, 'Jikkyou Powerful Pro Yakyuu 2012', 'Action', 'Konami Digital Entertainment', 2012, 'PSV'),
(71, 'Kamen Rider: Battride War Genesis', 'Action', 'Namco Bandai Games', 2016, 'PSV'),
(72, 'Kan Colle Kai', 'Action', 'Kadokawa Games', 2016, 'PSV'),
(73, 'Kenka Bancho Otome', 'Action', 'Screenlife', 2016, 'PSV'),
(74, 'Kidou Senshi Gundam Seed Battle Destiny', 'Action', 'Namco Bandai Games', 2012, 'PSV'),
(75, 'La Corda d\'Oro 4', 'Action', 'Tecmo Koei', 2016, 'PSV'),
(76, 'LEGO Batman 2: DC Super Heroes', 'Action', 'Warner Bros. Interactive Entertainment', 2012, 'PSV'),
(77, 'Lego Batman 3: Beyond Gotham', 'Action', 'Warner Bros. Interactive Entertainment', 2014, 'PSV'),
(78, 'LEGO Harry Potter: Years 5-7', 'Action', 'Warner Bros. Interactive Entertainment', 2012, 'PSV'),
(79, 'LEGO Jurassic World', 'Action', 'Warner Bros. Interactive Entertainment', 2015, 'PSV'),
(80, 'LEGO Marvel Super Heroes', 'Action', 'Warner Bros. Interactive Entertainment', 2013, 'PSV'),
(81, 'LEGO Marvel\'s Avengers', 'Action', 'Warner Bros. Interactive Entertainment', 2016, 'PSV'),
(82, 'LEGO Ninjago: Shadow of Ronin', 'Action', 'Warner Bros. Interactive Entertainment', 2015, 'PSV'),
(83, 'Lego Star Wars: The Force Awakens', 'Action', 'Warner Bros. Interactive Entertainment', 2016, 'PSV'),
(84, 'LEGO The Hobbit', 'Action', 'Warner Bros. Interactive Entertainment', 2014, 'PSV'),
(85, 'LEGO The Lord of the Rings', 'Action', 'Warner Bros. Interactive Entertainment', 2012, 'PSV'),
(86, 'Little Busters! Converted Edition', 'Action', 'Prototype', 2012, 'PSV'),
(87, 'Looney Tunes: Galactic Sports', 'Action', 'Sony Computer Entertainment', 2015, 'PSV'),
(88, 'Lovely x Cation 1 & 2', 'Action', '5pb', 2015, 'PSV'),
(89, 'Luminous Arc Infinity', 'Action', 'Marvel Entertainment', 2015, 'PSV'),
(90, 'MegaTagmension Blanc + Neptune VS Zombies', 'Action', 'Idea Factory International', 2015, 'PSV'),
(91, 'Metal Gear Solid HD Edition', 'Action', 'Konami Digital Entertainment', 2012, 'PSV'),
(92, 'Mobile Suit Gundam: Extreme VS Force', 'Action', 'Namco Bandai Games', 2015, 'PSV'),
(93, 'Ninja Gaiden Sigma', 'Action', 'Tecmo Koei', 2012, 'PSV'),
(94, 'Ninja Gaiden Sigma 2', 'Action', 'Tecmo Koei', 2013, 'PSV'),
(95, 'Norn + Nonette: Last Era', 'Action', 'Idea Factory', 2015, 'PSV'),
(96, 'One Piece: Pirate Warriors 2', 'Action', 'Namco Bandai Games', 2013, 'PSV'),
(97, 'One Piece: Pirate Warriors 3', 'Action', 'Namco Bandai Games', 2015, 'PSV'),
(98, 'One Piece: Unlimited World Red', 'Action', 'Namco Bandai Games', 2014, 'PSV'),
(99, 'Otoko Yukaku', 'Action', 'D3Publisher', 2015, 'PSV'),
(100, 'Ou to Maou to 7-nin no Himegimitachi: Shin Ousama Monogatari', 'Action', 'Konami Digital Entertainment', 2012, 'PSV'),
(101, 'Period Cube: Torikago no Amadeus', 'Action', 'Idea Factory', 2016, 'PSV'),
(102, 'Phantasy Star Online 2: Episode 3 Deluxe Package', 'Action', 'Sega', 2015, 'PSV'),
(103, 'PlayStation All-Stars Battle Royale', 'Action', 'Sony Computer Entertainment', 2012, 'PSV'),
(104, 'Pro Baseball Spirits 2015', 'Action', 'Konami Digital Entertainment', 2015, 'PSV'),
(105, 'Professional Farmer 2016', 'Action', 'Namco Bandai Games', 2015, 'PSV'),
(106, 'Psychedelica of the Black Butterfly', 'Action', 'Idea Factory', 2015, 'PSV'),
(107, 'Ratchet & Clank Collection', 'Action', 'Sony Computer Entertainment', 2014, 'PSV'),
(108, 'Refrain no Chika Meikyuu to Majo no Ryodan', 'Action', 'Nippon Ichi Software', 2016, 'PSV'),
(109, 'Reine des Fleurs', 'Action', 'Idea Factory', 2015, 'PSV'),
(110, 'Resident Evil: Revelations 2', 'Action', 'Capcom', 2015, 'PSV'),
(111, 'Rose to Tasogare no Kojou', 'Action', 'Nippon Ichi Software', 2016, 'PSV'),
(112, 'Saenai Kanojo no Sodatekata: Blessing Flowers', 'Action', '5pb', 2015, 'PSV'),
(113, 'Samurai & Dragons', 'Action', 'Sega', 2012, 'PSV'),
(114, 'Samurai Warriors 4', 'Action', 'Tecmo Koei', 2014, 'PSV'),
(115, 'Samurai Warriors 4-II', 'Action', 'Tecmo Koei', 2015, 'PSV'),
(116, 'Samurai Warriors 4: Empires', 'Action', 'Tecmo Koei', 2015, 'PSV'),
(117, 'Samurai Warriors Chronicles 3', 'Action', 'Tecmo Koei', 2014, 'PSV'),
(118, 'Sengoku Otome: Legend Battle', 'Action', 'Unknown', 2016, 'PSV'),
(119, 'Senran Kagura: Estival Versus', 'Action', 'Marvelous Interactive', 2015, 'PSV'),
(120, 'Shinobi, Koi Utsutsu: Setsugetsuka Koi Emaki', 'Action', 'Idea Factory', 2015, 'PSV'),
(121, 'Shinobido 2: Tales of the Ninja', 'Action', 'Sony Computer Entertainment', 2011, 'PSV'),
(122, 'Shiren the Wanderer 5 Plus: Fortune Tower and the Dice of Fate', 'Action', 'Aksys Games', 2015, 'PSV'),
(123, 'Silent Hill: Book of Memories', 'Action', 'Konami Digital Entertainment', 2012, 'PSV'),
(124, 'Soul Sacrifice Delta', 'Action', 'Sony Computer Entertainment', 2014, 'PSV'),
(125, 'Summon Night 6: Lost Borders', 'Action', 'Namco Bandai Games', 2016, 'PSV'),
(126, 'Taiko no Tatsujin: V Version', 'Action', 'Namco Bandai Games', 2015, 'PSV'),
(127, 'Terraria', 'Action', 'Screenlife', 2013, 'PSV'),
(128, 'The LEGO Movie Videogame', 'Action', 'Warner Bros. Interactive Entertainment', 2014, 'PSV'),
(129, 'To Love-Ru Trouble Darkness: Battle Ecstasy', 'Action', 'FuRyu', 2014, 'PSV'),
(130, 'To Love-Ru Trouble: Darkness - True Princess', 'Action', 'FuRyu', 2015, 'PSV'),
(131, 'Toukiden 2', 'Action', 'Tecmo Koei', 2016, 'PSV'),
(132, 'Toukiden Kiwami', 'Action', 'Tecmo Koei', 2014, 'PSV'),
(133, 'Toukiden: The Age of Demons', 'Action', 'Tecmo Koei', 2013, 'PSV'),
(134, 'Ukiyo no Roushi', 'Action', 'Unknown', 2015, 'PSV'),
(135, 'Uppers', 'Action', 'Marvelous Entertainment', 2016, 'PSV'),
(136, 'Uta no Prince-Sama: Music 3', 'Action', 'Broccoli', 2016, 'PSV'),
(137, 'Valkyrie Drive: Bhikkhuni', 'Action', 'PQube', 2015, 'PSV'),
(138, 'Warriors Orochi 3', 'Action', 'Tecmo Koei', 2013, 'PSV'),
(139, 'Winning Post 8 2015', 'Action', 'Tecmo Koei', 2015, 'PSV'),
(140, 'World Trigger: Borderless Mission', 'Action', 'Namco Bandai Games', 2015, 'PSV'),
(141, 'Ys: Memories of Celceta', 'Action', 'Nihon Falcom Corporation', 2012, 'PSV'),
(142, 'Yuki Yuna is a Hero: Memory of the Forest', 'Action', 'FuRyu', 2015, 'PSV'),
(143, 'AKB1/149: Love Election', 'Adventure', 'Namco Bandai Games', 2012, 'PSV'),
(144, 'Alia\'s Carnival! Sacrament', 'Adventure', 'dramatic create', 2015, 'PSV'),
(145, 'Amagami', 'Adventure', 'Kadokawa Games', 2014, 'PSV'),
(146, 'Amatsumi Sora ni! Kumo no Hatate ni', 'Adventure', 'Prototype', 2015, 'PSV'),
(147, 'AMNESIA World', 'Adventure', 'Idea Factory', 2014, 'PSV'),
(148, 'Ao no Kanata no Four Rhythm', 'Adventure', 'Unknown', 2016, 'PSV'),
(149, 'Binary Star', 'Adventure', 'Idea Factory', 2014, 'PSV'),
(150, 'Chaos;Child', 'Adventure', '5pb', 2015, 'PSV'),
(151, 'Chaos;Head Noah', 'Adventure', '5pb', 2014, 'PSV'),
(152, 'Ciel Nosurge: Ushinawareta Hoshi e Sasagu Uta', 'Adventure', 'Gust', 2012, 'PSV'),
(153, 'Code:Realize - Sousei no Himegimi', 'Adventure', 'Idea Factory', 2014, 'PSV'),
(154, 'Corpse Party: Blood Drive', 'Adventure', 'Marvelous Interactive', 2014, 'PSV'),
(155, 'Diabolik Lovers: Lunatic Parade', 'Adventure', 'Idea Factory', 2016, 'PSV'),
(156, 'Diabolik Lovers: More Blood', 'Adventure', 'Idea Factory', 2015, 'PSV'),
(157, 'Doki-Doki Universe', 'Adventure', 'Sony Computer Entertainment', 2013, 'PSV'),
(158, 'Dramatical Murder Re:code', 'Adventure', 'Nitroplus', 2014, 'PSV'),
(159, 'Fate/hollow ataraxia', 'Adventure', 'Type-Moon', 2014, 'PSV'),
(160, 'Fate/Stay Night [Réalta Nua]', 'Adventure', 'Kadokawa Shoten', 2012, 'PSV'),
(161, 'Getsuei Gakuen: kou', 'Adventure', 'Arc System Works', 2013, 'PSV'),
(162, 'Gochuumon wa Usagi Desu ka?? Wonderful Party!', 'Adventure', '5pb', 2016, 'PSV'),
(163, 'Golden Time: Vivid Memories', 'Adventure', 'ASCII Media Works', 2014, 'PSV'),
(164, 'Great Edo Blacksmith', 'Adventure', 'Nippon Ichi Software', 2014, 'PSV'),
(165, 'Grisaia no Meikyuu: Le Labyrinthe de la Grisaia', 'Adventure', 'Prototype', 2014, 'PSV'),
(166, 'Grisaia no Rakuen: Le Eden de la Grisaia', 'Adventure', 'Prototype', 2014, 'PSV'),
(167, 'Hakuoki: Shinkai - Hana no Shou', 'Adventure', 'Idea Factory', 2016, 'PSV'),
(168, 'Hakuouki SSL: Sweet School Life', 'Adventure', 'Idea Factory', 2014, 'PSV'),
(169, 'Hanasaku Manimani', 'Adventure', '5pb', 2014, 'PSV'),
(170, 'Hanayamata: Yosakoi Live', 'Adventure', 'Namco Bandai Games', 2014, 'PSV'),
(171, 'Hitotsu Tobashi Renai V', 'Adventure', 'Kaga Create', 2015, 'PSV'),
(172, 'Hyakka Hyakurou: Sengoku Ninpoujou', 'Adventure', 'D3Publisher', 2016, 'PSV'),
(173, 'I Doll U', 'Adventure', 'Idea Factory', 2015, 'PSV'),
(174, 'Infinite Stratos 2: Ignition Hearts', 'Adventure', '5pb', 2014, 'PSV'),
(175, 'Kadenz fermata//Akkord:fortissimo', 'Adventure', '5pb', 2014, 'PSV'),
(176, 'Kaleidoeve', 'Adventure', 'HuneX', 2015, 'PSV'),
(177, 'Kamigami no Asobi InFinite', 'Adventure', 'Broccoli', 2016, 'PSV'),
(178, 'Kiss Bell', 'Adventure', 'Giga', 2014, 'PSV'),
(179, 'Kisuato', 'Adventure', 'TGL', 2015, 'PSV'),
(180, 'Kurogane Kaikitan', 'Adventure', 'Minato Station', 2015, 'PSV'),
(181, 'Kyokugen Dasshutsu ADV: Zennin Shiboudesu', 'Adventure', 'ChunSoft', 2012, 'PSV'),
(182, 'LEGO Legends of Chima: Laval\'s Journey', 'Adventure', 'Warner Bros. Interactive Entertainment', 2013, 'PSV'),
(183, 'Mahouka Koukou no Rettousei: Out of Order', 'Adventure', 'Namco Bandai Games', 2014, 'PSV'),
(184, 'Marginal #4: Idol of Supernova', 'Adventure', 'Idea Factory', 2014, 'PSV'),
(185, 'Moshi, Kono Sekai ni Kami-sama ga Iru to suru Naraba.', 'Adventure', 'N/A', 2016, 'PSV'),
(186, 'MuvLuv Double Pack', 'Adventure', '5pb', 2016, 'PSV'),
(187, 'Net High', 'Adventure', 'Marvelous Games', 2015, 'PSV'),
(188, 'Nil Admirari no Tenbin: Teito Genwaku Toukidan', 'Adventure', 'Idea Factory', 2016, 'PSV'),
(189, 'Nisekoi: Yomeiri!?', 'Adventure', 'Konami Digital Entertainment', 2014, 'PSV'),
(190, 'Nyaruko-San: Nafushigatai Game no You na Mono', 'Adventure', '5pb', 2013, 'PSV'),
(191, 'OZMAFIA!! -vivace-', 'Adventure', 'dramatic create', 2015, 'PSV'),
(192, 'Parfait', 'Adventure', 'TGL', 2015, 'PSV'),
(193, 'PhotoKano', 'Adventure', 'Kadokawa Shoten', 2013, 'PSV'),
(194, 'Prince of Stride', 'Adventure', 'Kadokawa Games', 2015, 'PSV'),
(195, 'Psycho-Pass: Mandatory Happiness', 'Adventure', 'Nippon Ichi Software', 2016, 'PSV'),
(196, 'Ratchet & Clank: Full Frontal Assault', 'Adventure', 'Sony Computer Entertainment', 2012, 'PSV'),
(197, 'Renai Revenge', 'Adventure', 'TGL', 2015, 'PSV'),
(198, 'Rewrite', 'Adventure', 'Prototype', 2014, 'PSV'),
(199, 'Ro-Kyu-Bu! Secret Photo Op', 'Adventure', 'Kadokawa Games', 2014, 'PSV'),
(200, 'Robotics;Notes', 'Adventure', '5pb', 2014, 'PSV'),
(201, 'Root Infinity Rexx', 'Adventure', 'Idea Factory', 2015, 'PSV'),
(202, 'Sakura-Sou no Pet na Kanojo', 'Adventure', 'Kadokawa Games', 2013, 'PSV'),
(203, 'Sangoku Koi Senki: Omoide Gaeshi - CS Edition', 'Adventure', 'Prototype', 2016, 'PSV'),
(204, 'Senjou no Waltz', 'Adventure', 'Idea Factory', 2014, 'PSV'),
(205, 'Shin Hayarigami', 'Adventure', 'Nippon Ichi Software', 2014, 'PSV'),
(206, 'Shin Hayarigami 2', 'Adventure', 'Nippon Ichi Software', 2016, 'PSV'),
(207, 'Shin Kamaitachi no Yoru: 11 Hitome no Suspect', 'Adventure', 'ChunSoft', 2011, 'PSV'),
(208, 'Shitsuji ga Aruji o Erabu Toki', 'Adventure', 'Unknown', 2016, 'PSV'),
(209, 'Steins;Gate', 'Adventure', 'PQube', 2013, 'PSV'),
(210, 'Steins;Gate 0', 'Adventure', 'PQube', 2015, 'PSV'),
(211, 'Storm Lover 2nd V', 'Adventure', 'D3Publisher', 2016, 'PSV'),
(212, 'Taishou Moebius Line Vitable', 'Adventure', 'dramatic create', 2016, 'PSV'),
(213, 'Tearaway', 'Adventure', 'Sony Computer Entertainment Europe', 2013, 'PSV'),
(214, 'The Walking Dead: Season One', 'Adventure', 'Square Enix', 2013, 'PSV'),
(215, 'The Walking Dead: Season Two', 'Adventure', 'Telltale Games', 2014, 'PSV'),
(216, 'The Wolf Among Us', 'Adventure', 'Telltale Games', 2014, 'PSV'),
(217, 'Time Travelers', 'Adventure', 'Level 5', 2012, 'PSV'),
(218, 'To Heart 2: Dungeon Travelers', 'Adventure', 'Aqua Plus', 2015, 'PSV'),
(219, 'Tokushu Houdoubu', 'Adventure', 'Nippon Ichi Software', 2012, 'PSV'),
(220, 'Tsuki ni Yori Sou Otome no Sahou: Hidamari no Hibi', 'Adventure', 'dramatic create', 2015, 'PSV'),
(221, 'Utawarerumono: Itsuwari no Kamen', 'Adventure', 'Aqua Plus', 2015, 'PSV'),
(222, 'Wand of Fortune R', 'Adventure', 'Idea Factory', 2016, 'PSV'),
(223, 'White Album 2: Shiawase no Mukougawa', 'Adventure', 'Aqua Plus', 2013, 'PSV'),
(224, 'XBLAZE Code: Embryo', 'Adventure', 'Arc System Works', 2013, 'PSV'),
(225, 'Xblaze: Lost Memories', 'Adventure', 'Arc System Works', 2015, 'PSV'),
(226, 'Yahari Game Demo Ore no Seishun Love-Kome Hamachi Gatteiru', 'Adventure', '5pb', 2013, 'PSV'),
(227, 'Yomawari', 'Adventure', 'Nippon Ichi Software', 2015, 'PSV'),
(228, 'Zero Escape: Zero Time Dilemma', 'Adventure', 'Aksys Games', 2016, 'PSV'),
(229, 'Arcana Heart 3', 'Fighting', 'Arc System Works', 2014, 'PSV'),
(230, 'BlazBlue: Chrono Phantasma', 'Fighting', 'Arc System Works', 2014, 'PSV'),
(231, 'Blazblue: Continuum Shift Extend', 'Fighting', 'PQube', 2011, 'PSV'),
(232, 'Dead or Alive 5', 'Fighting', 'Tecmo Koei', 2013, 'PSV'),
(233, 'Dengeki Bunko Fighting Climax', 'Fighting', 'Sega', 2014, 'PSV'),
(234, 'Dragon Ball Z: Battle of Z', 'Fighting', 'Namco Bandai Games', 2014, 'PSV'),
(235, 'Gakusen Toshi Asterisk Festa: Houka Kenran', 'Fighting', 'Namco Bandai Games', 2016, 'PSV'),
(236, 'Injustice: Gods Among Us', 'Fighting', 'Warner Bros. Interactive Entertainment', 2013, 'PSV'),
(237, 'J Stars Victory Vs.', 'Fighting', 'Namco Bandai Games', 2014, 'PSV'),
(238, 'Mortal Kombat', 'Fighting', 'Warner Bros. Interactive Entertainment', 2012, 'PSV'),
(239, 'One Piece: Burning Blood', 'Fighting', 'Namco Bandai Games', 2016, 'PSV'),
(240, 'Reality Fighters', 'Fighting', 'Sony Computer Entertainment', 2012, 'PSV'),
(241, 'Senran Kagura Shinovi Versus: Sh?jo-tachi no Sh?mei', 'Fighting', 'Marvelous Entertainment', 2013, 'PSV'),
(242, 'Street Fighter X Tekken', 'Fighting', 'Capcom', 2012, 'PSV'),
(243, 'Supremacy MMA', 'Fighting', '505 Games', 2012, 'PSV'),
(244, 'Ultimate Marvel vs. Capcom 3', 'Fighting', 'Capcom', 2011, 'PSV'),
(245, 'Amnesia Later', 'Misc', 'Idea Factory', 2014, 'PSV'),
(246, 'Bakumatsu Rock: Ultra Soul', 'Misc', 'Marvelous Interactive', 2014, 'PSV'),
(247, 'Canimal Triple', 'Misc', 'Warner Bros. Interactive Entertainment', 2014, 'PSV'),
(248, 'Danganronpa 2: Goodbye Despair', 'Misc', 'Nippon Ichi Software', 2014, 'PSV'),
(249, 'Danganronpa: Trigger Happy Havoc', 'Misc', 'Nippon Ichi Software', 2013, 'PSV'),
(250, 'DJ Max Technika Tune', 'Misc', 'CyberFront', 2012, 'PSV'),
(251, 'Hatsune Miku: Project Diva f', 'Misc', 'Sega', 2012, 'PSV'),
(252, 'Hatsune Miku: Project Diva F 2nd', 'Misc', 'Sega', 2014, 'PSV'),
(253, 'Hatsune Miku: Project Diva X', 'Misc', 'Sega', 2016, 'PSV'),
(254, 'Hyperdimension Idol Neptunia PP', 'Misc', 'Namco Bandai Games', 2013, 'PSV'),
(255, 'IA/VT Colorful', 'Misc', 'Marvelous Entertainment', 2015, 'PSV'),
(256, 'Love Live! School Idol Paradise', 'Misc', 'Kadokawa Games', 2014, 'PSV'),
(257, 'Lumines: Electronic Symphony', 'Misc', 'Ubisoft', 2012, 'PSV'),
(258, 'Michael Jackson: The Experience', 'Misc', 'Ubisoft', 2011, 'PSV'),
(259, 'Minecraft', 'Misc', 'Sony Computer Entertainment Europe', 2014, 'PSV'),
(260, 'Minna to Issho', 'Misc', 'Sony Computer Entertainment', 2011, 'PSV'),
(261, 'Miracle Girls Festival', 'Misc', 'Sega', 2015, 'PSV'),
(262, 'Nobunaga\'s Ambition: Sphere of Influence - Sengoku Risshiden', 'Misc', 'Tecmo Koei', 2016, 'PSV'),
(263, 'Persona 4: Dancing All Night', 'Misc', 'Nippon Ichi Software', 2015, 'PSV'),
(264, 'Saki: Zenkoku-hen', 'Misc', 'Kaga Create', 2015, 'PSV'),
(265, 'Senran Kagura: Bon Appétit!', 'Misc', 'Marvelous Entertainment', 2014, 'PSV'),
(266, 'The Idolm@ster: Must Songs - Red Board / Blue Board', 'Misc', 'Namco Bandai Games', 2015, 'PSV'),
(267, 'Uta Kumi 575', 'Misc', 'Sega', 2014, 'PSV'),
(268, 'Utawarerumono: Futari no Hakuoro', 'Misc', 'Aqua Plus', 2016, 'PSV'),
(269, 'Airship Q', 'Platform', 'Cygames', 2015, 'PSV'),
(270, 'htoL#NiQ: The Firefly Diary', 'Platform', 'Nippon Ichi Software', 2014, 'PSV'),
(271, 'Little Deviants', 'Platform', 'Sony Computer Entertainment', 2011, 'PSV'),
(272, 'LittleBigPlanet PS Vita', 'Platform', 'Sony Computer Entertainment', 2012, 'PSV'),
(273, 'Putty Squad', 'Platform', 'System 3', 2013, 'PSV'),
(274, 'Rayman Legends', 'Platform', 'Ubisoft', 2014, 'PSV'),
(275, 'Rayman Origins', 'Platform', 'Ubisoft', 2012, 'PSV'),
(276, 'Sly Cooper: Thieves in Time', 'Platform', 'Sony Computer Entertainment Europe', 2013, 'PSV'),
(277, 'SpongeBob: HeroPants', 'Platform', 'Activision', 2015, 'PSV'),
(278, 'Teslagrad', 'Platform', 'Rain Games', 2015, 'PSV'),
(279, 'Puyo Puyo Tetris', 'Puzzle', 'Sega', 2014, 'PSV'),
(280, 'Tetris Ultimate', 'Puzzle', 'Ubisoft', 2014, 'PSV'),
(281, 'Touch My Katamari', 'Puzzle', 'Namco Bandai Games', 2011, 'PSV'),
(282, 'Ben 10 Galactic Racing', 'Racing', 'D3Publisher', 2012, 'PSV'),
(283, 'F1 2011', 'Racing', 'Codemasters', 2011, 'PSV'),
(284, 'Modnation Racers: Road Trip', 'Racing', 'Sony Computer Entertainment', 2012, 'PSV'),
(285, 'MotoGP 14', 'Racing', 'Milestone S.r.l.', 2014, 'PSV'),
(286, 'MotorStorm RC', 'Racing', 'Sony Computer Entertainment', 2012, 'PSV'),
(287, 'Need for Speed: Most Wanted', 'Racing', 'Electronic Arts', 2012, 'PSV'),
(288, 'Ridge Racer', 'Racing', 'Namco Bandai Games', 2011, 'PSV'),
(289, 'Sonic & All-Stars Racing Transformed', 'Racing', 'Sega', 2012, 'PSV'),
(290, 'Tokyo Ghoul: Jail', 'Racing', 'Namco Bandai Games', 2015, 'PSV'),
(291, 'Winning Post 8', 'Racing', 'Tecmo Koei', 2014, 'PSV'),
(292, 'Wipeout 2048', 'Racing', 'Sony Computer Entertainment', 2012, 'PSV'),
(293, '3rd Super Robot Wars Z Jigoku Hen', 'Role-Playing', 'Namco Bandai Games', 2014, 'PSV'),
(294, 'Ar Nosurge: Ode to an Unborn Star', 'Role-Playing', 'Tecmo Koei', 2014, 'PSV'),
(295, 'Atelier Ayesha: The Alchemist of Dusk', 'Role-Playing', 'Tecmo Koei', 2014, 'PSV'),
(296, 'Atelier Escha & Logy: Alchemists of the Dusk Sky', 'Role-Playing', 'Tecmo Koei', 2015, 'PSV'),
(297, 'Atelier Meruru: Alchemist of Arland 3', 'Role-Playing', 'Gust', 2013, 'PSV'),
(298, 'Atelier Rorona: Alchemist of Arland', 'Role-Playing', 'Nippon Ichi Software', 2013, 'PSV'),
(299, 'Atelier Shallie Plus: Alchemists of the Dusk Sea', 'Role-Playing', 'Tecmo Koei', 2016, 'PSV'),
(300, 'Atelier Sophie: The Alchemist of the Mysterious Book', 'Role-Playing', 'Tecmo Koei', 2015, 'PSV'),
(301, 'Atelier Totori: The Adventurer of Arland', 'Role-Playing', 'Gust', 2012, 'PSV'),
(302, 'Caligula', 'Role-Playing', 'FuRyu', 2016, 'PSV'),
(303, 'Chaos Rings III', 'Role-Playing', 'Square Enix', 2014, 'PSV'),
(304, 'Child of Light', 'Role-Playing', 'Ubisoft', 2014, 'PSV'),
(305, 'Conception II: Children of the Seven Stars', 'Role-Playing', 'Screenlife', 2013, 'PSV'),
(306, 'Criminal Girls 2', 'Role-Playing', 'Nippon Ichi Software', 2015, 'PSV'),
(307, 'Criminal Girls: Invite Only', 'Role-Playing', 'Nippon Ichi Software', 2013, 'PSV'),
(308, 'Demon Gaze', 'Role-Playing', 'Nippon Ichi Software', 2013, 'PSV'),
(309, 'Demon Gaze 2', 'Role-Playing', 'Experience Inc.', 2014, 'PSV'),
(310, 'Digimon Story: Cyber Sleuth', 'Role-Playing', 'Namco Bandai Games', 2015, 'PSV'),
(311, 'Disgaea 4: A Promise Unforgotten', 'Role-Playing', 'Nippon Ichi Software', 2014, 'PSV'),
(312, 'Dragon Quest Builders: Revive Alefgard', 'Role-Playing', 'Square Enix', 2016, 'PSV'),
(313, 'Dragon\'s Crown', 'Role-Playing', 'Nippon Ichi Software', 2013, 'PSV'),
(314, 'Dungeon Travelers 2: The Royal Library & The Monster Seal', 'Role-Playing', 'Atlus', 2014, 'PSV'),
(315, 'Exist Archive: The Other Side of the Sky', 'Role-Playing', 'Aksys Games', 2015, 'PSV'),
(316, 'Exstetra', 'Role-Playing', 'FuRyu', 2013, 'PSV'),
(317, 'Final Fantasy X / X-2 HD Remaster', 'Role-Playing', 'Square Enix', 2013, 'PSV'),
(318, 'Freedom Wars', 'Role-Playing', 'Sony Computer Entertainment', 2014, 'PSV'),
(319, 'Genkai Tokki: Moero Crystal', 'Role-Playing', 'Compile Heart', 2015, 'PSV'),
(320, 'Genkai Tokki: Seven Pirates', 'Role-Playing', 'Compile Heart', 2016, 'PSV'),
(321, 'Genkai Totsuki Moero Chronicle', 'Role-Playing', 'Compile Heart', 2014, 'PSV'),
(322, 'God Eater 2', 'Role-Playing', 'Namco Bandai Games', 2013, 'PSV'),
(323, 'God Eater 2: Rage Burst', 'Role-Playing', 'Namco Bandai Games', 2015, 'PSV'),
(324, 'Grand Kingdom', 'Role-Playing', 'Nippon Ichi Software', 2015, 'PSV'),
(325, 'Hyperdevotion Noire: Goddess Black Heart', 'Role-Playing', 'Idea Factory', 2014, 'PSV'),
(326, 'Hyperdimension Neptunia', 'Role-Playing', 'Compile Heart', 2013, 'PSV'),
(327, 'Hyperdimension Neptunia Victory', 'Role-Playing', 'Compile Heart', 2014, 'PSV'),
(328, 'Hyperdimension Neptunia Vs. Sega Hard Girls: Yume no Gattai Special', 'Role-Playing', 'Compile Heart', 2015, 'PSV'),
(329, 'Invizimals: The Resistance', 'Role-Playing', 'Sony Computer Entertainment', 2014, 'PSV'),
(330, 'Labyrinth Cross Blood: Infinity', 'Role-Playing', 'CyberFront', 2013, 'PSV'),
(331, 'Little Battlers eXperience W', 'Role-Playing', 'Level 5', 2012, 'PSV'),
(332, 'Lord of Apocalypse', 'Role-Playing', 'Square Enix', 2011, 'PSV'),
(333, 'Lost Dimension', 'Role-Playing', 'Nippon Ichi Software', 2014, 'PSV'),
(334, 'Makai Shin Trillion', 'Role-Playing', 'Idea Factory', 2014, 'PSV'),
(335, 'MeiQ no Chika Ni Shisu: A Maze to Eradicate Them All', 'Role-Playing', 'Idea Factory', 2015, 'PSV'),
(336, 'Mind Zero', 'Role-Playing', 'GungHo', 2013, 'PSV'),
(337, 'Muramasa: The Demon Blade', 'Role-Playing', 'Marvelous Entertainment', 2013, 'PSV'),
(338, 'Natural Doctrine', 'Role-Playing', 'Nippon Ichi Software', 2014, 'PSV'),
(339, 'New Interpretation Stranger of Sword City', 'Role-Playing', 'Experience Inc.', 2016, 'PSV'),
(340, 'New Tokyo Legacy: Operation Babel', 'Role-Playing', '5pb', 2015, 'PSV'),
(341, 'Odin Sphere: Leifthrasir', 'Role-Playing', 'Nippon Ichi Software', 2016, 'PSV'),
(342, 'Omega Labyrinth', 'Role-Playing', 'D3Publisher', 2015, 'PSV'),
(343, 'Operation Abyss: New Tokyo Legacy', 'Role-Playing', 'Nippon Ichi Software', 2014, 'PSV'),
(344, 'Oreshika: Tainted Bloodlines', 'Role-Playing', 'Sony Computer Entertainment', 2014, 'PSV'),
(345, 'Persona 4: Golden', 'Role-Playing', 'Atlus', 2012, 'PSV'),
(346, 'Phantasy Star Nova', 'Role-Playing', 'Sega', 2014, 'PSV'),
(347, 'Phantasy Star Online 2', 'Role-Playing', 'Sega', 2013, 'PSV'),
(348, 'Phantasy Star Online 2 Episode 4: Deluxe Package', 'Role-Playing', 'Sega', 2017, 'PSV'),
(349, 'Project Setsuna', 'Role-Playing', 'Square Enix', 2016, 'PSV'),
(350, 'Ragnarok Odyssey', 'Role-Playing', 'GungHo', 2012, 'PSV'),
(351, 'Ray Gigant', 'Role-Playing', 'Namco Bandai Games', 2015, 'PSV'),
(352, 'Sorcery Saga: The Curse of the Great Curry God', 'Role-Playing', 'Rising Star Games', 2013, 'PSV'),
(353, 'Soul Sacrifice', 'Role-Playing', 'Sony Computer Entertainment', 2013, 'PSV'),
(354, 'Stranger of Sword City', 'Role-Playing', 'Nippon Ichi Software', 2015, 'PSV'),
(355, 'Super Hero Generation', 'Role-Playing', 'Namco Bandai Games', 2014, 'PSV'),
(356, 'Super Heroine Chronicle', 'Role-Playing', 'Namco Bandai Games', 2014, 'PSV'),
(357, 'Sword Art Online: Hollow Fragment', 'Role-Playing', 'Namco Bandai Games', 2014, 'PSV'),
(358, 'Sword Art Online: Lost Song', 'Role-Playing', 'Namco Bandai Games', 2015, 'PSV'),
(359, 'Tales of Hearts', 'Role-Playing', 'Namco Bandai Games', 2013, 'PSV'),
(360, 'Tales of Innocence R', 'Role-Playing', 'Namco Bandai Games', 2012, 'PSV'),
(361, 'The Legend of Heroes VII: The Trail of Blue', 'Role-Playing', 'Nihon Falcom Corporation', 2014, 'PSV'),
(362, 'The Legend of Heroes VII: The Trail of Zero', 'Role-Playing', 'Falcom Corporation', 2012, 'PSV'),
(363, 'The Legend of Heroes: Trails in the Sky First Chapter', 'Role-Playing', 'Kadokawa Shoten', 2015, 'PSV'),
(364, 'The Legend of Heroes: Trails in the Sky SC Evolution', 'Role-Playing', 'Kadokawa Games', 2015, 'PSV'),
(365, 'The Legend of Heroes: Trails in the Sky Third Chapter', 'Role-Playing', 'Nihon Falcom Corporation', 2016, 'PSV'),
(366, 'The Legend of Heroes: Trails of Cold Steel', 'Role-Playing', 'Nippon Ichi Software', 2013, 'PSV'),
(367, 'The Legend of Heroes: Trails of Cold Steel II', 'Role-Playing', 'Nippon Ichi Software', 2014, 'PSV'),
(368, 'Tokyo Twilight Ghost Hunters', 'Role-Playing', 'Aksys Games', 2014, 'PSV'),
(369, 'Tokyo Xanadu', 'Role-Playing', 'Nihon Falcom Corporation', 2015, 'PSV'),
(370, 'Tsurugi no Machi no Ihoujin: Kuro no Kyuuden', 'Role-Playing', 'Experience Inc.', 2015, 'PSV'),
(371, 'Valhalla Knights 3', 'Role-Playing', 'Xseed Games', 2013, 'PSV'),
(372, 'Yoru no Nai Kuni', 'Role-Playing', 'Tecmo Koei', 2015, 'PSV'),
(373, 'Ys VIII: Lacrimosa of Dana', 'Role-Playing', 'Nihon Falcom Corporation', 2016, 'PSV'),
(374, 'Yuusha Shisu.', 'Role-Playing', 'Nippon Ichi Software', 2016, 'PSV'),
(375, 'Borderlands 2', 'Shooter', 'Take-Two Interactive', 2014, 'PSV'),
(376, 'Killzone: Mercenary', 'Shooter', 'Sony Computer Entertainment Europe', 2013, 'PSV'),
(377, 'Resistance: Burning Skies', 'Shooter', 'Sony Computer Entertainment', 2012, 'PSV'),
(378, 'Uncharted: Golden Abyss', 'Shooter', 'Sony Computer Entertainment', 2011, 'PSV'),
(379, 'Unit 13', 'Shooter', 'Sony Computer Entertainment', 2012, 'PSV'),
(380, 'Dream Club Zero Portable', 'Simulation', 'D3Publisher', 2011, 'PSV'),
(381, 'Farming Simulator 2014', 'Simulation', 'Focus Home Interactive', 2014, 'PSV'),
(382, 'Himoutou! Umaru-Chan: Himoutou Ikusei Keikaku', 'Simulation', 'FuRyu', 2015, 'PSV'),
(383, 'Dead or Alive Xtreme 3: Venus', 'Sports', 'Tecmo Koei', 2016, 'PSV'),
(384, 'FIFA 14', 'Sports', 'Electronic Arts', 2013, 'PSV'),
(385, 'FIFA 15', 'Sports', 'Electronic Arts', 2014, 'PSV'),
(386, 'FIFA Soccer', 'Sports', 'Electronic Arts', 2012, 'PSV'),
(387, 'Football Manager 2014', 'Sports', 'Sega', 2013, 'PSV'),
(388, 'Hot Shots Golf: World Invitational', 'Sports', 'Sony Computer Entertainment', 2011, 'PSV'),
(389, 'Jikkyou Powerful Pro Baseball 2016', 'Sports', 'Konami Digital Entertainment', 2016, 'PSV'),
(390, 'Jikkyou Powerful Pro Yakyuu 2013', 'Sports', 'Konami Digital Entertainment', 2013, 'PSV'),
(391, 'Jikkyou Powerful Pro Yakyuu 2014', 'Sports', 'Konami Digital Entertainment', 2014, 'PSV'),
(392, 'Madden NFL 13', 'Sports', 'Electronic Arts', 2012, 'PSV'),
(393, 'MLB 12: The Show', 'Sports', 'Sony Computer Entertainment', 2012, 'PSV'),
(394, 'MLB 13: The Show', 'Sports', 'Sony Computer Entertainment', 2013, 'PSV'),
(395, 'MLB 14: The Show', 'Sports', 'Sony Computer Entertainment America', 2014, 'PSV'),
(396, 'MLB 15: The Show', 'Sports', 'Sony Computer Entertainment', 2015, 'PSV'),
(397, 'Pro Yaky? Spirits 2012', 'Sports', 'Konami Digital Entertainment', 2012, 'PSV'),
(398, 'Pro Yaky? Spirits 2013', 'Sports', 'Konami Digital Entertainment', 2013, 'PSV'),
(399, 'Pro Yaky? Spirits 2014', 'Sports', 'Konami Digital Entertainment', 2014, 'PSV'),
(400, 'Rugby 15', 'Sports', 'Bigben Interactive', 2015, 'PSV'),
(401, 'Rugby World Cup 2015', 'Sports', 'Ubisoft', 2015, 'PSV'),
(402, 'Soccer Tsuku: Pro Soccer Club o Tsukurou!', 'Sports', 'Sega', 2013, 'PSV'),
(403, 'Virtua Tennis 4: World Tour', 'Sports', 'Sega', 2011, 'PSV'),
(404, 'Winning Post 7 2013', 'Sports', 'Tecmo Koei', 2013, 'PSV'),
(405, 'WRC 5: FIA World Rally Championship', 'Sports', 'Bigben Interactive', 2015, 'PSV'),
(406, 'Angry Birds Star Wars', 'Strategy', 'Activision', 2013, 'PSV'),
(407, 'Genkai Tokki Monster Monpiece', 'Strategy', 'Idea Factory', 2013, 'PSV'),
(408, 'Nobunaga\'s Ambition: Sphere of Influence', 'Strategy', 'Tecmo Koei', 2014, 'PSV'),
(409, 'Nobunaga\'s Ambition: Tenshouki with Power-Up Kit HD Version', 'Strategy', 'Tecmo Koei', 2015, 'PSV'),
(410, 'Sid Meier\'s Civilization Revolution 2+', 'Strategy', 'Take-Two Interactive', 2015, 'PSV'),
(411, 'Space Hulk', 'Strategy', 'Funbox Media', 2015, 'PSV'),
(412, 'Super Robot Taisen OG Saga: Masou Kishin III - Pride of Justice', 'Strategy', 'Namco Bandai Games', 2013, 'PSV');
