
-- --------------------------------------------------------

--
-- Struttura della tabella `snes`
--

DROP TABLE IF EXISTS `snes`;
CREATE TABLE IF NOT EXISTS `snes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `game_name` varchar(200) CHARACTER SET utf8mb3 DEFAULT NULL,
  `genre_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  `publisher_name` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL,
  `release_year` int DEFAULT NULL,
  `platform_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=240 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dump dei dati per la tabella `snes`
--

INSERT INTO `snes` (`id`, `game_name`, `genre_name`, `publisher_name`, `release_year`, `platform_name`) VALUES
(1, 'Final Fight', 'Action', 'Capcom', 1990, 'SNES'),
(2, 'Final Fight 2', 'Action', 'Capcom', 1993, 'SNES'),
(3, 'Kenyuu Densetsu Yaiba', 'Action', 'Banpresto', 1994, 'SNES'),
(4, 'Kidou Senshi V Gundam', 'Action', 'Namco Bandai Games', 1994, 'SNES'),
(5, 'Lord of Darkness', 'Action', 'Tecmo Koei', 1991, 'SNES'),
(6, 'Mega Man X3', 'Action', 'Laguna', 1995, 'SNES'),
(7, 'Ninja Warriors', 'Action', 'Titus', 1993, 'SNES'),
(8, 'Sailor Moon', 'Action', 'Namco Bandai Games', 1993, 'SNES'),
(9, 'Super Metroid', 'Action', 'Nintendo', 1994, 'SNES'),
(10, 'Super Wagyan Land', 'Action', 'Namco Bandai Games', 1991, 'SNES'),
(11, 'The Great Battle Gaiden 2: Matsuri da Wasshoi', 'Action', 'Banpresto', 1994, 'SNES'),
(12, 'The Legend of Zelda: A Link to the Past', 'Action', 'Nintendo', 1991, 'SNES'),
(13, 'Jirou Akagawa: Majotachi no Nemuri', 'Adventure', 'Pack-In-Video', 1995, 'SNES'),
(14, 'Kamaitachi no Yoru', 'Adventure', 'ChunSoft', 1994, 'SNES'),
(15, 'Otogirisou', 'Adventure', 'ChunSoft', 1992, 'SNES'),
(16, 'The Legend of the Mystical Ninja', 'Adventure', 'Konami Digital Entertainment', 1991, 'SNES'),
(17, 'Bishoujo Senshi Sailormoon R', 'Fighting', 'Namco Bandai Games', 1993, 'SNES'),
(18, 'Bishoujo Senshi Sailormoon S: Juugai Rantou!? Shuyaku Soudatsusen', 'Fighting', 'Angel Studios', 1994, 'SNES'),
(19, 'Dragon Ball Z', 'Fighting', 'Namco Bandai Games', 1993, 'SNES'),
(20, 'Dragon Ball Z Hyper Dimension', 'Fighting', 'Namco Bandai Games', 1995, 'SNES'),
(21, 'Dragon Ball Z: La Legende Saien', 'Fighting', 'Namco Bandai Games', 1993, 'SNES'),
(22, 'Dragon Ball Z: Ultime Menace', 'Fighting', 'Namco Bandai Games', 1993, 'SNES'),
(23, 'Fatal Fury', 'Fighting', 'Takara', 1992, 'SNES'),
(24, 'Fatal Fury 2', 'Fighting', 'Takara', 1993, 'SNES'),
(25, 'Fatal Fury Special', 'Fighting', 'Takara', 1994, 'SNES'),
(26, 'Killer Instinct', 'Fighting', 'Nintendo', 1995, 'SNES'),
(27, 'Mortal Kombat 3', 'Fighting', 'Acclaim Entertainment', 1994, 'SNES'),
(28, 'Mortal Kombat II', 'Fighting', 'Acclaim Entertainment', 1993, 'SNES'),
(29, 'Samurai Shodown', 'Fighting', 'Takara', 1994, 'SNES'),
(30, 'Saturday Night Slam Masters', 'Fighting', 'Capcom', 1994, 'SNES'),
(31, 'Street Fighter Alpha 2', 'Fighting', 'Nintendo', 1996, 'SNES'),
(32, 'Street Fighter II Turbo', 'Fighting', 'Capcom', 1992, 'SNES'),
(33, 'Street Fighter II: The World Warrior', 'Fighting', 'Capcom', 1992, 'SNES'),
(34, 'Sugoi Hebereke', 'Fighting', 'Sunsoft', 1994, 'SNES'),
(35, 'Super Fire ProWrestling', 'Fighting', 'Human Entertainment', 1991, 'SNES'),
(36, 'Super Fire ProWrestling Special', 'Fighting', 'Human Entertainment', 1994, 'SNES'),
(37, 'Super Fire ProWrestling X', 'Fighting', 'Human Entertainment', 1995, 'SNES'),
(38, 'Super Street Fighter II', 'Fighting', 'Nintendo', 1993, 'SNES'),
(39, 'Teenage Mutant Ninja Turtles: Tournament Fighters', 'Fighting', 'Konami Digital Entertainment', 1992, 'SNES'),
(40, 'Yuu Yuu Hakusho', 'Fighting', 'Namco Bandai Games', 1993, 'SNES'),
(41, 'Yuu Yuu Hakusho 2: Kakutou no Sho', 'Fighting', 'Namco Bandai Games', 1994, 'SNES'),
(42, 'Chibi Maruko-Chan: Harikiri 365-Nichi no Maki', 'Misc', 'Epoch', 1991, 'SNES'),
(43, 'Daibakushou: Jinsei Gekijou', 'Misc', 'Taito', 1995, 'SNES'),
(44, 'Hissatsu Pachinko Collection 3', 'Misc', 'Sunsoft', 1995, 'SNES'),
(45, 'Hisshou 777 Fighter: Pachi Slot Eiyu Densetsu', 'Misc', 'Vap', 1994, 'SNES'),
(46, 'Itadaki Street 2: Neon Sign wa Bara Iro ni', 'Misc', 'Enix Corporation', 1994, 'SNES'),
(47, 'Jissen Pachi-Slot Hisshouhou', 'Misc', 'Sammy Corporation', 1993, 'SNES'),
(48, 'Mario Paint', 'Misc', 'Nintendo', 1992, 'SNES'),
(49, 'Momotarou Dentetsu Happy', 'Misc', 'Hudson Soft', 1996, 'SNES'),
(50, 'Nichibutsu Arcade Classics', 'Misc', 'Nichibutsu', 1995, 'SNES'),
(51, 'Nishijin Pachinko Monogatari 2', 'Misc', 'KSS', 1996, 'SNES'),
(52, 'Pachinko Wars II', 'Misc', 'Coconuts Japan', 1993, 'SNES'),
(53, 'Parlor! Mini 2', 'Misc', 'Nippon Telenet', 1996, 'SNES'),
(54, 'Parlor! Mini 4', 'Misc', 'Nippon Telenet', 1996, 'SNES'),
(55, 'Sound Novel Tsukuru', 'Misc', 'ASCII Entertainment', 1996, 'SNES'),
(56, 'Super Jinsei Game 2', 'Misc', 'Takara', 1995, 'SNES'),
(57, 'Super Mahjong 2: Honkaku 4Jin Uchi', 'Misc', 'Imax', 1993, 'SNES'),
(58, 'Super Momotarou Dentetsu DX', 'Misc', 'Hudson Soft', 1995, 'SNES'),
(59, 'Castlevania Dracula X', 'Platform', 'Konami Digital Entertainment', 1995, 'SNES'),
(60, 'Crayon Shin-Chan: Arashi o Yobu Enji', 'Platform', 'Namco Bandai Games', 1993, 'SNES'),
(61, 'Disney\'s Aladdin', 'Platform', 'Capcom', 1993, 'SNES'),
(62, 'Disney\'s The Lion King', 'Platform', 'Virgin Interactive', 1994, 'SNES'),
(63, 'Donkey Kong Country', 'Platform', 'Nintendo', 1994, 'SNES'),
(64, 'Donkey Kong Country 2: Diddy\'s Kong Quest', 'Platform', 'Nintendo', 1995, 'SNES'),
(65, 'Donkey Kong Country 3: Dixie Kong\'s Double Trouble!', 'Platform', 'Nintendo', 1996, 'SNES'),
(66, 'Doraemon 4: Nobita to Toki no Okoku', 'Platform', 'Epoch', 1995, 'SNES'),
(67, 'Ganbare Goemon 2: Kiteretsu Shougun Magginesu', 'Platform', 'Konami Digital Entertainment', 1993, 'SNES'),
(68, 'Ganbare Goemon 3: Shishi Jyuurokubei no Karakuri Manji Katame', 'Platform', 'Konami Digital Entertainment', 1994, 'SNES'),
(69, 'Ganbare Goemon: KiraKira Douchuu - Boku ga Dancer ni Natta Riyuu', 'Platform', 'Konami Digital Entertainment', 1995, 'SNES'),
(70, 'Go Go Ackman 3', 'Platform', 'Banpresto', 1995, 'SNES'),
(71, 'Kirby Super Star', 'Platform', 'Nintendo', 1996, 'SNES'),
(72, 'Kirby\'s Dream Land 3', 'Platform', 'Nintendo', 1997, 'SNES'),
(73, 'Mega Man 7', 'Platform', 'Laguna', 1995, 'SNES'),
(74, 'Mega Man X', 'Platform', 'Capcom', 1993, 'SNES'),
(75, 'Mega Man X2', 'Platform', 'Laguna', 1993, 'SNES'),
(76, 'Pop\'n TwinBee: Rainbow Bell Adventure', 'Platform', 'Konami Digital Entertainment', 1993, 'SNES'),
(77, 'RockMan & Forte', 'Platform', 'Capcom', 1998, 'SNES'),
(78, 'Super Adventure Island', 'Platform', 'Hudson Soft', 1992, 'SNES'),
(79, 'Super Castlevania IV', 'Platform', 'Konami Digital Entertainment', 1991, 'SNES'),
(80, 'Super Ghouls \'n Ghosts', 'Platform', 'Capcom', 1991, 'SNES'),
(81, 'Super Mario All-Stars', 'Platform', 'Nintendo', 1993, 'SNES'),
(82, 'Super Mario World', 'Platform', 'Nintendo', 1990, 'SNES'),
(83, 'Super Mario World 2: Yoshi\'s Island', 'Platform', 'Nintendo', 1995, 'SNES'),
(84, 'The Magical Quest starring Mickey Mouse', 'Platform', 'Capcom', 1992, 'SNES'),
(85, 'Block Kuzushi', 'Puzzle', 'Pow', 1995, 'SNES'),
(86, 'Mario & Wario', 'Puzzle', 'Nintendo', 1993, 'SNES'),
(87, 'Mario no Super Picross', 'Puzzle', 'Nintendo', 1995, 'SNES'),
(88, 'Super Bomberman', 'Puzzle', 'Hudson Soft', 1992, 'SNES'),
(89, 'Super Bomberman 2', 'Puzzle', 'Hudson Soft', 1994, 'SNES'),
(90, 'Super Bomberman 3', 'Puzzle', 'Hudson Soft', 1994, 'SNES'),
(91, 'Super Bomberman 4', 'Puzzle', 'Hudson Soft', 1996, 'SNES'),
(92, 'Super Bomberman 5', 'Puzzle', 'Hudson Soft', 1997, 'SNES'),
(93, 'Super Nazo Puyo Tsuu: Ruruu no Tetsuwan Hanjyouki', 'Puzzle', 'Compile', 1996, 'SNES'),
(94, 'Super Nazo Puyo: Ruruu no Ruu', 'Puzzle', 'Banpresto', 1995, 'SNES'),
(95, 'Super Puyo Puyo', 'Puzzle', 'Banpresto', 1993, 'SNES'),
(96, 'Super Puyo Puyo 2', 'Puzzle', 'Compile', 1995, 'SNES'),
(97, 'Tetris Attack', 'Puzzle', 'Nintendo', 1995, 'SNES'),
(98, 'Drift King Shutokou Battle \'94', 'Racing', 'BPS', 1994, 'SNES'),
(99, 'F-1 Grand Prix', 'Racing', 'Video System', 1992, 'SNES'),
(100, 'F-Zero', 'Racing', 'Nintendo', 1990, 'SNES'),
(101, 'Mini-Yonku Shining Scorpion: Let\'s & Go!!', 'Racing', 'ASCII Entertainment', 1996, 'SNES'),
(102, 'Rock N\' Roll Racing', 'Racing', 'Interplay', 1993, 'SNES'),
(103, 'Stunt Race FX', 'Racing', 'Nintendo', 1993, 'SNES'),
(104, 'Super Mario Kart', 'Racing', 'Nintendo', 1992, 'SNES'),
(105, 'Zen-Nippon GT Senshuken', 'Racing', 'Banpresto', 1995, 'SNES'),
(106, 'Zero4 Champ RR-Z', 'Racing', 'Media Rings', 1995, 'SNES'),
(107, 'Bahamut Lagoon', 'Role-Playing', 'SquareSoft', 1996, 'SNES'),
(108, 'Breath of Fire II', 'Role-Playing', 'Laguna', 1994, 'SNES'),
(109, 'Chrono Trigger', 'Role-Playing', 'SquareSoft', 1995, 'SNES'),
(110, 'Daikaijyuu Monogatari', 'Role-Playing', 'Hudson Soft', 1994, 'SNES'),
(111, 'Daikaijyuu Monogatari II', 'Role-Playing', 'Hudson Soft', 1996, 'SNES'),
(112, 'Dark Half', 'Role-Playing', 'Enix Corporation', 1996, 'SNES'),
(113, 'Doraemon 2: Nobita no Toizurando Daibouken', 'Role-Playing', 'Epoch', 1993, 'SNES'),
(114, 'Dragon Ball Z Super Gokuden: Kakusei-Hen', 'Role-Playing', 'Namco Bandai Games', 1995, 'SNES'),
(115, 'Dragon Ball Z: Chou Saiya Densetsu', 'Role-Playing', 'Namco Bandai Games', 1992, 'SNES'),
(116, 'Dragon Quest I & II', 'Role-Playing', 'Enix Corporation', 1993, 'SNES'),
(117, 'Dragon Quest III: Soshite Densetsu e...', 'Role-Playing', 'Enix Corporation', 1996, 'SNES'),
(118, 'Dragon Quest V: Tenkuu no Hanayome', 'Role-Playing', 'Enix Corporation', 1992, 'SNES'),
(119, 'Dragon Quest VI: Maboroshi no Daichi', 'Role-Playing', 'Enix Corporation', 1995, 'SNES'),
(120, 'Dragon Slayer: The Legend of Heroes', 'Role-Playing', 'Epoch', 1992, 'SNES'),
(121, 'EarthBound', 'Role-Playing', 'Nintendo', 1994, 'SNES'),
(122, 'Far East of Eden Zero', 'Role-Playing', 'Hudson Soft', 1995, 'SNES'),
(123, 'Final Fantasy II', 'Role-Playing', 'Square', 1991, 'SNES'),
(124, 'Final Fantasy III', 'Role-Playing', 'SquareSoft', 1994, 'SNES'),
(125, 'Final Fantasy V', 'Role-Playing', 'SquareSoft', 1992, 'SNES'),
(126, 'Fire Emblem: Monsh? no Nazo', 'Role-Playing', 'Nintendo', 1994, 'SNES'),
(127, 'First Queen: Ornic Senki', 'Role-Playing', 'Culture Brain', 1994, 'SNES'),
(128, 'Front Mission: Gun Hazard', 'Role-Playing', 'SquareSoft', 1996, 'SNES'),
(129, 'Gaia Saver Hero Saidai no Sakusen', 'Role-Playing', 'Banpresto', 1994, 'SNES'),
(130, 'Illusion of Gaia', 'Role-Playing', 'Nintendo', 1993, 'SNES'),
(131, 'Lagoon', 'Role-Playing', 'Kemco', 1991, 'SNES'),
(132, 'Live A Live', 'Role-Playing', 'SquareSoft', 1994, 'SNES'),
(133, 'Majin Tensei', 'Role-Playing', 'Atlus', 1994, 'SNES'),
(134, 'Metal Max Returns', 'Role-Playing', 'Data East', 1995, 'SNES'),
(135, 'Mystery Dungeon: Shiren the Wanderer', 'Role-Playing', 'ChunSoft', 1995, 'SNES'),
(136, 'Mystic Ark', 'Role-Playing', 'Enix Corporation', 1995, 'SNES'),
(137, 'Ranma 1/2: Akanekodan Teki Hihou', 'Role-Playing', 'TOHO', 1993, 'SNES'),
(138, 'Romancing SaGa', 'Role-Playing', 'SquareSoft', 1992, 'SNES'),
(139, 'Romancing SaGa 2', 'Role-Playing', 'SquareSoft', 1993, 'SNES'),
(140, 'Romancing SaGa 3', 'Role-Playing', 'SquareSoft', 1995, 'SNES'),
(141, 'RPG Tsukuru 2', 'Role-Playing', 'ASCII Entertainment', 1996, 'SNES'),
(142, 'Rudra no Hihou', 'Role-Playing', 'SquareSoft', 1996, 'SNES'),
(143, 'SD Gundam Gaiden: Knight Gundam Monogatari: Ooinaru Isan', 'Role-Playing', 'Angel Studios', 1991, 'SNES'),
(144, 'Secret of Mana', 'Role-Playing', 'SquareSoft', 1993, 'SNES'),
(145, 'Seiken Densetsu 3', 'Role-Playing', 'SquareSoft', 1995, 'SNES'),
(146, 'Shin Megami Tensei II', 'Role-Playing', 'Atlus', 1994, 'SNES'),
(147, 'Shin Momotarou Densetsu', 'Role-Playing', 'Hudson Soft', 1993, 'SNES'),
(148, 'Slayers', 'Role-Playing', 'Banpresto', 1994, 'SNES'),
(149, 'Star Ocean', 'Role-Playing', 'Enix Corporation', 1996, 'SNES'),
(150, 'Super Mario RPG: Legend of the Seven Stars', 'Role-Playing', 'Nintendo', 1996, 'SNES'),
(151, 'Tactics Ogre: Let Us Cling Together', 'Role-Playing', 'Quest', 1995, 'SNES'),
(152, 'Tales of Phantasia', 'Role-Playing', 'Namco Bandai Games', 1995, 'SNES'),
(153, 'Terranigma', 'Role-Playing', 'Nintendo', 1995, 'SNES'),
(154, 'Torneko no Daibouken: Fushigi no Dungeon', 'Role-Playing', 'ChunSoft', 1993, 'SNES'),
(155, 'Treasure Hunter G', 'Role-Playing', 'SquareSoft', 1996, 'SNES'),
(156, 'Wizardry VI: Bane of the Cosmic Forge', 'Role-Playing', 'ASCII Entertainment', 1995, 'SNES'),
(157, 'Bomberman B-Daman', 'Shooter', 'Hudson Soft', 1996, 'SNES'),
(158, 'Contra III: The Alien Wars', 'Shooter', 'Konami Digital Entertainment', 1992, 'SNES'),
(159, 'Gokujou Parodius', 'Shooter', 'Konami Digital Entertainment', 1994, 'SNES'),
(160, 'Jikkyou Oshaberi Parodius', 'Shooter', 'Konami Digital Entertainment', 1995, 'SNES'),
(161, 'Lethal Enforcers', 'Shooter', 'Konami Digital Entertainment', 1993, 'SNES'),
(162, 'Space Invaders', 'Shooter', 'Taito', 1994, 'SNES'),
(163, 'Star Fox', 'Shooter', 'Nintendo', 1993, 'SNES'),
(164, 'Super R-Type', 'Shooter', 'Nintendo', 1991, 'SNES'),
(165, 'Super Scope 6', 'Shooter', 'Nintendo', 1991, 'SNES'),
(166, 'UN Squadron', 'Shooter', 'Capcom', 1991, 'SNES'),
(167, 'A llI S.V.: A Ressha de Gyoukou 3 Super Version', 'Simulation', 'Pack-In-Video', 1995, 'SNES'),
(168, 'Pilotwings', 'Simulation', 'Nintendo', 1990, 'SNES'),
(169, 'SimCity', 'Simulation', 'Nintendo', 1991, 'SNES'),
(170, 'SimCity 2000', 'Simulation', 'THQ', 1995, 'SNES'),
(171, 'SimEarth: The Living Planet', 'Simulation', 'Imagineer', 1991, 'SNES'),
(172, 'Super Momotarou Dentetsu III', 'Simulation', 'Hudson Soft', 1994, 'SNES'),
(173, 'Thoroughbred Breeder', 'Simulation', 'Hect', 1993, 'SNES'),
(174, 'Thoroughbred Breeder II', 'Simulation', 'Hect', 1994, 'SNES'),
(175, 'Wonder Project J: Kikai no Shonen Pino', 'Simulation', 'Enix Corporation', 1994, 'SNES'),
(176, 'Battle Dodge Ball', 'Sports', 'Banpresto', 1991, 'SNES'),
(177, 'Battle Soccer: Field no Hasha', 'Sports', 'Banpresto', 1992, 'SNES'),
(178, 'Capcom\'s Soccer Shootout', 'Sports', 'Nintendo', 1993, 'SNES'),
(179, 'Captain Tsubasa J: The Way to World Youth', 'Sports', 'Namco Bandai Games', 1995, 'SNES'),
(180, 'Classic Road', 'Sports', 'Victor Interactive', 1993, 'SNES'),
(181, 'Derby Jockey 2', 'Sports', 'Asmik Corp', 1995, 'SNES'),
(182, 'Derby Jockey: Kishou e no Michi', 'Sports', 'Asmik Corp', 1994, 'SNES'),
(183, 'Derby Stallion 96', 'Sports', 'ASCII Entertainment', 1996, 'SNES'),
(184, 'Derby Stallion 98', 'Sports', 'ASCII Entertainment', 1998, 'SNES'),
(185, 'Derby Stallion II', 'Sports', 'ASCII Entertainment', 1994, 'SNES'),
(186, 'Derby Stallion III', 'Sports', 'ASCII Entertainment', 1995, 'SNES'),
(187, 'F1 ROC: Race of Champions', 'Sports', 'Ocean', 1992, 'SNES'),
(188, 'Harukanaru Augusta 2: Masters', 'Sports', 'T&E Soft', 1993, 'SNES'),
(189, 'International Superstar Soccer', 'Sports', 'Konami Digital Entertainment', 1994, 'SNES'),
(190, 'International Superstar Soccer Deluxe', 'Sports', 'Konami Digital Entertainment', 1995, 'SNES'),
(191, 'Itoi Shigesato no Bass Tsuri No. 1', 'Sports', 'Nintendo', 1997, 'SNES'),
(192, 'J-League \'96 Dream Stadium', 'Sports', 'Hudson Soft', 1996, 'SNES'),
(193, 'J-League Excite Stage \'95', 'Sports', 'Epoch', 1995, 'SNES'),
(194, 'J-League Excite Stage \'96', 'Sports', 'Epoch', 1996, 'SNES'),
(195, 'J-League Soccer: Prime Goal', 'Sports', 'Namco Bandai Games', 1993, 'SNES'),
(196, 'J-League Soccer: Prime Goal 2', 'Sports', 'Namco Bandai Games', 1994, 'SNES'),
(197, 'Jikkyou Powerful Pro Yakuu \'94', 'Sports', 'Konami Digital Entertainment', 1994, 'SNES'),
(198, 'Jikkyou Powerful Pro Yakyuu \'96 Kaimakuban', 'Sports', 'Konami Digital Entertainment', 1996, 'SNES'),
(199, 'Jikkyou Powerful Pro Yakyuu 2', 'Sports', 'Konami Digital Entertainment', 1995, 'SNES'),
(200, 'Jikkyou Powerful Pro Yakyuu 3', 'Sports', 'Konami Digital Entertainment', 1996, 'SNES'),
(201, 'Jikkyou Powerful Pro Yakyuu 3 \'97 Haru', 'Sports', 'Konami Digital Entertainment', 1997, 'SNES'),
(202, 'John Madden Football', 'Sports', 'Imagineer', 1991, 'SNES'),
(203, 'Keiba Eight Special', 'Sports', 'Misawa', 1993, 'SNES'),
(204, 'Kirby\'s Dream Course', 'Sports', 'Nintendo', 1994, 'SNES'),
(205, 'Mega Man Soccer', 'Sports', 'Capcom', 1993, 'SNES'),
(206, 'NBA Jam', 'Sports', 'Acclaim Entertainment', 1994, 'SNES'),
(207, 'NBA Jam Tournament Edition', 'Sports', 'Acclaim Entertainment', 1995, 'SNES'),
(208, 'Slam Dunk SD Heat Up!!', 'Sports', 'Namco Bandai Games', 1995, 'SNES'),
(209, 'Slam Dunk: Yonkyo Taiketsu!!', 'Sports', 'Namco Bandai Games', 1994, 'SNES'),
(210, 'Super Baseball Simulator 1.000', 'Sports', 'Culture Brain', 1991, 'SNES'),
(211, 'Super Batter Up', 'Sports', 'Namco Bandai Games', 1992, 'SNES'),
(212, 'Super Famista 3', 'Sports', 'Namco Bandai Games', 1994, 'SNES'),
(213, 'Super Famista 4', 'Sports', 'Namco Bandai Games', 1995, 'SNES'),
(214, 'Super Famista 5', 'Sports', 'Namco Bandai Games', 1996, 'SNES'),
(215, 'Super Formation Soccer 94', 'Sports', 'Human Entertainment', 1994, 'SNES'),
(216, 'Super Power League', 'Sports', 'Hudson Soft', 1993, 'SNES'),
(217, 'Super Power League 2', 'Sports', 'Hudson Soft', 1994, 'SNES'),
(218, 'Super Soccer', 'Sports', 'Nintendo', 1991, 'SNES'),
(219, 'Virtual Soccer', 'Sports', 'Hudson Soft', 1993, 'SNES'),
(220, 'Winning Post', 'Sports', 'Tecmo Koei', 1993, 'SNES'),
(221, 'Winning Post 2', 'Sports', 'Tecmo Koei', 1995, 'SNES'),
(222, 'World Class Rugby 2: Kokunai Gekitou Hen \'93', 'Sports', 'Misawa', 1994, 'SNES'),
(223, 'World League Soccer', 'Sports', 'Imagineer', 1991, 'SNES'),
(224, 'Zero4 Champ RR', 'Sports', 'Media Rings', 1994, 'SNES'),
(225, 'Battle Commander: Hachibushu Shura no Heihou', 'Strategy', 'Banpresto', 1991, 'SNES'),
(226, 'Dai-4-Ji Super Robot Taisen', 'Strategy', 'Banpresto', 1995, 'SNES'),
(227, 'Fire Emblem: Seisen no Keifu', 'Strategy', 'Nintendo', 1996, 'SNES'),
(228, 'Fire Emblem: Thracia 776', 'Strategy', 'Nintendo', 1999, 'SNES'),
(229, 'Front Mission', 'Strategy', 'SquareSoft', 1995, 'SNES'),
(230, 'Kidou Senshi Gundam F91: Formula Senki 0122', 'Strategy', 'Namco Bandai Games', 1991, 'SNES'),
(231, 'Konpeki no Kantai', 'Strategy', 'Angel Studios', 1995, 'SNES'),
(232, 'Nobunaga no Yabou: Haouden', 'Strategy', 'Tecmo Koei', 1993, 'SNES'),
(233, 'Nobunaga no Yabou: Tenshoki', 'Strategy', 'Tecmo Koei', 1996, 'SNES'),
(234, 'Romance of the Three Kingdoms II', 'Strategy', 'Tecmo Koei', 1991, 'SNES'),
(235, 'Romance of the Three Kingdoms III: Dragon of Destiny', 'Strategy', 'Tecmo Koei', 1992, 'SNES'),
(236, 'Romance of the Three Kingdoms IV: Wall of Fire', 'Strategy', 'Tecmo Koei', 1994, 'SNES'),
(237, 'SD Gundam GNext', 'Strategy', 'Namco Bandai Games', 1995, 'SNES'),
(238, 'SD Gundam GX', 'Strategy', 'Namco Bandai Games', 1994, 'SNES'),
(239, 'Super Robot Taisen EX', 'Strategy', 'Banpresto', 1994, 'SNES');
