
-- --------------------------------------------------------

--
-- Struttura della tabella `wii`
--

DROP TABLE IF EXISTS `wii`;
CREATE TABLE IF NOT EXISTS `wii` (
  `game_name` varchar(200) CHARACTER SET utf8mb3 DEFAULT NULL,
  `genre_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  `publisher_name` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL,
  `release_year` int DEFAULT NULL,
  `platform_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dump dei dati per la tabella `wii`
--

INSERT INTO `wii` (`game_name`, `genre_name`, `publisher_name`, `release_year`, `platform_name`) VALUES
('007: Quantum of Solace', 'Action', 'Activision', 2008, 'Wii'),
('Aliens in the Attic', 'Action', 'Playlogic Game Factory', 2009, 'Wii'),
('All Star Karate', 'Action', 'THQ', 2010, 'Wii'),
('America\'s Next Top Model', 'Action', 'Crave Entertainment', 2010, 'Wii'),
('Astro Boy: The Video Game', 'Action', 'D3Publisher', 2009, 'Wii'),
('Avatar: The Game', 'Action', 'Ubisoft', 2009, 'Wii'),
('Avatar: The Last Airbender - The Burning Earth', 'Action', 'THQ', 2007, 'Wii'),
('Bakugan Battle Brawlers: Defenders of the Core', 'Action', 'Activision', 2010, 'Wii'),
('Bakugan: Battle Brawlers', 'Action', 'Activision', 2009, 'Wii'),
('Barbie and Her Sisters Puppy Rescue', 'Action', 'Namco Bandai Games', 2015, 'Wii'),
('Barbie: Groom and Glam Pups', 'Action', 'THQ', 2010, 'Wii'),
('Barnyard', 'Action', 'THQ', 2006, 'Wii'),
('Batman: The Brave and the Bold the Videogame', 'Action', 'Warner Bros. Interactive Entertainment', 2010, 'Wii'),
('Bee Movie Game', 'Action', 'Activision', 2007, 'Wii'),
('Ben 10 Alien Force: Vilgax Attacks', 'Action', 'D3Publisher', 2009, 'Wii'),
('Ben 10: Alien Force', 'Action', 'Koch Media', 2008, 'Wii'),
('Ben 10: Protector of Earth', 'Action', 'D3Publisher', 2007, 'Wii'),
('Beyblade: Metal Fusion - Battle Fortress', 'Action', 'Konami Digital Entertainment', 2009, 'Wii'),
('Boot Camp Academy', 'Action', 'Zoo Games', 2010, 'Wii'),
('Bratz: Girlz Really Rock', 'Action', 'THQ', 2008, 'Wii'),
('Brave: A Warrior\'s Tale', 'Action', 'SouthPeak Games', 2009, 'Wii'),
('Brave: The Video Game', 'Action', 'Disney Interactive Studios', 2012, 'Wii'),
('Bully: Scholarship Edition', 'Action', 'Take-Two Interactive', 2008, 'Wii'),
('Burger Island', 'Action', 'Destineer', 2009, 'Wii'),
('Candace Kane\'s Candy Factory', 'Action', 'Destineer', 2008, 'Wii'),
('Chaotic: Shadow Warriors', 'Action', 'Activision', 2009, 'Wii'),
('Chicken Riot', 'Action', 'City Interactive', 2010, 'Wii'),
('Chicken Shoot', 'Action', 'Zoo Digital Publishing', 2007, 'Wii'),
('Chuck E. Cheese\'s Super Collection', 'Action', 'UFO Interactive', 2011, 'Wii'),
('Code Lyoko: Quest for Infinity', 'Action', 'Game Factory', 2007, 'Wii'),
('Coraline', 'Action', 'D3Publisher', 2009, 'Wii'),
('Crash of the Titans', 'Action', 'Vivendi Games', 2007, 'Wii'),
('Crazy Chicken Tales', 'Action', 'Conspiracy Entertainment', 2009, 'Wii'),
('Create', 'Action', 'Electronic Arts', 2010, 'Wii'),
('Dead Rising: Chop Till You Drop', 'Action', 'Capcom', 2009, 'Wii'),
('Deadly Creatures', 'Action', 'THQ', 2009, 'Wii'),
('Destroy All Humans! Big Willy Unleashed', 'Action', 'THQ', 2008, 'Wii'),
('Disaster: Day of Crisis', 'Action', 'Nintendo', 2008, 'Wii'),
('Disney Infinity', 'Action', 'Disney Interactive Studios', 2013, 'Wii'),
('Disney Planes Fire & Rescue', 'Action', 'Disney Interactive Studios', 2014, 'Wii'),
('Disney Tangled', 'Action', 'Disney Interactive Studios', 2010, 'Wii'),
('Disney Universe', 'Action', 'Disney Interactive Studios', 2011, 'Wii'),
('Disney\'s Meet the Robinsons', 'Action', 'Disney Interactive Studios', 2007, 'Wii'),
('Domino Rally', 'Action', 'Nordcurrent', 2007, 'Wii'),
('Dragon Ball: Revenge of King Piccolo', 'Action', 'Namco Bandai Games', 2009, 'Wii'),
('Dragon Blade: Wrath of Fire', 'Action', 'D3Publisher', 2007, 'Wii'),
('Elebits', 'Action', 'Konami Digital Entertainment', 2006, 'Wii'),
('Epic Mickey 2: The Power of Two', 'Action', 'Disney Interactive Studios', 2012, 'Wii'),
('Escape from Bug Island', 'Action', 'Eidos Interactive', 2006, 'Wii'),
('Family Fest presents: Movie Games', 'Action', 'Ubisoft', 2008, 'Wii'),
('Fantastic Four: Rise of the Silver Surfer', 'Action', 'Take-Two Interactive', 2007, 'Wii'),
('Fatal Frame 2: Wii Edition', 'Action', 'Nintendo', 2012, 'Wii'),
('FIFA Soccer 13', 'Action', 'Electronic Arts', 2012, 'Wii'),
('Final Fantasy Crystal Chronicles: The Crystal Bearers', 'Action', 'Square Enix', 2009, 'Wii'),
('FlingSmash', 'Action', 'Nintendo', 2010, 'Wii'),
('G-Force', 'Action', 'Disney Interactive Studios', 2009, 'Wii'),
('G.I. Joe: The Rise of Cobra', 'Action', 'Electronic Arts', 2009, 'Wii'),
('Generator Rex: Agent of Providence', 'Action', 'Activision', 2011, 'Wii'),
('Ghostbusters: The Video Game', 'Action', 'Atari', 2009, 'Wii'),
('Gintama: Banji Oku Chuubu!', 'Action', 'Namco Bandai Games', 2007, 'Wii'),
('Go Diego Go! Great Dinosaur Rescue', 'Action', 'Take-Two Interactive', 2008, 'Wii'),
('Go Diego Go! Safari Rescue', 'Action', 'Take-Two Interactive', 2008, 'Wii'),
('Go Play: Circus Star', 'Action', 'Majesco Entertainment', 2009, 'Wii'),
('GoldenEye 007 (2010)', 'Action', 'Activision', 2010, 'Wii'),
('Green Lantern: Rise of the Manhunters', 'Action', 'Warner Bros. Interactive Entertainment', 2011, 'Wii'),
('Guinness World Records: The Videogame', 'Action', 'Warner Bros. Interactive Entertainment', 2008, 'Wii'),
('Hannah Montana: Spotlight World Tour', 'Action', 'Disney Interactive Studios', 2007, 'Wii'),
('Happy Feet', 'Action', 'Midway Games', 2006, 'Wii'),
('Harry Potter and the Deathly Hallows - Part 1', 'Action', 'Electronic Arts', 2010, 'Wii'),
('Harry Potter and the Deathly Hallows - Part 2', 'Action', 'Electronic Arts', 2011, 'Wii'),
('Harry Potter and the Half-Blood Prince', 'Action', 'Electronic Arts', 2009, 'Wii'),
('Harry Potter and the Order of the Phoenix', 'Action', 'Electronic Arts', 2007, 'Wii'),
('Haunted House', 'Action', 'Atari', 2010, 'Wii'),
('Heatseeker', 'Action', 'Codemasters', 2007, 'Wii'),
('How to Train Your Dragon', 'Action', 'Activision', 2010, 'Wii'),
('Hysteria Hospital: Emergency Ward', 'Action', 'Oxygen Interactive', 2009, 'Wii'),
('Ice Age: Dawn of the Dinosaurs', 'Action', 'Activision', 2009, 'Wii'),
('Indiana Jones and the Staff of Kings', 'Action', 'Activision', 2009, 'Wii'),
('Iron Man', 'Action', 'Sega', 2008, 'Wii'),
('Iron Man 2', 'Action', 'Sega', 2010, 'Wii'),
('Jaws: Ultimate Predator', 'Action', 'Majesco Entertainment', 2011, 'Wii'),
('JU-ON: The Grudge', 'Action', 'Rising Star Games', 2009, 'Wii'),
('Jumper: Griffin\'s Story', 'Action', 'Eidos Interactive', 2008, 'Wii'),
('Katekyoo Hitman Reborn! Kindan no Yami no Delta', 'Action', 'Marvelous Interactive', 2008, 'Wii'),
('Kekkaishi: Kokubourou no Kage', 'Action', 'Namco Bandai Games', 2007, 'Wii'),
('Kid Adventures: Sky Captain', 'Action', 'Unknown', 2010, 'Wii'),
('Kirby\'s Dream Collection: Special Edition', 'Action', 'Nintendo', 2012, 'Wii'),
('Kung Fu Panda', 'Action', 'Activision', 2008, 'Wii'),
('Kung Fu Panda 2', 'Action', 'THQ', 2011, 'Wii'),
('Kung Fu Panda: Legendary Warriors', 'Action', 'Activision', 2008, 'Wii'),
('Legend of the Guardians: The Owls of Ga\'Hoole', 'Action', 'Warner Bros. Interactive Entertainment', 2010, 'Wii'),
('LEGO Batman 2: DC Super Heroes', 'Action', 'Warner Bros. Interactive Entertainment', 2012, 'Wii'),
('LEGO Harry Potter: Years 1-4', 'Action', 'Warner Bros. Interactive Entertainment', 2010, 'Wii'),
('LEGO Indiana Jones 2: The Adventure Continues', 'Action', 'Activision', 2009, 'Wii'),
('LEGO Pirates of the Caribbean: The Video Game', 'Action', 'Disney Interactive Studios', 2011, 'Wii'),
('LEGO Star Wars III: The Clone Wars', 'Action', 'LucasArts', 2011, 'Wii'),
('LEGO Star Wars: The Complete Saga', 'Action', 'LucasArts', 2007, 'Wii'),
('LEGO The Lord of the Rings', 'Action', 'Warner Bros. Interactive Entertainment', 2012, 'Wii'),
('Looney Tunes: Acme Arsenal', 'Action', 'Warner Bros. Interactive Entertainment', 2007, 'Wii'),
('Madagascar: Escape 2 Africa', 'Action', 'Activision', 2008, 'Wii'),
('MadWorld', 'Action', 'Sega', 2009, 'Wii'),
('Man vs. Wild', 'Action', 'Crave Entertainment', 2011, 'Wii'),
('Manhunt 2', 'Action', 'Take-Two Interactive', 2007, 'Wii'),
('Marvel Super Hero Squad: Comic Combat', 'Action', 'THQ', 2011, 'Wii'),
('Marvel Super Hero Squad: The Infinity Gauntlet', 'Action', 'THQ', 2010, 'Wii'),
('Marvel Superheroes 3D: Grandmaster\'s Challenge', 'Action', 'Neko Entertainment', 2010, 'Wii'),
('Medieval Games', 'Action', 'Vir2L Studios', 2009, 'Wii'),
('Mercury Meltdown Revolution', 'Action', 'Ignition Entertainment', 2007, 'Wii'),
('Metroid: Other M', 'Action', 'Nintendo', 2010, 'Wii'),
('Mini Ninjas', 'Action', 'Eidos Interactive', 2009, 'Wii'),
('Monster High: New Ghoul in School', 'Action', 'Little Orbit', 2015, 'Wii'),
('Monsters vs. Aliens', 'Action', 'Activision', 2009, 'Wii'),
('Mushroom Men: The Spore Wars', 'Action', 'SouthPeak Games', 2008, 'Wii'),
('MySims SkyHeroes', 'Action', 'Electronic Arts', 2010, 'Wii'),
('Naruto Shippuden: Dragon Blade Chronicles', 'Action', '505 Games', 2009, 'Wii'),
('NBA 2K11', 'Action', 'Take-Two Interactive', 2010, 'Wii'),
('Need for Speed: The Run', 'Action', 'Electronic Arts', 2011, 'Wii'),
('Night at the Museum: Battle of the Smithsonian', 'Action', 'Majesco Entertainment', 2009, 'Wii'),
('Ninja Reflex', 'Action', 'Electronic Arts', 2008, 'Wii'),
('Ninjabread Man', 'Action', 'Popcorn Arcade', 2007, 'Wii'),
('No More Heroes', 'Action', 'Rising Star Games', 2007, 'Wii'),
('No More Heroes 2: Desperate Struggle', 'Action', 'Rising Star Games', 2010, 'Wii'),
('Obscure: The Aftermath', 'Action', 'Playlogic Game Factory', 2008, 'Wii'),
('Okami', 'Action', 'Capcom', 2008, 'Wii'),
('One Piece Unlimited Cruise 2: Awakening of a Hero', 'Action', 'Namco Bandai Games', 2009, 'Wii'),
('Onechanbara: Bikini Zombie Slayers', 'Action', 'D3Publisher', 2008, 'Wii'),
('Overlord: Dark Legend', 'Action', 'Codemasters', 2009, 'Wii'),
('Pacific Liberator', 'Action', 'Zoo Games', 2009, 'Wii'),
('Penguins of Madagascar', 'Action', 'Namco Bandai Games', 2014, 'Wii'),
('Phineas and Ferb: Across the 2nd Dimension', 'Action', 'Disney Interactive Studios', 2011, 'Wii'),
('Pirates of the Caribbean: At World\'s End', 'Action', 'Disney Interactive Studios', 2007, 'Wii'),
('Pirates PlundArrr', 'Action', 'Majesco Entertainment', 2010, 'Wii'),
('Planet 51', 'Action', 'Sega', 2009, 'Wii'),
('Playmobil Circus', 'Action', 'Mindscape', 2009, 'Wii'),
('PokePark 2: Wonders Beyond', 'Action', 'Nintendo', 2011, 'Wii'),
('Power Rangers Samurai', 'Action', 'Namco Bandai Games', 2011, 'Wii'),
('Prince of Persia: Rival Swords', 'Action', 'Ubisoft', 2007, 'Wii'),
('Prince of Persia: The Forgotten Sands', 'Action', 'Ubisoft', 2010, 'Wii'),
('Pro Evolution Soccer 2012', 'Action', 'Konami Digital Entertainment', 2011, 'Wii'),
('Puss in Boots', 'Action', 'THQ', 2011, 'Wii'),
('Rampage: Total Destruction', 'Action', 'Midway Games', 2006, 'Wii'),
('Rango: The Video Game', 'Action', 'Electronic Arts', 2011, 'Wii'),
('Ratatouille', 'Action', 'THQ', 2007, 'Wii'),
('Real Heroes: Firefighter', 'Action', 'Rondomedia', 2009, 'Wii'),
('Resident Evil 4', 'Action', 'Capcom', 2007, 'Wii'),
('Resident Evil Archives: Resident Evil', 'Action', 'Capcom', 2008, 'Wii'),
('Resident Evil Archives: Resident Evil Zero', 'Action', 'Capcom', 2008, 'Wii'),
('Resident Evil: The Darkside Chronicles', 'Action', 'Capcom', 2009, 'Wii'),
('Resident Evil: The Umbrella Chronicles', 'Action', 'Capcom', 2007, 'Wii'),
('Ringling Bros. and Barnum & Bailey Circus', 'Action', 'Take-Two Interactive', 2009, 'Wii'),
('Rudolph the Red-Nosed Reindeer', 'Action', 'Crave Entertainment', 2010, 'Wii'),
('Rygar: The Battle of Argus', 'Action', 'Rising Star Games', 2008, 'Wii'),
('Samurai Warriors 3', 'Action', 'Nintendo', 2009, 'Wii'),
('Samurai Warriors: Katana', 'Action', 'Tecmo Koei', 2007, 'Wii'),
('Scarface: The World is Yours', 'Action', 'Vivendi Games', 2007, 'Wii'),
('Scooby-Doo! and the Spooky Swamp', 'Action', 'Warner Bros. Interactive Entertainment', 2010, 'Wii'),
('Scooby-Doo! First Frights', 'Action', 'Warner Bros. Interactive Entertainment', 2009, 'Wii'),
('Sengoku Basara 2 Heroes', 'Action', 'Capcom', 2007, 'Wii'),
('Sengoku Basara 3 Utage', 'Action', 'Capcom', 2011, 'Wii'),
('Sengoku Basara: Samurai Heroes', 'Action', 'Capcom', 2010, 'Wii'),
('Sengoku Musou 3: Moushouden', 'Action', 'Ackkstudios', 2011, 'Wii'),
('Shin Chan: Las Nuevas Aventuras Para Wii!', 'Action', '505 Games', 2006, 'Wii'),
('Shrek the Third', 'Action', 'Activision', 2007, 'Wii'),
('Silent Hill: Shattered Memories', 'Action', 'Konami Digital Entertainment', 2009, 'Wii'),
('Skylanders Giants', 'Action', 'Activision', 2012, 'Wii'),
('Skylanders: Spyro\'s Adventure', 'Action', 'Activision', 2011, 'Wii'),
('Skylanders: SuperChargers', 'Action', 'Activision', 2015, 'Wii'),
('Skylanders: Trap Team', 'Action', 'Activision', 2014, 'Wii'),
('Soul Eater: Monotone Princess', 'Action', 'Square Enix', 2008, 'Wii'),
('SoulCalibur Legends', 'Action', 'Namco Bandai Games', 2007, 'Wii'),
('SoulCalibur Legends (JP sales)', 'Action', 'Namco Bandai Games', 2007, 'Wii'),
('Space Camp', 'Action', 'Activision', 2009, 'Wii'),
('Spider-Man: Edge of Time', 'Action', 'Activision', 2011, 'Wii'),
('Spider-Man: Friend or Foe', 'Action', 'Activision', 2007, 'Wii'),
('Spider-Man: Shattered Dimensions', 'Action', 'Activision', 2010, 'Wii'),
('Spider-Man: Web of Shadows', 'Action', 'Activision', 2008, 'Wii'),
('SpongeBob SquarePants featuring Nicktoons: Globs of Doom', 'Action', 'THQ', 2008, 'Wii'),
('SpongeBob\'s Atlantis SquarePantis', 'Action', 'THQ', 2007, 'Wii'),
('SpongeBob\'s Truth or Square (US sales)', 'Action', 'THQ', 2009, 'Wii'),
('SPRay', 'Action', 'Tecmo Koei', 2008, 'Wii'),
('Spyborgs', 'Action', 'Capcom', 2009, 'Wii'),
('Star Wars The Clone Wars: Lightsaber Duels', 'Action', 'LucasArts', 2008, 'Wii'),
('Star Wars The Clone Wars: Republic Heroes', 'Action', 'LucasArts', 2009, 'Wii'),
('Star Wars: The Force Unleashed', 'Action', 'LucasArts', 2008, 'Wii'),
('Star Wars: The Force Unleashed II', 'Action', 'LucasArts', 2010, 'Wii'),
('Super Monkey Ball: Step & Roll', 'Action', 'Sega', 2010, 'Wii'),
('Super Sentai Battle: Ranger Cross', 'Action', 'Namco Bandai Games', 2011, 'Wii'),
('Tak and the Guardians of Gross', 'Action', 'THQ', 2008, 'Wii'),
('Teenage Mutant Ninja Turtles', 'Action', 'Konami Digital Entertainment', 2007, 'Wii'),
('Tenchu: Shadow Assassins', 'Action', 'Ubisoft', 2008, 'Wii'),
('The Adventures of Tintin: The Game', 'Action', 'Ubisoft', 2011, 'Wii'),
('The Amazing Spider-Man (Console Version)', 'Action', 'Activision', 2012, 'Wii'),
('The Chronicles of Narnia: Prince Caspian', 'Action', 'Disney Interactive Studios', 2008, 'Wii'),
('The Cube', 'Action', 'Funbox Media', 2012, 'Wii'),
('The Destiny of Zorro', 'Action', '505 Games', 2009, 'Wii'),
('The Grim Adventures of Billy & Mandy', 'Action', 'Midway Games', 2006, 'Wii'),
('The Incredible Hulk', 'Action', 'Sega', 2008, 'Wii'),
('The Last Airbender', 'Action', 'THQ', 2010, 'Wii'),
('The Legend of Zelda: Skyward Sword', 'Action', 'Nintendo', 2011, 'Wii'),
('The Legend of Zelda: Twilight Princess', 'Action', 'Nintendo', 2006, 'Wii'),
('The Lord of the Rings: Aragorn\'s Quest', 'Action', 'Warner Bros. Interactive Entertainment', 2010, 'Wii'),
('The Mummy: Tomb of the Dragon Emperor', 'Action', 'Vivendi Games', 2008, 'Wii'),
('The Munchables', 'Action', 'Namco Bandai Games', 2009, 'Wii'),
('The Penguins of Madagascar: Dr. Blowhole Returns - Again!', 'Action', 'THQ', 2011, 'Wii'),
('The Secret Saturdays: Beasts of the 5th Sun', 'Action', 'D3Publisher', 2009, 'Wii'),
('The Simpsons Game', 'Action', 'Electronic Arts', 2007, 'Wii'),
('The Spiderwick Chronicles', 'Action', 'Vivendi Games', 2008, 'Wii'),
('Thor: God of Thunder', 'Action', 'Sega', 2011, 'Wii'),
('TMNT', 'Action', 'Ubisoft', 2007, 'Wii'),
('Tom Clancy\'s HAWX 2', 'Action', 'Ubisoft', 2010, 'Wii'),
('Tom Clancy\'s Splinter Cell: Double Agent', 'Action', 'Ubisoft', 2006, 'Wii'),
('Tomb Raider: Anniversary', 'Action', 'Eidos Interactive', 2007, 'Wii'),
('Tomb Raider: Underworld', 'Action', 'Eidos Interactive', 2008, 'Wii'),
('Top Spin 3', 'Action', 'Take-Two Interactive', 2008, 'Wii'),
('Tornado Outbreak', 'Action', 'Konami Digital Entertainment', 2009, 'Wii'),
('Toy Story 3: The Video Game', 'Action', 'Disney Interactive Studios', 2010, 'Wii'),
('Transformers: Cybertron Adventures', 'Action', 'Activision', 2010, 'Wii'),
('Transformers: Dark of the Moon', 'Action', 'Activision', 2011, 'Wii'),
('Transformers: Prime', 'Action', 'Activision', 2012, 'Wii'),
('Transformers: The Game (XBox 360, PS2, PS3, Wii & PC Versions)', 'Action', 'Activision', 2007, 'Wii'),
('Up', 'Action', 'THQ', 2009, 'Wii'),
('Water Sports', 'Action', 'Avanquest', 2009, 'Wii'),
('We Wish You A Merry Christmas', 'Action', 'Destineer', 2009, 'Wii'),
('WipeOut 3 The Game', 'Action', 'Activision', 2012, 'Wii'),
('WWE \'13', 'Action', 'THQ', 2012, 'Wii'),
('X-Men Origins: Wolverine', 'Action', 'Activision', 2009, 'Wii'),
('X-Men: Destiny', 'Action', 'Activision', 2011, 'Wii'),
('Yogi Bear: The Video Game', 'Action', 'D3Publisher', 2010, 'Wii'),
('Young Justice: Legacy', 'Action', 'Namco Bandai Games', 2013, 'Wii'),
('Zangeki no Reginleiv', 'Action', 'Nintendo', 2010, 'Wii'),
('428: Fuusa Sareta Shibuya de', 'Adventure', 'Sega', 2008, 'Wii'),
('Agatha Christie: And Then There Were None', 'Adventure', 'The Adventure Company', 2008, 'Wii'),
('Agatha Christie: Evil Under the Sun', 'Adventure', 'The Adventure Company', 2008, 'Wii'),
('Alice in Wonderland', 'Adventure', 'Disney Interactive Studios', 2010, 'Wii'),
('Alone in the Dark', 'Adventure', 'Atari', 2008, 'Wii'),
('Animal Kingdom: Wildlife Expedition', 'Adventure', 'Natsume', 2009, 'Wii'),
('Another Code R: A Journey into Lost Memories', 'Adventure', 'Nintendo', 2009, 'Wii'),
('Arctic Tale', 'Adventure', 'Zoo Digital Publishing', 2007, 'Wii'),
('Avatar: The Last Airbender', 'Adventure', 'THQ', 2006, 'Wii'),
('Avatar: The Last Airbender - Into the Inferno', 'Adventure', 'THQ', 2008, 'Wii'),
('Back to the Future: The Game', 'Adventure', 'Telltale Games', 2011, 'Wii'),
('Barbie and the Three Musketeers', 'Adventure', 'Activision', 2009, 'Wii'),
('Barbie as The Island Princess', 'Adventure', 'Activision', 2007, 'Wii'),
('Bolt', 'Adventure', 'Disney Interactive Studios', 2008, 'Wii'),
('Broken Sword: Shadow of the Templars - The Director\'s Cut', 'Adventure', 'Ubisoft', 2009, 'Wii'),
('Calling', 'Adventure', 'Konami Digital Entertainment', 2009, 'Wii'),
('Captain Morgane and the Golden Turtle', 'Adventure', 'Reef Entertainment', 2012, 'Wii'),
('Captain Rainbow', 'Adventure', 'Nintendo', 2008, 'Wii'),
('Case Closed: One Truth Prevails', 'Adventure', 'Nobilis', 2007, 'Wii'),
('Cate West: The Vanishing Files', 'Adventure', 'Oxygen Interactive', 2009, 'Wii'),
('CSI: Deadly Intent', 'Adventure', 'Ubisoft', 2009, 'Wii'),
('CSI: Fatal Conspiracy', 'Adventure', 'Ubisoft', 2010, 'Wii'),
('CSI: Hard Evidence', 'Adventure', 'Ubisoft', 2008, 'Wii'),
('Cursed Mountain', 'Adventure', 'Deep Silver', 2009, 'Wii'),
('Disney Princess: Enchanted Journey', 'Adventure', 'Disney Interactive Studios', 2007, 'Wii'),
('Doctor Who: Return to Earth', 'Adventure', 'Asylum Entertainment', 2010, 'Wii'),
('Dragon\'s Lair Trilogy', 'Adventure', 'Destineer', 2010, 'Wii'),
('Endless Ocean', 'Adventure', 'Nintendo', 2007, 'Wii'),
('Escape The Museum', 'Adventure', 'Majesco Entertainment', 2009, 'Wii'),
('Freddi Fish: Kelp Seed Mystery', 'Adventure', 'Majesco Entertainment', 2008, 'Wii'),
('Fullmetal Alchemist: Prince of the Dawn', 'Adventure', 'Square Enix', 2009, 'Wii'),
('Goosebumps HorrorLand', 'Adventure', 'Scholastic Inc.', 2008, 'Wii'),
('Gormiti: The Lords of Nature!', 'Adventure', 'Konami Digital Entertainment', 2010, 'Wii'),
('Grey\'s Anatomy: The Video Game', 'Adventure', 'Ubisoft', 2009, 'Wii'),
('Hannah Montana: The Movie', 'Adventure', 'Disney Interactive Studios', 2009, 'Wii'),
('Harvey Birdman: Attorney at Law', 'Adventure', 'Capcom', 2008, 'Wii'),
('Hello Kitty Seasons', 'Adventure', 'Namco Bandai Games', 2010, 'Wii'),
('Hidden Mysteries: Titanic - Secrets of the Fateful Voyage', 'Adventure', 'GSP', 2009, 'Wii'),
('Horrid Henry: Missions of Mischief', 'Adventure', 'SouthPeak Games', 2010, 'Wii'),
('How to Train Your Dragon 2', 'Adventure', 'Little Orbit', 2014, 'Wii'),
('iCarly', 'Adventure', 'Activision', 2009, 'Wii'),
('iCarly 2: iJoin The Click!', 'Adventure', 'Activision', 2010, 'Wii'),
('Igor: The Game', 'Adventure', 'CDV Software Entertainment', 2008, 'Wii'),
('JumpStart: Escape from Adventure Island', 'Adventure', 'Knowledge Adventure', 2009, 'Wii'),
('Lost in Blue: Shipwrecked', 'Adventure', 'Konami Digital Entertainment', 2008, 'Wii'),
('Martian Panic', 'Adventure', 'Unknown', 2010, 'Wii'),
('Megamind: Mega Team Unite', 'Adventure', 'THQ', 2010, 'Wii'),
('Mr Bean\'s Wacky World of Wii', 'Adventure', 'Blast! Entertainment Ltd', 2009, 'Wii'),
('MySims Agents', 'Adventure', 'Electronic Arts', 2009, 'Wii'),
('Mystery Case Files: The Malgrave Incident', 'Adventure', 'Nintendo', 2011, 'Wii'),
('Nancy Drew: The White Wolf of Icicle Creek', 'Adventure', 'Sega', 2008, 'Wii'),
('NCIS', 'Adventure', 'Ubisoft', 2011, 'Wii'),
('One Piece Unlimited Cruise 1: The Treasure Beneath the Waves', 'Adventure', 'Namco Bandai Games', 2008, 'Wii'),
('One Piece: Unlimited Adventure', 'Adventure', 'Namco Bandai Games', 2007, 'Wii'),
('Pajama Sam: Don\'t Fear The Dark', 'Adventure', 'Atari', 2008, 'Wii'),
('Pippa Funnell: Ranch Rescue', 'Adventure', 'Ubisoft', 2007, 'Wii'),
('Pirates: Hunt For Blackbeard\'s Booty', 'Adventure', 'Activision', 2008, 'Wii'),
('Pitfall: The Big Adventure', 'Adventure', 'Activision', 2008, 'Wii'),
('PokéPark Wii: Pikachu\'s Adventure', 'Adventure', 'Nintendo', 2009, 'Wii'),
('Princess Isabella: A Witch\'s Curse', 'Adventure', 'Destineer', 2010, 'Wii'),
('Raving Rabbids: Travel in Time', 'Adventure', 'Ubisoft', 2010, 'Wii'),
('Rooms: The Main Building', 'Adventure', 'Hudson Soft', 2010, 'Wii'),
('Safari Adventures: Africa', 'Adventure', 'Neko Entertainment', 2007, 'Wii'),
('Sam & Max: Beyond Time and Space', 'Adventure', 'Atari', 2010, 'Wii'),
('Sam & Max: Season One', 'Adventure', 'JoWood Productions', 2008, 'Wii'),
('Sea Monsters: A Prehistoric Adventure', 'Adventure', 'Zushi Games', 2007, 'Wii'),
('Secret Files 2: Puritas Cordis', 'Adventure', 'Deep Silver', 2009, 'Wii'),
('Secret Files: Tunguska', 'Adventure', 'Koch Media', 2008, 'Wii'),
('Sherlock Holmes: Secret of The Silver Earring', 'Adventure', 'Focus Home Interactive', 2010, 'Wii'),
('Spy Fox in Dry Cereal', 'Adventure', 'Majesco Entertainment', 2008, 'Wii'),
('Story Hour: Adventures', 'Adventure', 'Zoo Digital Publishing', 2008, 'Wii'),
('Story Hour: Fairy Tales', 'Adventure', 'Zoo Digital Publishing', 2008, 'Wii'),
('Survivor', 'Adventure', 'Valcon Games', 2010, 'Wii'),
('Suzumiya Haruhi no Gekidou', 'Adventure', 'Kadokawa Shoten', 2009, 'Wii'),
('Suzumiya Haruhi no Heiretsu', 'Adventure', 'Sega', 2009, 'Wii'),
('The Dog Island', 'Adventure', 'Ubisoft', 2007, 'Wii'),
('The Godfather: Blackhand Edition', 'Adventure', 'Electronic Arts', 2007, 'Wii'),
('The Hardy Boys: The Hidden Theft', 'Adventure', 'The Adventure Company', 2009, 'Wii'),
('The Island of Dr. Frankenstein', 'Adventure', 'Storm City Games', 2009, 'Wii'),
('Ultimate I Spy', 'Adventure', 'Scholastic Inc.', 2008, 'Wii'),
('Where\'s Waldo? The Fantastic Journey', 'Adventure', 'Ubisoft', 2009, 'Wii'),
('Wii de Asobu Chibi-Robo!', 'Adventure', 'Nintendo', 2009, 'Wii'),
('Zack & Wiki: Quest for Barbaros\' Treasure', 'Adventure', 'Nintendo', 2007, 'Wii'),
('Bleach: Shattered Blade', 'Fighting', 'Sega', 2006, 'Wii'),
('Bleach: Versus Crusade', 'Fighting', 'Sega', 2008, 'Wii'),
('Cartoon Network: Punch Time Explosion XL', 'Fighting', 'Crave Entertainment', 2011, 'Wii'),
('Castlevania Judgment', 'Fighting', 'Konami Digital Entertainment', 2008, 'Wii'),
('Daikaijuu Battle: Ultra Coliseum', 'Fighting', 'Namco Bandai Games', 2008, 'Wii'),
('Daikaijuu Battle: Ultra Coliseum DX - Ultra Senshi Daishuuketsu', 'Fighting', 'Namco Bandai Games', 2010, 'Wii'),
('Dragon Ball Z: Budokai Tenkaichi 2', 'Fighting', 'Atari', 2006, 'Wii'),
('Dragon Ball Z: Budokai Tenkaichi 3', 'Fighting', 'Atari', 2007, 'Wii'),
('FaceBreaker K.O. Party', 'Fighting', 'Electronic Arts', 2008, 'Wii'),
('Godzilla Unleashed', 'Fighting', 'Atari', 2007, 'Wii'),
('Guilty Gear XX Accent Core', 'Fighting', '505 Games', 2007, 'Wii'),
('Guilty Gear XX Accent Core Plus', 'Fighting', 'PQube', 2009, 'Wii'),
('Kamen Rider: Dragon Knight', 'Fighting', 'D3Publisher', 2009, 'Wii'),
('Katekyoo Hitman Reborn! Dream Hyper Battle! Wii', 'Fighting', 'Marvelous Interactive', 2008, 'Wii'),
('Legend of the Dragon', 'Fighting', 'Game Factory', 2007, 'Wii'),
('Mahou Sensei Negima!? Neo-Pactio Fight!!', 'Fighting', 'Marvelous Interactive', 2007, 'Wii'),
('Marvel Super Hero Squad', 'Fighting', 'THQ', 2009, 'Wii'),
('Mortal Kombat: Armageddon', 'Fighting', 'Midway Games', 2007, 'Wii'),
('Naruto Shippuden: Clash of Ninja Revolution 3', 'Fighting', 'Nintendo', 2009, 'Wii'),
('Naruto Shippuden: Gekito Ninja Taisen! EX', 'Fighting', 'Takara Tomy', 2007, 'Wii'),
('Naruto Shippuden: Gekito Ninja Taisen! EX 2', 'Fighting', 'Takara Tomy', 2007, 'Wii'),
('Naruto Shippuden: Gekito Ninja Taisen! EX 3', 'Fighting', 'Takara Tomy', 2008, 'Wii'),
('Naruto Shippuden: Gekito Ninja Taisen! Special', 'Fighting', 'Takara Tomy', 2010, 'Wii'),
('Naruto: Clash of Ninja Revolution', 'Fighting', 'Tomy Corporation', 2007, 'Wii'),
('Naruto: Clash of Ninja Revolution 2', 'Fighting', 'Tomy Corporation', 2008, 'Wii'),
('Samurai Shodown Anthology', 'Fighting', 'Ignition Entertainment', 2008, 'Wii'),
('Showtime Championship Boxing', 'Fighting', 'Zoo Digital Publishing', 2007, 'Wii'),
('Super Smash Bros. Brawl', 'Fighting', 'Nintendo', 2008, 'Wii'),
('Tatsunoko vs. Capcom: Cross Generation of Heroes', 'Fighting', 'Capcom', 2008, 'Wii'),
('Tatsunoko vs. Capcom: Ultimate All-Stars', 'Fighting', 'Capcom', 2010, 'Wii'),
('Teenage Mutant Ninja Turtles: Smash-Up', 'Fighting', 'Ubisoft', 2009, 'Wii'),
('The King of Fighters Collection: The Orochi Saga', 'Fighting', 'Ignition Entertainment', 2008, 'Wii'),
('TNA iMPACT!', 'Fighting', 'Midway Games', 2008, 'Wii'),
('Tournament of Legends', 'Fighting', 'Sega', 2010, 'Wii'),
('Victorious Boxers: Revolution', 'Fighting', 'Ubisoft', 2007, 'Wii'),
('WWE \'12', 'Fighting', 'THQ', 2011, 'Wii'),
('WWE All Stars', 'Fighting', 'THQ', 2011, 'Wii'),
('WWE SmackDown vs Raw 2008', 'Fighting', 'THQ', 2007, 'Wii'),
('WWE SmackDown vs. Raw 2009', 'Fighting', 'THQ', 2008, 'Wii'),
('WWE SmackDown vs. Raw 2010', 'Fighting', 'THQ', 2009, 'Wii'),
('WWE SmackDown vs. Raw 2011', 'Fighting', 'THQ', 2010, 'Wii'),
('101-in-1 Party Megamix Wii', 'Misc', 'Nordcurrent', 2009, 'Wii'),
('ABBA: You Can Dance', 'Misc', 'Ubisoft', 2011, 'Wii'),
('AC/DC LIVE: Rock Band Track Pack', 'Misc', 'MTV Games', 2008, 'Wii'),
('Active Life: Magical Carnival', 'Misc', 'Namco Bandai Games', 2011, 'Wii'),
('Alvin and the Chipmunks', 'Misc', 'Eidos Interactive', 2007, 'Wii'),
('Alvin and the Chipmunks: Chipwrecked', 'Misc', '505 Games', 2011, 'Wii'),
('Alvin and the Chipmunks: The Squeakquel', 'Misc', 'Majesco Entertainment', 2009, 'Wii'),
('Arcade Zone', 'Misc', 'Activision', 2009, 'Wii'),
('Are You Smarter Than a 5th Grader? Back to School', 'Misc', 'Nintendo', 2010, 'Wii'),
('Are You Smarter than a 5th Grader? Make the Grade', 'Misc', 'THQ', 2008, 'Wii'),
('Band Hero', 'Misc', 'Activision', 2009, 'Wii'),
('Barbie: Jet, Set & Style!', 'Misc', 'THQ', 2011, 'Wii'),
('Beastly', 'Misc', 'Unknown', 2011, 'Wii'),
('Big Brain Academy: Wii Degree', 'Misc', 'Nintendo', 2007, 'Wii'),
('Big Family Games', 'Misc', 'THQ', 2009, 'Wii'),
('Birthday Party Bash', 'Misc', 'Take-Two Interactive', 2009, 'Wii'),
('BIT.TRIP COMPLETE', 'Misc', 'Rising Star Games', 2011, 'Wii'),
('Block Party', 'Misc', 'Activision', 2008, 'Wii'),
('Bomberman Land', 'Misc', 'Rising Star Games', 2007, 'Wii'),
('Boogie', 'Misc', 'Electronic Arts', 2007, 'Wii'),
('Boogie SuperStar', 'Misc', 'Electronic Arts', 2008, 'Wii'),
('Bratz Kidz', 'Misc', 'Game Factory', 2008, 'Wii'),
('Cabela\'s Adventure Camp', 'Misc', 'Activision', 2011, 'Wii'),
('Calvin Tucker\'s Redneck Jamboree', 'Misc', 'Zoo Games', 2008, 'Wii'),
('Carnival Games', 'Misc', 'Take-Two Interactive', 2007, 'Wii'),
('Cars Toon: Mater\'s Tall Tales', 'Misc', 'Disney Interactive Studios', 2010, 'Wii'),
('Charm Girls Club: Pajama Party', 'Misc', 'Electronic Arts', 2009, 'Wii'),
('Chuck E. Cheese\'s Party Games', 'Misc', 'UFO Interactive', 2010, 'Wii'),
('City Builder', 'Misc', 'Virtual Play Games', 2010, 'Wii'),
('Cold Stone Creamery: Scoop It Up', 'Misc', 'Zoo Games', 2009, 'Wii'),
('Cook Wars', 'Misc', 'Ubisoft', 2009, 'Wii'),
('Cosmic Family', 'Misc', 'Ubisoft', 2007, 'Wii'),
('Country Dance', 'Misc', 'Funbox Media', 2011, 'Wii'),
('Country Dance 2', 'Misc', 'GameMill Entertainment', 2011, 'Wii'),
('Cranium Kabookii', 'Misc', 'Ubisoft', 2007, 'Wii'),
('Crayola: Colorful Journey', 'Misc', 'Crave Entertainment', 2009, 'Wii'),
('Dance Dance Revolution: Hottest Party 5', 'Misc', 'Konami Digital Entertainment', 2011, 'Wii'),
('Dance on Broadway', 'Misc', 'Ubisoft', 2010, 'Wii'),
('Dance Party: Pop Hits', 'Misc', 'Nordic Games', 2009, 'Wii'),
('Dance Sensation!', 'Misc', 'Majesco Entertainment', 2010, 'Wii'),
('Dancing With The Stars', 'Misc', 'Activision', 2007, 'Wii'),
('Dancing with the Stars: We Dance!', 'Misc', 'Activision', 2008, 'Wii'),
('Data East Arcade Classics', 'Misc', 'Majesco Entertainment', 2010, 'Wii'),
('Deal or No Deal', 'Misc', 'Zoo Games', 2009, 'Wii'),
('Deepak Chopra\'s Leela', 'Misc', 'THQ', 2011, 'Wii'),
('Def Jam Rapstar', 'Misc', 'Konami Digital Entertainment', 2010, 'Wii'),
('Disney Channel: All Star Party', 'Misc', 'Disney Interactive Studios', 2010, 'Wii'),
('Disney Guilty Party', 'Misc', 'Disney Interactive Studios', 2010, 'Wii'),
('Disney Princess: Enchanting Storybooks', 'Misc', 'THQ', 2011, 'Wii'),
('Disney Sing It', 'Misc', 'Disney Interactive Studios', 2008, 'Wii'),
('Disney Sing It! High School Musical 3: Senior Year', 'Misc', 'Disney Interactive Studios', 2008, 'Wii'),
('Disney Sing It: Family Hits', 'Misc', 'Disney Interactive Studios', 2010, 'Wii'),
('Disney Sing It: Party Hits', 'Misc', 'Disney Interactive Studios', 2010, 'Wii'),
('Disney Sing It: Pop Hits', 'Misc', 'Disney Interactive Studios', 2009, 'Wii'),
('Disney TH!NK Fast: The Ultimate Trivia Showdown', 'Misc', 'Disney Interactive Studios', 2008, 'Wii'),
('DJ Hero', 'Misc', 'Activision', 2009, 'Wii'),
('DJ Hero 2', 'Misc', 'Activision', 2010, 'Wii'),
('Dora the Explorer: Dora Saves the Crystal Kingdom', 'Misc', 'Take-Two Interactive', 2009, 'Wii'),
('Dora\'s Big Birthday Adventure', 'Misc', 'Take-Two Interactive', 2010, 'Wii'),
('Doraemon Wii: Himitsu Douguou Ketteisen!', 'Misc', 'Sega', 2007, 'Wii'),
('Dream Dance & Cheer', 'Misc', 'Zoo Games', 2009, 'Wii'),
('Dream Pinball 3D', 'Misc', 'SouthPeak Games', 2008, 'Wii'),
('Dream Salon', 'Misc', 'Zoo Games', 2009, 'Wii'),
('Ennichi no Tatsujin', 'Misc', 'Namco Bandai Games', 2006, 'Wii'),
('Family Fest Presents Circus Games', 'Misc', 'Ubisoft', 2008, 'Wii'),
('Family Feud Decades', 'Misc', 'Ubisoft', 2010, 'Wii'),
('Family Feud: 2010 Edition', 'Misc', 'Ubisoft', 2009, 'Wii'),
('Family Feud: 2012 Edition', 'Misc', 'Ubisoft', 2011, 'Wii'),
('Family Fortunes', 'Misc', 'Mindscape', 2009, 'Wii'),
('Family Game Night 4: The Game Show', 'Misc', 'Electronic Arts', 2011, 'Wii'),
('Family GameShow', 'Misc', 'Zushi Games', 2009, 'Wii'),
('Family Party: 30 Great Games', 'Misc', 'D3Publisher', 2008, 'Wii'),
('Family Party: 30 Great Games Outdoor Fun', 'Misc', 'D3Publisher', 2009, 'Wii'),
('Family Party: 90 Great Games Party Pack', 'Misc', 'D3Publisher', 2010, 'Wii'),
('Fishing Master', 'Misc', 'Konami Digital Entertainment', 2007, 'Wii'),
('Food Network: Cook or Be Cooked', 'Misc', 'Namco Bandai Games', 2009, 'Wii'),
('Fortune Street', 'Misc', 'Nintendo', 2011, 'Wii'),
('Furu Furu Park', 'Misc', 'Taito', 2007, 'Wii'),
('Game Party', 'Misc', 'Midway Games', 2007, 'Wii'),
('Game Party 2', 'Misc', 'Midway Games', 2008, 'Wii'),
('Get Up and Dance', 'Misc', 'O-Games', 2011, 'Wii'),
('Go Vacation', 'Misc', 'Namco Bandai Games', 2011, 'Wii'),
('Grease', 'Misc', '505 Games', 2010, 'Wii'),
('Great Party Games', 'Misc', 'O-Games', 2010, 'Wii'),
('Green Day: Rock Band', 'Misc', 'MTV Games', 2010, 'Wii'),
('Guitar Hero 5', 'Misc', 'Activision', 2009, 'Wii'),
('Guitar Hero III: Legends of Rock', 'Misc', 'Activision', 2007, 'Wii'),
('Guitar Hero: Aerosmith', 'Misc', 'Activision', 2008, 'Wii'),
('Guitar Hero: Metallica', 'Misc', 'Activision', 2009, 'Wii'),
('Guitar Hero: Smash Hits', 'Misc', 'Activision', 2009, 'Wii'),
('Guitar Hero: Van Halen', 'Misc', 'Activision', 2009, 'Wii'),
('Guitar Hero: Warriors of Rock', 'Misc', 'Activision', 2010, 'Wii'),
('Guitar Hero: World Tour', 'Misc', 'Activision', 2008, 'Wii'),
('Haneru no Tobira Wii: Girigirissu', 'Misc', 'Namco Bandai Games', 2007, 'Wii'),
('Happy Dance Collection', 'Misc', 'Namco Bandai Games', 2008, 'Wii'),
('Hasbro Family Game Night 2', 'Misc', 'Electronic Arts', 2009, 'Wii'),
('Hasbro Family Game Night 3', 'Misc', 'Electronic Arts', 2010, 'Wii'),
('Hasbro Family Game Night Fun Pack', 'Misc', 'Electronic Arts', 2011, 'Wii'),
('High School Musical 3: Senior Year DANCE!', 'Misc', 'Disney Interactive Studios', 2008, 'Wii'),
('High School Musical: Sing It!', 'Misc', 'Disney Interactive Studios', 2007, 'Wii'),
('Hollywood Squares', 'Misc', 'Ubisoft', 2010, 'Wii'),
('I\'m A Celebrity: Get Me Out of Here!', 'Misc', 'Mindscape', 2009, 'Wii'),
('Jenga World Tour', 'Misc', 'Atari', 2007, 'Wii'),
('Jeopardy!', 'Misc', 'THQ', 2010, 'Wii'),
('Jinsei Game Wii', 'Misc', 'Takara Tomy', 2007, 'Wii'),
('Jump Start Pet Rescue', 'Misc', 'Knowledge Adventure', 2009, 'Wii'),
('Just Dance', 'Misc', 'Ubisoft', 2009, 'Wii'),
('Just Dance 2', 'Misc', 'Ubisoft', 2010, 'Wii'),
('Just Dance 2014', 'Misc', 'Ubisoft', 2013, 'Wii'),
('Just Dance 2015', 'Misc', 'Ubisoft', 2014, 'Wii'),
('Just Dance 2016', 'Misc', 'Ubisoft', 2015, 'Wii'),
('Just Dance 2: Extra Songs', 'Misc', 'Ubisoft', 2011, 'Wii'),
('Just Dance 3', 'Misc', 'Ubisoft', 2011, 'Wii'),
('Just Dance 4', 'Misc', 'Ubisoft', 2012, 'Wii'),
('Just Dance Kids', 'Misc', 'Ubisoft', 2010, 'Wii'),
('Just Dance Kids 2', 'Misc', 'Ubisoft', 2011, 'Wii'),
('Just Dance Wii', 'Misc', 'Nintendo', 2011, 'Wii'),
('Just Dance Wii 2', 'Misc', 'Nintendo', 2012, 'Wii'),
('Just Dance: Disney Party', 'Misc', 'Ubisoft', 2012, 'Wii'),
('Just Dance: Greatest Hits', 'Misc', 'Ubisoft', 2012, 'Wii'),
('Just Dance: Summer Party', 'Misc', 'Ubisoft', 2011, 'Wii'),
('Karaoke Joysound Wii', 'Misc', 'Hudson Soft', 2008, 'Wii'),
('Karaoke Joysound Wii DX', 'Misc', 'Hudson Soft', 2009, 'Wii'),
('Karaoke Joysound Wii Super DX: Hitori de Minna de Utai Houdai!', 'Misc', 'Hudson Soft', 2010, 'Wii'),
('Karaoke Revolution', 'Misc', 'Konami Digital Entertainment', 2009, 'Wii'),
('Karaoke Revolution Glee', 'Misc', 'Konami Digital Entertainment', 2010, 'Wii'),
('Karaoke Revolution Glee 2: Road to Regionals', 'Misc', 'Konami Digital Entertainment', 2011, 'Wii'),
('Karaoke Revolution Glee: Volume 3', 'Misc', 'Konami Digital Entertainment', 2011, 'Wii'),
('Karaoke Revolution Presents American Idol Encore', 'Misc', 'Konami Digital Entertainment', 2008, 'Wii'),
('Karaoke Revolution Presents American Idol Encore 2', 'Misc', 'Konami Digital Entertainment', 2008, 'Wii'),
('Kidz Bop Dance Party! The Video Game', 'Misc', 'D3Publisher', 2010, 'Wii'),
('LEGO Rock Band', 'Misc', 'Warner Bros. Interactive Entertainment', 2009, 'Wii'),
('Let\'s TAP', 'Misc', 'Sega', 2008, 'Wii'),
('M&M\'s Beach Party', 'Misc', 'Zoo Digital Publishing', 2009, 'Wii'),
('Major Minor\'s Majestic March', 'Misc', 'Majesco Entertainment', 2009, 'Wii'),
('Mario Party 8', 'Misc', 'Nintendo', 2007, 'Wii'),
('Mario Party 9', 'Misc', 'Nintendo', 2012, 'Wii'),
('Michael Jackson: The Experience', 'Misc', 'Ubisoft', 2010, 'Wii'),
('Minna ga Shuyaku no NHK Kouhaku Quiz Kassen', 'Misc', 'Nintendo', 2009, 'Wii'),
('Minna no Joushiki Ryoku TV', 'Misc', 'Nintendo', 2008, 'Wii'),
('Minute to Win It', 'Misc', 'Zoo Games', 2010, 'Wii'),
('Momotarou Dentetsu 16', 'Misc', 'Hudson Soft', 2007, 'Wii'),
('Momu-chan Diet Wii: Figurobics by Chon Dayon', 'Misc', 'Hudson Soft', 2010, 'Wii'),
('Monkey Mischief! Party Time', 'Misc', 'Activision', 2008, 'Wii'),
('Monopoly', 'Misc', 'Electronic Arts', 2008, 'Wii'),
('Monopoly Collection', 'Misc', 'Electronic Arts', 2011, 'Wii'),
('Monopoly Streets', 'Misc', 'Electronic Arts', 2010, 'Wii'),
('Monotaro Dentetsu 2010: Sengoku Ishin no Hero Daishuugou! no Maki', 'Misc', 'Hudson Soft', 2009, 'Wii'),
('Monster High: Ghoul Spirit', 'Misc', 'THQ', 2011, 'Wii'),
('My First Songs', 'Misc', 'Mindscape', 2010, 'Wii'),
('My Word Coach', 'Misc', 'Ubisoft', 2007, 'Wii'),
('MySims Collection', 'Misc', 'Electronic Arts', 2010, 'Wii'),
('Namco Museum Megamix', 'Misc', 'Namco Bandai Games', 2010, 'Wii'),
('Namco Museum Remix', 'Misc', 'Atari', 2007, 'Wii'),
('NatGeo Challenge! Wild Life', 'Misc', 'Black Bean Games', 2010, 'Wii'),
('National Geographic Challenge!', 'Misc', 'Black Bean Games', 2011, 'Wii'),
('Neighborhood Games', 'Misc', 'THQ', 2009, 'Wii'),
('New Carnival Games', 'Misc', 'Take-Two Interactive', 2010, 'Wii'),
('Ni Hao, Kai-lan: Super Game Day', 'Misc', 'Take-Two Interactive', 2009, 'Wii'),
('Nickelodeon Dance', 'Misc', 'Take-Two Interactive', 2011, 'Wii'),
('Now! That\'s What I Call Music: Dance & Sing', 'Misc', 'Unknown', 2011, 'Wii'),
('Order Up!', 'Misc', 'Zoo Digital Publishing', 2008, 'Wii'),
('Pac-Man Party', 'Misc', 'Namco Bandai Games', 2010, 'Wii'),
('Party Pigs: Farmyard Games', 'Misc', 'Data Design Interactive', 2009, 'Wii'),
('Peppa Pig: Fun and Games', 'Misc', 'Ubisoft', 2010, 'Wii'),
('Peppa Pig: The Game', 'Misc', 'Pinnacle', 2009, 'Wii'),
('Petz: Horse Club', 'Misc', 'Ubisoft', 2008, 'Wii'),
('Pinball Hall of Fame: The Gottlieb Collection', 'Misc', 'System 3 Arcade Software', 2006, 'Wii'),
('Pinball Hall of Fame: The Williams Collection', 'Misc', 'System 3 Arcade Software', 2008, 'Wii'),
('Pop\'n Music', 'Misc', 'Konami Digital Entertainment', 2009, 'Wii'),
('PopStar Guitar', 'Misc', 'Midway Games', 2008, 'Wii'),
('Press Your Luck 2010 Edition', 'Misc', 'Ubisoft', 2009, 'Wii'),
('Pretty Cure All Stars Everyone Gather ? Let\'s Dance!', 'Misc', 'Namco Bandai Games', 2013, 'Wii'),
('QUIZ PARTY', 'Misc', 'Nintendo', 2012, 'Wii'),
('Rabbids Party Collection', 'Misc', 'Ubisoft', 2010, 'Wii'),
('Rayman Raving Rabbids', 'Misc', 'Ubisoft', 2006, 'Wii'),
('Rayman Raving Rabbids 2', 'Misc', 'Ubisoft', 2007, 'Wii'),
('Rayman Raving Rabbids: TV Party', 'Misc', 'Ubisoft', 2008, 'Wii'),
('Reader Rabbit 1st Grade', 'Misc', 'Graffiti', 2010, 'Wii'),
('Reader Rabbit Kindergarten', 'Misc', 'Graffiti', 2010, 'Wii'),
('Rio', 'Misc', 'THQ', 2011, 'Wii'),
('Rock Band 2', 'Misc', 'MTV Games', 2008, 'Wii'),
('Rock Band 3', 'Misc', 'MTV Games', 2010, 'Wii'),
('Rock Band Country Track Pack', 'Misc', 'MTV Games', 2009, 'Wii'),
('Rock Band Country Track Pack 2', 'Misc', 'MTV Games', 2011, 'Wii'),
('Rock Band Track Pack Volume 1', 'Misc', 'MTV Games', 2008, 'Wii'),
('Rock Band Track Pack Volume 2', 'Misc', 'MTV Games', 2008, 'Wii'),
('Rock Band Track Pack: Classic Rock', 'Misc', 'MTV Games', 2009, 'Wii'),
('Rock Band: Metal Track Pack', 'Misc', 'MTV Games', 2009, 'Wii'),
('Rolling Stone: Drum King', 'Misc', '505 Games', 2009, 'Wii'),
('Samba De Amigo', 'Misc', 'Sega', 2008, 'Wii'),
('Satisfashion', 'Misc', 'Destineer', 2010, 'Wii'),
('Scene It? Bright Lights! Big Screen!', 'Misc', 'Warner Bros. Interactive Entertainment', 2009, 'Wii'),
('Scene It? Twilight', 'Misc', 'Konami Digital Entertainment', 2009, 'Wii'),
('Schlag den Raab', 'Misc', 'Namco Bandai Games', 2010, 'Wii'),
('Science Papa', 'Misc', 'Activision', 2009, 'Wii'),
('Sesame Street: Cookie\'s Counting Carnival', 'Misc', 'Warner Bros. Interactive Entertainment', 2010, 'Wii'),
('Sesame Street: Elmo\'s A-to-Zoo Adventure', 'Misc', 'Warner Bros. Interactive Entertainment', 2010, 'Wii'),
('Sesame Street: Ready, Set, Grover!', 'Misc', 'Warner Bros. Interactive Entertainment', 2011, 'Wii'),
('Shrek\'s Carnival Craze Party Games', 'Misc', 'Activision', 2008, 'Wii'),
('Sing4: The Hits Edition', 'Misc', 'Crave Entertainment', 2011, 'Wii'),
('Six Flags Fun Park', 'Misc', 'Ubisoft', 2009, 'Wii'),
('Sleepover Party', 'Misc', 'Ubisoft', 2009, 'Wii'),
('Smarty Pants', 'Misc', 'Electronic Arts', 2007, 'Wii'),
('SNK Arcade Classics Vol. 1', 'Misc', 'Ignition Entertainment', 2008, 'Wii'),
('SpongeBob SquigglePants', 'Misc', 'THQ', 2011, 'Wii'),
('SpongeBob\'s Boating Bash', 'Misc', 'THQ', 2010, 'Wii'),
('Storybook Workshop', 'Misc', 'Konami Digital Entertainment', 2009, 'Wii'),
('Super Monkey Ball: Banana Blitz', 'Misc', 'Sega', 2006, 'Wii'),
('Taiko no Tatsujin Wii', 'Misc', 'Namco Bandai Games', 2008, 'Wii'),
('Taiko no Tatsujin Wii: Dodon to 2 Yome!', 'Misc', 'Namco Bandai Games', 2009, 'Wii'),
('Taiko no Tatsujin Wii: Ketteiban', 'Misc', 'Namco Bandai Games', 2011, 'Wii'),
('Taiko no Tatsujin Wii: Minna de Party * 3-Yome!', 'Misc', 'Namco Bandai Games', 2010, 'Wii'),
('Tamagotchi Party On!', 'Misc', 'Namco Bandai Games', 2006, 'Wii'),
('Team Elimination Games', 'Misc', 'Ubisoft', 2009, 'Wii'),
('The $1 Pyramid', 'Misc', 'Ubisoft', 2011, 'Wii'),
('The Amazing Race', 'Misc', 'Ubisoft', 2010, 'Wii'),
('The Bachelor: The Videogame', 'Misc', 'Warner Bros. Interactive Entertainment', 2010, 'Wii'),
('The Beatles: Rock Band', 'Misc', 'MTV Games', 2009, 'Wii'),
('The Black Eyed Peas Experience', 'Misc', 'Ubisoft', 2011, 'Wii'),
('The Croods: Prehistoric Party!', 'Misc', 'D3Publisher', 2013, 'Wii'),
('The Naked Brothers Band: The Video Game', 'Misc', 'THQ', 2008, 'Wii'),
('The Price is Right', 'Misc', 'Ubisoft', 2008, 'Wii'),
('The Price is Right 2010 Edition', 'Misc', 'Ubisoft', 2009, 'Wii'),
('The Price is Right: Decades', 'Misc', 'Ubisoft', 2011, 'Wii'),
('The Smurfs: Dance Party', 'Misc', 'Ubisoft', 2011, 'Wii'),
('The Ultimate Battle of the Sexes', 'Misc', 'DTP Entertainment', 2010, 'Wii'),
('The Ultimate Red Ball Challenge', 'Misc', 'Mindscape', 2009, 'Wii'),
('The X-Factor', 'Misc', 'Deep Silver', 2010, 'Wii'),
('thinkSMART FAMILY!', 'Misc', 'Conspiracy Entertainment', 2010, 'Wii'),
('Thomas & Friends: Hero of the Rails', 'Misc', 'Unknown', 2010, 'Wii'),
('Totally Spies! Totally Party', 'Misc', 'Ubisoft', 2008, 'Wii'),
('Toy Story Mania!', 'Misc', 'Disney Interactive Studios', 2009, 'Wii'),
('Trivial Pursuit', 'Misc', 'Electronic Arts', 2009, 'Wii'),
('Trivial Pursuit: Bet You Know It', 'Misc', 'Electronic Arts', 2011, 'Wii'),
('Truth or Lies', 'Misc', 'THQ', 2010, 'Wii'),
('TV Total Events', 'Misc', '7G//AMES', 2011, 'Wii'),
('U-Sing', 'Misc', 'Mindscape', 2009, 'Wii'),
('U-Sing  2', 'Misc', 'Mindscape', 2010, 'Wii'),
('U-Sing: Girls Night', 'Misc', 'Mindscape', 2010, 'Wii'),
('uDraw Studio', 'Misc', 'THQ', 2010, 'Wii'),
('uDraw Studio: Instant Artist', 'Misc', 'THQ', 2011, 'Wii'),
('Ultimate Band', 'Misc', 'Disney Interactive Studios', 2008, 'Wii'),
('Ultimate Board Game Collection', 'Misc', 'Xplosiv', 2007, 'Wii'),
('Ultimate Party Challenge', 'Misc', 'Konami Digital Entertainment', 2009, 'Wii'),
('Vacation Isle: Beach Party', 'Misc', 'Warner Bros. Interactive Entertainment', 2010, 'Wii'),
('We Dance', 'Misc', 'Nordic Games', 2011, 'Wii'),
('We Sing', 'Misc', 'Nordic Games', 2009, 'Wii'),
('We Sing 80s', 'Misc', 'Nordic Games', 2012, 'Wii'),
('We Sing Deutsche Hits', 'Misc', 'Nordic Games', 2011, 'Wii'),
('We Sing Encore', 'Misc', 'Nordic Games', 2010, 'Wii'),
('We Sing Pop!', 'Misc', 'Nordic Games', 2012, 'Wii'),
('We Sing Robbie Williams', 'Misc', 'Nordic Games', 2010, 'Wii'),
('We Sing Rock!', 'Misc', 'Nordic Games', 2011, 'Wii'),
('We Sing UK Hits', 'Misc', 'Nordic Games', 2011, 'Wii'),
('Wheel of Fortune', 'Misc', 'THQ', 2010, 'Wii'),
('Who Wants to be a Millionaire: 1st Edition', 'Misc', 'Ubisoft', 2007, 'Wii'),
('Who Wants to be a Millionaire: 2nd Edition', 'Misc', 'Ubisoft', 2008, 'Wii'),
('Who Wants to Be a Millionaire: 3rd Edition', 'Misc', 'Ubisoft', 2010, 'Wii'),
('Wii Music', 'Misc', 'Nintendo', 2008, 'Wii'),
('Wii Party', 'Misc', 'Nintendo', 2010, 'Wii'),
('Wii Play', 'Misc', 'Nintendo', 2006, 'Wii'),
('Wii Play: Motion', 'Misc', 'Nintendo', 2011, 'Wii'),
('Wipeout 2', 'Misc', 'Activision', 2011, 'Wii'),
('Wipeout: The Game', 'Misc', 'Mindscape', 2009, 'Wii'),
('Wonder World Amusement Park', 'Misc', 'Majesco Entertainment', 2008, 'Wii'),
('World Championship Poker featuring Howard Lederer: All In', 'Misc', '505 Games', 2006, 'Wii'),
('World Party Games', 'Misc', '505 Games', 2009, 'Wii'),
('World Series of Poker: Tournament of Champions 2007 Edition', 'Misc', 'Activision', 2006, 'Wii'),
('You Don\'t Know Jack', 'Misc', 'THQ', 2011, 'Wii'),
('Zumba Fitness Core', 'Misc', '505 Games', 2012, 'Wii'),
('Zumba Fitness: World Party', 'Misc', 'Majesco Entertainment', 2013, 'Wii'),
('A Boy and His Blob', 'Platform', 'Majesco Entertainment', 2009, 'Wii'),
('Anubis II', 'Platform', 'Metro 3D', 2007, 'Wii'),
('Ben 10 Ultimate Alien: Cosmic Destruction', 'Platform', 'D3Publisher', 2010, 'Wii'),
('CID The Dummy', 'Platform', 'Oxygen Interactive', 2009, 'Wii'),
('Cloudy With a Chance of Meatballs', 'Platform', 'Ubisoft', 2009, 'Wii'),
('Crash: Mind Over Mutant', 'Platform', 'Vivendi Games', 2008, 'Wii'),
('de Blob', 'Platform', 'THQ', 2008, 'Wii'),
('de Blob 2', 'Platform', 'THQ', 2011, 'Wii'),
('Death Jr.: Root of Evil', 'Platform', 'Eidos Interactive', 2008, 'Wii'),
('Despicable Me: The Game', 'Platform', 'D3Publisher', 2010, 'Wii'),
('Dewy\'s Adventure', 'Platform', 'Konami Digital Entertainment', 2007, 'Wii'),
('Donkey Kong Country Returns', 'Platform', 'Nintendo', 2010, 'Wii'),
('Donkey Kong Jungle Beat', 'Platform', 'Nintendo', 2008, 'Wii'),
('Dood\'s Big Adventure', 'Platform', 'THQ', 2010, 'Wii'),
('Dora The Explorer: Dora Saves the Snow Princess', 'Platform', 'Take-Two Interactive', 2008, 'Wii'),
('Epic Mickey', 'Platform', 'Disney Interactive Studios', 2010, 'Wii'),
('Gem Smashers', 'Platform', 'Crave Entertainment', 2011, 'Wii'),
('George of the Jungle and the Search for the Secret', 'Platform', 'Ignition Entertainment', 2008, 'Wii'),
('Gummy Bears Magical Medallion', 'Platform', 'Storm City Games', 2011, 'Wii'),
('Ice Age 2: The Meltdown', 'Platform', 'Vivendi Games', 2006, 'Wii'),
('Kirby\'s Epic Yarn', 'Platform', 'Nintendo', 2010, 'Wii'),
('Kirby\'s Return to Dreamland', 'Platform', 'Nintendo', 2011, 'Wii'),
('Klonoa', 'Platform', 'Namco Bandai Games', 2008, 'Wii'),
('Lost in Shadow', 'Platform', 'Konami Digital Entertainment', 2010, 'Wii'),
('Max & the Magic Marker', 'Platform', 'Unknown', 2011, 'Wii'),
('Myth Makers: Trixie in Toyland', 'Platform', 'Popcorn Arcade', 2008, 'Wii'),
('New Play Control! Donkey Kong Jungle Beat', 'Platform', 'Nintendo', 2008, 'Wii'),
('New Super Mario Bros. Wii', 'Platform', 'Nintendo', 2009, 'Wii'),
('Nicktoons: Attack of the Toybots', 'Platform', 'THQ', 2007, 'Wii'),
('NiGHTS: Journey of Dreams', 'Platform', 'Sega', 2007, 'Wii'),
('Open Season', 'Platform', 'Ubisoft', 2006, 'Wii'),
('Rabbids Go Home', 'Platform', 'Ubisoft', 2009, 'Wii'),
('Rayman Origins', 'Platform', 'Ubisoft', 2011, 'Wii'),
('Rock \'N\' Roll Adventures', 'Platform', 'Popcorn Arcade', 2007, 'Wii'),
('Shrek: Forever After', 'Platform', 'Activision', 2010, 'Wii'),
('Skylanders SWAP Force', 'Platform', 'Activision', 2013, 'Wii'),
('Sonic and the Black Knight', 'Platform', 'Sega', 2009, 'Wii'),
('Sonic and the Secret Rings', 'Platform', 'Sega', 2007, 'Wii'),
('Sonic Colors', 'Platform', 'Sega', 2010, 'Wii'),
('Sonic Unleashed', 'Platform', 'Sega', 2008, 'Wii'),
('Space Chimps', 'Platform', 'Brash Entertainment', 2008, 'Wii'),
('Spider-Man 3', 'Platform', 'Activision', 2007, 'Wii'),
('SpongeBob SquarePants: Creature from the Krusty Krab', 'Platform', 'THQ', 2006, 'Wii'),
('Super Mario All-Stars: Limited Edition', 'Platform', 'Nintendo', 2010, 'Wii'),
('Super Mario Galaxy', 'Platform', 'Nintendo', 2007, 'Wii'),
('Super Mario Galaxy 2', 'Platform', 'Nintendo', 2010, 'Wii'),
('Super Paper Mario', 'Platform', 'Nintendo', 2007, 'Wii'),
('The Ant Bully', 'Platform', 'Midway Games', 2006, 'Wii'),
('The Kore Gang', 'Platform', 'Flashpoint Games', 2010, 'Wii'),
('The Legend of Spyro: Dawn of the Dragon', 'Platform', 'Vivendi Games', 2008, 'Wii'),
('The Legend of Spyro: The Eternal Night', 'Platform', 'Vivendi Games', 2007, 'Wii'),
('The Princess and the Frog', 'Platform', 'Disney Interactive Studios', 2009, 'Wii'),
('The Smurfs 2', 'Platform', 'Ubisoft', 2013, 'Wii'),
('The Tale of Despereaux', 'Platform', 'Brash Entertainment', 2008, 'Wii'),
('Wall-E', 'Platform', 'THQ', 2008, 'Wii'),
('Wario Land: Shake It!', 'Platform', 'Nintendo', 2008, 'Wii'),
('Where the Wild Things Are', 'Platform', 'Warner Bros. Interactive Entertainment', 2009, 'Wii'),
('Are You Smarter than a 5th Grader? Game Time', 'Puzzle', 'THQ', 2009, 'Wii'),
('Balloon Pop', 'Puzzle', '505 Games', 2007, 'Wii'),
('Bomberman', 'Puzzle', 'Hudson Entertainment', 2008, 'Wii'),
('Boom Blox', 'Puzzle', 'Electronic Arts', 2008, 'Wii'),
('Boom Blox Bash Party', 'Puzzle', 'Electronic Arts', 2009, 'Wii'),
('Bust-A-Move Bash!', 'Puzzle', '505 Games', 2007, 'Wii'),
('Cake Mania: In The Mix!', 'Puzzle', 'Majesco Entertainment', 2008, 'Wii'),
('Challenge Me: Brain Puzzles 2', 'Puzzle', 'O-Games', 2010, 'Wii'),
('Countdown: The Game', 'Puzzle', 'Mindscape', 2009, 'Wii'),
('Crazy Machines', 'Puzzle', 'DTP Entertainment', 2010, 'Wii'),
('Cruise Ship Vacation Games', 'Puzzle', 'Avanquest', 2009, 'Wii'),
('Drawn to Life: The Next Chapter', 'Puzzle', 'THQ', 2009, 'Wii'),
('Game Party 3', 'Puzzle', 'Warner Bros. Interactive Entertainment', 2009, 'Wii'),
('Geon Cube', 'Puzzle', 'P2 Games', 2009, 'Wii'),
('Groovin\' Blocks', 'Puzzle', 'Zoo Games', 2009, 'Wii'),
('Hamster Heroes', 'Puzzle', 'Popcorn Arcade', 2008, 'Wii'),
('Hasbro Family Game Night', 'Puzzle', 'Electronic Arts', 2008, 'Wii'),
('I Spy: Spooky Mansion', 'Puzzle', 'Storm City Games', 2010, 'Wii'),
('Ivy the Kiwi?', 'Puzzle', 'Rising Star Games', 2010, 'Wii'),
('Jelly Belly: Ballistic Beans', 'Puzzle', 'Zoo Digital Publishing', 2009, 'Wii'),
('Jewel Master: Cradle of Rome', 'Puzzle', 'Rondomedia', 2008, 'Wii'),
('Kororinpa: Marble Mania', 'Puzzle', 'Nintendo', 2006, 'Wii'),
('Line Rider 2: Unbound', 'Puzzle', 'Deep Silver', 2008, 'Wii'),
('Luxor 3', 'Puzzle', 'Mumbo Jumbo', 2008, 'Wii'),
('Marble Saga: Kororinpa', 'Puzzle', 'Konami Digital Entertainment', 2009, 'Wii'),
('Margot\'s Word Brain', 'Puzzle', 'Zoo Digital Publishing', 2008, 'Wii'),
('Merv Griffin\'s Crosswords', 'Puzzle', 'THQ', 2008, 'Wii'),
('Mortimer Beckett and the Secrets of Spooky Manor', 'Puzzle', 'Avanquest', 2008, 'Wii'),
('Myth Makers: Orbs of Doom', 'Puzzle', 'Popcorn Arcade', 2007, 'Wii'),
('Neopets Puzzle Adventure', 'Puzzle', 'Capcom', 2008, 'Wii'),
('Octomania', 'Puzzle', 'Midas Interactive Entertainment', 2007, 'Wii'),
('Pictionary', 'Puzzle', 'THQ', 2010, 'Wii'),
('Professor Heinz Wolff\'s Gravity', 'Puzzle', 'Deep Silver', 2008, 'Wii'),
('Puyo Puyo 7', 'Puzzle', 'Sega', 2009, 'Wii'),
('Puzzle Challenge: Crosswords and More!', 'Puzzle', 'Crave Entertainment', 2009, 'Wii'),
('Puzzle Kingdoms', 'Puzzle', 'Zoo Digital Publishing', 2009, 'Wii'),
('Puzzle Quest: Challenge of the Warlords', 'Puzzle', 'D3Publisher', 2007, 'Wii'),
('Puzzler Brain Games', 'Puzzle', 'Namco Bandai Games', 2012, 'Wii'),
('Puzzler Collection', 'Puzzle', 'Ubisoft', 2008, 'Wii'),
('Rock Blast', 'Puzzle', 'UFO Interactive', 2010, 'Wii'),
('Roogoo Twisted Towers', 'Puzzle', 'SouthPeak Games', 2009, 'Wii'),
('Rubik\'s World', 'Puzzle', 'Game Factory', 2008, 'Wii'),
('SafeCracker: The Ultimate Puzzle Adventure', 'Puzzle', 'The Adventure Company', 2008, 'Wii'),
('Santa Claus Is Comin\' to Town!', 'Puzzle', 'Crave Entertainment', 2011, 'Wii'),
('Solitaire & Mahjong', 'Puzzle', 'Crave Entertainment', 2009, 'Wii'),
('Squeeballs Party', 'Puzzle', 'Performance Designed Products', 2009, 'Wii'),
('Sudoku Ball Detective', 'Puzzle', 'Playlogic Game Factory', 2009, 'Wii'),
('Super Fruit Fall', 'Puzzle', 'System 3 Arcade Software', 2006, 'Wii'),
('Tetris Party Deluxe', 'Puzzle', 'Nintendo', 2010, 'Wii'),
('th!nk Logic Trainer', 'Puzzle', 'Conspiracy Entertainment', 2009, 'Wii'),
('Titanic Mystery', 'Puzzle', 'O-Games', 2010, 'Wii'),
('TV Show King Party', 'Puzzle', 'Ubisoft', 2008, 'Wii'),
('WarioWare: Smooth Moves', 'Puzzle', 'Nintendo', 2006, 'Wii'),
('WordJong Party', 'Puzzle', 'Destineer', 2008, 'Wii'),
('Aladdin Magic Racer', 'Racing', 'Big Ben Interactive', 2011, 'Wii'),
('ATV Quad Kings', 'Racing', 'Zoo Digital Publishing', 2009, 'Wii'),
('Ben 10 Galactic Racing', 'Racing', 'D3Publisher', 2011, 'Wii'),
('Bigfoot King of Crush', 'Racing', 'Zoo Games', 2011, 'Wii'),
('Bigfoot: Collision Course', 'Racing', 'Zoo Digital Publishing', 2008, 'Wii'),
('Billy the Wizard: Rocket Broomstick Racing', 'Racing', 'Metro 3D', 2007, 'Wii'),
('Build \'n Race', 'Racing', 'Zoo Games', 2009, 'Wii'),
('Cars', 'Racing', 'THQ', 2006, 'Wii'),
('Cars 2', 'Racing', 'Disney Interactive Studios', 2011, 'Wii'),
('Cars Mater-National Championship', 'Racing', 'THQ', 2007, 'Wii'),
('Cars: Race-O-Rama', 'Racing', 'THQ', 2009, 'Wii'),
('Chevrolet Camaro: Wild Ride', 'Racing', 'Storm City Games', 2010, 'Wii'),
('Chrysler Classic Racing', 'Racing', 'Zoo Games', 2008, 'Wii'),
('Cocoto Kart Racer', 'Racing', 'Conspiracy Entertainment', 2008, 'Wii'),
('Cruis\'n', 'Racing', 'Midway Games', 2007, 'Wii'),
('DiRT 2', 'Racing', 'Codemasters', 2009, 'Wii'),
('Dodge Racing: Charger vs Challenger', 'Racing', 'Zushi Games', 2009, 'Wii'),
('Donkey Kong Barrel Blast', 'Racing', 'Nintendo', 2007, 'Wii'),
('Dreamworks Madagascar Kartz', 'Racing', 'Activision', 2009, 'Wii'),
('DreamWorks Super Star Kartz', 'Racing', 'Activision', 2011, 'Wii'),
('Driver: Parallel Lines', 'Racing', 'Ubisoft', 2007, 'Wii'),
('Driver: San Francisco', 'Racing', 'Ubisoft', 2011, 'Wii'),
('Emergency Heroes', 'Racing', 'Ubisoft', 2008, 'Wii'),
('Emergency Mayhem', 'Racing', 'Codemasters', 2008, 'Wii'),
('Excite Truck', 'Racing', 'Nintendo', 2006, 'Wii'),
('ExciteBots: Trick Racing', 'Racing', 'Nintendo', 2009, 'Wii'),
('F1 2009', 'Racing', 'Codemasters', 2009, 'Wii'),
('Ferrari Challenge Trofeo Pirelli Deluxe', 'Racing', 'System 3 Arcade Software', 2009, 'Wii'),
('Ford Racing Off Road', 'Racing', 'Xplosiv', 2008, 'Wii'),
('Glacier2', 'Racing', 'Zoo Games', 2009, 'Wii'),
('GT Pro Series', 'Racing', 'Ubisoft', 2006, 'Wii'),
('GTI Club: Supermini Festa!', 'Racing', 'Konami Digital Entertainment', 2010, 'Wii'),
('Harley-Davidson: Road Trip', 'Racing', 'Destineer', 2010, 'Wii'),
('Heathcliff! The Fast and the Furriest', 'Racing', 'Storm City Games', 2010, 'Wii'),
('Honda ATV Fever', 'Racing', 'Storm City Games', 2010, 'Wii'),
('Hot Wheels: Battle Force 5', 'Racing', 'Activision', 2009, 'Wii'),
('Hot Wheels: Beat That!', 'Racing', 'Activision', 2007, 'Wii'),
('Hot Wheels: Track Attack', 'Racing', 'THQ', 2010, 'Wii'),
('Indianapolis 500 Legends', 'Racing', 'Destineer', 2007, 'Wii'),
('Jeep Thrills', 'Racing', 'Zoo Digital Publishing', 2008, 'Wii'),
('Jimmie Johnson\'s Anything With an Engine', 'Racing', 'Konami Digital Entertainment', 2011, 'Wii'),
('Kart Racer', 'Racing', 'Nordic Games', 2009, 'Wii'),
('Kawasaki Jet Ski', 'Racing', 'Metro 3D', 2008, 'Wii'),
('Kawasaki Quad Bikes', 'Racing', 'Data Design Interactive', 2007, 'Wii'),
('Kawasaki Snowmobiles', 'Racing', 'Metro 3D', 2008, 'Wii'),
('M&M\'s Kart Racing', 'Racing', 'Zoo Digital Publishing', 2007, 'Wii'),
('Mario Kart Wii', 'Racing', 'Nintendo', 2008, 'Wii'),
('Maximum Racing: Crash Car Racer', 'Racing', 'Nordic Games', 2010, 'Wii'),
('Maximum Racing: Drag & Stock Racer', 'Racing', 'Nordic Games', 2010, 'Wii'),
('Maximum Racing: GP Classic Racing', 'Racing', 'Nordic Games', 2010, 'Wii'),
('Mini Desktop Racing', 'Racing', 'Popcorn Arcade', 2007, 'Wii'),
('Monster 4x4: Stunt Racer', 'Racing', 'Ubisoft', 2009, 'Wii'),
('Monster 4X4: World Circuit', 'Racing', 'Ubisoft', 2006, 'Wii'),
('Monster Jam', 'Racing', 'Activision', 2007, 'Wii'),
('Monster Jam: Path of Destruction', 'Racing', 'Activision', 2010, 'Wii'),
('Monster Jam: Urban Assault', 'Racing', 'Activision', 2008, 'Wii'),
('Monster Trucks Mayhem', 'Racing', 'Zoo Games', 2009, 'Wii'),
('Monster Trux Arenas: Special Edition', 'Racing', 'Popcorn Arcade', 2007, 'Wii'),
('Monster Trux Offroad', 'Racing', 'Popcorn Arcade', 2007, 'Wii'),
('MotoGP', 'Racing', 'Capcom', 2009, 'Wii'),
('MX vs. ATV Untamed', 'Racing', 'THQ', 2008, 'Wii'),
('MySims Racing', 'Racing', 'Electronic Arts', 2009, 'Wii'),
('Myth Makers: Super Kart GP', 'Racing', 'Popcorn Arcade', 2007, 'Wii'),
('NASCAR 2011: The Game', 'Racing', 'Activision', 2011, 'Wii'),
('NASCAR Kart Racing', 'Racing', 'Electronic Arts', 2009, 'Wii'),
('NASCAR Unleashed', 'Racing', 'Activision', 2011, 'Wii'),
('Need for Speed Carbon', 'Racing', 'Electronic Arts', 2006, 'Wii'),
('Need for Speed: Hot Pursuit', 'Racing', 'Electronic Arts', 2010, 'Wii'),
('Need for Speed: Nitro', 'Racing', 'Electronic Arts', 2009, 'Wii'),
('Need for Speed: ProStreet', 'Racing', 'Electronic Arts', 2007, 'Wii'),
('Need For Speed: Undercover', 'Racing', 'Electronic Arts', 2008, 'Wii'),
('Nitrobike', 'Racing', 'Ubisoft', 2008, 'Wii'),
('Penny Racers Party: Turbo-Q Speedway', 'Racing', 'Takara Tomy', 2008, 'Wii'),
('Pimp My Ride', 'Racing', 'Activision', 2008, 'Wii'),
('SCORE International Baja 1000: The Official Game', 'Racing', 'Activision', 2008, 'Wii'),
('Ski-Doo Snowmobile Challenge', 'Racing', 'Valcon Games', 2009, 'Wii'),
('Sonic & Sega All-Stars Racing', 'Racing', 'Sega', 2010, 'Wii'),
('Sonic Riders: Zero Gravity', 'Racing', 'Sega', 2008, 'Wii'),
('Speed', 'Racing', 'Unknown', 2010, 'Wii'),
('Speed Racer: The Videogame', 'Racing', 'Warner Bros. Interactive Entertainment', 2008, 'Wii'),
('Speed Zone', 'Racing', 'Bethesda Softworks', 2009, 'Wii'),
('Super PickUps', 'Racing', 'XS Games', 2009, 'Wii'),
('System 3 presents Ferrari Challenge Trofeo Pirelli', 'Racing', 'System 3 Arcade Software', 2008, 'Wii'),
('TrackMania: Build to Race', 'Racing', 'Focus Home Interactive', 2010, 'Wii'),
('TRON: Evolution - Battle Grids', 'Racing', 'Disney Interactive Studios', 2010, 'Wii'),
('Truck Racer', 'Racing', 'Nordic Games', 2009, 'Wii'),
('Turbo Trainz', 'Racing', 'Mastertronic', 2012, 'Wii'),
('Wacky Races: Crash & Dash', 'Racing', 'Eidos Interactive', 2008, 'Wii'),
('Yamaha Supercross', 'Racing', 'Zoo Digital Publishing', 2009, 'Wii'),
('Yattaman Wii: BikkuriDokkiri Machine de Mou Race da Koron', 'Racing', 'Takara Tomy', 2008, 'Wii'),
('Yu-Gi-Oh! 5D\'s Wheelie Breakers', 'Racing', 'Konami Digital Entertainment', 2009, 'Wii'),
('Zenkoku Dekotora Matsuri', 'Racing', 'Jaleco', 2008, 'Wii'),
('Alien Syndrome', 'Role-Playing', 'Sega', 2007, 'Wii'),
('Arc Rise Fantasia', 'Role-Playing', 'Marvelous Interactive', 2009, 'Wii'),
('Baroque', 'Role-Playing', 'Rising Star Games', 2008, 'Wii'),
('Dokapon Kingdom', 'Role-Playing', 'Sting', 2008, 'Wii'),
('Dragon Quest 25 Shuunen Kinin: Famicom & Super Famicom Dragon Quest I-II-III', 'Role-Playing', 'Square Enix', 2011, 'Wii'),
('Dragon Quest Swords: The Masked Queen and the Tower of Mirrors', 'Role-Playing', 'Square Enix', 2007, 'Wii'),
('Dragon Quest X', 'Role-Playing', 'Square Enix', 2012, 'Wii'),
('Earth Seeker', 'Role-Playing', 'Kadokawa Shoten', 2011, 'Wii'),
('Eyeshield 21: Field Saikyou no Senshi Tachi', 'Role-Playing', 'Nintendo', 2007, 'Wii'),
('Final Fantasy Crystal Chronicles: Echoes of Time', 'Role-Playing', 'Square Enix', 2009, 'Wii'),
('Final Fantasy Fables: Chocobo\'s Dungeon', 'Role-Playing', 'Square Enix', 2007, 'Wii'),
('Fragile Dreams: Farewell Ruins of the Moon', 'Role-Playing', 'Rising Star Games', 2009, 'Wii'),
('Inazuma Eleven GO Strikers 2013', 'Role-Playing', 'Level 5', 2012, 'Wii'),
('Inazuma Eleven Strikers', 'Role-Playing', 'Nintendo', 2011, 'Wii'),
('Inazuma Eleven Strikers 2012 Xtreme', 'Role-Playing', 'Level 5', 2011, 'Wii'),
('Marvel: Ultimate Alliance', 'Role-Playing', 'Activision', 2006, 'Wii'),
('Marvel: Ultimate Alliance 2', 'Role-Playing', 'Activision', 2009, 'Wii'),
('Monster Hunter G', 'Role-Playing', 'Capcom', 2009, 'Wii'),
('Monster Hunter Tri', 'Role-Playing', 'Nintendo', 2009, 'Wii'),
('Monster Lab', 'Role-Playing', 'Eidos Interactive', 2008, 'Wii'),
('Muramasa: The Demon Blade', 'Role-Playing', 'Rising Star Games', 2009, 'Wii'),
('Opoona', 'Role-Playing', 'Tecmo Koei', 2007, 'Wii'),
('Pandora\'s Tower', 'Role-Playing', 'Nintendo', 2011, 'Wii'),
('Phantom Brave: We Meet Again', 'Role-Playing', 'Nippon Ichi Software', 2009, 'Wii'),
('Pokemon Battle Revolution', 'Role-Playing', 'Nintendo', 2006, 'Wii'),
('Rune Factory: Frontier', 'Role-Playing', 'Rising Star Games', 2008, 'Wii'),
('Rune Factory: Tides of Destiny', 'Role-Playing', 'Marvelous Interactive', 2011, 'Wii'),
('Sakura Wars: So Long, My Love', 'Role-Playing', 'Ackkstudios', 2010, 'Wii'),
('Shiren the Wanderer', 'Role-Playing', 'Sega', 2008, 'Wii'),
('Spectrobes: Origins', 'Role-Playing', 'Disney Interactive Studios', 2009, 'Wii'),
('Tales of Graces', 'Role-Playing', 'Namco Bandai Games', 2009, 'Wii'),
('Tales of Symphonia: Dawn of the New World', 'Role-Playing', 'Namco Bandai Games', 2008, 'Wii'),
('The Last Story', 'Role-Playing', 'Nintendo', 2011, 'Wii'),
('Valhalla Knights: Eldar Saga', 'Role-Playing', 'Rising Star Games', 2009, 'Wii'),
('Xenoblade Chronicles', 'Role-Playing', 'Nintendo', 2010, 'Wii'),
('Arcade Shooting Gallery', 'Shooter', 'Zoo Games', 2008, 'Wii'),
('Army Men: Soldiers of Misfortune', 'Shooter', 'Zoo Games', 2008, 'Wii'),
('Army Rescue', 'Shooter', 'UFO Interactive', 2009, 'Wii'),
('Attack of the Movies 3D', 'Shooter', 'Majesco Entertainment', 2010, 'Wii'),
('Battle Rage', 'Shooter', 'Popcorn Arcade', 2008, 'Wii'),
('Bionicle Heroes', 'Shooter', 'Eidos Interactive', 2007, 'Wii'),
('Blast Works: Build, Trade, Destroy', 'Shooter', 'Eidos Interactive', 2008, 'Wii'),
('Brothers in Arms: Double Time', 'Shooter', 'Ubisoft', 2008, 'Wii'),
('Call of Duty: Black Ops', 'Shooter', 'Activision', 2010, 'Wii'),
('Call of Duty: Modern Warfare 3', 'Shooter', 'Activision', 2011, 'Wii'),
('Call of Duty: Modern Warfare: Reflex Edition', 'Shooter', 'Activision', 2009, 'Wii'),
('Call of Duty: World at War', 'Shooter', 'Activision', 2008, 'Wii'),
('Castle of Shikigami III', 'Shooter', 'PQube', 2007, 'Wii'),
('Centipede: Infestation', 'Shooter', 'Atari', 2011, 'Wii'),
('Chicken Blaster', 'Shooter', 'Zushi Games', 2009, 'Wii'),
('Cocoto Magic Circus', 'Shooter', 'Neko Entertainment', 2008, 'Wii'),
('Conduit 2', 'Shooter', 'Sega', 2011, 'Wii'),
('Counter Force', 'Shooter', '505 Games', 2007, 'Wii'),
('Dead Space Extraction', 'Shooter', 'Electronic Arts', 2009, 'Wii'),
('Far Cry Vengeance', 'Shooter', 'Ubisoft', 2006, 'Wii'),
('Geometry Wars: Galaxies', 'Shooter', 'Vivendi Games', 2007, 'Wii'),
('Ghost Squad', 'Shooter', 'Sega', 2007, 'Wii'),
('Greg Hastings Paintball 2', 'Shooter', '505 Games', 2010, 'Wii'),
('Gunblade NY & L.A. Machineguns Arcade Hits Pack', 'Shooter', 'Sega', 2010, 'Wii'),
('Gunslingers', 'Shooter', 'Neko Entertainment', 2010, 'Wii'),
('Heavenly Guardian', 'Shooter', '505 Games', 2007, 'Wii'),
('Heavy Fire: Afghanistan', 'Shooter', 'Mastiff', 2011, 'Wii'),
('Jurassic: The Hunted', 'Shooter', 'Activision', 2009, 'Wii'),
('Link\'s Crossbow Training', 'Shooter', 'Nintendo', 2007, 'Wii'),
('Mad Dog McCree: Gunslinger Pack', 'Shooter', 'Majesco Entertainment', 2009, 'Wii'),
('Marines: Modern Urban Combat', 'Shooter', 'O-Games', 2010, 'Wii'),
('Medal of Honor Heroes 2', 'Shooter', 'Electronic Arts', 2007, 'Wii'),
('Medal of Honor: Vanguard', 'Shooter', 'Electronic Arts', 2007, 'Wii'),
('Metal Slug Anthology', 'Shooter', 'Ignition Entertainment', 2006, 'Wii'),
('Metroid Prime 3: Corruption', 'Shooter', 'Nintendo', 2007, 'Wii'),
('Metroid Prime: Trilogy', 'Shooter', 'Nintendo', 2009, 'Wii'),
('NERF N-Strike', 'Shooter', 'Electronic Arts', 2008, 'Wii'),
('NERF N-Strike Elite', 'Shooter', 'Electronic Arts', 2009, 'Wii'),
('NERF N-Strike: Double Blast Bundle', 'Shooter', 'Electronic Arts', 2010, 'Wii'),
('NPPL: Championship Paintball 2009', 'Shooter', 'Activision Value', 2008, 'Wii'),
('Pheasants Forever Wingshooter', 'Shooter', 'Unknown', 2010, 'Wii'),
('Red Steel', 'Shooter', 'Ubisoft', 2006, 'Wii'),
('Red Steel 2', 'Shooter', 'Ubisoft', 2010, 'Wii'),
('Reload: Target Down', 'Shooter', 'Mastiff', 2010, 'Wii'),
('Rogue Trooper: Quartz Zone Massacre', 'Shooter', 'Reef Entertainment', 2009, 'Wii'),
('Sin and Punishment: Star Successor', 'Shooter', 'Nintendo', 2009, 'Wii'),
('Sniper Elite', 'Shooter', 'Reef Entertainment', 2010, 'Wii'),
('Spy Games: Elevator Mission', 'Shooter', 'Tommo', 2007, 'Wii'),
('Target: Terror', 'Shooter', 'Konami Digital Entertainment', 2008, 'Wii'),
('The Conduit', 'Shooter', 'Sega', 2009, 'Wii'),
('The History Channel: Battle for the Pacific', 'Shooter', 'Activision', 2007, 'Wii'),
('The House of the Dead 2 & 3 Return', 'Shooter', 'Sega', 2008, 'Wii'),
('The House of the Dead: Overkill', 'Shooter', 'Sega', 2009, 'Wii'),
('The Monkey King: The Legend Begins', 'Shooter', 'Starfish', 2007, 'Wii'),
('Tom Clancy\'s Ghost Recon', 'Shooter', 'Ubisoft', 2010, 'Wii'),
('Top Shot Arcade', 'Shooter', 'Activision', 2011, 'Wii'),
('Transformers: Revenge of the Fallen (XBox 360, PS3, & PC Versions)', 'Shooter', 'Activision', 2009, 'Wii'),
('Twin Strike: Operation Thunder', 'Shooter', 'Zoo Games', 2008, 'Wii'),
('Ultimate Shooting Collection', 'Shooter', 'Milestone', 2008, 'Wii'),
('Wicked Monster Blast!', 'Shooter', 'PQube', 2011, 'Wii'),
('Wild West Shootout', 'Shooter', 'Unknown', 2010, 'Wii'),
('Animal Crossing: City Folk', 'Simulation', 'Nintendo', 2008, 'Wii'),
('Animal Planet: Vet Life', 'Simulation', 'Activision', 2009, 'Wii'),
('Babysitting Mama', 'Simulation', '505 Games', 2010, 'Wii'),
('Blazing Angels: Squadrons of WWII', 'Simulation', 'Ubisoft', 2007, 'Wii'),
('Bratz: The Movie', 'Simulation', 'THQ', 2007, 'Wii'),
('Build-A-Bear Workshop: A Friend Fur All Seasons', 'Simulation', 'Game Factory', 2008, 'Wii'),
('Busy Scissors', 'Simulation', 'Little Orbit', 2010, 'Wii'),
('Cooking Mama: Cook Off', 'Simulation', '505 Games', 2007, 'Wii'),
('Cooking Mama: World Kitchen', 'Simulation', '505 Games', 2008, 'Wii'),
('Dance Dance Revolution: Disney Grooves', 'Simulation', 'Konami Digital Entertainment', 2009, 'Wii'),
('Dance Dance Revolution: Hottest Party', 'Simulation', 'Konami Digital Entertainment', 2007, 'Wii'),
('Dance Dance Revolution: Hottest Party 2', 'Simulation', 'Konami Digital Entertainment', 2008, 'Wii'),
('Dance Dance Revolution: Hottest Party 3', 'Simulation', 'Konami Digital Entertainment', 2009, 'Wii'),
('DanceDanceRevolution', 'Simulation', 'Konami Digital Entertainment', 2010, 'Wii'),
('Dawn of Discovery', 'Simulation', 'Ubisoft', 2009, 'Wii'),
('Densha de Go! Shinkansen EX: Sanyou Shinkansen-hen', 'Simulation', 'Taito', 2007, 'Wii'),
('Disney\'s Planes', 'Simulation', 'Disney Interactive Studios', 2013, 'Wii'),
('Endless Ocean: Blue World', 'Simulation', 'Nintendo', 2009, 'Wii'),
('Fantasy Aquarium World', 'Simulation', 'Destineer', 2009, 'Wii'),
('Fast Food Panic', 'Simulation', 'Nobilis', 2009, 'Wii'),
('Germany\'s Next Topmodel 2011', 'Simulation', '7G//AMES', 2011, 'Wii'),
('Go Play: Lumberjacks', 'Simulation', 'Majesco Entertainment', 2009, 'Wii'),
('Harvest Moon: Animal Parade', 'Simulation', 'Rising Star Games', 2008, 'Wii'),
('Harvest Moon: Magical Melody', 'Simulation', 'Rising Star Games', 2008, 'Wii'),
('Harvest Moon: Tree of Tranquility', 'Simulation', 'Rising Star Games', 2007, 'Wii'),
('Hell\'s Kitchen: The Game', 'Simulation', 'Ubisoft', 2008, 'Wii'),
('Help Wanted: 50 Wacky Jobs', 'Simulation', 'Hudson Soft', 2008, 'Wii'),
('Help Wanted: 50 Wacky Jobs (jp sales)', 'Simulation', 'Hudson Soft', 2008, 'Wii'),
('Horse Life Adventures', 'Simulation', 'Deep Silver', 2008, 'Wii'),
('Hotel for Dogs', 'Simulation', '505 Games', 2009, 'Wii'),
('I Am In The Movie', 'Simulation', 'Namco Bandai Games', 2012, 'Wii'),
('I Love Horses: Rider\'s Paradise', 'Simulation', 'Destineer', 2010, 'Wii'),
('Imagine: Fashion Party', 'Simulation', 'Ubisoft', 2009, 'Wii'),
('Imagine: Party Babyz', 'Simulation', 'Ubisoft', 2008, 'Wii'),
('Iron Chef America: Supreme Cuisine', 'Simulation', 'Destineer', 2008, 'Wii'),
('Jambo! Safari Animal Rescue', 'Simulation', 'Sega', 2009, 'Wii'),
('Let\'s Paint', 'Simulation', 'Zoo Games', 2010, 'Wii'),
('Let\'s Play Garden', 'Simulation', 'Deep Silver', 2010, 'Wii'),
('Littlest Pet Shop', 'Simulation', 'Electronic Arts', 2008, 'Wii'),
('Littlest Pet Shop: Friends', 'Simulation', 'Electronic Arts', 2009, 'Wii'),
('Mary King\'s Riding School 2', 'Simulation', 'Midas Interactive Entertainment', 2009, 'Wii'),
('MiniCopter: Adventure Flight', 'Simulation', '505 Games', 2007, 'Wii'),
('Mobile Suit Gundam: MS Sensen 0079', 'Simulation', 'Namco Bandai Games', 2007, 'Wii'),
('Monster Mayhem: Build and Battle', 'Simulation', 'Zushi Games', 2009, 'Wii'),
('My Animal Centre', 'Simulation', 'Deep Silver', 2009, 'Wii'),
('My Baby: First Steps', 'Simulation', 'SouthPeak Games', 2009, 'Wii'),
('My Ballet Studio', 'Simulation', '505 Games', 2009, 'Wii'),
('MySims', 'Simulation', 'Electronic Arts', 2007, 'Wii'),
('MySims Kingdom', 'Simulation', 'Electronic Arts', 2008, 'Wii'),
('MySims Party', 'Simulation', 'Electronic Arts', 2009, 'Wii'),
('Ocean Commander', 'Simulation', 'Valcon Games', 2009, 'Wii'),
('Paws & Claws: Pet Resort', 'Simulation', 'THQ', 2009, 'Wii'),
('Paws & Claws: Pet Vet', 'Simulation', 'THQ', 2009, 'Wii'),
('Pet Pals: Animal Doctor', 'Simulation', 'JoWood Productions', 2008, 'Wii'),
('Petz Dogz 2', 'Simulation', 'Ubisoft', 2007, 'Wii'),
('Petz Rescue: Wildlife Vet', 'Simulation', 'Ubisoft', 2008, 'Wii'),
('Petz Sports', 'Simulation', 'Ubisoft', 2008, 'Wii'),
('Petz: Catz 2', 'Simulation', 'Ubisoft', 2007, 'Wii'),
('Petz: Crazy Monkeyz', 'Simulation', 'Ubisoft', 2008, 'Wii'),
('Petz: Horsez 2', 'Simulation', 'Ubisoft', 2007, 'Wii'),
('Pizza Delivery Boy', 'Simulation', 'Majesco Entertainment', 2010, 'Wii'),
('Pony Friends 2', 'Simulation', 'Eidos Interactive', 2009, 'Wii'),
('Project Runway', 'Simulation', 'Atari', 2010, 'Wii'),
('Purr Pals', 'Simulation', 'Deep Silver', 2008, 'Wii'),
('SimAnimals', 'Simulation', 'Electronic Arts', 2009, 'Wii'),
('SimAnimals Africa', 'Simulation', 'Electronic Arts', 2009, 'Wii'),
('SimCity Creator', 'Simulation', 'Electronic Arts', 2008, 'Wii'),
('Spore Hero', 'Simulation', 'Electronic Arts', 2009, 'Wii'),
('Sushi Go-Round', 'Simulation', 'Asylum Entertainment', 2010, 'Wii'),
('The Oregon Trail', 'Simulation', 'Crave Entertainment', 2011, 'Wii'),
('The Sims 2: Castaway', 'Simulation', 'Electronic Arts', 2007, 'Wii'),
('The Sims 2: Pets', 'Simulation', 'Electronic Arts', 2007, 'Wii'),
('The Sims 3', 'Simulation', 'Electronic Arts', 2010, 'Wii'),
('The Sky Crawlers: Innocent Aces', 'Simulation', 'Namco Bandai Games', 2008, 'Wii'),
('Trauma Center: New Blood', 'Simulation', 'Nintendo', 2007, 'Wii'),
('Trauma Center: Second Opinion', 'Simulation', 'Nintendo', 2006, 'Wii'),
('We Cheer', 'Simulation', '505 Games', 2008, 'Wii'),
('We Cheer 2', 'Simulation', 'Namco Bandai Games', 2009, 'Wii'),
('Wild Earth: African Safari', 'Simulation', 'Majesco Entertainment', 2008, 'Wii'),
('Wing Island', 'Simulation', 'Konami Digital Entertainment', 2006, 'Wii'),
('World of Zoo', 'Simulation', 'THQ', 2009, 'Wii'),
('WWII Aces', 'Simulation', 'Destineer', 2008, 'Wii'),
('ZhuZhu Pets: Featuring The Wild Bunch', 'Simulation', 'Activision', 2010, 'Wii'),
('Zoo Hospital', 'Simulation', 'Majesco Entertainment', 2008, 'Wii'),
('10 Minute Solution', 'Sports', 'Activision', 2010, 'Wii'),
('101-in-1 Sports Party Megamix', 'Sports', 'Nordcurrent', 2010, 'Wii'),
('2010 FIFA World Cup South Africa', 'Sports', 'Electronic Arts', 2010, 'Wii'),
('Academy of Champions: Soccer', 'Sports', 'Ubisoft', 2009, 'Wii'),
('Active Life Explorer', 'Sports', 'Namco Bandai Games', 2010, 'Wii'),
('Active Life: Extreme Challenge', 'Sports', 'Namco Bandai Games', 2009, 'Wii'),
('Active Life: Outdoor Challenge', 'Sports', 'Atari', 2008, 'Wii'),
('Alien Monster Bowling League', 'Sports', 'Destineer', 2009, 'Wii'),
('All Star Cheer Squad', 'Sports', 'THQ', 2008, 'Wii'),
('All Star Cheer Squad 2', 'Sports', 'THQ', 2009, 'Wii'),
('AMF Bowling Pinbusters!', 'Sports', 'Bethesda Softworks', 2007, 'Wii'),
('AMF Bowling World Lanes', 'Sports', 'Bethesda Softworks', 2008, 'Wii'),
('Ashes Cricket 2009', 'Sports', 'Codemasters', 2009, 'Wii'),
('Backyard Baseball \'09', 'Sports', 'Atari', 2008, 'Wii'),
('Backyard Baseball \'10', 'Sports', 'Atari', 2009, 'Wii'),
('Backyard NFL Football', 'Sports', 'Atari', 2007, 'Wii'),
('Backyard NFL Football \'09', 'Sports', 'Atari', 2008, 'Wii'),
('Backyard NFL Football \'10', 'Sports', 'Atari', 2009, 'Wii'),
('Backyard Sports Football: Rookie Rush', 'Sports', 'Atari', 2010, 'Wii'),
('Backyard Sports: Sandlot Sluggers', 'Sports', 'Atari', 2010, 'Wii'),
('Balls of Fury', 'Sports', 'Zoo Digital Publishing', 2007, 'Wii'),
('Barbie Horse Adventures: Riding Camp', 'Sports', 'Activision', 2008, 'Wii'),
('Baseball Blast!', 'Sports', 'Take-Two Interactive', 2009, 'Wii'),
('Basketball Hall of Fame Ultimate Hoops Challenge', 'Sports', 'Zoo Games', 2010, 'Wii'),
('Bass Pro Shops: The Hunt', 'Sports', 'XS Games', 2010, 'Wii'),
('Bass Pro Shops: The Strike', 'Sports', 'XS Games', 2009, 'Wii'),
('Big Beach Sports', 'Sports', 'THQ', 2008, 'Wii'),
('Big League Sports', 'Sports', 'Activision', 2008, 'Wii'),
('Big League Sports: Summer', 'Sports', 'Activision', 2009, 'Wii'),
('Billy\'s Boot Camp: Wii de Enjoy Diet!', 'Sports', 'Rocket Company', 2011, 'Wii'),
('Brunswick Cosmic Bowling', 'Sports', 'GameMill Entertainment', 2010, 'Wii'),
('Brunswick Pro Bowling', 'Sports', '505 Games', 2007, 'Wii'),
('Buck Fever', 'Sports', 'Destineer', 2009, 'Wii'),
('Cabela\'s Big Game Hunter (2008)', 'Sports', 'Activision', 2007, 'Wii'),
('Cabela\'s Big Game Hunter 2010', 'Sports', 'Activision Value', 2009, 'Wii'),
('Cabela\'s Big Game Hunter 2012', 'Sports', 'Activision', 2011, 'Wii'),
('Cabela\'s Dangerous Hunts 2009', 'Sports', 'Activision Value', 2008, 'Wii'),
('Cabela\'s Dangerous Hunts 2011', 'Sports', 'Activision', 2010, 'Wii'),
('Cabela\'s Legendary Adventures', 'Sports', 'Activision', 2008, 'Wii'),
('Cabela\'s Monster Buck Hunter', 'Sports', 'Activision', 2010, 'Wii'),
('Cabela\'s North American Adventures', 'Sports', 'Activision', 2010, 'Wii'),
('Cabela\'s Outdoor Adventures (2009)', 'Sports', 'Activision Value', 2009, 'Wii'),
('Cabela\'s Survival: Shadows of Katmai', 'Sports', 'Activision', 2011, 'Wii'),
('Cabela\'s Trophy Bucks', 'Sports', 'Activision Value', 2008, 'Wii'),
('Canada Hunt', 'Sports', 'Virtual Play Games', 2010, 'Wii'),
('Carnival Games: Mini Golf', 'Sports', 'Take-Two Interactive', 2008, 'Wii'),
('Casper\'s Scare School: Spooky Sports Day', 'Sports', 'Blast! Entertainment Ltd', 2009, 'Wii'),
('Celebrity Sports Showdown', 'Sports', 'Electronic Arts', 2008, 'Wii'),
('Champion Jockey: G1 Jockey & Gallop Racer', 'Sports', 'Tecmo Koei', 2011, 'Wii'),
('Championship Foosball', 'Sports', '505 Games', 2008, 'Wii'),
('Chuck E. Cheese\'s Sports Games', 'Sports', 'UFO Interactive', 2011, 'Wii'),
('Club Penguin: Game Day!', 'Sports', 'Disney Interactive Studios', 2010, 'Wii'),
('Daisy Fuentes Pilates', 'Sports', '505 Games', 2009, 'Wii'),
('Dancing on Ice', 'Sports', 'Ghostlight', 2010, 'Wii'),
('Dave Mirra BMX Challenge', 'Sports', '505 Games', 2007, 'Wii'),
('Deadliest Catch: Sea of Chaos', 'Sports', 'Crave Entertainment', 2010, 'Wii'),
('Deca Sports', 'Sports', 'Konami Digital Entertainment', 2008, 'Wii'),
('Deca Sports 2', 'Sports', 'Hudson Soft', 2009, 'Wii'),
('Deca Sports 3', 'Sports', 'Hudson Soft', 2010, 'Wii'),
('Deer Drive', 'Sports', 'Big Ben Interactive', 2009, 'Wii'),
('Diva Girls: Divas on Ice', 'Sports', '505 Games', 2009, 'Wii'),
('Don King Boxing', 'Sports', 'Take-Two Interactive', 2009, 'Wii'),
('EA Playground', 'Sports', 'Electronic Arts', 2007, 'Wii'),
('EA Sports Active', 'Sports', 'Electronic Arts', 2009, 'Wii'),
('EA Sports Active 2', 'Sports', 'Electronic Arts', 2010, 'Wii'),
('EA Sports Active NFL Training Camp', 'Sports', 'Electronic Arts', 2010, 'Wii'),
('EA Sports Active: More Workouts', 'Sports', 'Electronic Arts', 2009, 'Wii'),
('EA Sports Grand Slam Tennis', 'Sports', 'Electronic Arts', 2009, 'Wii'),
('ExerBeat', 'Sports', 'Namco Bandai Games', 2010, 'Wii'),
('Family Fun Football', 'Sports', 'Tecmo Koei', 2009, 'Wii'),
('Family Jockey', 'Sports', 'Namco Bandai Games', 2008, 'Wii'),
('Family Party: 30 Great Games Winter Fun', 'Sports', 'D3Publisher', 2010, 'Wii'),
('Family Party: Fitness Fun', 'Sports', 'D3Publisher', 2010, 'Wii'),
('Family Trainer: Treasure Adventure', 'Sports', 'Namco Bandai Games', 2010, 'Wii'),
('FIFA 12', 'Sports', 'Electronic Arts', 2011, 'Wii'),
('FIFA 14', 'Sports', 'Electronic Arts', 2013, 'Wii'),
('FIFA 15', 'Sports', 'Electronic Arts', 2014, 'Wii'),
('FIFA Soccer 08', 'Sports', 'Electronic Arts', 2007, 'Wii'),
('FIFA Soccer 09 All-Play', 'Sports', 'Electronic Arts', 2008, 'Wii'),
('FIFA Soccer 10', 'Sports', 'Electronic Arts', 2009, 'Wii'),
('FIFA Soccer 11', 'Sports', 'Electronic Arts', 2010, 'Wii'),
('Fishing Master (jp sales)', 'Sports', 'Konami Digital Entertainment', 2007, 'Wii'),
('Fishing Master World Tour', 'Sports', 'Hudson Entertainment', 2009, 'Wii'),
('Fishing Resort', 'Sports', 'Namco Bandai Games', 2011, 'Wii'),
('Fit & Fun', 'Sports', 'Unknown', 2011, 'Wii'),
('Fit in Six', 'Sports', 'Ubisoft', 2011, 'Wii'),
('Free Running', 'Sports', 'Reef Entertainment', 2009, 'Wii'),
('G1 Jockey Wii', 'Sports', 'Tecmo Koei', 2007, 'Wii'),
('Gallop & Ride!', 'Sports', 'THQ', 2008, 'Wii'),
('Get Fit with Mel B', 'Sports', 'Black Bean Games', 2010, 'Wii'),
('Go Play: City Sports', 'Sports', 'Majesco Entertainment', 2009, 'Wii'),
('Gold\'s Gym: Cardio Workout', 'Sports', 'Ubisoft', 2008, 'Wii'),
('Gold\'s Gym: Cardio Workout (Others sales)', 'Sports', 'Ubisoft', 2008, 'Wii'),
('Gold\'s Gym: Dance Workout', 'Sports', 'Ubisoft', 2010, 'Wii'),
('Gummy Bears Mini Golf', 'Sports', 'Unknown', 2010, 'Wii'),
('Hooked! Again: Real Motion Fishing', 'Sports', '505 Games', 2009, 'Wii'),
('Hooked! Real Motion Fishing', 'Sports', '505 Games', 2007, 'Wii'),
('Jerry Rice and Nitus\' Dog Football', 'Sports', 'Tommo', 2011, 'Wii'),
('Jikkyou Powerful Major League 2009', 'Sports', 'Konami Digital Entertainment', 2009, 'Wii'),
('Jikkyou Powerful Pro Yakyuu 15', 'Sports', 'Konami Digital Entertainment', 2008, 'Wii'),
('Jikkyou Powerful Pro Yakyuu Next', 'Sports', 'Konami Digital Entertainment', 2009, 'Wii'),
('Jikkyou Powerful Pro Yakyuu Wii', 'Sports', 'Konami Digital Entertainment', 2007, 'Wii'),
('Jikkyou Powerful Pro Yakyuu Wii Ketteiban', 'Sports', 'Konami Digital Entertainment', 2007, 'Wii'),
('Jillian Michaels Fitness Ultimatum 2010', 'Sports', 'Majesco Entertainment', 2009, 'Wii'),
('Jillian Michaels Fitness Ultimatum 2011', 'Sports', 'D3Publisher', 2010, 'Wii'),
('Jillian Michaels\' Fitness Ultimatum 2009', 'Sports', 'Deep Silver', 2008, 'Wii'),
('Kevin Van Dam: Big Bass Challenge', 'Sports', 'Zoo Games', 2010, 'Wii'),
('Kid Fit Island Resort', 'Sports', 'Avanquest', 2010, 'Wii'),
('Kidz Sports: Crazy Golf', 'Sports', 'Data Design Interactive', 2008, 'Wii'),
('King of Clubs: Mini Golf', 'Sports', 'Oxygen Interactive', 2008, 'Wii'),
('Let\'s Dance with Mel B', 'Sports', 'Black Bean Games', 2011, 'Wii'),
('Let\'s Play Ballerina', 'Sports', 'Deep Silver', 2010, 'Wii'),
('Little League World Series Baseball 2008', 'Sports', 'Activision', 2008, 'Wii'),
('Little League World Series Baseball 2009', 'Sports', 'Activision', 2009, 'Wii'),
('Little League World Series Baseball: Double Play', 'Sports', 'Activision', 2010, 'Wii'),
('Madden NFL 07', 'Sports', 'Electronic Arts', 2006, 'Wii'),
('Madden NFL 08', 'Sports', 'Electronic Arts', 2007, 'Wii'),
('Madden NFL 09 All-Play', 'Sports', 'Electronic Arts', 2008, 'Wii'),
('Madden NFL 10', 'Sports', 'Electronic Arts', 2009, 'Wii'),
('Madden NFL 12', 'Sports', 'Electronic Arts', 2011, 'Wii'),
('Madden NFL 13', 'Sports', 'Electronic Arts', 2012, 'Wii'),
('Major Dream: Major Wii Nagero! Gyroball!!', 'Sports', 'Takara Tomy', 2008, 'Wii'),
('Major League Baseball 2K10', 'Sports', 'Take-Two Interactive', 2010, 'Wii'),
('Major League Baseball 2K11', 'Sports', 'Take-Two Interactive', 2011, 'Wii'),
('Major League Baseball 2K12', 'Sports', 'Take-Two Interactive', 2012, 'Wii'),
('Major League Baseball 2K8', 'Sports', 'Take-Two Interactive', 2008, 'Wii'),
('Major League Baseball 2K9', 'Sports', 'Take-Two Interactive', 2009, 'Wii'),
('Mario & Sonic at the London 2012 Olympic Games', 'Sports', 'Sega', 2011, 'Wii'),
('Mario & Sonic at the Olympic Games', 'Sports', 'Sega', 2007, 'Wii'),
('Mario & Sonic at the Olympic Winter Games', 'Sports', 'Sega', 2009, 'Wii'),
('Mario Sports Mix', 'Sports', 'Nintendo', 2010, 'Wii'),
('Mario Strikers Charged', 'Sports', 'Nintendo', 2007, 'Wii'),
('Mario Super Sluggers', 'Sports', 'Nintendo', 2008, 'Wii'),
('Mario Tennis', 'Sports', 'Nintendo', 2010, 'Wii'),
('Mathews Bowhunting', 'Sports', 'Zoo Games', 2010, 'Wii'),
('Mesaze!! Tsuri Master: Sekai ni Challenge! Hen', 'Sports', 'Hudson Soft', 2008, 'Wii'),
('MLB Power Pros', 'Sports', 'Konami Digital Entertainment', 2007, 'Wii'),
('MLB Power Pros 2008', 'Sports', 'Konami Digital Entertainment', 2008, 'Wii'),
('MLB Superstars', 'Sports', 'Take-Two Interactive', 2008, 'Wii'),
('Mountain Sports', 'Sports', 'Activision', 2009, 'Wii'),
('My Body Coach', 'Sports', 'Big Ben Interactive', 2009, 'Wii'),
('My Fitness Coach', 'Sports', 'Ubisoft', 2008, 'Wii'),
('My Fitness Coach 2: Exercise and Nutrition', 'Sports', 'Black Bean Games', 2009, 'Wii'),
('My Fitness Coach: Club', 'Sports', 'Ubisoft', 2011, 'Wii'),
('My Horse & Me', 'Sports', 'Atari', 2007, 'Wii'),
('My Horse & Me: Riding for Gold', 'Sports', 'Atari', 2008, 'Wii'),
('NBA 2K10', 'Sports', 'Take-Two Interactive', 2009, 'Wii'),
('NBA 2K12', 'Sports', 'Take-Two Interactive', 2011, 'Wii'),
('NBA 2K13', 'Sports', 'Take-Two Interactive', 2012, 'Wii'),
('NBA Jam', 'Sports', 'Electronic Arts', 2010, 'Wii'),
('NBA Live 08', 'Sports', 'Electronic Arts', 2007, 'Wii'),
('NBA Live 09 All-Play', 'Sports', 'Electronic Arts', 2008, 'Wii'),
('NCAA Football 09 All-Play', 'Sports', 'Electronic Arts', 2008, 'Wii'),
('New Play Control! Mario Power Tennis', 'Sports', 'Nintendo', 2009, 'Wii'),
('NewU Fitness First Mind Body, Yoga & Pilates Workout', 'Sports', 'Black Bean Games', 2010, 'Wii'),
('NHL 2K10', 'Sports', 'Take-Two Interactive', 2009, 'Wii'),
('NHL 2K11', 'Sports', 'Take-Two Interactive', 2010, 'Wii'),
('NHL 2K9', 'Sports', 'Take-Two Interactive', 2008, 'Wii'),
('Nickelodeon Fit', 'Sports', 'Take-Two Interactive', 2010, 'Wii'),
('Nicktoons: MLB', 'Sports', 'Take-Two Interactive', 2011, 'Wii'),
('North American Hunting Extravaganza', 'Sports', 'Zushi Games', 2008, 'Wii'),
('North American Hunting Extravaganza 2', 'Sports', 'Unknown', 2010, 'Wii'),
('PBR: Out of the Chute', 'Sports', 'Crave Entertainment', 2008, 'Wii'),
('PDC World Championship Darts 2008', 'Sports', 'Oxygen Interactive', 2008, 'Wii'),
('PDC World Championship Darts 2009', 'Sports', 'Oxygen Interactive', 2009, 'Wii'),
('PDC World Championship Darts: Pro Tour', 'Sports', 'O-Games', 2010, 'Wii'),
('PES 2009: Pro Evolution Soccer', 'Sports', 'Konami Digital Entertainment', 2009, 'Wii'),
('Pirates vs Ninja Dodgeball', 'Sports', 'SouthPeak Games', 2009, 'Wii'),
('Pool Hall Pro', 'Sports', 'Playlogic Game Factory', 2009, 'Wii'),
('Pool Party', 'Sports', 'SouthPeak Games', 2007, 'Wii'),
('Pro Evolution Soccer 2008', 'Sports', 'Konami Digital Entertainment', 2008, 'Wii'),
('Pro Evolution Soccer 2010', 'Sports', 'Konami Digital Entertainment', 2009, 'Wii'),
('pro evolution soccer 2011', 'Sports', 'Konami Digital Entertainment', 2010, 'Wii'),
('Pro Evolution Soccer 2013', 'Sports', 'Konami Digital Entertainment', 2012, 'Wii'),
('Pro Yakyuu Family Stadium', 'Sports', 'Namco Bandai Games', 2008, 'Wii'),
('Punch-Out!!', 'Sports', 'Nintendo', 2007, 'Wii'),
('Racquet Sports', 'Sports', 'Ubisoft', 2010, 'Wii'),
('Rapala Pro Bass Fishing 2010', 'Sports', 'Activision', 2010, 'Wii'),
('Rapala Tournament Fishing!', 'Sports', 'Activision', 2006, 'Wii'),
('Rapala\'s Fishing Frenzy', 'Sports', 'Activision', 2008, 'Wii'),
('Rapala: We Fish', 'Sports', 'Activision', 2009, 'Wii'),
('Ready 2 Rumble Revolution', 'Sports', 'Atari', 2009, 'Wii'),
('Rec Room Games', 'Sports', 'Destineer', 2009, 'Wii'),
('Reel Fishing: Angler\'s Dream', 'Sports', 'Zushi Games', 2009, 'Wii'),
('Remington Great American Bird Hunt', 'Sports', 'Mastiff', 2009, 'Wii'),
('Remington Super Slam Hunting: Africa', 'Sports', 'Mastiff', 2010, 'Wii'),
('Remington Super Slam Hunting: Alaska', 'Sports', 'Mastiff', 2011, 'Wii'),
('Remington Super Slam Hunting: North America', 'Sports', 'Mastiff', 2010, 'Wii'),
('Rockstar Games presents Table Tennis', 'Sports', 'Take-Two Interactive', 2007, 'Wii'),
('Rugby League 3', 'Sports', 'Alternative Software', 2010, 'Wii'),
('Sega Bass Fishing', 'Sports', 'Sega', 2008, 'Wii'),
('Sega Superstars Tennis', 'Sports', 'Sega', 2008, 'Wii'),
('Shaun White Skateboarding', 'Sports', 'Ubisoft', 2010, 'Wii'),
('Shaun White Snowboarding: Road Trip', 'Sports', 'Ubisoft', 2008, 'Wii'),
('Shaun White Snowboarding: World Stage', 'Sports', 'Ubisoft', 2009, 'Wii'),
('Shawn Johnson Gymnastics', 'Sports', 'Zoo Games', 2010, 'Wii'),
('Shimano Xtreme Fishing', 'Sports', 'Mastiff', 2009, 'Wii'),
('Skate City Heroes', 'Sports', 'Zoo Digital Publishing', 2008, 'Wii'),
('Skate it', 'Sports', 'Electronic Arts', 2008, 'Wii'),
('Ski and Shoot', 'Sports', 'RTL', 2008, 'Wii'),
('Sled Shred featuring the Jamaican Bobsled Team', 'Sports', 'SouthPeak Games', 2010, 'Wii'),
('SSX Blur', 'Sports', 'Electronic Arts', 2007, 'Wii'),
('Summer Athletics: The Ultimate Challenge (Others sales)', 'Sports', 'DTP Entertainment', 2008, 'Wii'),
('Summer Athletics: The Ultimate Challenge (US sales)', 'Sports', 'DTP Entertainment', 2008, 'Wii'),
('Summer Challenge: Athletics Tournament', 'Sports', 'PQube', 2011, 'Wii'),
('Summer Sports 2: Island Sports Party', 'Sports', 'Ubisoft', 2008, 'Wii'),
('Summer Sports: Paradise Island', 'Sports', 'Ubisoft', 2008, 'Wii'),
('Summer Sports: Paradise Island (Others sales)', 'Sports', 'Ubisoft', 2008, 'Wii'),
('Super Swing Golf', 'Sports', 'Nintendo', 2006, 'Wii'),
('Super Swing Golf Season 2', 'Sports', 'Rising Star Games', 2007, 'Wii'),
('Surf\'s Up', 'Sports', 'Ubisoft', 2007, 'Wii'),
('Ten Pin Alley 2', 'Sports', 'XS Games', 2008, 'Wii'),
('The Biggest Loser', 'Sports', 'THQ', 2009, 'Wii'),
('The Biggest Loser: Challenge', 'Sports', 'THQ', 2010, 'Wii'),
('The BIGS', 'Sports', 'Take-Two Interactive', 2007, 'Wii'),
('The BIGS 2', 'Sports', 'Take-Two Interactive', 2009, 'Wii'),
('The Cages: Pro Style Batting Practice', 'Sports', 'Konami Digital Entertainment', 2010, 'Wii'),
('Tiger Woods PGA Tour 08', 'Sports', 'Electronic Arts', 2007, 'Wii'),
('Tiger Woods PGA Tour 09 All-Play', 'Sports', 'Electronic Arts', 2008, 'Wii'),
('Tiger Woods PGA Tour 10', 'Sports', 'Electronic Arts', 2009, 'Wii'),
('Tiger Woods PGA Tour 11', 'Sports', 'Electronic Arts', 2010, 'Wii'),
('Tiger Woods PGA Tour 12: The Masters', 'Sports', 'Electronic Arts', 2011, 'Wii'),
('Tony Hawk\'s Proving Ground', 'Sports', 'Activision', 2007, 'Wii'),
('Tony Hawk: RIDE', 'Sports', 'Activision', 2009, 'Wii'),
('Tony Hawk: Shred', 'Sports', 'Activision', 2010, 'Wii'),
('Top Spin 4', 'Sports', 'Take-Two Interactive', 2011, 'Wii'),
('Tournament Pool', 'Sports', 'Destineer', 2009, 'Wii'),
('Triple Crown Championship Snowboarding', 'Sports', 'Destineer', 2010, 'Wii'),
('Turbo: Super Stunt Squad', 'Sports', 'D3Publisher', 2013, 'Wii'),
('UFC Personal Trainer: The Ultimate Fitness System', 'Sports', 'THQ', 2011, 'Wii'),
('Ultimate Duck Hunting', 'Sports', 'Zoo Digital Publishing', 2009, 'Wii'),
('Ultimate Duck Hunting: Hunting & Retrieving Ducks', 'Sports', 'Detn8 Games', 2007, 'Wii'),
('Vacation Sports', 'Sports', 'Ubisoft', 2009, 'Wii'),
('Virtua Tennis 2009', 'Sports', 'Sega', 2009, 'Wii'),
('Virtua Tennis 4', 'Sports', 'Sega', 2011, 'Wii'),
('Wacky World of Sports', 'Sports', 'Sega', 2009, 'Wii'),
('Walk it Out!', 'Sports', 'Konami Digital Entertainment', 2010, 'Wii'),
('We Love Golf!', 'Sports', 'Capcom', 2007, 'Wii'),
('We Ski', 'Sports', 'Namco Bandai Games', 2008, 'Wii'),
('We Ski & Snowboard', 'Sports', 'Atari', 2008, 'Wii'),
('Wii Fit', 'Sports', 'Nintendo', 2007, 'Wii'),
('Wii Fit Plus', 'Sports', 'Nintendo', 2009, 'Wii'),
('Wii Sports', 'Sports', 'Nintendo', 2006, 'Wii'),
('Wii Sports Resort', 'Sports', 'Nintendo', 2009, 'Wii'),
('Winning Eleven Playmaker 2010: Aoki Samurai no Chousen', 'Sports', 'Konami Digital Entertainment', 2010, 'Wii'),
('Winter Blast: 9 Snow & Ice Games', 'Sports', 'Destineer', 2010, 'Wii'),
('Winter Sports 2011', 'Sports', 'DTP Entertainment', 2011, 'Wii'),
('Winter Sports 2: The Next Challenge', 'Sports', 'RTL', 2008, 'Wii'),
('Winter Sports 3: The Great Tournament', 'Sports', 'Tradewest', 2010, 'Wii'),
('Winter Sports: The Ultimate Challenge', 'Sports', 'RTL', 2007, 'Wii'),
('Winter Stars', 'Sports', 'Deep Silver', 2011, 'Wii'),
('World Championship Athletics', 'Sports', 'DTP Entertainment', 2009, 'Wii'),
('Yoga Wii', 'Sports', 'JoWood Productions', 2009, 'Wii'),
('Your Shape featuring Jenny McCarthy', 'Sports', 'Ubisoft', 2009, 'Wii'),
('Zumba Fitness', 'Sports', '505 Games', 2010, 'Wii'),
('Zumba Fitness 2', 'Sports', 'Majesco Entertainment', 2011, 'Wii'),
('Angry Birds Star Wars', 'Strategy', 'Activision', 2013, 'Wii'),
('Battalion Wars 2', 'Strategy', 'Nintendo', 2007, 'Wii'),
('Battle of Giants: Dinosaurs Strike', 'Strategy', 'Ubisoft', 2010, 'Wii'),
('Creeper World 3: Arc Eternal', 'Strategy', 'Namco Bandai Games', 2009, 'Wii'),
('Defendin\' De Penguin', 'Strategy', 'Zushi Games', 2008, 'Wii'),
('Dragon Quest Monsters: Battle Road Victory', 'Strategy', 'Square Enix', 2010, 'Wii'),
('Fire Emblem: Radiant Dawn', 'Strategy', 'Nintendo', 2007, 'Wii'),
('Fritz Chess', 'Strategy', 'Deep Silver', 2009, 'Wii'),
('Little King\'s Story', 'Strategy', 'Rising Star Games', 2009, 'Wii'),
('Making History: The Great War', 'Strategy', 'Namco Bandai Games', 2010, 'Wii'),
('McDROID', 'Strategy', 'Namco Bandai Games', 2011, 'Wii'),
('New Play Control! Pikmin', 'Strategy', 'Nintendo', 2008, 'Wii'),
('New Play Control! Pikmin 2', 'Strategy', 'Nintendo', 2009, 'Wii'),
('SD Gundam G Generation Wars', 'Strategy', 'Namco Bandai Games', 2009, 'Wii'),
('SD Gundam G Generation World', 'Strategy', 'Namco Bandai Games', 2011, 'Wii'),
('SD Gundam: Gashapon Wars', 'Strategy', 'Namco Bandai Games', 2010, 'Wii'),
('SD Gundam: Scad Hammers', 'Strategy', 'Namco Bandai Games', 2006, 'Wii'),
('Sid Meier\'s Pirates!', 'Strategy', 'Take-Two Interactive', 2010, 'Wii'),
('Star Trek: Conquest', 'Strategy', 'Bethesda Softworks', 2007, 'Wii'),
('Super Robot Taisen Neo', 'Strategy', 'Namco Bandai Games', 2009, 'Wii'),
('Thrillville: Off the Rails', 'Strategy', 'LucasArts', 2007, 'Wii'),
('Vertigo', 'Strategy', 'Playlogic Game Factory', 2009, 'Wii'),
('Worms: A Space Oddity', 'Strategy', 'THQ', 2008, 'Wii'),
('Worms: Battle Islands', 'Strategy', 'THQ', 2010, 'Wii'),
('Yu-Gi-Oh! 5D\'s: Duel Transer', 'Strategy', 'Konami Digital Entertainment', 2010, 'Wii');
