
-- --------------------------------------------------------

--
-- Struttura della tabella `xb`
--

DROP TABLE IF EXISTS `xb`;
CREATE TABLE IF NOT EXISTS `xb` (
  `game_name` varchar(200) CHARACTER SET utf8mb3 DEFAULT NULL,
  `genre_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL,
  `publisher_name` varchar(100) CHARACTER SET utf8mb3 DEFAULT NULL,
  `release_year` int DEFAULT NULL,
  `platform_name` varchar(50) CHARACTER SET utf8mb3 DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dump dei dati per la tabella `xb`
--

INSERT INTO `xb` (`game_name`, `genre_name`, `publisher_name`, `release_year`, `platform_name`) VALUES
('50 Cent: Bulletproof', 'Action', 'Vivendi Games', 2005, 'XB'),
('Advent Rising', 'Action', 'THQ', 2005, 'XB'),
('Aeon Flux', 'Action', 'THQ', 2005, 'XB'),
('Alias', 'Action', 'Acclaim Entertainment', 2004, 'XB'),
('And1 Streetball', 'Action', 'Ubisoft', 2006, 'XB'),
('Azurik: Rise of Perathia', 'Action', 'Microsoft Game Studios', 2001, 'XB'),
('Batman Begins', 'Action', 'Electronic Arts', 2005, 'XB'),
('Batman: Dark Tomorrow', 'Action', 'Kemco', 2003, 'XB'),
('Batman: Rise of Sin Tzu', 'Action', 'Ubisoft', 2003, 'XB'),
('Beatdown: Fists of Vengeance', 'Action', 'Capcom', 2005, 'XB'),
('Bionicle', 'Action', 'Electronic Arts', 2003, 'XB'),
('Blade II', 'Action', 'Activision', 2002, 'XB'),
('Blood Omen 2', 'Action', 'Eidos Interactive', 2002, 'XB'),
('Buffy the Vampire Slayer', 'Action', 'Electronic Arts', 2002, 'XB'),
('Buffy the Vampire Slayer: Chaos Bleeds', 'Action', 'Vivendi Games', 2003, 'XB'),
('Carmen Sandiego: The Secret of the Stolen Drums', 'Action', 'BAM! Entertainment', 2004, 'XB'),
('Castlevania: Curse of Darkness', 'Action', 'Konami Digital Entertainment', 2005, 'XB'),
('Catwoman', 'Action', 'Electronic Arts', 2004, 'XB'),
('Cold Fear', 'Action', 'Ubisoft', 2005, 'XB'),
('Constantine', 'Action', 'SCi', 2005, 'XB'),
('Crime Life: Gang Wars', 'Action', 'Konami Digital Entertainment', 2005, 'XB'),
('Crimson Sea', 'Action', 'Tecmo Koei', 2002, 'XB'),
('Crouching Tiger, Hidden Dragon', 'Action', 'Ubisoft', 2003, 'XB'),
('Curious George', 'Action', 'Namco Bandai Games', 2006, 'XB'),
('Dino Crisis 3', 'Action', 'Capcom', 2003, 'XB'),
('Dinotopia: The Sunstone Odyssey', 'Action', 'TDK Mediactive', 2003, 'XB'),
('Double Pack: Finding Nemo / The Incredibles', 'Action', 'THQ', 2006, 'XB'),
('Dynasty Warriors 3', 'Action', 'THQ', 2002, 'XB'),
('Dynasty Warriors 4', 'Action', 'Tecmo Koei', 2003, 'XB'),
('Dynasty Warriors 5', 'Action', 'Tecmo Koei', 2005, 'XB'),
('Enter the Matrix', 'Action', 'Atari', 2003, 'XB'),
('Evil Dead: Fistfull of Boomstick', 'Action', 'THQ', 2003, 'XB'),
('Evil Dead: Regeneration', 'Action', 'THQ', 2005, 'XB'),
('Fantastic 4', 'Action', 'Activision', 2005, 'XB'),
('Fatal Frame', 'Action', 'Tecmo Koei', 2002, 'XB'),
('Fatal Frame II: Crimson Butterfly Director\'s Cut', 'Action', 'Microsoft Game Studios', 2004, 'XB'),
('Final Fight: Streetwise', 'Action', 'Capcom', 2006, 'XB'),
('Finding Nemo', 'Action', 'THQ', 2003, 'XB'),
('Fireblade', 'Action', 'Midway Games', 2002, 'XB'),
('Forgotten Realms: Demon Stone', 'Action', 'Atari', 2004, 'XB'),
('From Russia With Love', 'Action', 'Electronic Arts', 2005, 'XB'),
('Galleon: Islands of Mystery', 'Action', 'SCi', 2004, 'XB'),
('Gauntlet: Dark Legacy', 'Action', 'Midway Games', 2002, 'XB'),
('Genma Onimusha', 'Action', 'Capcom', 2002, 'XB'),
('Gladiator: Sword of Vengeance', 'Action', 'Acclaim Entertainment', 2003, 'XB'),
('Grabbed by the Ghoulies', 'Action', 'Microsoft Game Studios', 2003, 'XB'),
('Grand Theft Auto: San Andreas', 'Action', 'Take-Two Interactive', 2005, 'XB'),
('Harry Potter and the Chamber of Secrets', 'Action', 'Electronic Arts', 2002, 'XB'),
('Harry Potter and the Goblet of Fire', 'Action', 'Electronic Arts', 2005, 'XB'),
('Harry Potter and the Prisoner of Azkaban', 'Action', 'Electronic Arts', 2004, 'XB'),
('Harry Potter and the Sorcerer\'s Stone', 'Action', 'Electronic Arts', 2003, 'XB'),
('Headhunter: Redemption', 'Action', 'Sega', 2004, 'XB'),
('Hitman: Blood Money', 'Action', 'Eidos Interactive', 2006, 'XB'),
('Hulk', 'Action', 'Universal Interactive', 2003, 'XB'),
('Hunter: The Reckoning', 'Action', 'Interplay', 2002, 'XB'),
('Hunter: The Reckoning Redeemer', 'Action', 'Interplay', 2003, 'XB'),
('Indiana Jones and the Emperor\'s Tomb', 'Action', 'LucasArts', 2003, 'XB'),
('Indycar Series 2005', 'Action', 'Codemasters', 2004, 'XB'),
('James Cameron\'s Dark Angel', 'Action', 'Vivendi Games', 2002, 'XB'),
('Jaws Unleashed', 'Action', 'THQ', 2006, 'XB'),
('JSRF: Jet Set Radio Future', 'Action', 'Sega', 2002, 'XB'),
('Kabuki Warriors', 'Action', 'Genki', 2001, 'XB'),
('King Arthur', 'Action', 'Konami Digital Entertainment', 2004, 'XB'),
('Knight\'s Apprentice: Memorick\'s Adventures', 'Action', 'Microids', 2004, 'XB'),
('Legacy of Kain: Defiance', 'Action', 'Eidos Interactive', 2003, 'XB'),
('LEGO Star Wars II: The Original Trilogy', 'Action', 'LucasArts', 2006, 'XB'),
('LEGO Star Wars: The Video Game', 'Action', 'Eidos Interactive', 2005, 'XB'),
('Loons: The Fight For Fame', 'Action', 'Atari', 2002, 'XB'),
('Mafia', 'Action', 'Take-Two Interactive', 2004, 'XB'),
('Manhunt', 'Action', 'Take-Two Interactive', 2004, 'XB'),
('Mercenaries: Playground of Destruction', 'Action', 'LucasArts', 2005, 'XB'),
('Minority Report: Everybody Runs', 'Action', 'Activision', 2002, 'XB'),
('Mortal Kombat: Shaolin Monks', 'Action', 'Midway Games', 2005, 'XB'),
('NBA 2K6', 'Action', 'Take-Two Interactive', 2005, 'XB'),
('New Legends', 'Action', 'THQ', 2002, 'XB'),
('NightCaster', 'Action', 'Microsoft Game Studios', 2002, 'XB'),
('NightCaster II: Equinox', 'Action', 'Jaleco', 2002, 'XB'),
('Ninja Gaiden', 'Action', 'Microsoft Game Studios', 2004, 'XB'),
('Ninja Gaiden Black', 'Action', 'Microsoft Game Studios', 2005, 'XB'),
('Otogi 2: Immortal Warriors', 'Action', 'Sega', 2003, 'XB'),
('Otogi: Myth of Demons', 'Action', 'Sega', 2002, 'XB'),
('Pac-Man World 2', 'Action', 'Namco Bandai Games', 2002, 'XB'),
('Pariah', 'Action', 'Hip Interactive', 2005, 'XB'),
('Peter Jackson\'s King Kong: The Official Game of the Movie', 'Action', 'Ubisoft', 2005, 'XB'),
('Phantom Dust', 'Action', 'Microsoft Game Studios', 2004, 'XB'),
('Predator: Concrete Jungle', 'Action', 'Vivendi Games', 2005, 'XB'),
('Prince of Persia: The Sands of Time', 'Action', 'Ubisoft', 2003, 'XB'),
('Prince of Persia: The Two Thrones', 'Action', 'Ubisoft', 2005, 'XB'),
('Prince of Persia: Warrior Within', 'Action', 'Ubisoft', 2004, 'XB'),
('Project Gotham Racing (JP weekly sales)', 'Action', 'Microsoft Game Studios', 2002, 'XB'),
('Project Gotham Racing 2 (JP weekly sales)', 'Action', 'Microsoft Game Studios', 2003, 'XB'),
('Project: Snowblind', 'Action', 'Eidos Interactive', 2005, 'XB'),
('Red Ninja: End of Honor', 'Action', 'Vivendi Games', 2005, 'XB'),
('RoadKill', 'Action', 'Midway Games', 2003, 'XB'),
('Robots', 'Action', 'Vivendi Games', 2005, 'XB'),
('Rockstar Games Double Pack: Grand Theft Auto III & Grand Theft Auto Vice City', 'Action', 'Take-Two Interactive', 2003, 'XB'),
('Rocky: Legends', 'Action', 'Ubisoft', 2004, 'XB'),
('Rogue Ops', 'Action', 'Kemco', 2003, 'XB'),
('Samurai Warriors', 'Action', 'Tecmo Koei', 2004, 'XB'),
('Scarface: The World is Yours', 'Action', 'Vivendi Games', 2006, 'XB'),
('Scooby-Doo! Mystery Mayhem', 'Action', 'THQ', 2004, 'XB'),
('ScrapLand', 'Action', 'Deep Silver', 2005, 'XB'),
('Shark Tale', 'Action', 'Activision', 2004, 'XB'),
('Shrek SuperSlam', 'Action', 'Activision', 2005, 'XB'),
('Silent Hill 2: Restless Dreams', 'Action', 'Konami Digital Entertainment', 2001, 'XB'),
('Silent Hill 4: The Room', 'Action', 'Konami Digital Entertainment', 2004, 'XB'),
('Spartan: Total Warrior', 'Action', 'Sega', 2005, 'XB'),
('Spawn: Armageddon', 'Action', 'Electronic Arts', 2003, 'XB'),
('Sphinx and the Cursed Mummy', 'Action', 'THQ', 2003, 'XB'),
('Spider-Man 2', 'Action', 'Activision', 2004, 'XB'),
('Spider-Man: The Movie', 'Action', 'Activision', 2002, 'XB'),
('Spy vs Spy', 'Action', 'Global Star', 2005, 'XB'),
('Star Wars Episode III: Revenge of the Sith', 'Action', 'Activision', 2005, 'XB'),
('Star Wars: Obi-Wan', 'Action', 'Activision', 2001, 'XB'),
('State of Emergency', 'Action', 'Take-Two Interactive', 2003, 'XB'),
('Stubbs the Zombie in Rebel Without a Pulse', 'Action', 'THQ', 2005, 'XB'),
('Superman: The Man of Steel', 'Action', 'Atari', 2002, 'XB'),
('Syberia', 'Action', 'Microids', 2003, 'XB'),
('Teenage Mutant Ninja Turtles', 'Action', 'Konami Digital Entertainment', 2003, 'XB'),
('Teenage Mutant Ninja Turtles 2: Battle Nexus', 'Action', 'Konami Digital Entertainment', 2004, 'XB'),
('Teenage Mutant Ninja Turtles 3: Mutant Nightmare', 'Action', 'Konami Digital Entertainment', 2005, 'XB'),
('Tenchu: Return From Darkness', 'Action', 'Activision', 2004, 'XB'),
('Terminator 3: Rise of the Machines', 'Action', 'Atari', 2003, 'XB'),
('The Chronicles of Narnia: The Lion, The Witch and The Wardrobe', 'Action', 'Disney Interactive Studios', 2005, 'XB'),
('The Da Vinci Code', 'Action', 'Take-Two Interactive', 2006, 'XB'),
('The Godfather (old US sales)', 'Action', 'Electronic Arts', 2006, 'XB'),
('The Godfather (US sales)', 'Action', 'Electronic Arts', 2006, 'XB'),
('The Great Escape', 'Action', 'SCi', 2003, 'XB'),
('The Incredible Hulk: Ultimate Destruction', 'Action', 'Vivendi Games', 2005, 'XB'),
('The Incredibles: Rise of the Underminer', 'Action', 'THQ', 2005, 'XB'),
('The Lord of the Rings: The Fellowship of the Ring', 'Action', 'Universal Interactive', 2002, 'XB'),
('The Lord of the Rings: The Return of the King', 'Action', 'Electronic Arts', 2003, 'XB'),
('The Lord of the Rings: The Two Towers', 'Action', 'Electronic Arts', 2002, 'XB'),
('The Matrix: Path of Neo', 'Action', 'Atari', 2005, 'XB'),
('The Punisher', 'Action', 'THQ', 2005, 'XB'),
('The Suffering', 'Action', 'Midway Games', 2004, 'XB'),
('The Suffering: Ties That Bind', 'Action', 'Midway Games', 2005, 'XB'),
('The Terminator: Dawn of Fate', 'Action', 'Atari', 2002, 'XB'),
('The Warriors', 'Action', 'Take-Two Interactive', 2005, 'XB'),
('Thief: Deadly Shadows', 'Action', 'Eidos Interactive', 2004, 'XB'),
('ToeJam & Earl III: Mission to Earth', 'Action', 'Sega', 2002, 'XB'),
('Tom Clancy\'s Splinter Cell', 'Action', 'Ubisoft', 2002, 'XB'),
('Tom Clancy\'s Splinter Cell: Chaos Theory', 'Action', 'Ubisoft', 2005, 'XB'),
('Tom Clancy\'s Splinter Cell: Pandora Tomorrow', 'Action', 'Ubisoft', 2004, 'XB'),
('Tomb Raider: Legend', 'Action', 'Eidos Interactive', 2006, 'XB'),
('Tron 2.0: Killer App', 'Action', 'Disney Interactive Studios', 2004, 'XB'),
('True Crime: New York City', 'Action', 'Activision', 2005, 'XB'),
('True Crime: Streets of LA', 'Action', 'Activision', 2003, 'XB'),
('Ty the Tasmanian Tiger 3: Night of the Quinkan', 'Action', 'Zoo Digital Publishing', 2005, 'XB'),
('Ultimate Spider-Man', 'Action', 'Activision', 2005, 'XB'),
('Van Helsing', 'Action', 'Activision', 2007, 'XB'),
('X-Men: The Official Game', 'Action', 'Activision', 2006, 'XB'),
('Beyond Good & Evil', 'Adventure', 'Ubisoft', 2003, 'XB'),
('Breakdown', 'Adventure', 'Electronic Arts', 2004, 'XB'),
('Broken Sword: The Sleeping Dragon', 'Adventure', 'THQ', 2003, 'XB'),
('Call of Cthulhu: Dark Corners of the Earth', 'Adventure', 'Take-Two Interactive', 2005, 'XB'),
('Charlie and the Chocolate Factory', 'Adventure', 'Global Star', 2005, 'XB'),
('Conker: Live And Reloaded', 'Adventure', 'Microsoft Game Studios', 2005, 'XB'),
('CSI: Crime Scene Investigation', 'Adventure', 'Ubisoft', 2004, 'XB'),
('Dreamfall: The Longest Journey', 'Adventure', 'Empire Interactive', 2006, 'XB'),
('Enclave', 'Adventure', 'Swing! Entertainment', 2002, 'XB'),
('Indigo Prophecy', 'Adventure', 'Atari', 2005, 'XB'),
('Leisure Suit Larry: Magna Cum Laude', 'Adventure', 'Vivendi Games', 2004, 'XB'),
('Myst III: Exile', 'Adventure', 'Ubisoft', 2002, 'XB'),
('Myst IV: Revelation', 'Adventure', 'Ubisoft', 2005, 'XB'),
('Obscure', 'Adventure', 'MC2 Entertainment', 2004, 'XB'),
('Oddworld: Stranger\'s Wrath', 'Adventure', 'Electronic Arts', 2005, 'XB'),
('Pirates: The Legend of Black Kat', 'Adventure', 'Electronic Arts', 2002, 'XB'),
('Prisoner of War', 'Adventure', 'Atari', 2002, 'XB'),
('SeaWorld Adventure Parks: Shamu\'s Deep Sea Adventure', 'Adventure', 'Activision', 2005, 'XB'),
('Second Sight', 'Adventure', 'Codemasters', 2004, 'XB'),
('Shenmue II', 'Adventure', 'Microsoft Game Studios', 2002, 'XB'),
('Still Life', 'Adventure', 'Microids', 2005, 'XB'),
('Syberia II', 'Adventure', 'Ubisoft', 2004, 'XB'),
('The Thing', 'Adventure', 'Vivendi Games', 2002, 'XB'),
('Tim Burton\'s The Nightmare Before Christmas: Oogie\'s Revenge', 'Adventure', 'Disney Interactive Studios', 2005, 'XB'),
('Wallace & Gromit: Curse of the Were-Rabbit', 'Adventure', 'Konami Digital Entertainment', 2005, 'XB'),
('Zathura', 'Adventure', 'Take-Two Interactive', 2005, 'XB'),
('Backyard Wrestling 2: There Goes the Neighborhood', 'Fighting', 'Eidos Interactive', 2004, 'XB'),
('Backyard Wrestling: Don\'t Try This at Home', 'Fighting', 'Eidos Interactive', 2003, 'XB'),
('Bloody Roar Extreme', 'Fighting', 'Hudson Soft', 2003, 'XB'),
('Bruce Lee: Quest of the Dragon', 'Fighting', 'Universal Interactive', 2002, 'XB'),
('Capcom Fighting Evolution', 'Fighting', 'Capcom', 2005, 'XB'),
('Capcom vs. SNK 2 EO', 'Fighting', 'Capcom', 2003, 'XB'),
('Dead or Alive 3', 'Fighting', 'Microsoft Game Studios', 2001, 'XB'),
('Dead or Alive Ultimate', 'Fighting', 'Tecmo Koei', 2004, 'XB'),
('Digimon Rumble Arena 2', 'Fighting', 'Atari', 2004, 'XB'),
('Dragon Ball Z: Sagas', 'Fighting', 'Atari', 2005, 'XB'),
('Fight Club', 'Fighting', 'Vivendi Games', 2004, 'XB'),
('Fight Night 2004', 'Fighting', 'Electronic Arts', 2004, 'XB'),
('Fight Night Round 2', 'Fighting', 'Electronic Arts', 2005, 'XB'),
('Fight Night Round 2004', 'Fighting', 'Electronic Arts', 2004, 'XB'),
('Fight Night Round 3', 'Fighting', 'Electronic Arts', 2006, 'XB'),
('Godzilla: Save the Earth', 'Fighting', 'Atari', 2004, 'XB'),
('Guilty Gear X2 #Reload', 'Fighting', 'Zoo Digital Publishing', 2004, 'XB'),
('Iron Phoenix', 'Fighting', 'Sega', 2005, 'XB'),
('Kakuto Chojin', 'Fighting', 'Microsoft Game Studios', 2002, 'XB'),
('Kung Fu Chaos', 'Fighting', 'Microsoft Game Studios', 2003, 'XB'),
('Legends of Wrestling', 'Fighting', 'Acclaim Entertainment', 2002, 'XB'),
('Legends of Wrestling II', 'Fighting', 'Acclaim Entertainment', 2002, 'XB'),
('Marvel Nemesis: Rise of the Imperfects', 'Fighting', 'Electronic Arts', 2005, 'XB'),
('Marvel vs. Capcom 2: New Age of Heroes', 'Fighting', 'Capcom', 2002, 'XB'),
('Mortal Kombat: Deadly Alliance', 'Fighting', 'Midway Games', 2002, 'XB'),
('Mortal Kombat: Deception', 'Fighting', 'Midway Games', 2004, 'XB'),
('MTV Celebrity Deathmatch', 'Fighting', 'Gotham Games', 2003, 'XB'),
('Rocky', 'Fighting', 'Rage Software', 2002, 'XB'),
('Samurai Shodown V', 'Fighting', 'Ignition Entertainment', 2006, 'XB'),
('Showdown: Legends of Wrestling', 'Fighting', 'Acclaim Entertainment', 2004, 'XB'),
('SNK vs. Capcom: SVC Chaos', 'Fighting', 'Ignition Entertainment', 2004, 'XB'),
('SoulCalibur II', 'Fighting', 'Namco Bandai Games', 2003, 'XB'),
('Stake: Fortune Fighters', 'Fighting', 'Metro 3D', 2003, 'XB'),
('Street Fighter Anniversary Collection', 'Fighting', 'Capcom', 2004, 'XB'),
('Tao Feng: Fist of the Lotus', 'Fighting', 'Microsoft Game Studios', 2003, 'XB'),
('The King of Fighters 02/03', 'Fighting', 'SNK Playmore', 2005, 'XB'),
('The King of Fighters NeoWave', 'Fighting', 'SNK Playmore', 2006, 'XB'),
('TMNT: Mutant Melee', 'Fighting', 'Konami Digital Entertainment', 2005, 'XB'),
('UFC: Tapout', 'Fighting', 'Crave Entertainment', 2002, 'XB'),
('UFC: Tapout 2', 'Fighting', 'Capcom', 2003, 'XB'),
('WWE Raw 2', 'Fighting', 'THQ', 2003, 'XB'),
('WWE WrestleMania 21', 'Fighting', 'THQ', 2005, 'XB'),
('WWF Raw', 'Fighting', 'THQ', 2002, 'XB'),
('X-Men: Next Dimension', 'Fighting', 'Activision', 2002, 'XB'),
('2 in 1 Combo Pack: Sonic Heroes / Super Monkey Ball Deluxe', 'Misc', 'Sega', 2004, 'XB'),
('Atari Anthology', 'Misc', 'Atari', 2004, 'XB'),
('Bicycle Casino 2005', 'Misc', 'Zoo Digital Publishing', 2004, 'XB'),
('Capcom Classics Collection', 'Misc', 'Capcom', 2005, 'XB'),
('Chessmaster', 'Misc', 'Ubisoft', 2004, 'XB'),
('Defender', 'Misc', 'Midway Games', 2002, 'XB'),
('Dr. Seuss\' The Cat in the Hat', 'Misc', 'Vivendi Games', 2003, 'XB'),
('Exhibition', 'Misc', 'Microsoft Game Studios', 2001, 'XB'),
('Exhibition Volume 02', 'Misc', 'Microsoft Game Studios', 2003, 'XB'),
('Exhibition Volume 03', 'Misc', 'Microsoft Game Studios', 2003, 'XB'),
('Exhibition Volume 4', 'Misc', 'Microsoft Game Studios', 2003, 'XB'),
('Exhibition Volume 5', 'Misc', 'Microsoft Game Studios', 2004, 'XB'),
('Exhibition Volume 6', 'Misc', 'Microsoft Game Studios', 2004, 'XB'),
('Fuzion Frenzy', 'Misc', 'Microsoft Game Studios', 2001, 'XB'),
('High Rollers Casino', 'Misc', 'Mud Duck Productions', 2004, 'XB'),
('Intellivision Lives!', 'Misc', 'Crave Entertainment', 2004, 'XB'),
('Karaoke Revolution', 'Misc', 'Konami Digital Entertainment', 2004, 'XB'),
('Karaoke Revolution Party', 'Misc', 'Konami Digital Entertainment', 2005, 'XB'),
('Midway Arcade Treasures', 'Misc', 'Midway Games', 2003, 'XB'),
('Midway Arcade Treasures 2', 'Misc', 'Midway Games', 2004, 'XB'),
('Midway Arcade Treasures 3', 'Misc', 'Midway Games', 2005, 'XB'),
('Monopoly Party', 'Misc', 'Infogrames', 2002, 'XB'),
('MTV Music Generator 3: This Is the Remix', 'Misc', 'Codemasters', 2004, 'XB'),
('Namco Museum: 50th Anniversary', 'Misc', 'Namco Bandai Games', 2005, 'XB'),
('Nickelodeon Party Blast', 'Misc', 'Infogrames', 2002, 'XB'),
('Pinball Hall of Fame: The Gottlieb Collection', 'Misc', 'Crave Entertainment', 2004, 'XB'),
('Pump It Up: Exceed', 'Misc', 'Mastiff', 2005, 'XB'),
('Pure Pinball', 'Misc', 'XS Games', 2004, 'XB'),
('Shrek Super Party', 'Misc', 'TDK Mediactive', 2002, 'XB'),
('Sonic Mega Collection Plus', 'Misc', 'Sega', 2004, 'XB'),
('SpongeBob SquarePants: Lights, Camera, Pants!', 'Misc', 'THQ', 2005, 'XB'),
('Stacked with Daniel Negreanu', 'Misc', 'Myelin Media', 2006, 'XB'),
('Star Wars: The Clone Wars & Tetris Worlds', 'Misc', 'Microsoft Game Studios', 2002, 'XB'),
('Super Monkey Ball Deluxe', 'Misc', 'Sega', 2005, 'XB'),
('Taito Legends', 'Misc', 'Empire Interactive', 2005, 'XB'),
('Tecmo Classic Arcade', 'Misc', 'Microsoft Game Studios', 2005, 'XB'),
('The Bible Game', 'Misc', 'Crave Entertainment', 2005, 'XB'),
('The Guy Game', 'Misc', 'Gathering of Developers', 2004, 'XB'),
('Trivial Pursuit unhinged', 'Misc', 'Atari', 2004, 'XB'),
('Whacked!', 'Misc', 'Microsoft Game Studios', 2002, 'XB'),
('World Championship Poker', 'Misc', 'Crave Entertainment', 2004, 'XB'),
('World Championship Poker 2: Featuring Howard Lederer', 'Misc', 'Crave Entertainment', 2005, 'XB'),
('World Poker Tour', 'Misc', 'Take-Two Interactive', 2005, 'XB'),
('World Series of Poker', 'Misc', 'Activision', 2005, 'XB'),
('Xbox Music Mixer', 'Misc', 'Microsoft Game Studios', 2003, 'XB'),
('Blinx 2: Masters of Time & Space', 'Platform', 'Microsoft Game Studios', 2004, 'XB'),
('Blinx: The Time Sweeper', 'Platform', 'Microsoft Game Studios', 2002, 'XB'),
('Codename: Kids Next Door: Operation V.I.D.E.O.G.A.M.E.', 'Platform', 'Global Star', 2005, 'XB'),
('Crash Bandicoot: The Wrath of Cortex', 'Platform', 'Universal Interactive', 2002, 'XB'),
('Crash: Twinsanity', 'Platform', 'Vivendi Games', 2004, 'XB'),
('Disney\'s Chicken Little', 'Platform', 'Disney Interactive Studios', 2005, 'XB'),
('Disney\'s The Haunted Mansion', 'Platform', 'Take-Two Interactive', 2003, 'XB'),
('Dr. Muto', 'Platform', 'Midway Games', 2002, 'XB'),
('Dragon\'s Lair 3D: Return to the Lair', 'Platform', 'Ubisoft', 2002, 'XB'),
('Ed, Edd n Eddy: The Mis-Edventures', 'Platform', 'Midway Games', 2005, 'XB'),
('Frogger Beyond', 'Platform', 'Konami Digital Entertainment', 2002, 'XB'),
('Frogger: Ancient Shadow', 'Platform', 'Konami Digital Entertainment', 2005, 'XB'),
('Futurama', 'Platform', 'SCi', 2003, 'XB'),
('I-Ninja', 'Platform', 'Namco Bandai Games', 2003, 'XB'),
('Ice Age 2: The Meltdown', 'Platform', 'Vivendi Games', 2006, 'XB'),
('Lemony Snicket\'s A Series of Unfortunate Events', 'Platform', 'Activision', 2004, 'XB'),
('Madagascar', 'Platform', 'Activision', 2005, 'XB'),
('Malice', 'Platform', 'Evolved Games', 2004, 'XB'),
('Mega Man Anniversary Collection', 'Platform', 'Capcom', 2005, 'XB'),
('Mission: Impossible - Operation Surma', 'Platform', 'Atari', 2003, 'XB'),
('Oddworld: Munch\'s Oddysee', 'Platform', 'Atari', 2001, 'XB'),
('Over the Hedge', 'Platform', 'Activision', 2006, 'XB'),
('Pac-Man World 3', 'Platform', 'Namco Bandai Games', 2005, 'XB'),
('Pitfall: The Lost Expedition', 'Platform', 'Activision', 2004, 'XB'),
('Psychonauts', 'Platform', 'THQ', 2005, 'XB'),
('Rayman 3: Hoodlum Havoc', 'Platform', 'Ubisoft', 2003, 'XB'),
('Scaler', 'Platform', 'Global Star', 2004, 'XB'),
('Scooby-Doo! Night of 100 Frights', 'Platform', 'THQ', 2003, 'XB'),
('Scooby-Doo! Unmasked', 'Platform', 'THQ', 2005, 'XB'),
('Shadow The Hedgehog', 'Platform', 'Sega', 2005, 'XB'),
('Shrek', 'Platform', 'TDK Mediactive', 2001, 'XB'),
('Shrek 2', 'Platform', 'Activision', 2004, 'XB'),
('Sonic Heroes', 'Platform', 'Sega', 2003, 'XB'),
('SpongeBob SquarePants: Battle for Bikini Bottom', 'Platform', 'THQ', 2003, 'XB'),
('Spyro: A Hero\'s Tail', 'Platform', 'Vivendi Games', 2004, 'XB'),
('Tak 2: The Staff of Dreams', 'Platform', 'THQ', 2004, 'XB'),
('Tak: The Great Juju Challenge', 'Platform', 'THQ', 2005, 'XB'),
('Taz Wanted', 'Platform', 'Atari', 2002, 'XB'),
('The Fairly Odd Parents: Breakin Da Rules', 'Platform', 'THQ', 2003, 'XB'),
('The Hobbit', 'Platform', 'Vivendi Games', 2003, 'XB'),
('The SpongeBob SquarePants Movie', 'Platform', 'THQ', 2004, 'XB'),
('Tork: Prehistoric Punk', 'Platform', 'Microsoft Game Studios', 2005, 'XB'),
('Ty the Tasmanian Tiger', 'Platform', 'Electronic Arts', 2002, 'XB'),
('Ty the Tasmanian Tiger 2: Bush Rescue', 'Platform', 'Electronic Arts', 2004, 'XB'),
('Vexx', 'Platform', 'Acclaim Entertainment', 2003, 'XB'),
('Voodoo Vince', 'Platform', 'Microsoft Game Studios', 2003, 'XB'),
('Wallace & Gromit in Project Zoo', 'Platform', 'BAM! Entertainment', 2003, 'XB'),
('X2: Wolverine\'s Revenge', 'Platform', 'Activision', 2003, 'XB'),
('Zapper: One Wicked Cricket!', 'Platform', 'Infogrames', 2002, 'XB'),
('Egg Mania: Eggstreme Madness', 'Puzzle', 'Kemco', 2002, 'XB'),
('Guess the Logos', 'Puzzle', 'Sega', 2004, 'XB'),
('Mojo!', 'Puzzle', 'DreamCatcher Interactive', 2003, 'XB'),
('Sneakers', 'Puzzle', 'Microsoft Game Studios', 2002, 'XB'),
('Super Bubble Pop', 'Puzzle', 'Jaleco', 2002, 'XB'),
('Tetris Worlds (Online Edition)', 'Puzzle', 'THQ', 2003, 'XB'),
('Ultra Bust-A-Move', 'Puzzle', '505 Games', 2004, 'XB'),
('187: Ride or Die', 'Racing', 'Ubisoft', 2005, 'XB'),
('4x4 EVO 2', 'Racing', 'Gathering of Developers', 2001, 'XB'),
('American Chopper', 'Racing', 'Zoo Digital Publishing', 2004, 'XB'),
('American Chopper 2: Full Throttle', 'Racing', 'Zoo Digital Publishing', 2005, 'XB'),
('Antz Extreme Racing', 'Racing', 'Empire Interactive', 2002, 'XB'),
('Apex', 'Racing', 'Atari', 2003, 'XB'),
('Arctic Thunder', 'Racing', 'Midway Games', 2001, 'XB'),
('ATV Quad Power Racing 2', 'Racing', 'Acclaim Entertainment', 2003, 'XB'),
('Big Mutha Truckers', 'Racing', 'Empire Interactive', 2002, 'XB'),
('Big Mutha Truckers 2', 'Racing', 'Empire Interactive', 2005, 'XB'),
('Burnout', 'Racing', 'Acclaim Entertainment', 2002, 'XB'),
('Burnout 2: Point of Impact', 'Racing', 'Acclaim Entertainment', 2003, 'XB'),
('Burnout 3: Takedown', 'Racing', 'Electronic Arts', 2004, 'XB'),
('Burnout Revenge', 'Racing', 'Electronic Arts', 2005, 'XB'),
('Cars', 'Racing', 'THQ', 2006, 'XB'),
('Carve', 'Racing', 'Global Star', 2004, 'XB'),
('Cel Damage', 'Racing', 'Electronic Arts', 2001, 'XB'),
('Chase: Hollywood Stunt Driver', 'Racing', 'BAM! Entertainment', 2002, 'XB'),
('Circus Maximus: Chariot Wars', 'Racing', 'THQ', 2002, 'XB'),
('Colin McRae Rally 04', 'Racing', 'Codemasters', 2004, 'XB'),
('Colin McRae Rally 2005', 'Racing', 'Codemasters', 2004, 'XB'),
('Colin McRae Rally 3', 'Racing', 'Codemasters', 2002, 'XB'),
('Corvette', 'Racing', 'TDK Mediactive', 2003, 'XB'),
('Crash \'N\' Burn', 'Racing', 'Eidos Interactive', 2004, 'XB'),
('Crash Nitro Kart', 'Racing', 'Vivendi Games', 2003, 'XB'),
('Crash Tag Team Racing', 'Racing', 'Vivendi Games', 2005, 'XB'),
('Crazy Taxi 3: High Roller', 'Racing', 'Sega', 2002, 'XB'),
('Dakar 2: The World\'s Ultimate Rally', 'Racing', 'Acclaim Entertainment', 2003, 'XB'),
('Driv3r', 'Racing', 'Atari', 2004, 'XB'),
('Driver: Parallel Lines', 'Racing', 'Atari', 2006, 'XB'),
('F1 2001', 'Racing', 'Electronic Arts', 2001, 'XB'),
('FlatOut', 'Racing', 'Empire Interactive', 2004, 'XB'),
('FlatOut 2', 'Racing', 'Empire Interactive', 2006, 'XB'),
('Ford Mustang: The Legend Lives', 'Racing', 'Take-Two Interactive', 2005, 'XB'),
('Ford Racing 2', 'Racing', 'Empire Interactive', 2003, 'XB'),
('Ford Racing 3', 'Racing', 'Take-Two Interactive', 2004, 'XB'),
('Ford vs. Chevy', 'Racing', 'Global Star', 2005, 'XB'),
('Forza Motorsport', 'Racing', 'Microsoft Game Studios', 2005, 'XB'),
('Freaky Flyers', 'Racing', 'Midway Games', 2003, 'XB'),
('Freestyle Metal X', 'Racing', 'Midway Games', 2003, 'XB'),
('Furious Karting', 'Racing', 'Atari', 2003, 'XB'),
('Grooverider: Slot Car Thunder', 'Racing', 'Encore', 2003, 'XB'),
('Group S Challenge', 'Racing', 'Capcom', 2003, 'XB'),
('Hot Wheels: Stunt Track Challenge', 'Racing', 'THQ', 2004, 'XB'),
('Hummer Badlands', 'Racing', 'Global Star', 2006, 'XB'),
('IHRA Drag Racing 2004', 'Racing', 'Bethesda Softworks', 2003, 'XB'),
('IHRA Drag Racing: Sportsman Edition', 'Racing', 'Bethesda Softworks', 2006, 'XB'),
('IHRA Professional Drag Racing 2005', 'Racing', 'Bethesda Softworks', 2004, 'XB'),
('IndyCar Series', 'Racing', 'Codemasters', 2003, 'XB'),
('Juiced', 'Racing', 'THQ', 2005, 'XB'),
('L.A. Rush', 'Racing', 'Midway Games', 2005, 'XB'),
('Mad Dash Racing', 'Racing', 'Eidos Interactive', 2001, 'XB'),
('Maximum Chase', 'Racing', 'Microsoft Game Studios', 2002, 'XB'),
('Midnight Club 3: DUB Edition', 'Racing', 'Take-Two Interactive', 2005, 'XB'),
('Midnight Club 3: DUB Edition Remix', 'Racing', 'Take-Two Interactive', 2006, 'XB'),
('Midnight Club II', 'Racing', 'Take-Two Interactive', 2003, 'XB'),
('Midtown Madness 3', 'Racing', 'Microsoft Game Studios', 2003, 'XB'),
('Motocross Mania 3', 'Racing', 'Take-Two Interactive', 2005, 'XB'),
('MotoGP', 'Racing', 'THQ', 2002, 'XB'),
('MotoGP 2', 'Racing', 'THQ', 2003, 'XB'),
('Motor Trend presents Lotus Challenge', 'Racing', 'Xicat Interactive', 2003, 'XB'),
('MTX Mototrax', 'Racing', 'Activision', 2004, 'XB'),
('MX 2002 Featuring Ricky Carmichael', 'Racing', 'THQ', 2001, 'XB'),
('MX SuperFly featuring Ricky Carmichael', 'Racing', 'THQ', 2002, 'XB'),
('MX Unleashed', 'Racing', 'THQ', 2004, 'XB'),
('MX vs. ATV Unleashed', 'Racing', 'THQ', 2005, 'XB'),
('MX World Tour Featuring Jamie Little', 'Racing', 'Crave Entertainment', 2005, 'XB'),
('NASCAR 06: Total Team Control', 'Racing', 'Electronic Arts', 2005, 'XB'),
('NASCAR 07', 'Racing', 'Electronic Arts', 2006, 'XB'),
('NASCAR 2005: Chase for the Cup', 'Racing', 'Electronic Arts', 2004, 'XB'),
('NASCAR Heat 2002', 'Racing', 'Infogrames', 2001, 'XB'),
('NASCAR Thunder 2002', 'Racing', 'Electronic Arts', 2001, 'XB'),
('NASCAR Thunder 2003', 'Racing', 'Electronic Arts', 2002, 'XB'),
('NASCAR Thunder 2004', 'Racing', 'Electronic Arts', 2003, 'XB'),
('Need for Speed Carbon', 'Racing', 'Electronic Arts', 2006, 'XB'),
('Need for Speed Underground', 'Racing', 'Electronic Arts', 2003, 'XB'),
('Need for Speed Underground 2', 'Racing', 'Electronic Arts', 2004, 'XB'),
('Need for Speed: Hot Pursuit 2', 'Racing', 'Electronic Arts', 2002, 'XB'),
('Need for Speed: Most Wanted', 'Racing', 'Electronic Arts', 2005, 'XB'),
('OutRun 2', 'Racing', 'Sega', 2004, 'XB'),
('PGR: Project Gotham Racing 2', 'Racing', 'Microsoft Game Studios', 2003, 'XB'),
('Powerdrome', 'Racing', 'Evolved Games', 2004, 'XB'),
('Pro Race Driver', 'Racing', 'Codemasters', 2003, 'XB'),
('Project Gotham Racing', 'Racing', 'Microsoft Game Studios', 2001, 'XB'),
('Pulse Racer', 'Racing', 'Jaleco', 2003, 'XB'),
('Quantum Redshift', 'Racing', 'Microsoft Game Studios', 2002, 'XB'),
('R: Racing Evolution', 'Racing', 'Namco Bandai Games', 2003, 'XB'),
('RalliSport Challenge', 'Racing', 'Microsoft Game Studios', 2002, 'XB'),
('RalliSport Challenge 2', 'Racing', 'Microsoft Game Studios', 2004, 'XB'),
('RalliSport Challenge(JP sales)', 'Racing', 'Microsoft Game Studios', 2002, 'XB'),
('Rally Fusion: Race of Champions', 'Racing', 'Activision', 2002, 'XB'),
('Room Zoom: Race for Impact', 'Racing', 'Jaleco', 2004, 'XB'),
('Sega GT 2002', 'Racing', 'Sega', 2002, 'XB'),
('Sega GT Online', 'Racing', 'Sega', 2003, 'XB'),
('Smashing Drive', 'Racing', 'Namco Bandai Games', 2002, 'XB'),
('Sonic Riders', 'Racing', 'Sega', 2006, 'XB'),
('Speed Kings', 'Racing', 'Acclaim Entertainment', 2003, 'XB'),
('SplashDown', 'Racing', 'Atari', 2002, 'XB'),
('Spy Hunter', 'Racing', 'Midway Games', 2002, 'XB'),
('Spy Hunter 2', 'Racing', 'Midway Games', 2003, 'XB'),
('SRS: Street Racing Syndicate', 'Racing', 'Namco Bandai Games', 2004, 'XB'),
('Starsky & Hutch', 'Racing', 'Empire Interactive', 2003, 'XB'),
('SX Superstar', 'Racing', 'Acclaim Entertainment', 2003, 'XB'),
('Test Drive', 'Racing', 'Atari', 2002, 'XB'),
('Test Drive Off-Road Wide Open', 'Racing', 'Infogrames', 2001, 'XB'),
('Test Drive: Eve of Destruction', 'Racing', 'Atari', 2004, 'XB'),
('The Dukes of Hazzard: Return of the General Lee', 'Racing', 'Ubisoft', 2004, 'XB'),
('The Italian Job', 'Racing', 'Eidos Interactive', 2003, 'XB'),
('The Simpsons: Hit & Run', 'Racing', 'Vivendi Games', 2003, 'XB'),
('The Simpsons: Road Rage', 'Racing', 'Electronic Arts', 2001, 'XB'),
('TOCA Race Driver 2', 'Racing', 'Codemasters', 2004, 'XB'),
('TOCA Race Driver 2: Ultimate Racing Simulator', 'Racing', 'Codemasters', 2004, 'XB'),
('TOCA Race Driver 3', 'Racing', 'Codemasters', 2006, 'XB'),
('Top Gear RPM Tuning', 'Racing', 'Wanadoo', 2005, 'XB'),
('Total Immersion Racing', 'Racing', 'Empire Interactive', 2002, 'XB'),
('Totaled!', 'Racing', 'Rage Software', 2002, 'XB'),
('V-Rally 3', 'Racing', 'Atari', 2003, 'XB'),
('Whiplash', 'Racing', 'Eidos Interactive', 2003, 'XB'),
('Whiteout', 'Racing', 'Konami Digital Entertainment', 2002, 'XB'),
('World Racing', 'Racing', 'TDK Mediactive', 2003, 'XB'),
('Wreckless: ThE YaKuza MisSiOns', 'Racing', 'Activision', 2002, 'XB'),
('XGRA: Extreme G Racing Association', 'Racing', 'Acclaim Entertainment', 2003, 'XB'),
('Arx Fatalis', 'Role-Playing', 'Mindscape', 2003, 'XB'),
('Baldur\'s Gate: Dark Alliance', 'Role-Playing', 'Virgin Interactive', 2002, 'XB'),
('Baldur\'s Gate: Dark Alliance II', 'Role-Playing', 'Acclaim Entertainment', 2004, 'XB'),
('Black Stone: Magic & Steel', 'Role-Playing', 'THQ', 2003, 'XB'),
('Digimon World 4', 'Role-Playing', 'Atari', 2005, 'XB'),
('Dungeons & Dragons Heroes', 'Role-Playing', 'Atari', 2003, 'XB'),
('Fable', 'Role-Playing', 'Microsoft Game Studios', 2004, 'XB'),
('Fallout: Brotherhood of Steel', 'Role-Playing', 'Avalon Interactive', 2004, 'XB'),
('Gauntlet: Seven Sorrows', 'Role-Playing', 'Midway Games', 2005, 'XB'),
('Jade Empire', 'Role-Playing', 'Microsoft Game Studios', 2005, 'XB'),
('Lord of the Rings: The Third Age', 'Role-Playing', 'Electronic Arts', 2004, 'XB'),
('Metal Dungeon', 'Role-Playing', 'Xicat Interactive', 2002, 'XB'),
('Phantasy Star Online Episode I & II', 'Role-Playing', 'Sega', 2003, 'XB'),
('Pirates of the Caribbean', 'Role-Playing', 'Ubisoft', 2003, 'XB'),
('Royal Palace of White Sword and The City of Gentiles', 'Role-Playing', 'Take-Two Interactive', 2005, 'XB'),
('Shin Megami Tensei NINE', 'Role-Playing', 'Atlus', 2002, 'XB'),
('Star Wars Knights of the Old Republic II: The Sith Lords', 'Role-Playing', 'Activision', 2004, 'XB'),
('Star Wars: Knights of the Old Republic', 'Role-Playing', 'Activision', 2003, 'XB'),
('Sudeki', 'Role-Playing', 'Microsoft Game Studios', 2004, 'XB'),
('The Bard\'s Tale', 'Role-Playing', 'Ubisoft', 2004, 'XB'),
('The Elder Scrolls III: Morrowind', 'Role-Playing', 'Ubisoft', 2002, 'XB'),
('X-Men Legends', 'Role-Playing', 'Activision', 2004, 'XB'),
('X-Men Legends II: Rise of Apocalypse', 'Role-Playing', 'Activision', 2005, 'XB'),
('25 to Life', 'Shooter', 'Eidos Interactive', 2006, 'XB'),
('AirForce Delta Storm', 'Shooter', 'Konami Digital Entertainment', 2001, 'XB'),
('Alter Echo', 'Shooter', 'THQ', 2003, 'XB'),
('America\'s Army: Rise of a Soldier', 'Shooter', 'Ubisoft', 2005, 'XB'),
('Area 51', 'Shooter', 'Midway Games', 2005, 'XB'),
('Armed and Dangerous', 'Shooter', 'LucasArts', 2003, 'XB'),
('Army Men: Major Malfunction', 'Shooter', 'Global Star', 2006, 'XB'),
('Army Men: Sarge\'s War', 'Shooter', 'Global Star', 2004, 'XB'),
('Bad Boys: Miami Takedown', 'Shooter', 'Empire Interactive', 2004, 'XB'),
('Battle Engine Aquila', 'Shooter', 'Atari', 2003, 'XB'),
('Battlefield 2: Modern Combat', 'Shooter', 'Electronic Arts', 2005, 'XB'),
('Battlestar Galactica', 'Shooter', 'Vivendi Games', 2003, 'XB'),
('Black', 'Shooter', 'Electronic Arts', 2006, 'XB'),
('Blood Wake', 'Shooter', 'Microsoft Game Studios', 2001, 'XB'),
('BloodRayne', 'Shooter', 'Universal Interactive', 2002, 'XB'),
('BloodRayne 2', 'Shooter', 'THQ', 2004, 'XB'),
('BlowOut', 'Shooter', 'Zoo Digital Publishing', 2003, 'XB'),
('Brothers In Arms: Earned in Blood', 'Shooter', 'Ubisoft', 2005, 'XB'),
('Brothers In Arms: Road to Hill 30', 'Shooter', 'Ubisoft', 2005, 'XB'),
('Brute Force', 'Shooter', 'Microsoft Game Studios', 2003, 'XB'),
('Call Of Duty 2: Big Red One', 'Shooter', 'Activision', 2005, 'XB'),
('Call of Duty: Finest Hour', 'Shooter', 'Activision', 2004, 'XB'),
('Chicago Enforcer', 'Shooter', 'Kemco', 2005, 'XB'),
('Close Combat: First to Fight', 'Shooter', 'Take-Two Interactive', 2005, 'XB'),
('Cold War', 'Shooter', 'DreamCatcher Interactive', 2005, 'XB'),
('Combat: Task Force 121', 'Shooter', 'Zoo Digital Publishing', 2005, 'XB'),
('Commandos: Strike Force', 'Shooter', 'Eidos Interactive', 2006, 'XB'),
('Conflict: Desert Storm', 'Shooter', 'SCi', 2002, 'XB'),
('Conflict: Desert Storm II - Back to Bagdhad', 'Shooter', 'SCi', 2003, 'XB'),
('Conflict: Global Terror', 'Shooter', 'SCi', 2005, 'XB'),
('Conflict: Vietnam', 'Shooter', 'SCi', 2004, 'XB'),
('Counter-Strike', 'Shooter', 'Microsoft Game Studios', 2003, 'XB'),
('Darkwatch', 'Shooter', 'Ubisoft', 2005, 'XB'),
('Dead Man\'s Hand', 'Shooter', 'Atari', 2004, 'XB'),
('Dead to Rights', 'Shooter', 'Electronic Arts', 2002, 'XB'),
('Dead to Rights II', 'Shooter', 'Electronic Arts', 2005, 'XB'),
('Delta Force: Black Hawk Down', 'Shooter', 'NovaLogic', 2005, 'XB'),
('Destroy All Humans!', 'Shooter', 'THQ', 2005, 'XB'),
('Deus Ex: Invisible War', 'Shooter', 'Eidos Interactive', 2003, 'XB'),
('Doom 3', 'Shooter', 'Activision', 2005, 'XB'),
('Doom 3: Resurrection of Evil', 'Shooter', 'Activision', 2005, 'XB'),
('Far Cry Instincts', 'Shooter', 'Ubisoft', 2005, 'XB'),
('Far Cry Instincts Evolution', 'Shooter', 'Ubisoft', 2006, 'XB'),
('Freedom Fighters', 'Shooter', 'Electronic Arts', 2003, 'XB'),
('GoldenEye: Rogue Agent', 'Shooter', 'Electronic Arts', 2004, 'XB'),
('Greg Hastings\' Tournament Paintball', 'Shooter', 'Activision', 2004, 'XB'),
('Gun', 'Shooter', 'Activision', 2005, 'XB'),
('Gun Metal', 'Shooter', 'Rage Software', 2002, 'XB'),
('Gunvalkyrie', 'Shooter', 'Infogrames', 2002, 'XB'),
('Half-Life 2', 'Shooter', 'Electronic Arts', 2005, 'XB'),
('Halo 2', 'Shooter', 'Microsoft Game Studios', 2004, 'XB'),
('Halo 2 Multiplayer Map Pack', 'Shooter', 'Microsoft Game Studios', 2005, 'XB'),
('Halo Triple Pack', 'Shooter', 'Microsoft Game Studios', 2005, 'XB'),
('Halo: Combat Evolved', 'Shooter', 'Microsoft Game Studios', 2001, 'XB'),
('Hitman: Contracts', 'Shooter', 'Eidos Interactive', 2004, 'XB'),
('James Bond 007: Agent Under Fire', 'Shooter', 'Electronic Arts', 2002, 'XB'),
('James Bond 007: Everything or Nothing', 'Shooter', 'Electronic Arts', 2004, 'XB'),
('James Bond 007: Nightfire', 'Shooter', 'Electronic Arts', 2002, 'XB'),
('Judge Dredd: Dredd Vs Death', 'Shooter', 'Vivendi Games', 2003, 'XB'),
('Kill.Switch', 'Shooter', 'Namco Bandai Games', 2003, 'XB'),
('Land of the Dead: Road to Fiddler\'s Green', 'Shooter', 'Groove Games', 2005, 'XB'),
('Mace Griffin: Bounty Hunter', 'Shooter', 'Electronic Arts', 2003, 'XB'),
('Max Payne', 'Shooter', 'Take-Two Interactive', 2001, 'XB'),
('Max Payne 2: The Fall of Max Payne', 'Shooter', 'Take-Two Interactive', 2003, 'XB'),
('Medal of Honor: European Assault', 'Shooter', 'Electronic Arts', 2005, 'XB'),
('Medal of Honor: Frontline', 'Shooter', 'Electronic Arts', 2002, 'XB'),
('Medal of Honor: Rising Sun', 'Shooter', 'Electronic Arts', 2003, 'XB'),
('Men of Valor', 'Shooter', 'Vivendi Games', 2004, 'XB'),
('Metal Arms: Glitch in the System', 'Shooter', 'Vivendi Games', 2003, 'XB'),
('Metal Slug 3', 'Shooter', 'Ignition Entertainment', 2004, 'XB'),
('Metal Slug 4 & 5', 'Shooter', 'SNK Playmore', 2005, 'XB'),
('Murakumo: Renegade Mech Pursuit', 'Shooter', 'From Software', 2002, 'XB'),
('NARC', 'Shooter', 'Midway Games', 2005, 'XB'),
('Operation Flashpoint: Elite', 'Shooter', 'Codemasters', 2005, 'XB'),
('Painkiller: Hell Wars', 'Shooter', 'DreamCatcher Interactive', 2006, 'XB'),
('Panzer Dragoon Orta', 'Shooter', 'Sega', 2002, 'XB'),
('Psi-Ops: The Mindgate Conspiracy', 'Shooter', 'Midway Games', 2004, 'XB'),
('Raze\'s Hell', 'Shooter', 'Majesco Entertainment', 2005, 'XB'),
('Red Dead Revolver', 'Shooter', 'Take-Two Interactive', 2004, 'XB'),
('Red Faction II', 'Shooter', 'THQ', 2003, 'XB'),
('Reign of Fire', 'Shooter', 'BAM! Entertainment', 2002, 'XB'),
('Return to Castle Wolfenstein: Tides of War', 'Shooter', 'Activision', 2003, 'XB'),
('RLH: Run Like Hell', 'Shooter', 'Avalon Interactive', 2003, 'XB'),
('RoboCop', 'Shooter', 'Titus', 2003, 'XB'),
('Robotech: Invasion', 'Shooter', 'Global Star', 2004, 'XB'),
('Rogue Trooper', 'Shooter', 'Eidos Interactive', 2006, 'XB'),
('SeaBlade', 'Shooter', 'TDK Mediactive', 2002, 'XB'),
('Serious Sam', 'Shooter', 'Take-Two Interactive', 2002, 'XB'),
('Serious Sam II', 'Shooter', 'Take-Two Interactive', 2005, 'XB'),
('Shadow Ops: Red Mercury', 'Shooter', 'Atari', 2004, 'XB'),
('Shellshock: Nam \'67', 'Shooter', 'Eidos Interactive', 2004, 'XB'),
('Silent Scope Complete', 'Shooter', 'Konami Digital Entertainment', 2004, 'XB'),
('Sniper Elite', 'Shooter', 'Ubisoft', 2005, 'XB'),
('Soldier of Fortune II: Double Helix', 'Shooter', 'Activision', 2003, 'XB'),
('Special Forces: Nemesis Strike', 'Shooter', 'Hip Interactive', 2005, 'XB'),
('Star Wars Jedi Knight: Jedi Academy', 'Shooter', 'Activision', 2003, 'XB'),
('Star Wars: Battlefront', 'Shooter', 'Activision', 2004, 'XB'),
('Star Wars: Battlefront II', 'Shooter', 'Activision', 2005, 'XB'),
('Star Wars: Clone Wars', 'Shooter', 'LucasArts', 2003, 'XB'),
('Star Wars: Republic Commando', 'Shooter', 'Activision', 2005, 'XB'),
('SWAT: Global Strike Team', 'Shooter', 'Vivendi Games', 2003, 'XB'),
('Terminator 3: The Redemption', 'Shooter', 'Atari', 2004, 'XB'),
('The House of The Dead III', 'Shooter', 'Sega', 2002, 'XB'),
('TimeSplitters 2', 'Shooter', 'Eidos Interactive', 2002, 'XB'),
('TimeSplitters: Future Perfect', 'Shooter', 'Electronic Arts', 2005, 'XB'),
('Tom Clancy\'s Classic Trilogy', 'Shooter', 'Ubisoft', 2004, 'XB'),
('Tom Clancy\'s Ghost Recon', 'Shooter', 'Ubisoft', 2002, 'XB'),
('Tom Clancy\'s Ghost Recon 2', 'Shooter', 'Ubisoft', 2004, 'XB'),
('Tom Clancy\'s Ghost Recon 2: Summit Strike', 'Shooter', 'Ubisoft', 2005, 'XB'),
('Tom Clancy\'s Ghost Recon Advanced Warfighter', 'Shooter', 'Ubisoft', 2006, 'XB'),
('Tom Clancy\'s Ghost Recon: Island Thunder', 'Shooter', 'Ubisoft', 2003, 'XB'),
('Tom Clancy\'s Rainbow Six 3', 'Shooter', 'Ubisoft', 2003, 'XB'),
('Tom Clancy\'s Rainbow Six 3: Black Arrow', 'Shooter', 'Ubisoft', 2004, 'XB'),
('Tom Clancy\'s Rainbow Six: Lockdown', 'Shooter', 'Ubisoft', 2005, 'XB'),
('Total Overdose: A Gunslinger\'s Tale in Mexico', 'Shooter', 'Eidos Interactive', 2005, 'XB'),
('Trigger Man', 'Shooter', 'Crave Entertainment', 2004, 'XB'),
('Turok: Evolution', 'Shooter', 'Acclaim Entertainment', 2002, 'XB'),
('Unreal Championship', 'Shooter', 'Atari', 2002, 'XB'),
('Unreal II: The Awakening', 'Shooter', 'Atari', 2004, 'XB'),
('Urban Chaos: Riot Response', 'Shooter', 'Eidos Interactive', 2006, 'XB'),
('Vietcong: Purple Haze', 'Shooter', 'Gathering of Developers', 2004, 'XB'),
('World War II Combat: Road To Berlin', 'Shooter', 'Groove Games', 2006, 'XB'),
('XIII', 'Shooter', 'Ubisoft', 2003, 'XB'),
('Yager', 'Shooter', 'THQ', 2003, 'XB'),
('Blazing Angels: Squadrons of WWII', 'Simulation', 'Ubisoft', 2006, 'XB'),
('Crimson Skies: High Road to Revenge', 'Simulation', 'Microsoft Game Studios', 2003, 'XB'),
('Dance Dance Revolution Ultramix', 'Simulation', 'Konami Digital Entertainment', 2003, 'XB'),
('Dance Dance Revolution Ultramix 2', 'Simulation', 'Konami Digital Entertainment', 2004, 'XB'),
('Dance Dance Revolution Ultramix 3', 'Simulation', 'Konami Digital Entertainment', 2005, 'XB'),
('GunGriffon: Allied Strike', 'Simulation', 'Microsoft Game Studios', 2004, 'XB'),
('Heroes of the Pacific', 'Simulation', 'Codemasters', 2005, 'XB'),
('Jurassic Park: Operation Genesis', 'Simulation', 'Konami Digital Entertainment', 2003, 'XB'),
('MechAssault', 'Simulation', 'Microsoft Game Studios', 2002, 'XB'),
('MechAssault 2: Lone Wolf', 'Simulation', 'Microsoft Game Studios', 2004, 'XB'),
('NTRA Breeders\' Cup World Thoroughbred Championships', 'Simulation', 'Bethesda Softworks', 2005, 'XB'),
('Phantom Crash', 'Simulation', 'Phantagram', 2002, 'XB'),
('Playboy: The Mansion', 'Simulation', 'Ubisoft', 2005, 'XB'),
('Secret Weapons Over Normandy', 'Simulation', 'LucasArts', 2003, 'XB'),
('Star Trek: Shattered Universe', 'Simulation', 'Global Star', 2004, 'XB'),
('Star Wars Starfighter: Special Edition', 'Simulation', 'LucasArts', 2001, 'XB'),
('Star Wars: Jedi Starfighter', 'Simulation', 'Activision', 2002, 'XB'),
('Steel Battalion', 'Simulation', 'Microsoft Game Studios', 2002, 'XB'),
('Steel Battalion: Line of Contact', 'Simulation', 'Capcom', 2004, 'XB'),
('The Sims', 'Simulation', 'Electronic Arts', 2003, 'XB'),
('The Sims 2', 'Simulation', 'Electronic Arts', 2005, 'XB'),
('The Sims: Bustin\' Out', 'Simulation', 'Electronic Arts', 2003, 'XB'),
('The Urbz: Sims in the City', 'Simulation', 'Electronic Arts', 2004, 'XB'),
('Wings of War', 'Simulation', 'Take-Two Interactive', 2004, 'XB'),
('2002 FIFA World Cup', 'Sports', 'Electronic Arts', 2002, 'XB'),
('Aggressive Inline', 'Sports', 'Acclaim Entertainment', 2002, 'XB'),
('All-Star Baseball 2003', 'Sports', 'Acclaim Entertainment', 2002, 'XB'),
('All-Star Baseball 2004', 'Sports', 'Acclaim Entertainment', 2003, 'XB'),
('AMF Bowling 2004', 'Sports', 'Mud Duck Productions', 2003, 'XB'),
('Amped 2', 'Sports', 'Microsoft Game Studios', 2003, 'XB'),
('Amped: Freestyle Snowboarding', 'Sports', 'Microsoft Game Studios', 2001, 'XB'),
('Arena Football', 'Sports', 'Electronic Arts', 2006, 'XB'),
('Barbie Horse Adventures: Wild Horse Rescue', 'Sports', 'Vivendi Games', 2003, 'XB'),
('Blitz: The League', 'Sports', 'Midway Games', 2004, 'XB'),
('BMX XXX', 'Sports', 'Acclaim Entertainment', 2002, 'XB'),
('Cabela\'s Big Game Hunter 2005 Adventures', 'Sports', 'Activision', 2004, 'XB'),
('Cabela\'s Dangerous Hunts', 'Sports', 'Zoo Digital Publishing', 2003, 'XB'),
('Cabela\'s Dangerous Hunts 2', 'Sports', 'Activision', 2005, 'XB'),
('Cabela\'s Deer Hunt 2005 Season', 'Sports', 'Activision', 2004, 'XB'),
('Cabela\'s Deer Hunt: 2004 Season', 'Sports', 'Activision Value', 2003, 'XB'),
('Cabela\'s Outdoor Adventures', 'Sports', 'Zoo Digital Publishing', 2005, 'XB'),
('College Hoops 2K6', 'Sports', 'Take-Two Interactive', 2005, 'XB'),
('Dark Summit', 'Sports', 'THQ', 2001, 'XB'),
('Dave Mirra Freestyle BMX 2', 'Sports', 'Acclaim Entertainment', 2001, 'XB'),
('Dead or Alive Xtreme Beach Volleyball', 'Sports', 'Microsoft Game Studios', 2003, 'XB'),
('Deathrow: Underground Team Combat', 'Sports', 'Ubisoft', 2002, 'XB'),
('Disney\'s Extreme Skate Adventure', 'Sports', 'Activision', 2003, 'XB'),
('ESPN College Hoops 2K5', 'Sports', 'Sega', 2004, 'XB'),
('ESPN MLB Baseball', 'Sports', 'Sega', 2004, 'XB'),
('ESPN MLS ExtraTime 2002', 'Sports', 'Konami Digital Entertainment', 2002, 'XB'),
('ESPN NBA 2K5', 'Sports', 'Global Star', 2004, 'XB'),
('ESPN NBA 2Night 2002', 'Sports', 'Konami Digital Entertainment', 2002, 'XB'),
('ESPN NBA Basketball', 'Sports', 'Sega', 2003, 'XB'),
('ESPN NFL 2K5', 'Sports', 'Sega', 2004, 'XB'),
('ESPN NFL Football', 'Sports', 'Sega', 2003, 'XB'),
('ESPN NFL Primetime 2002', 'Sports', 'Konami Digital Entertainment', 2002, 'XB'),
('ESPN NHL 2K5', 'Sports', 'Global Star', 2004, 'XB'),
('ESPN NHL Hockey', 'Sports', 'Sega', 2003, 'XB'),
('ESPN Winter X Games: Snowboarding 2002', 'Sports', 'Konami Digital Entertainment', 2002, 'XB'),
('FIFA Soccer 06', 'Sports', 'Electronic Arts', 2005, 'XB'),
('FIFA Soccer 07', 'Sports', 'Electronic Arts', 2006, 'XB'),
('FIFA Soccer 2003', 'Sports', 'Electronic Arts', 2002, 'XB'),
('FIFA Soccer 2004', 'Sports', 'Electronic Arts', 2003, 'XB'),
('FIFA Soccer 2005', 'Sports', 'Electronic Arts', 2004, 'XB'),
('FIFA Street', 'Sports', 'Electronic Arts', 2005, 'XB'),
('FIFA Street 2', 'Sports', 'Electronic Arts', 2006, 'XB'),
('FIFA World Cup Germany 2006', 'Sports', 'Electronic Arts', 2006, 'XB'),
('Harry Potter: Quidditch World Cup', 'Sports', 'Electronic Arts', 2003, 'XB'),
('High Heat Major League Baseball 2004', 'Sports', '3DO', 2003, 'XB'),
('Kelly Slater\'s Pro Surfer', 'Sports', 'Activision', 2002, 'XB'),
('Knockout Kings 2002', 'Sports', 'Electronic Arts', 2002, 'XB'),
('Links 2004', 'Sports', 'Microsoft Game Studios', 2003, 'XB'),
('Madden NFL 06', 'Sports', 'Electronic Arts', 2005, 'XB'),
('Madden NFL 07', 'Sports', 'Electronic Arts', 2006, 'XB'),
('Madden NFL 08', 'Sports', 'Electronic Arts', 2007, 'XB'),
('Madden NFL 09', 'Sports', 'Electronic Arts', 2008, 'XB'),
('Madden NFL 2003', 'Sports', 'Electronic Arts', 2002, 'XB'),
('Madden NFL 2004', 'Sports', 'Electronic Arts', 2003, 'XB'),
('Madden NFL 2005', 'Sports', 'Electronic Arts', 2004, 'XB'),
('Major League Baseball 2K5', 'Sports', 'Take-Two Interactive', 2005, 'XB'),
('Major League Baseball 2K6', 'Sports', 'Take-Two Interactive', 2006, 'XB'),
('Mat Hoffman\'s Pro BMX 2', 'Sports', 'Activision', 2002, 'XB'),
('Mike Tyson Heavyweight Boxing', 'Sports', 'Codemasters', 2002, 'XB'),
('MLB Inside Pitch 2003', 'Sports', 'Microsoft Game Studios', 2003, 'XB'),
('MLB SlugFest 20-03', 'Sports', 'Midway Games', 2002, 'XB'),
('MLB SlugFest 20-04', 'Sports', 'Midway Games', 2003, 'XB'),
('MLB SlugFest 2006', 'Sports', 'Midway Games', 2006, 'XB'),
('MLB SlugFest Loaded', 'Sports', 'Midway Games', 2004, 'XB'),
('MVP 06 NCAA Baseball', 'Sports', 'Electronic Arts', 2006, 'XB'),
('MVP Baseball 2003', 'Sports', 'Electronic Arts', 2003, 'XB'),
('MVP Baseball 2004', 'Sports', 'Electronic Arts', 2004, 'XB'),
('MVP Baseball 2005', 'Sports', 'Electronic Arts', 2005, 'XB'),
('NBA 2K2', 'Sports', 'Sega', 2002, 'XB'),
('NBA 2K3', 'Sports', 'Sega', 2002, 'XB'),
('NBA 2K7', 'Sports', 'Take-Two Interactive', 2006, 'XB'),
('NBA Ballers', 'Sports', 'Midway Games', 2004, 'XB'),
('NBA Ballers: Phenom', 'Sports', 'Midway Games', 2006, 'XB'),
('NBA Inside Drive 2002', 'Sports', 'Microsoft Game Studios', 2002, 'XB'),
('NBA Inside Drive 2003', 'Sports', 'Microsoft Game Studios', 2002, 'XB'),
('NBA Inside Drive 2004', 'Sports', 'Microsoft Game Studios', 2003, 'XB'),
('NBA Jam', 'Sports', 'Acclaim Entertainment', 2003, 'XB'),
('NBA Live 06', 'Sports', 'Electronic Arts', 2005, 'XB'),
('NBA Live 07', 'Sports', 'Electronic Arts', 2006, 'XB'),
('NBA Live 2002', 'Sports', 'Electronic Arts', 2001, 'XB'),
('NBA Live 2004', 'Sports', 'Electronic Arts', 2003, 'XB'),
('NBA Live 2005', 'Sports', 'Electronic Arts', 2004, 'XB'),
('NBA Starting Five', 'Sports', 'Konami Digital Entertainment', 2002, 'XB'),
('NBA Street V3', 'Sports', 'Electronic Arts', 2005, 'XB'),
('NBA Street Vol. 2', 'Sports', 'Electronic Arts', 2003, 'XB'),
('NCAA College Basketball 2K3', 'Sports', 'Sega', 2002, 'XB'),
('NCAA Football 06', 'Sports', 'Electronic Arts', 2005, 'XB'),
('NCAA Football 07', 'Sports', 'Electronic Arts', 2006, 'XB'),
('NCAA Football 08', 'Sports', 'Electronic Arts', 2007, 'XB'),
('NCAA Football 2003', 'Sports', 'Electronic Arts', 2002, 'XB'),
('NCAA Football 2004', 'Sports', 'Electronic Arts', 2003, 'XB'),
('NCAA Football 2005', 'Sports', 'Electronic Arts', 2004, 'XB'),
('NCAA March Madness 06', 'Sports', 'Electronic Arts', 2005, 'XB'),
('NCAA March Madness 2004', 'Sports', 'Electronic Arts', 2003, 'XB'),
('NCAA March Madness 2005', 'Sports', 'Electronic Arts', 2004, 'XB'),
('NFL 2K2', 'Sports', 'Sega', 2002, 'XB'),
('NFL 2K3', 'Sports', 'Sega', 2002, 'XB'),
('NFL Blitz 20-02', 'Sports', 'Midway Games', 2002, 'XB'),
('NFL Blitz 20-03', 'Sports', 'Midway Games', 2002, 'XB'),
('NFL Blitz Pro', 'Sports', 'Midway Games', 2003, 'XB'),
('NFL Fever 2002', 'Sports', 'Microsoft Game Studios', 2000, 'XB'),
('NFL Fever 2003', 'Sports', 'Microsoft Game Studios', 2002, 'XB'),
('NFL Fever 2004', 'Sports', 'Microsoft Game Studios', 2003, 'XB'),
('NFL Head Coach', 'Sports', 'Electronic Arts', 2006, 'XB'),
('NFL Street', 'Sports', 'Electronic Arts', 2004, 'XB'),
('NFL Street 2', 'Sports', 'Electronic Arts', 2004, 'XB'),
('NHL 06', 'Sports', 'Electronic Arts', 2005, 'XB'),
('NHL 07', 'Sports', 'Electronic Arts', 2006, 'XB'),
('NHL 2002', 'Sports', 'Electronic Arts', 2001, 'XB'),
('NHL 2003', 'Sports', 'Electronic Arts', 2002, 'XB'),
('NHL 2004', 'Sports', 'Electronic Arts', 2003, 'XB'),
('NHL 2005', 'Sports', 'Electronic Arts', 2004, 'XB'),
('NHL 2K3', 'Sports', 'Sega', 2002, 'XB'),
('NHL 2K6', 'Sports', 'Take-Two Interactive', 2005, 'XB'),
('NHL 2K7', 'Sports', 'Take-Two Interactive', 2006, 'XB'),
('NHL Hitz 20-02', 'Sports', 'Midway Games', 2001, 'XB'),
('NHL Hitz 20-03', 'Sports', 'Midway Games', 2002, 'XB'),
('NHL Hitz Pro', 'Sports', 'Midway Games', 2003, 'XB'),
('NHL Rivals 2004', 'Sports', 'Microsoft Game Studios', 2003, 'XB'),
('Outlaw Golf', 'Sports', 'TDK Mediactive', 2002, 'XB'),
('Outlaw Golf 2', 'Sports', 'Global Star', 2004, 'XB'),
('Outlaw Golf: Nine Holes of Christmas', 'Sports', 'Simon & Schuster Interactive', 2002, 'XB'),
('Outlaw Tennis', 'Sports', 'Global Star', 2005, 'XB'),
('Outlaw Volleyball', 'Sports', 'TDK Mediactive', 2003, 'XB'),
('Pro Cast Sports Fishing', 'Sports', 'Capcom', 2003, 'XB'),
('Pro Fishing Challenge', 'Sports', 'Atlus', 2004, 'XB'),
('Rapala Pro Fishing', 'Sports', 'Zoo Digital Publishing', 2004, 'XB'),
('Real World Golf', 'Sports', 'Mad Catz', 2006, 'XB'),
('RedCard 20-03', 'Sports', 'Midway Games', 2002, 'XB'),
('Rugby 06', 'Sports', 'Electronic Arts', 2006, 'XB'),
('Rugby 2005', 'Sports', 'Electronic Arts', 2005, 'XB'),
('Sega Soccer Slam', 'Sports', 'Sega', 2002, 'XB'),
('Splat Renegade Paintball', 'Sports', 'Take-Two Interactive', 2005, 'XB'),
('SSX 3', 'Sports', 'Electronic Arts', 2003, 'XB'),
('SSX On Tour', 'Sports', 'Electronic Arts', 2005, 'XB'),
('SSX Tricky', 'Sports', 'Electronic Arts', 2001, 'XB'),
('Street Hoops', 'Sports', 'Activision', 2002, 'XB'),
('Strike Force Bowling', 'Sports', 'Crave Entertainment', 2004, 'XB'),
('Tennis Masters Series 2003', 'Sports', 'Microids', 2002, 'XB'),
('The Hustle: Detroit Streets', 'Sports', 'Activision', 2006, 'XB'),
('Tiger Woods PGA Tour 06', 'Sports', 'Electronic Arts', 2005, 'XB'),
('Tiger Woods PGA Tour 07', 'Sports', 'Electronic Arts', 2006, 'XB'),
('Tiger Woods PGA Tour 2003', 'Sports', 'Electronic Arts', 2002, 'XB'),
('Tiger Woods PGA Tour 2004', 'Sports', 'Electronic Arts', 2003, 'XB'),
('Tiger Woods PGA Tour 2005', 'Sports', 'Electronic Arts', 2004, 'XB'),
('Tony Hawk\'s American Wasteland', 'Sports', 'Activision', 2005, 'XB'),
('Tony Hawk\'s Pro Skater 2x', 'Sports', 'Activision', 2001, 'XB'),
('Tony Hawk\'s Pro Skater 3', 'Sports', 'Activision', 2002, 'XB'),
('Tony Hawk\'s Pro Skater 4', 'Sports', 'Activision', 2002, 'XB'),
('Tony Hawk\'s Underground', 'Sports', 'Activision', 2003, 'XB'),
('Tony Hawk\'s Underground 2', 'Sports', 'Activision', 2004, 'XB'),
('Top Spin', 'Sports', 'Microsoft Game Studios', 2003, 'XB'),
('Torino 2006', 'Sports', 'Take-Two Interactive', 2006, 'XB'),
('Toxic Grind', 'Sports', 'THQ', 2002, 'XB'),
('Transworld Snowboarding', 'Sports', 'Atari', 2002, 'XB'),
('Triple Play 2002', 'Sports', 'Electronic Arts', 2002, 'XB'),
('UEFA Euro 2004: Portugal', 'Sports', 'Electronic Arts', 2004, 'XB'),
('Virtual Pool: Tournament Edition', 'Sports', 'Global Star', 2005, 'XB'),
('Wakeboarding Unleashed Featuring Shaun Murray', 'Sports', 'Activision', 2003, 'XB'),
('World Championship Pool 2004', 'Sports', 'Jaleco', 2003, 'XB'),
('World Series Baseball', 'Sports', 'Sega', 2002, 'XB'),
('World Series Baseball 2K3', 'Sports', 'Sega', 2003, 'XB'),
('World Soccer Winning Eleven 8 International', 'Sports', 'Konami Digital Entertainment', 2004, 'XB'),
('World Soccer Winning Eleven 9', 'Sports', 'Konami Digital Entertainment', 2005, 'XB'),
('WTA Tour Tennis', 'Sports', 'Konami Digital Entertainment', 2002, 'XB'),
('Yourself Fitness', 'Sports', 'responDESIGN', 2004, 'XB'),
('Aliens versus Predator: Extinction', 'Strategy', 'Electronic Arts', 2003, 'XB'),
('Commandos 2: Men of Courage', 'Strategy', 'Eidos Interactive', 2002, 'XB'),
('Dai Senryaku VII: Modern Military Tactics', 'Strategy', 'Kool Kizz', 2003, 'XB'),
('Full Spectrum Warrior', 'Strategy', 'THQ', 2004, 'XB'),
('Full Spectrum Warrior: Ten Hammers', 'Strategy', 'THQ', 2006, 'XB'),
('Future Tactics: The Uprising', 'Strategy', 'JoWood Productions', 2004, 'XB'),
('Gladius', 'Strategy', 'Activision', 2003, 'XB'),
('Goblin Commander: Unleash the Horde', 'Strategy', 'Jaleco', 2003, 'XB'),
('Kingdom Under Fire: Heroes', 'Strategy', 'Deep Silver', 2005, 'XB'),
('Kingdom Under Fire: The Crusaders', 'Strategy', 'Deep Silver', 2004, 'XB'),
('Magic: The Gathering - Battlegrounds', 'Strategy', 'Atari', 2003, 'XB'),
('Monster Garage', 'Strategy', 'Activision Value', 2004, 'XB'),
('Robin Hood: Defender of the Crown', 'Strategy', 'Capcom', 2003, 'XB'),
('RollerCoaster Tycoon', 'Strategy', 'Atari', 2003, 'XB'),
('Shattered Union', 'Strategy', 'Take-Two Interactive', 2005, 'XB'),
('Sid Meier\'s Pirates!', 'Strategy', 'Take-Two Interactive', 2005, 'XB'),
('Worms 3D', 'Strategy', 'Sega', 2003, 'XB'),
('Worms 4: Mayhem', 'Strategy', 'Codemasters', 2005, 'XB'),
('Worms Forts: Under Siege', 'Strategy', 'Sega', 2004, 'XB'),
('Wrath Unleashed', 'Strategy', 'LucasArts', 2004, 'XB'),
('Yu-Gi-Oh! The Dawn of Destiny', 'Strategy', 'Konami Digital Entertainment', 2004, 'XB');
